INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <https://data.vlaanderen.be/id/concept/BesluitType/b04bc642-c892-4aae-ac1f-f6ff21362704>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "b04bc642-c892-4aae-ac1f-f6ff21362704";

        # Only visible for "dienstverlenende vereniging" and "opdrachthoudende vereniging" types
        <http://lblod.data.gift/vocabularies/besluit/decidableBy> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71>,
                                                                  <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#definition> "De algemene vergadering stelt een code van goed bestuur vast.";
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Code van goed bestuur"@nl.
  }
} 