INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # This is a boiler-plate
    <https://data.vlaanderen.be/id/concept/BesluitType/cb361927-1aab-4016-bd8a-1a84841391ba>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "cb361927-1aab-4016-bd8a-1a84841391ba" ;

        # Only "Gemeente" and "District" can select this decision type
        <http://lblod.data.gift/vocabularies/besluit/decidableBy> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>,
                                                                  <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000003>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5> ;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>  ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Collectieve motie van wantrouwen"@nl .
  }
} 