PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX costPerEenheid: <http://data.lblod.info/vocabularies/climate-subsidies/cost-per-eenheid/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://data.lblod.info/id/subsidies/rules/26358160-ea1b-4416-86b6-b60faf5c7afa> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/climate-subsidies/ClimateSubsidyWithdrawalRule>;
        mu:uuid "26358160-ea1b-4416-86b6-b60faf5c7afa" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9a3f018b-6528-4abb-82d5-b7920d05a3da> ;
        skos:prefLabel 'Algemene beleidsdoelstellingen: Organisatie en ondersteuning Klimaattafels'@nl ;
        costPerEenheid:description 'Per klimaattafel'@nl .
  }
}
