PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s a besluit:Bestuurseenheid, ere:BestuurVanDeEredienst .
} WHERE {
  ?s a ere:BestuurVanDeEredienst.
}
