PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20230413154257-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "c6d6dab4-62f9-4546-bd36-32360f23915f" ;
      nfo:fileName "20230413154257-forms.ttl" ;
      dct:created "2023-04-13T15:42:57"^^xsd:dateTime ;
      dct:modified "2023-04-13T15:42:57"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "351050"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    