DELETE {
  GRAPH ?j {
    ?s <http://schema.org/publication> <http://lblod.data.gift/concepts/83f7b480-fcaf-4795-b603-7f3bce489325> .
  }
}
INSERT {
  GRAPH ?h {
    ?s <http://schema.org/publication> <http://lblod.data.gift/concepts/83f7b480-fcaf-4795-b603-7f3bce489325> .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> .
  }
  GRAPH ?i {
    ?s <http://schema.org/publication> <http://lblod.data.gift/concepts/83f7b480-fcaf-4795-b603-7f3bce489325> .
  }
  FILTER(?g NOT IN (<http://redpencil.data.gift/id/deltas/producer/loket-submissions>))
  BIND(?g as ?h)
  BIND(?i as ?j)
}
