PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20250114144449-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "985e8e6f-2817-40db-b057-e021853fd419" ;
      nfo:fileName "20250114144449-forms.ttl" ;
      dct:created "2025-01-14T14:44:49"^^xsd:dateTime ;
      dct:modified "2025-01-14T14:44:49"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "465490"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    