
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offers/b03215cf-2206-493c-b534-0546a2479eef>
      a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
      mu:uuid "b03215cf-2206-493c-b534-0546a2479eef";
      dct:title """Opknapwerken slaapplekken Oekraïne""";
      skos:prefLabel """Opknapwerken slaapplekken Oekraïne""";
      skos:related <https://www.vlaanderen.be/vlaanderen-helpt-oekraine/financiering>;
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/7d9ffc75-29ee-45a6-8f7a-e2f88a81aab9>;
      lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773>.

    <http://data.lblod.info/id/subsidy-procedural-steps/7d9ffc75-29ee-45a6-8f7a-e2f88a81aab9> a subsidie:Subsidieprocedurestap;
      mu:uuid "7d9ffc75-29ee-45a6-8f7a-e2f88a81aab9";
      dct:description """Aanvraag""";
      mobiliteit:periode <http://data.lblod.info/id/periodes/9e11f337-8575-4c8f-a9e5-34d7d91988da>.

    <http://lblod.data.info/id/subsidy-measure-offer-series/fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      mu:uuid "fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773";
      dct:title "Oproep 1"@nl;
      dct:description "14/03/2022 — 31/12/2022"@nl ;
      common:active <http://lblod.data.info/id/subsidie-application-flows/e47eb2f7-3d68-487e-bca7-aeb7f2f21e18> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/cbc00fd0-0d0e-4c99-8dfc-691db7dde72d> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/7d9ffc75-29ee-45a6-8f7a-e2f88a81aab9>.

    <http://lblod.data.info/id/subsidie-application-flows/e47eb2f7-3d68-487e-bca7-aeb7f2f21e18> a lblodSubsidie:ApplicationFlow;
      mu:uuid "e47eb2f7-3d68-487e-bca7-aeb7f2f21e18";
      xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773>;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/74d52acc-06a8-44ef-8cc7-a069c0ea0413>.

    <http://lblod.data.info/id/subsidie-application-flow-steps/74d52acc-06a8-44ef-8cc7-a069c0ea0413> a lblodSubsidie:ApplicationStep;
      mu:uuid "74d52acc-06a8-44ef-8cc7-a069c0ea0413";
      qb:order 0;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/7d9ffc75-29ee-45a6-8f7a-e2f88a81aab9>;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/e47eb2f7-3d68-487e-bca7-aeb7f2f21e18>;
      dct:source <config://forms/ukraine/proposal/versions/20220509100012/form.ttl>.

    <http://data.lblod.info/id/periodes/cbc00fd0-0d0e-4c99-8dfc-691db7dde72d> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "cbc00fd0-0d0e-4c99-8dfc-691db7dde72d";
      <http://data.europa.eu/m8g/startTime> "2022-03-14T03:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2022-12-31T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.

    <http://data.lblod.info/id/periodes/9e11f337-8575-4c8f-a9e5-34d7d91988da> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "9e11f337-8575-4c8f-a9e5-34d7d91988da";
      <http://data.europa.eu/m8g/startTime> "2022-03-14T03:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2022-12-31T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}