PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

      # Insert bestuurseenheid
      <http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>, ;
        <http://mu.semte.ch/vocabularies/core/uuid>	"66DB132B6ABCA6E6BF2DBBED" ;
        skos:prefLabel	"Sint-Anna" ;
        <http://www.w3.org/ns/adms#identifier>	"1011411080" ;
        <http://mu.semte.ch/vocabularies/ext/kbonummer> "1011411080" ;
        <http://www.w3.org/ns/regorg#orgStatus>	<http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> ;
        <http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/e8294b73-87c9-4fa2-9441-1937350763c9> .

      # Bestuursorganen voor Sint-Anna
      <http://data.lblod.info/id/bestuursorganen/40d628b0-6c5d-11ef-8f29-2728b827bd59> <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .
      <http://data.lblod.info/id/bestuursorganen/40bfba80-6c5d-11ef-8f29-2728b827bd59> <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .
      <http://data.lblod.info/id/bestuursorganen/40cab700-6c5d-11ef-8f29-2728b827bd59> <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .

      # Insert bestuursorganen
      <http://data.lblod.info/id/bestuursorganen/40d628b0-6c5d-11ef-8f29-2728b827bd59> rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid>	"40d628b0-6c5d-11ef-8f29-2728b827bd59" ;
        <http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .

      <http://data.lblod.info/id/bestuursorganen/40bfba80-6c5d-11ef-8f29-2728b827bd59> rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
	      <http://mu.semte.ch/vocabularies/core/uuid>	"40bfba80-6c5d-11ef-8f29-2728b827bd59" ;
	      <http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
	      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .

      <http://data.lblod.info/id/bestuursorganen/40cab700-6c5d-11ef-8f29-2728b827bd59> rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid>	"40cab700-6c5d-11ef-8f29-2728b827bd59" ;
        <http://data.vlaanderen.be/ns/besluit#classificatie>	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/66DB132B6ABCA6E6BF2DBBED> .

      # Insert bestuursorganen in tijd
      <http://data.lblod.info/id/bestuursorganen/40ec21b0-6c5d-11ef-8f29-2728b827bd59>
        rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid>	"40ec21b0-6c5d-11ef-8f29-2728b827bd59" ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01T00:00:00Z"^^xsd:dateTime ;
        <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/40d628b0-6c5d-11ef-8f29-2728b827bd59> .

      <http://data.lblod.info/id/bestuursorganen/40e4f5c0-6c5d-11ef-8f29-2728b827bd59>
        rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid>	"40e4f5c0-6c5d-11ef-8f29-2728b827bd59" ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01T00:00:00Z"^^xsd:dateTime ;
        <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/40bfba80-6c5d-11ef-8f29-2728b827bd59> .

      <http://data.lblod.info/id/bestuursorganen/40e8ed60-6c5d-11ef-8f29-2728b827bd59> <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/40cab700-6c5d-11ef-8f29-2728b827bd59> . # No bestuurseenheid in tijd data, only uri
  }
}