DELETE WHERE {
GRAPH ?g {
  <http://data.lblod.info/id/subsidy-measure-consumptions/6165A794E575460008000217> ?p ?o.
  <http://data.lblod.info/id/application-forms/6165A7E7E575460008000219> ?form1P ?form1O.
  <http://data.lblod.info/id/application-forms/6165A796E575460008000218> ?form2P ?form2O.
  <http://data.lblod.info/form-data/nodes/b05d9d15-41ca-4200-8bac-a72719b3fbaf> ?contactP ?contactO.
  <http://mu.semte.ch/services/file-service/files/6165a7d593982c000c00143e> ?fileP ?fileO.
  <share://6165a7d593982c000c00143f.pdf> ?pFileP ?pFileO.
  }
}