PREFIX m8g: <http://data.europa.eu/m8g/>

DELETE {
  GRAPH ?g {
    ?s m8g:endTime ?end .
  }
}
INSERT {
  GRAPH ?g {
    ?s m8g:endTime "2023-10-05T21:59:59Z"^^xsd:dateTime .
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/33f16980-1d9b-49b9-b26c-d595ecb8689f> as ?s)
  GRAPH ?g {
    ?s m8g:endTime ?end .
  }
} 