PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?g {
    ?subsidy skos:related ?oldLink .
  }
}
INSERT {
  GRAPH ?g {
    ?subsidy skos:related """https://www.vlaanderen.be/lokaal-bestuur/beleid-in-ontwikkeling-2019-2024/relanceprojecten/lokaal-energie-en-klimaatpact""" .
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/subsidy-measure-offers/8815fe07-e53f-4657-94be-efaa4898f03c> as ?subsidy)

  GRAPH ?g {
    ?subsidy skos:related ?oldLink .
  }
}