PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20220721150218-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "c7c4cc24-212a-4b3c-a160-0688c8d77783" ;
      nfo:fileName "20220721150218-forms.ttl" ;
      dct:created "2022-07-21T15:02:18"^^xsd:dateTime ;
      dct:modified "2022-07-21T15:02:18"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "319201"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    