INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853>
      rdf:type  <http://lblod.data.gift/vocabularies/employee/EducationalLevel> , skos:Concept ;
      <http://mu.semte.ch/vocabularies/core/uuid> "d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853" ;
      skos:prefLabel  "IFIC-personeel"@nl ;
      skos:topConceptOf  <http://lblod.data.gift/concept-schemes/ac6766b6-6d9c-458a-b60b-1338db2f870c> ;
      skos:inScheme  <http://lblod.data.gift/concept-schemes/ac6766b6-6d9c-458a-b60b-1338db2f870c> .
  }
}