# FTE
INSERT {
  GRAPH ?g {
    ?slice <http://purl.org/linked-data/cube#observation> ?obs1, ?obs2, ?obs3, ?obs4, ?obs5, ?obs6, ?obs7, ?obs8.

    ?obs1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs1 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/FEMALE> .
    ?obs1 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs1 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/58c0fc8f-1ec9-469d-a13d-87a0e48fc0a3> .
    ?obs1 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/a29dd9d3-f0a2-4e40-b19a-dbc0ffd6f682> .
    ?obs1 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs1 .
    ?obs1 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs2 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/MALE> .
    ?obs2 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs2 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/58c0fc8f-1ec9-469d-a13d-87a0e48fc0a3> .
    ?obs2 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/a29dd9d3-f0a2-4e40-b19a-dbc0ffd6f682> .
    ?obs2 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs2 .
    ?obs2 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs3 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/MALE> .
    ?obs3 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs3 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/58c0fc8f-1ec9-469d-a13d-87a0e48fc0a3> .
    ?obs3 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/5ac28613-801b-4b2e-ab79-68a6ad0a584d> .
    ?obs3 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs3 .
    ?obs3 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs4 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/FEMALE> .
    ?obs4 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs4 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/00b0467e-4dac-42ff-a5be-2892f0e6eca5> .
    ?obs4 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/5ac28613-801b-4b2e-ab79-68a6ad0a584d> .
    ?obs4 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs4 .
    ?obs4 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs5 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/MALE> .
    ?obs5 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs5 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/00b0467e-4dac-42ff-a5be-2892f0e6eca5> .
    ?obs5 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/5ac28613-801b-4b2e-ab79-68a6ad0a584d> .
    ?obs5 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs5 .
    ?obs5 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs6 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/FEMALE> .
    ?obs6 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs6 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/58c0fc8f-1ec9-469d-a13d-87a0e48fc0a3> .
    ?obs6 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/5ac28613-801b-4b2e-ab79-68a6ad0a584d> .
    ?obs6 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs6 .
    ?obs6 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs7 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/MALE> .
    ?obs7 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs7 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/00b0467e-4dac-42ff-a5be-2892f0e6eca5> .
    ?obs7 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/a29dd9d3-f0a2-4e40-b19a-dbc0ffd6f682> .
    ?obs7 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs7 .
    ?obs7 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .

    ?obs8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/employee/EmployeeObservation> .
    ?obs8 <http://purl.org/linked-data/sdmx/2009/dimension#sex> <http://publications.europa.eu/resource/authority/human-sex/FEMALE> .
    ?obs8 <http://purl.org/linked-data/sdmx/2009/attribute#unitMeasure> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a> .
    ?obs8 <http://lblod.data.gift/vocabularies/employee/workingTimeCategory> <http://lblod.data.gift/concepts/00b0467e-4dac-42ff-a5be-2892f0e6eca5> .
    ?obs8 <http://lblod.data.gift/vocabularies/employee/legalStatus> <http://lblod.data.gift/concepts/a29dd9d3-f0a2-4e40-b19a-dbc0ffd6f682> .
    ?obs8 <http://mu.semte.ch/vocabularies/core/uuid> ?uuidObs8 .
    ?obs8 <http://purl.org/linked-data/sdmx/2009/dimension#educationLev> <http://lblod.data.gift/concepts/d1a7ac1f-587c-48fb-ba6f-1a3bd19aa853> .
  }

}
WHERE {
  GRAPH ?g {
    ?dataset a <http://lblod.data.gift/vocabularies/employee/EmployeeDataset>;
      <http://purl.org/dc/terms/subject> <http://lblod.data.gift/concepts/a97325c1-f572-4dd8-8952-c2cb254f114a>;
      <http://purl.org/linked-data/cube#slice> ?slice.

    ?slice a <http://lblod.data.gift/vocabularies/employee/EmployeePeriodSlice>.

    BIND(SHA256(CONCAT(STR(?slice), "obs1")) as ?uuidObs1)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs1)) as ?obs1)

    BIND(SHA256(CONCAT(STR(?slice), "obs2")) as ?uuidObs2)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs2)) as ?obs2)

    BIND(SHA256(CONCAT(STR(?slice), "obs3")) as ?uuidObs3)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs3)) as ?obs3)

    BIND(SHA256(CONCAT(STR(?slice), "obs4")) as ?uuidObs4)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs4)) as ?obs4)

    BIND(SHA256(CONCAT(STR(?slice), "obs5")) as ?uuidObs5)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs5)) as ?obs5)

    BIND(SHA256(CONCAT(STR(?slice), "obs6")) as ?uuidObs6)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs6)) as ?obs6)

    BIND(SHA256(CONCAT(STR(?slice), "obs7")) as ?uuidObs7)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs7)) as ?obs7)

    BIND(SHA256(CONCAT(STR(?slice), "obs8")) as ?uuidObs8)
    BIND(IRI(CONCAT("http://data.lblod.info/employee-observations/", ?uuidObs8)) as ?obs8)

  }
}
