#################################################################
# Links all forms from 2018 to the correct
# toezicht:InzendingVoorToezichtFormVersion
#################################################################
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>


# clean application graph
DELETE {
  GRAPH <http://mu.semte.ch/application> {
  ?s ?p ?o.
 }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
  ?s ?p ?o.
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/application> {

    ?s a  ?type.
    FILTER (?type IN (ext:FormInput, ext:FormNode, ext:DynamicSubform, ext:FormSolution,
                      toezicht:TaxRate, toezicht:DecisionType, toezicht:InzendingType,
                      toezicht:DocumentAuthenticityType, toezicht:AccountAcceptanceStatus, toezicht:DeliveryReportType,
                      toezicht:FiscalPeriod, toezicht:Nomenclature, toezicht:TaxType, toezicht:InzendingVoorToezicht, ext:InputState ) ).
    ?s ?p ?o.
 }
}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
  ?s toezicht:formVersionScope <http://data.lblod.info/inzending-voor-toezicht-form-version/b516c7c5-4ab9-4a8f-86ca-8c50f1021b32>.
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a  toezicht:DecisionType.
 }
}