PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {

GRAPH <http://mu.semte.ch/graphs/public> {
  <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "e0920e46-85b9-4736-a906-b254cc7f1855" ;
    skos:prefLabel  "AG2B" ;
    skos:altLabel   "" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie>   <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>;
    <http://mu.semte.ch/vocabularies/ext/kbonummer> "0801578801";
    <http://purl.org/dc/terms/identifier> "0801578801" ;
    <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/4bd8337aa40880e343b7f0ca8495ef4460e4e79d9e697495b179a93f41aba153>;
    <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .



  <http://data.lblod.info/id/bestuursorganen/73f00aa16ea5533b945b3389f55c2f03>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "73f00aa16ea5533b945b3389f55c2f03" ;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>   <http://data.lblod.info/id/bestuursorganen/0c33fc5f1190a67eddb5d9bdd9765d09> ;
    <http://data.vlaanderen.be/ns/mandaat#bindingStart>   "2019-01-01T00:00:00"^^xsd:dateTime .


  <http://data.lblod.info/id/bestuursorganen/0c33fc5f1190a67eddb5d9bdd9765d09>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "0c33fc5f1190a67eddb5d9bdd9765d09" ;
    skos:prefLabel  "Raad van bestuur AG2B" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie>   <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
    <http://data.vlaanderen.be/ns/besluit#bestuurt>   <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> .


  <http://data.lblod.info/id/bestuursorganen/ed3772d02753b38047618ef36b1bb7ec>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "ed3772d02753b38047618ef36b1bb7ec" ;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>   <http://data.lblod.info/id/bestuursorganen/6f00afa24980af75c0a46bcef3274a47> ;
    <http://data.vlaanderen.be/ns/mandaat#bindingStart>   "2019-01-01T00:00:00"^^xsd:dateTime .


  <http://data.lblod.info/id/bestuursorganen/6f00afa24980af75c0a46bcef3274a47>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "6f00afa24980af75c0a46bcef3274a47" ;
    skos:prefLabel  "Bevoegd beslissingsorgaan AG2B" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie>   <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
    <http://data.vlaanderen.be/ns/besluit#bestuurt>   <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> .


  <http://data.lblod.info/id/bestuursorganen/a3b7868f4400f7e5daf4fc8f5b604e0a>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "a3b7868f4400f7e5daf4fc8f5b604e0a" ;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>   <http://data.lblod.info/id/bestuursorganen/1a0d37a334f31834bb12954626191911> ;
    <http://data.vlaanderen.be/ns/mandaat#bindingStart>   "2019-01-01T00:00:00"^^xsd:dateTime .


  <http://data.lblod.info/id/bestuursorganen/1a0d37a334f31834bb12954626191911>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "1a0d37a334f31834bb12954626191911" ;
    skos:prefLabel  "Algemene vergadering AG2B" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie>   <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
    <http://data.vlaanderen.be/ns/besluit#bestuurt>   <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> .


  <http://data.lblod.info/id/bestuursorganen/8b1b2a6c8554af739cbf5a67740ceb2a>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "8b1b2a6c8554af739cbf5a67740ceb2a" ;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>   <http://data.lblod.info/id/bestuursorganen/e454c30cddc80b2249e3b80879d3f3c7> ;
    <http://data.vlaanderen.be/ns/mandaat#bindingStart>   "2019-01-01T00:00:00"^^xsd:dateTime ;
    <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie>  <http://data.lblod.info/id/bestuursfuncties/03a35138371b39620555ee9afc06d61e> .


  <http://data.lblod.info/id/bestuursorganen/e454c30cddc80b2249e3b80879d3f3c7>
    rdf:type  <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
    <http://mu.semte.ch/vocabularies/core/uuid>   "e454c30cddc80b2249e3b80879d3f3c7" ;
    skos:prefLabel  "Leidend Ambtenaar AG2B" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie>   <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
    <http://data.vlaanderen.be/ns/besluit#bestuurt>   <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> .
  }
}
