DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
}

WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855>
  }
  GRAPH ?g {
    ?s ?p ?o
  }
}

;

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
      PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
      PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
      PREFIX dcterms: <http://purl.org/dc/terms/>
      PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
      PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
      PREFIX foaf: <http://xmlns.com/foaf/0.1/>

      DELETE {

        GRAPH ?g {
          ?persoon a foaf:Person;
             foaf:member <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> ;
             foaf:account ?account;
             ?persoonP ?persoonO.

          ?account ?accountP ?accountO.
        }

      } WHERE {

        GRAPH ?g {
          ?persoon a foaf:Person;
             foaf:member <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> ;
             foaf:account ?account;
             ?persoonP ?persoonO.

          ?account ?accountP ?accountO.
        }
      }
