PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
      PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
      PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
      PREFIX dcterms: <http://purl.org/dc/terms/>
      PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
      PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
      PREFIX foaf: <http://xmlns.com/foaf/0.1/>

      INSERT {
        GRAPH ?g {
           ?persoon a foaf:Person;
                 mu:uuid ?uuidPersoon;
                 foaf:firstName ?classificatie;
                 foaf:familyName ?naam;
                 foaf:member <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> ;
                 foaf:account ?account.
           ?account a foaf:OnlineAccount;
                 mu:uuid ?uuidAccount;
                 foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
                 ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker", "LoketLB-berichtenGebruiker", "LoketLB-leidinggevendenGebruiker", "LoketLB-personeelsbeheer", "LoketLB-subsidies".
        }
      } WHERE {
           <http://data.lblod.info/id/bestuurseenheden/e0920e46-85b9-4736-a906-b254cc7f1855> a besluit:Bestuurseenheid;
           skos:prefLabel ?naam;
           besluit:classificatie/skos:prefLabel ?classificatie.
           BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
           BIND(MD5(?volledigeNaam) as ?uuidPersoon)
           BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
           BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
           BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

           VALUES ?g {
              <http://mu.semte.ch/graphs/organizations/e0920e46-85b9-4736-a906-b254cc7f1855>
              <http://mu.semte.ch/graphs/public>
           }
      }
