PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct:  <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/b6a991c7-e126-4f9e-a956-4a4684502ba6>
        a skos:ConceptScheme, rdfs:Class ;
        mu:uuid "b6a991c7-e126-4f9e-a956-4a4684502ba6" ;
        dct:title "publication-event-types"@en ;
        dct:title "publicatie-event-types"@nl ;
        dct:definition """Type of publication events that could occur."""@en ;
        dct:definition """Type publicatiegebeurtenissen dat kunnen plaatsvinden."""@nl .

    <http://lblod.data.gift/concepts/83f7b480-fcaf-4795-b603-7f3bce489325>
        a skos:Concept, rdfs:Class;
        mu:uuid "83f7b480-fcaf-4795-b603-7f3bce489325" ;
        skos:prefLabel "Publicatie op de publieke beslissings database"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b6a991c7-e126-4f9e-a956-4a4684502ba6> .
  }
}
