PREFIX mg8: <http://data.europa.eu/m8g/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Period of step Proposal
     <http://data.lblod.info/id/periodes/ce0ad95a-baba-42df-9d94-28f0d83e0ed7> mg8:endTime "2022-10-15T21:59:00Z"^^xsd:dateTime .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://data.lblod.info/id/periodes/ce0ad95a-baba-42df-9d94-28f0d83e0ed7> mg8:endTime "2022-11-15T21:59:00Z"^^xsd:dateTime.
  }
}