PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX ext:     <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>

INSERT {
  GRAPH ?g {
    ?persoon
      a               foaf:Person ;
      mu:uuid         ?uuidPersoon ;
      foaf:firstName  ?classificatie ;
      foaf:familyName ?naam ;
      foaf:member     <http://data.lblod.info/id/bestuurseenheden/b25f4408-0b7c-46d0-a234-0936cac4eb7c> ;
      foaf:account    ?account .

    ?account
      a                           foaf:OnlineAccount ;
      mu:uuid                     ?uuidAccount ;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> ;
      ext:sessionRole             "LoketLB-leidinggevendenGebruiker" , "LoketLB-mandaatGebruiker" , "LoketLB-subsidies" , "LoketLB-toezichtGebruiker" , "LoketLB-ContactOrganisatiegegevensGebruiker" , "LoketLB-bbcdrGebruiker" , "LoketLB-berichtenGebruiker" , "LoketLB-personeelsbeheer" , "LoketLB-LPDCGebruiker" .
  }
}
WHERE {
  <http://data.lblod.info/id/bestuurseenheden/b25f4408-0b7c-46d0-a234-0936cac4eb7c>
    a                                     besluit:Bestuurseenheid ;
    skos:prefLabel                        ?naam ;
    besluit:classificatie/skos:prefLabel  ?classificatie .

  BIND(CONCAT(?classificatie, " ", ?naam) AS ?volledigeNaam)
  BIND(MD5(?volledigeNaam) AS ?uuidPersoon)
  BIND(MD5(CONCAT(?volledigeNaam, "ACCOUNT")) AS ?uuidAccount)
  BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
  BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

  VALUES ?g {
    <http://mu.semte.ch/graphs/organizations/b25f4408-0b7c-46d0-a234-0936cac4eb7c>
    <http://mu.semte.ch/graphs/public>
  }
}
