# Those triples have a notion of versionning.
# We will delete them if they are old enough and have a more recent version of them.
# That way we ensure keeping at least one version, even if it's an old one.

# Reports : comparing on the title to find same type reports, deleting the ones older
# than a month and with a more recent version of the same type.

# The query is heavy, so splitting on title.

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having two start dates" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having two start dates" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having two end dates" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having two end dates" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having no start date" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having no start date" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having no person linked" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen having no person linked" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen linked to an empty person" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List mandatarissen linked to an empty person" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 2, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 2, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 1, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 1, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 4, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 4, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 3, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report oproep 3, step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-11-30"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of GzG Report step 1" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}
