PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX m8g: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2697fbe1-4226-4325-807b-5dfa58e40a95>
      lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/5ff552d1-6e96-4a7c-aa06-8188bd047aef> ;
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/6e6b1f8a-0758-42e8-95e6-bec36e04864e> .

    <http://lblod.data.info/id/subsidy-measure-offer-series/5ff552d1-6e96-4a7c-aa06-8188bd047aef>
      a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
      mu:uuid "5ff552d1-6e96-4a7c-aa06-8188bd047aef" ;
      dct:title "Zomer 2021"@nl ;
      dct:description "Zomer 2021 (1 april 2021 — 31 augustus 2021)"@nl ;
      common:active <http://lblod.data.info/id/subsidie-application-flows/3fae7ac3-ef14-4d4e-b2bf-79a07347eb07> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/72069cd1-bfe2-4464-a9e6-ce2c7185b68c> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/6e6b1f8a-0758-42e8-95e6-bec36e04864e> .

    <http://lblod.data.info/id/subsidie-application-flows/3fae7ac3-ef14-4d4e-b2bf-79a07347eb07>
      a lblodSubsidie:ApplicationFlow ;
      mu:uuid "3fae7ac3-ef14-4d4e-b2bf-79a07347eb07" ;
      xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/5ff552d1-6e96-4a7c-aa06-8188bd047aef> ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/19633dda-cdc5-4488-bdad-02f08bb15a63> .

    <http://lblod.data.info/id/subsidie-application-flow-steps/19633dda-cdc5-4488-bdad-02f08bb15a63>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "19633dda-cdc5-4488-bdad-02f08bb15a63" ;
      qb:order 0;
      dct:source <config://forms/contact-tracing/versions/20210617184000-summer-update/form.ttl> ;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/6e6b1f8a-0758-42e8-95e6-bec36e04864e> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/3fae7ac3-ef14-4d4e-b2bf-79a07347eb07> .

    <http://data.lblod.info/id/periodes/72069cd1-bfe2-4464-a9e6-ce2c7185b68c>
      a m8g:PeriodOfTime ;
      mu:uuid "72069cd1-bfe2-4464-a9e6-ce2c7185b68c" ;
      m8g:startTime "2021-04-01T00:00:00"^^xsd:dateTime ;
      m8g:endTime "2021-08-31T00:00:00"^^xsd:dateTime .

    <http://data.lblod.info/id/subsidy-procedural-steps/6e6b1f8a-0758-42e8-95e6-bec36e04864e>
      a subsidie:Subsidieprocedurestap ;
      mu:uuid "6e6b1f8a-0758-42e8-95e6-bec36e04864e" ;
      dct:description """Aanvraag""" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/b00f2fa2-9ca4-453d-9fa4-de1f57b627ae> .

    <http://data.lblod.info/id/periodes/b00f2fa2-9ca4-453d-9fa4-de1f57b627ae>
      a m8g:PeriodOfTime ;
      mu:uuid "b00f2fa2-9ca4-453d-9fa4-de1f57b627ae" ;
      m8g:startTime "2021-04-01T00:00:00"^^xsd:dateTime ;
      m8g:endTime "2021-10-31T00:00:00"^^xsd:dateTime .
  }
}
