PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/dcfb437e-1219-4d1e-891d-057f262da9d6>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://mu.semte.ch/vocabularies/core/uuid> "dcfb437e-1219-4d1e-891d-057f262da9d6" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> """All administrative-units with as besluit:classficatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>"""@en .
  }
}
;
INSERT {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?s skos:inScheme <http://lblod.data.gift/concept-schemes/dcfb437e-1219-4d1e-891d-057f262da9d6>.
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?s a besluit:Bestuurseenheid ;
       	    besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .
    }
}


