INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/dd44f316-7a30-45ab-b0f3-5dd642e0b6c7>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "dd44f316-7a30-45ab-b0f3-5dd642e0b6c7" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> """additional contact tracing measures"""@en .

    <http://lblod.data.gift/concepts/6d28bd69-ff30-4539-9a79-4faec57a1156>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "6d28bd69-ff30-4539-9a79-4faec57a1156" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Awareness raising, prevention, source tracing, quarantine coaching"@en ; # TODO
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/dd44f316-7a30-45ab-b0f3-5dd642e0b6c7> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Sensibilisering, preventie, bronopsporing, quarantaine coaching"@nl .

    <http://lblod.data.gift/concepts/2e0b5013-8c7e-4d3d-9f2b-2460c0095e38>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "2e0b5013-8c7e-4d3d-9f2b-2460c0095e38" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Awareness raising, prevention, source tracing, quarantine coaching and contact investigation"@en ; # TODO
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/dd44f316-7a30-45ab-b0f3-5dd642e0b6c7> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Sensibilisering, preventie, bronopsporing, quarantaine coaching en contactonderzoek"@nl .

    <http://lblod.data.gift/concepts/eb99fc40-4a7e-4544-80ab-20d00dd3a0c4> #
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "eb99fc40-4a7e-4544-80ab-20d00dd3a0c4" ;
        <http://www.w3.org/2004/02/skos/core#definition> "No additional"@en ; # TODO
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/dd44f316-7a30-45ab-b0f3-5dd642e0b6c7> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Geen bijkomende inzet"@nl .
  }
}
