INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2697fbe1-4226-4325-807b-5dfa58e40a95>
        a   <http://www.w3.org/2000/01/rdf-schema#Class>,
            <http://www.w3.org/2004/02/skos/core#Concept>,
            <http://www.w3.org/2004/02/skos/core#ConceptScheme>,
            <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
        <http://mu.semte.ch/vocabularies/core/uuid> "2697fbe1-4226-4325-807b-5dfa58e40a95" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Subsidy measure offer: contact and source tracking"@en;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/33e233eb-6a9b-4141-b607-2ff72fe2ded2>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Contact-en bronopsporing"@nl ;
        <http://purl.org/dc/terms/title> "Contact-en bronopsporing"@nl .
  }
}
