DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f> .
    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f> .
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f> .
    <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f> .
    <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://mu.semte.ch/vocabularies/core/uuid> "a3293c46-06b7-458d-a15c-2f312294773f" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Subsidy time-blocks"@en .
   }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> a <http://www.w3.org/2004/02/skos/core#ConceptScheme> .
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> .
    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> .
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> .
    <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> .
   }
}
