PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "923b203c-b8e0-4f20-9076-c2381e0f4294" ;
      skos:prefLabel "IJzervallei" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0736658976" ;
      dcterms:identifier "OVO036417", "0736658976" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/2a4fefb9a88e5ccbea5c3f1b24ed5fbf>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"2a4fefb9a88e5ccbea5c3f1b24ed5fbf" ;
      skos:prefLabel "Directiecomité IJzervallei" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294> .

    <http://data.lblod.info/id/bestuursorganen/deb2f03b43e335ad9c790a7a8f63ac8c>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"deb2f03b43e335ad9c790a7a8f63ac8c" ;
      skos:prefLabel "Raad van bestuur IJzervallei" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294> .

    <http://data.lblod.info/id/bestuursorganen/0466c1def739c23a366facbcf9f0761d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"0466c1def739c23a366facbcf9f0761d" ;
      skos:prefLabel "Bevoegd beslissingsorgaan IJzervallei" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294> .

    <http://data.lblod.info/id/bestuursorganen/c95e353c416e68e6ba85bdba9f32224d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"c95e353c416e68e6ba85bdba9f32224d" ;
      skos:prefLabel "Algemene vergadering IJzervallei" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294> .

    <http://data.lblod.info/id/bestuursorganen/883ebefa0da5cef5dcc9494e0c345b6e>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"883ebefa0da5cef5dcc9494e0c345b6e" ;
      skos:prefLabel "Leidend Ambtenaar IJzervallei" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/a0a25af7f82f9193e9d18336c464c059>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"a0a25af7f82f9193e9d18336c464c059" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/2a4fefb9a88e5ccbea5c3f1b24ed5fbf> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/6913b8ef6ec06626724fddb6e315ae6b>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6913b8ef6ec06626724fddb6e315ae6b" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/deb2f03b43e335ad9c790a7a8f63ac8c> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/111f39918c947605b804788868bb9e59>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"111f39918c947605b804788868bb9e59" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/0466c1def739c23a366facbcf9f0761d> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/f3d26c2328a4afbfbaa79a20e9cd57ac>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"f3d26c2328a4afbfbaa79a20e9cd57ac" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/c95e353c416e68e6ba85bdba9f32224d> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/f09e884c4ffa87d29fa18241cadc0f91>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"f09e884c4ffa87d29fa18241cadc0f91" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/883ebefa0da5cef5dcc9494e0c345b6e> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
