PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX task: <http://redpencil.data.gift/vocabularies/tasks/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX oslc: <http://open-services.net/ns/core#>
PREFIX cogs: <http://vocab.deri.ie/cogs#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX dbpedia: <http://dbpedia.org/resource/>


DELETE {
  GRAPH ?g {
    ?job ?jobP ?jobO.
    ?task ?taskP ?taskO.
    ?container ?containerP ?containerO.
 }
} WHERE {
  VALUES ?operation {
    <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/op-public>
    <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/op-public>
  }

  GRAPH ?g {
    {
      ?job a <http://vocab.deri.ie/cogs#Job>;
        task:operation ?operation;
        ?jobP ?jobO.

      ?task dct:isPartOf ?job;
      task:resultsContainer ?container;
      ?taskP ?taskO.

      ?container a nfo:DataContainer;
        ?containerP ?containerO.
    }
    UNION
    {
      ?job a <http://vocab.deri.ie/cogs#Job>;
        task:operation ?operation;
        ?jobP ?jobO.

      ?task dct:isPartOf ?job;
      ?taskP ?taskO.
    }
  }
}
