DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuursorganen/53e96e3b-3ace-463a-bf31-4a8ce363e355> <http://www.w3.org/2004/02/skos/core#prefLabel> "POLITIEZONE CARMA: AS - BOCHOLT - BREE - GENK- HOUTHALEN-HELCHTEREN - KINROOI - OUDSBERGEN - ZUTENDAAL" .
    <http://data.lblod.info/id/bestuursorganen/53e96e3b-3ace-463a-bf31-4a8ce363e355> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/1afce932-53c1-46d8-8aab-90dcc331e67d> .
    <http://data.lblod.info/id/bestuurseenheden/e7692f99-9a36-43e3-af78-b320390318dc> <http://www.w3.org/2004/02/skos/core#prefLabel> "Lokale politiezone Carma : As/Bochlot/Bree/Genk/Houthalen-Helchteren/Kinrooi/Oudsbergen/Zutendaal" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuursorganen/53e96e3b-3ace-463a-bf31-4a8ce363e355> <http://www.w3.org/2004/02/skos/core#prefLabel> "Politieraad POLITIEZONE CARMA: AS - BOCHOLT - BREE - GENK- HOUTHALEN-HELCHTEREN - KINROOI - OUDSBERGEN - ZUTENDAAL" .
    <http://data.lblod.info/id/bestuursorganen/53e96e3b-3ace-463a-bf31-4a8ce363e355> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/a9e30e31-0cd2-4f4a-9352-545c5d43be83> .
    <http://data.lblod.info/id/bestuurseenheden/e7692f99-9a36-43e3-af78-b320390318dc> <http://www.w3.org/2004/02/skos/core#prefLabel> "POLITIEZONE CARMA: AS - BOCHOLT - BREE - GENK- HOUTHALEN-HELCHTEREN - KINROOI - OUDSBERGEN - ZUTENDAAL" .
  }
}