PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8c8fb770-1b84-4d18-8bcc-3ed9440476d5" ;
      skos:prefLabel "VARIANT" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0738732697" ;
      dcterms:identifier "OVO038851", "0738732697" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/efa0441afd2191afe9fd7bb5c9a804a2>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"efa0441afd2191afe9fd7bb5c9a804a2" ;
      skos:prefLabel "Directiecomité VARIANT" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5> .

    <http://data.lblod.info/id/bestuursorganen/a95c935e1187f5de4dc0ddb95e04ee58>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"a95c935e1187f5de4dc0ddb95e04ee58" ;
      skos:prefLabel "Raad van bestuur VARIANT" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5> .

    <http://data.lblod.info/id/bestuursorganen/6c73e72e5cc5449d283aba3c80a734eb>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"6c73e72e5cc5449d283aba3c80a734eb" ;
      skos:prefLabel "Bevoegd beslissingsorgaan VARIANT" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5> .

    <http://data.lblod.info/id/bestuursorganen/8139736b6d0ea9fc704abe817d76ef31>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"8139736b6d0ea9fc704abe817d76ef31" ;
      skos:prefLabel "Algemene vergadering VARIANT" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5> .

    <http://data.lblod.info/id/bestuursorganen/e6bf96a96c194438a3c1bd9c3a99351d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"e6bf96a96c194438a3c1bd9c3a99351d" ;
      skos:prefLabel "Leidend Ambtenaar VARIANT" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/40672f06d55a5d9c4c5edc91075590b5>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"40672f06d55a5d9c4c5edc91075590b5" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/efa0441afd2191afe9fd7bb5c9a804a2> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/84e674911c00724b7c39d77917c71994>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "84e674911c00724b7c39d77917c71994" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/a95c935e1187f5de4dc0ddb95e04ee58> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/6db6cf8db1eb21510968488c67d0996a>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"6db6cf8db1eb21510968488c67d0996a" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/6c73e72e5cc5449d283aba3c80a734eb> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/8b73831070100f4a617e0f0cba4f2496>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"8b73831070100f4a617e0f0cba4f2496" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/8139736b6d0ea9fc704abe817d76ef31> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/ce8ae39e90947bfc75be42d0ef817127>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"ce8ae39e90947bfc75be42d0ef817127" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/e6bf96a96c194438a3c1bd9c3a99351d> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
