INSERT {
  GRAPH ?g {
    ?subsidy <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/80301a63-927c-48e5-8678-048c87c25847> # Allow VGC criterion
  }
} WHERE {
 BIND(<http://lblod.data.info/id/subsidy-measure-offers/80737eb2-4f1b-4a0b-b8c7-3f69d296b6a3> as ?subsidy) # Thematische subsidy
  GRAPH ?g {
    ?subsidy a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>
  }
}