PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca> a skos:ConceptScheme ;
      mu:uuid "19c53ee2-bac1-4ce8-8015-6ff589ccfaca" ;
      skos:prefLabel "Worship services sensitive export" .

    #Bestuurseenheden
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Bestuur van de eredienst
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/f9cac08a-13c1-49da-9bcb-f650b0604054> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Centraal bestuur van de eredienst
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Bestuur van de eredienst

    #Bestuursorganen
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/04f65457bf125b2dc59fd71917ac3d08> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Kerkraad
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/af811edba97c6ec34874d0830cbb1183> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Kerkfabriekraad
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/a0701624aefb115b7eda2ff39139c2dd> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Kathedrale kerkraad
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0d985699479162198b889f10e4f1a8ce> skos:inScheme <http://lblod.data.gift/concept-schemes/19c53ee2-bac1-4ce8-8015-6ff589ccfaca>. # Centraal kerkbestuur
  }
}