PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/accounts/deltas> {
    <http://data.lblod.info/foaf/account/id/f185b63e-5bd9-40a5-8906-4ac1fb5a8db7>
      a foaf:OnlineAccount.

    <http://data.lblod.info/foaf/agent/id/acac91b8-9f53-41a7-9614-6d2e08446b0a>
      a foaf:Agent;
      foaf:account <http://data.lblod.info/foaf/account/id/f185b63e-5bd9-40a5-8906-4ac1fb5a8db7>.

    <http://data.lblod.info/foaf/group/id/c59564df-8a3e-4834-bda4-ceca83e1dad7>
      a foaf:Group;
      foaf:member <http://data.lblod.info/foaf/agent/id/acac91b8-9f53-41a7-9614-6d2e08446b0a>;
      foaf:name "worship-services-sensitive-deltas".
  }
}