PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX org: <http://www.w3.org/ns/org#>
#########################################################
# GEMEENTEBESTUUR
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(?bestuursorgaan), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
    (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/39e08271-68db-4282-897f-5cba88c71862> )# algemeen directeur
    (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> ) # adjunct algemeen directeur
    (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/6d4cf4dd-2080-4752-8733-d02a036b2df0>) # financieel directeur
    (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789>) # adjunct financieel directeur
  }
};
#########################################################
# Provincie
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(?bestuursorgaan), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
      (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab19107-82d2-4273-a986-3da86fda050d> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/63195ec6-02cb-4f86-ac8e-29c5183a11dc>) # Grifier
      (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/3e9f22c1-0d35-445b-8a37-494addedf2d8> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/b213c870-c762-4e39-9f78-3abdeda4b64a>) # financieel beheerder
  }
};
#########################################################
# AGB APB Intergemeentelijk samenwerkings verband OCMW vereniging
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(?bestuursorgaan), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
  (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f>) # leidend ambtenaar
  }
}