PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

#########################################################
# GEMEENTEBESTUUR
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.
  }
  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa>
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc>
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35>
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0>
  }
};
#########################################################
# Provincie
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>.
  }
  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab19107-82d2-4273-a986-3da86fda050d>
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/3e9f22c1-0d35-445b-8a37-494addedf2d8>
  }
};
#########################################################
# AGB
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>.
  }
    FILTER (NOT EXISTS {
                ?bestuursorgaan a besluit:Bestuursorgaan .
                ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
                ?bestuursorgaan besluit:classificatie ?classificatie.
                })
  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4>
  }
};
#########################################################
# APB
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>.
  }
      FILTER (NOT EXISTS {
                ?bestuursorgaan a besluit:Bestuursorgaan .
                ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
                ?bestuursorgaan besluit:classificatie ?classificatie.
                })
  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4>
  }
};
#########################################################
# Intergemeentelijk samenwerkings verband
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004>.
  }
    FILTER (NOT EXISTS {
                ?bestuursorgaan a besluit:Bestuursorgaan .
                ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
                ?bestuursorgaan besluit:classificatie ?classificatie.
                })

  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4>      
  }
};

#########################################################
# OCMW vereniging
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
    ?bestuursorgaan mu:uuid ?uuid .
    ?bestuursorgaan skos:prefLabel ?naam .
    ?bestuursorgaan besluit:classificatie ?classificatie.
    ?bestuursorgaanInTijd a besluit:Bestuursorgaan .
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursorgaanInTijd mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaanInTijd mu:uuid ?uuidInTijd .

  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
       skos:prefLabel ?bestuurseenheidLabel;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089>.
  }
  ?classificatie skos:prefLabel ?classificatieLabel;
                 mu:uuid ?classificatieUuid.
  BIND(SHA256(CONCAT("zoht5shohshohw8ChaesAhMah8thudoh4chaGoiwfea3cah8ofaequae$Quu", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(CONCAT(?classificatieLabel, ?bestuurseenheidLabel) AS ?bestuursorgaanNaam).
  BIND(SHA256(CONCAT("yi5cheiReeph9seesah8vaiSaidie5bahzah9Oxeum3eS6er5ohL0iewoo4h", ":", STR(?bestuurseenheid), ?classificatieUuid )) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
  VALUES ?classificatie {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4>
  }
  FILTER (NOT EXISTS {
                ?bestuursorgaan a besluit:Bestuursorgaan .
                ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
                ?bestuursorgaan besluit:classificatie ?classificatie.
  })
}