DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?src ?refers ?s.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/org#Post>.
    ?s ?p ?o.
    OPTIONAL { ?src ?refers ?s }
  }
}

;

DELETE DATA {
GRAPH <http://mu.semte.ch/graphs/public/> {
<http://data.vlaanderen.be/id/concept/functionarisRol/45dff078-95f3-4b5f-a475-aa9dd857ae0a> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "45dff078-95f3-4b5f-a475-aa9dd857ae0a";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "algemeen directeur".

<http://data.vlaanderen.be/id/concept/functionarisRol/783917b6-89ca-4ab2-8656-9ca960061ab1> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "783917b6-89ca-4ab2-8656-9ca960061ab1";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "adjunct-algemeen directeur".

<http://data.vlaanderen.be/id/concept/functionarisRol/f0bf6754-e5e2-479c-824f-865cbca19241> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "f0bf6754-e5e2-479c-824f-865cbca19241";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "financieel directeur".

<http://data.vlaanderen.be/id/concept/functionarisRol/1dd348cd-ce46-4aa3-8ad1-16a6e35dc81a> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "1dd348cd-ce46-4aa3-8ad1-16a6e35dc81a";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "adjunct-financieel directeur".

<http://data.vlaanderen.be/id/concept/functionarisRol/9ece500e-ed34-4e8b-8c77-40fa68c1c240> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "9ece500e-ed34-4e8b-8c77-40fa68c1c240";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "leidend ambtenaar".

<http://data.vlaanderen.be/id/concept/functionarisRol/ae519a4c-0bb7-4278-91a8-a09967ef535b> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "c2543ec5-4075-4619-9f45-037256cec57a";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "griffier".

<http://data.vlaanderen.be/id/concept/functionarisRol/cb447355-f7c1-4406-88aa-081d529ad2d5> a <http://www.w3.org/ns/org#Role>;
  <http://mu.semte.ch/vocabularies/core/uuid> "cb447355-f7c1-4406-88aa-081d529ad2d5";
  <http://www.w3.org/2004/02/skos/core#prefLabel> "financieel beheerder".
}};

DELETE DATA {
GRAPH <http://mu.semte.ch/graphs/public/> {
<http://data.vlaanderen.be/id/concept/functionarisStatusCode/45b4b155-d22a-4eaf-be3a-97022c6b7fcd> a <http://data.lblod.info/vocabularies/lblod/FunctionarisStatusCode>.
<http://data.vlaanderen.be/id/concept/functionarisStatusCode/188fc9c0-dae7-43b2-b2b3-6122c1594479> a <http://data.lblod.info/vocabularies/lblod/FunctionarisStatusCode>.
}};

INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/public/> {
<http://data.vlaanderen.be/id/concept/functionarisStatusCode/45b4b155-d22a-4eaf-be3a-97022c6b7fcd> a <http://data.lblod.info/vocabularies/leidinggevenden/FunctionarisStatusCode>.
<http://data.vlaanderen.be/id/concept/functionarisStatusCode/188fc9c0-dae7-43b2-b2b3-6122c1594479> a <http://data.lblod.info/vocabularies/leidinggevenden/FunctionarisStatusCode>.
}}