services:
  deltanotifier:
    image: nvdk/mu-delta-notifier:1.1.0
  database:
    image: semtech/sparql-parser:0.0.15
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
      LISP_DYNAMIC_SPACE_SIZE: 16384
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data/
  cache:
    image: semtech/mu-cache:2.0.2
  resource:
    image: semtech/mu-cl-resources:1.27.2