DELETE {
    GRAPH ?g {
        ?s ?p ?o .
    }
} WHERE {
    GRAPH ?g {
        VALUES ?s {
            <share://versions/20201130150729-form>
            <share://versions/20201207135752-form>
            <share://versions/20210108094916-form>
            <share://versions/20210113150324-form>
            <share://versions/20210113153339-form>
            <share://versions/20210121152225-introduction-subsidy-form-contact-tracing>
        }
        ?s ?p ?o .
    }
}