PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?h {
    ?s skos:prefLabel ?o .
  }
} INSERT {
  GRAPH ?h {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>  skos:prefLabel  "Herfstvakantie (09 november 2020 — 13 november 2020)"@nl .
    <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848>  skos:prefLabel  "Winter 2020 (16 november 2020 - 31 december 2020)"@nl .
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>  skos:prefLabel	"Winter 2021 (01 januari 2021 - 12 februari 2020)"@nl .
    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257>  skos:prefLabel	"Kerstvakantie (21 december 2020 — 03 januari 2021)"@nl .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?s {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
    <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848>
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257>
    }
    ?s skos:prefLabel ?o .
  }
  BIND(?g as ?h)
}