INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

      <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
         <http://www.w3.org/2004/02/skos/core#prefLabel> "Explanation type LEKP"@en,
         "Type Toelichting LEKP"@nl .
<http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85> <http://mu.semte.ch/vocabularies/core/uuid> "0b93ef1c-4435-4922-8611-31b4f3ca3c85".


      <http://lblod.data.gift/concepts/88cde908-912d-4acc-a4cc-60e6549864d1> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Toelichting - tekst en cijfers zijn correct maar dienen toegelicht te worden"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85> .

<http://lblod.data.gift/concepts/f6084275-751d-4bf7-a744-904247571f64> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Correctie - tekst of cijfers zijn verkeerd"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85> .

<http://lblod.data.gift/concepts/dda522c7-a5e7-4952-926f-94bc742b5b85> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Aanvulling - tekst en cijfers kunnen aangevuld worden"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/0b93ef1c-4435-4922-8611-31b4f3ca3c85> .

<http://lblod.data.gift/concepts/88cde908-912d-4acc-a4cc-60e6549864d1> <http://mu.semte.ch/vocabularies/core/uuid> "88cde908-912d-4acc-a4cc-60e6549864d1".

<http://lblod.data.gift/concepts/f6084275-751d-4bf7-a744-904247571f64> <http://mu.semte.ch/vocabularies/core/uuid> "f6084275-751d-4bf7-a744-904247571f64".

<http://lblod.data.gift/concepts/dda522c7-a5e7-4952-926f-94bc742b5b85> <http://mu.semte.ch/vocabularies/core/uuid> "dda522c7-a5e7-4952-926f-94bc742b5b85".




  }
}