INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {


      <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "LEKP-Goal"@en,
     "LEKP-doelstelling"@nl .

<http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> <http://mu.semte.ch/vocabularies/core/uuid> "5d05a003-4692-4aff-9e93-325db2aefb8a".

    <http://lblod.data.gift/concepts/2d39e883-336c-4c6f-99cb-73ffd5030bfc> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 1: Vergroening - Bomen"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/59f0da6e-aa99-413c-86ef-413039855046> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 1: Vergroening - Haag of geveltuinbeplanting"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/bbafc2df-34bd-4e38-9f18-f920ad9312ad> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 1: Vergroening - Natuurgroenperken"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/bd65603a-83a4-4256-ac87-b79a45a1fc51> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 2: Verrijk je wijk - Collectieve renovaties"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/cbaf5b3a-b255-44d0-8658-40f0eecf6f0f> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 2: Klimaattafels"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/b0d6ef6f-1d56-4c83-a5b9-f06eadfb48ee> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 2: Verrijk je wijk - Coöperatieve hernieuwbare energieprojecten"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/2b81fc8c-6539-4669-9206-c4b03b1b7626> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 3: Mobiliteit - Deelsystemen"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/1ad0d2ca-081f-49c0-8007-54f9b82f8ac2> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 3: Mobiliteit - Laadpunten"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/1ffeaaf3-8328-4ae0-8ff5-35ababf2c6ba> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 3: Mobiliteit - Fietspaden"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/166fda59-21ee-41fb-86a5-402eff1107a7> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 4: Droogte - Ontharding"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/8d6b745c-418b-437a-b900-042087093a9b> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 4: Droogte - Hemelwateropvang"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/2b36d596-ea7c-4d40-b597-7de1dbdd2bf9> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - Burgemeestersconvenant"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/73ab8fa4-dede-4a48-90f4-9519825d5813> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - Energiebesparing lokaal patrimonium"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/0cf892d4-b49b-4da8-80b4-3ecb7b1854e2> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - Reductie CO2-uitstoot lokaal patrimonium"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/64ab9463-0f5b-4dc2-aba0-cc1d72e760a2> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - verLEDing"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/9b187f89-1c0c-4638-a86e-46ed735573d3> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - Geen heffing op hernieuwbare energie"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .

<http://lblod.data.gift/concepts/91441419-3d3b-4932-ac68-6cd8d53b04f3> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemene doelstellingen - Lokaal warmte- en sloopbeleid"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/5d05a003-4692-4aff-9e93-325db2aefb8a> .


<http://lblod.data.gift/concepts/2d39e883-336c-4c6f-99cb-73ffd5030bfc>  <http://mu.semte.ch/vocabularies/core/uuid> "2d39e883-336c-4c6f-99cb-73ffd5030bfc".

<http://lblod.data.gift/concepts/59f0da6e-aa99-413c-86ef-413039855046>  <http://mu.semte.ch/vocabularies/core/uuid> "59f0da6e-aa99-413c-86ef-413039855046".

<http://lblod.data.gift/concepts/bbafc2df-34bd-4e38-9f18-f920ad9312ad>  <http://mu.semte.ch/vocabularies/core/uuid> "bbafc2df-34bd-4e38-9f18-f920ad9312ad".

<http://lblod.data.gift/concepts/bd65603a-83a4-4256-ac87-b79a45a1fc51>  <http://mu.semte.ch/vocabularies/core/uuid> "bd65603a-83a4-4256-ac87-b79a45a1fc51".

<http://lblod.data.gift/concepts/cbaf5b3a-b255-44d0-8658-40f0eecf6f0f> <http://mu.semte.ch/vocabularies/core/uuid> "cbaf5b3a-b255-44d0-8658-40f0eecf6f0f".

<http://lblod.data.gift/concepts/b0d6ef6f-1d56-4c83-a5b9-f06eadfb48ee> <http://mu.semte.ch/vocabularies/core/uuid> "b0d6ef6f-1d56-4c83-a5b9-f06eadfb48ee".

<http://lblod.data.gift/concepts/2b81fc8c-6539-4669-9206-c4b03b1b7626> <http://mu.semte.ch/vocabularies/core/uuid> "2b81fc8c-6539-4669-9206-c4b03b1b7626".

<http://lblod.data.gift/concepts/1ad0d2ca-081f-49c0-8007-54f9b82f8ac2> <http://mu.semte.ch/vocabularies/core/uuid> "1ad0d2ca-081f-49c0-8007-54f9b82f8ac2".

<http://lblod.data.gift/concepts/1ffeaaf3-8328-4ae0-8ff5-35ababf2c6ba> <http://mu.semte.ch/vocabularies/core/uuid> "1ffeaaf3-8328-4ae0-8ff5-35ababf2c6ba".

<http://lblod.data.gift/concepts/166fda59-21ee-41fb-86a5-402eff1107a7> <http://mu.semte.ch/vocabularies/core/uuid> "166fda59-21ee-41fb-86a5-402eff1107a7".

<http://lblod.data.gift/concepts/8d6b745c-418b-437a-b900-042087093a9b> <http://mu.semte.ch/vocabularies/core/uuid> "8d6b745c-418b-437a-b900-042087093a9b".

<http://lblod.data.gift/concepts/2b36d596-ea7c-4d40-b597-7de1dbdd2bf9> <http://mu.semte.ch/vocabularies/core/uuid> "2b36d596-ea7c-4d40-b597-7de1dbdd2bf9".

<http://lblod.data.gift/concepts/73ab8fa4-dede-4a48-90f4-9519825d5813> <http://mu.semte.ch/vocabularies/core/uuid> "73ab8fa4-dede-4a48-90f4-9519825d5813".

<http://lblod.data.gift/concepts/0cf892d4-b49b-4da8-80b4-3ecb7b1854e2> <http://mu.semte.ch/vocabularies/core/uuid> "0cf892d4-b49b-4da8-80b4-3ecb7b1854e2".

<http://lblod.data.gift/concepts/64ab9463-0f5b-4dc2-aba0-cc1d72e760a2> <http://mu.semte.ch/vocabularies/core/uuid> "64ab9463-0f5b-4dc2-aba0-cc1d72e760a2".

<http://lblod.data.gift/concepts/9b187f89-1c0c-4638-a86e-46ed735573d3> <http://mu.semte.ch/vocabularies/core/uuid> "9b187f89-1c0c-4638-a86e-46ed735573d3".

<http://lblod.data.gift/concepts/91441419-3d3b-4932-ac68-6cd8d53b04f3> <http://mu.semte.ch/vocabularies/core/uuid> "91441419-3d3b-4932-ac68-6cd8d53b04f3".




  }
}