INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

  <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Authentic source LEKP-report"@en, "Authentieke bron LEKP-report"@nl .
     <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> <http://mu.semte.ch/vocabularies/core/uuid> "c2e7699a-b543-443c-b8b2-b60bef8767dc".

  <http://lblod.data.gift/concepts/7ff9914a-517d-4af1-8896-f4256308722f> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Nieuwe (deel)databron"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/c3f26429-776b-4ae3-a608-dfbb0b2a2cbd> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Autodelen.net"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/f9fbf216-58fc-4083-a111-87c831999f1b> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Eco-movement"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/531a388c-4220-41a8-8399-250b3dd58e3a> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Energiekaart VEKA"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/84708640-241b-4758-bd52-46135bc9b333> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "Fluvius"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/2ec5db96-f1d6-499c-8c75-92d51ed68d12> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "MOW"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/540b3a69-3b01-49e4-9634-60b6ebe15869> a <http://www.w3.org/2004/02/skos/core#Concept>;
     <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc>;
     <http://www.w3.org/2004/02/skos/core#prefLabel> "VVSG"@nl;
     <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/c2e7699a-b543-443c-b8b2-b60bef8767dc> .

  <http://lblod.data.gift/concepts/7ff9914a-517d-4af1-8896-f4256308722f> <http://mu.semte.ch/vocabularies/core/uuid> "7ff9914a-517d-4af1-8896-f4256308722f".
  <http://lblod.data.gift/concepts/c3f26429-776b-4ae3-a608-dfbb0b2a2cbd> <http://mu.semte.ch/vocabularies/core/uuid> "c3f26429-776b-4ae3-a608-dfbb0b2a2cbd".
  <http://lblod.data.gift/concepts/f9fbf216-58fc-4083-a111-87c831999f1b> <http://mu.semte.ch/vocabularies/core/uuid> "f9fbf216-58fc-4083-a111-87c831999f1b".
  <http://lblod.data.gift/concepts/531a388c-4220-41a8-8399-250b3dd58e3a> <http://mu.semte.ch/vocabularies/core/uuid> "531a388c-4220-41a8-8399-250b3dd58e3a".
  <http://lblod.data.gift/concepts/84708640-241b-4758-bd52-46135bc9b333> <http://mu.semte.ch/vocabularies/core/uuid> "84708640-241b-4758-bd52-46135bc9b333".
  <http://lblod.data.gift/concepts/2ec5db96-f1d6-499c-8c75-92d51ed68d12> <http://mu.semte.ch/vocabularies/core/uuid> "2ec5db96-f1d6-499c-8c75-92d51ed68d12".
  <http://lblod.data.gift/concepts/540b3a69-3b01-49e4-9634-60b6ebe15869> <http://mu.semte.ch/vocabularies/core/uuid> "540b3a69-3b01-49e4-9634-60b6ebe15869".
  }
}