INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Correction type LEKP"@en,
        "Type correctie LEKP"@nl .

    <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14> <http://mu.semte.ch/vocabularies/core/uuid> "1dfc51af-99fd-4be9-a681-41360c195f14".


    <http://lblod.data.gift/concepts/626000ca-527d-49cd-8d40-fbef31e37a20> a <http://www.w3.org/2004/02/skos/core#Concept>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Correctie - informatie dient gecorrigeerd te worden"@nl;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14> .

    <http://lblod.data.gift/concepts/7afd0113-a7c4-4f7d-bef5-30dda3fddd60> a <http://www.w3.org/2004/02/skos/core#Concept>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Aanvulling - informatie dient aangevuld te worden"@nl;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14> .

    <http://lblod.data.gift/concepts/8576ab0c-461f-4f26-b3ba-cf1be4c7efb3> a <http://www.w3.org/2004/02/skos/core#Concept>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Schrapping - informatie dient geschrapt te worden"@nl;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/1dfc51af-99fd-4be9-a681-41360c195f14> .

    <http://lblod.data.gift/concepts/626000ca-527d-49cd-8d40-fbef31e37a20> <http://mu.semte.ch/vocabularies/core/uuid> "626000ca-527d-49cd-8d40-fbef31e37a20".

    <http://lblod.data.gift/concepts/7afd0113-a7c4-4f7d-bef5-30dda3fddd60> <http://mu.semte.ch/vocabularies/core/uuid> "7afd0113-a7c4-4f7d-bef5-30dda3fddd60".

    <http://lblod.data.gift/concepts/8576ab0c-461f-4f26-b3ba-cf1be4c7efb3> <http://mu.semte.ch/vocabularies/core/uuid> "8576ab0c-461f-4f26-b3ba-cf1be4c7efb3".





  }
}