PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20221006135946-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "67e4b475-8403-42bd-8611-37e17467e6b4" ;
      nfo:fileName "20221006135946-forms.ttl" ;
      dct:created "2022-10-06T13:59:46"^^xsd:dateTime ;
      dct:modified "2022-10-06T13:59:46"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "329461"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}