PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>

# Lokaal bestuurlijk talent - subsidieaanvraag
DELETE {
  GRAPH ?g {
    ?s m8g:endTime ?endTimeSubsidy .
  }
}
INSERT {
  GRAPH ?g {
    ?s m8g:endTime "2024-06-14T21:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?s {
      <http://data.lblod.info/id/periodes/08a297a6-cb71-462e-94cc-2a9d462f520c> # Subsidie periode
      <http://data.lblod.info/id/periodes/bec549e5-1f59-42d1-9325-3c8c8a10c5bb> # Stap periode
    }
    ?s m8g:endTime ?endTimeSubsidy .
  }
}