INSERT {
  GRAPH ?g {
    ?subsidy <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/80301a63-927c-48e5-8678-048c87c25847> # Allow VGC criterion
  }
} WHERE {
 BIND(<http://data.lblod.info/id/subsidy-measure-offers/e0b5d28a-041b-4ef9-bd45-c4f0d7da3298> as ?subsidy) # conceptsubsiie - stadsvernieuwing
  GRAPH ?g {
    ?subsidy a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>
  }
}