PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Update LEKP 1.0 Opvolgmoment 2024 deadline
DELETE {
  GRAPH ?g {
    ?s m8g:endTime ?endTimeSubsidy .
    ?s m8g:endTime ?endTimeStep .
  }
}
INSERT {
  GRAPH ?g {
    # Time is set to 21:59:00 because Belgium time is UTC+2 instead of UTC+1 in June.
    ?s m8g:endTime "2024-06-28T21:59:00Z"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?s {
      <http://data.lblod.info/id/periodes/d177ffb3-5934-4005-b481-5a424f136ec6> # LEKP 1.0 subsidy deadline
      <http://data.lblod.info/id/periodes/cea1f5f8-a659-4f59-886a-fe8f75cb2305> # LEKP 1.0 Opvolgmoment 2024 step deadline
    }
    ?s m8g:endTime ?endTimeSubsidy.
    ?s m8g:endTime ?endTimeStep .
  }
}
