PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Add new criterion for autonoom provinciebedrijf
    <http://data.lblod.info/id/criterions/d496bffa-363e-4c04-a4d1-bb88a71ddfff>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "d496bffa-363e-4c04-a4d1-bb88a71ddfff" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep autonoom provinciebedrijf (APB)" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/b38d9e20-a18d-4431-b07d-50a6334cc98c> .

    <http://data.lblod.info/id/requirement-groups/b38d9e20-a18d-4431-b07d-50a6334cc98c>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "b38d9e20-a18d-4431-b07d-50a6334cc98c" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een autonoom provinciebedrijf." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/6429a9c8-ae26-4fd1-b9ab-03519bef164c> .

    <http://data.lblod.info/id/criterion-requirement/6429a9c8-ae26-4fd1-b9ab-03519bef164c>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "6429a9c8-ae26-4fd1-b9ab-03519bef164c" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode autonoom provinciebedrijf." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d> .

    # Add new criterion for intercommunale (intergemeentelijk samenwerkingsverband)
    <http://data.lblod.info/id/criterions/8b9915bc-6668-4388-85ce-ba273a31fd4d>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "8b9915bc-6668-4388-85ce-ba273a31fd4d" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep intercommunale" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/8942326b-ea09-4289-8cf4-c39e12f8adda> .

    <http://data.lblod.info/id/requirement-groups/8942326b-ea09-4289-8cf4-c39e12f8adda>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "8942326b-ea09-4289-8cf4-c39e12f8adda" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een intercommunale." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/59552ee0-1ca1-46cb-a3d2-ac435b88787d> .

    <http://data.lblod.info/id/criterion-requirement/59552ee0-1ca1-46cb-a3d2-ac435b88787d>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "59552ee0-1ca1-46cb-a3d2-ac435b88787d" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode intercommunale." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .

    <http://data.lblod.info/id/subsidy-procedural-steps/f647d85b-9876-42b3-aab8-33d3bda0aade> a subsidie:Subsidieprocedurestap;
      mu:uuid "f647d85b-9876-42b3-aab8-33d3bda0aade";
      dct:description """Subsidieaanvraag""";
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6>;
      mobiliteit:periode  <http://data.lblod.info/id/periodes/bec549e5-1f59-42d1-9325-3c8c8a10c5bb>.

    # New application flow
    <http://data.lblod.info/id/subsidie-application-flows/ff2dc49d-b4d6-4684-86da-04544ece1742> a lblodSubsidie:ApplicationFlow;
      mu:uuid "ff2dc49d-b4d6-4684-86da-04544ece1742";
      xkos:belongsTo  <http://data.lblod.info/id/subsidy-measure-offer-series/f575ece7-2e2d-42bd-b307-30b2f90aed9f> ;
      xkos:next <http://data.lblod.info/id/subsidie-application-flow-steps/6e5cca42-3fe6-4491-bf42-cbd1faeac9b8> .

    <http://data.lblod.info/id/subsidie-application-flow-steps/6e5cca42-3fe6-4491-bf42-cbd1faeac9b8> a lblodSubsidie:ApplicationStep;
      mu:uuid "6e5cca42-3fe6-4491-bf42-cbd1faeac9b8";
      qb:order 0;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/f647d85b-9876-42b3-aab8-33d3bda0aade>;
      dct:isPartOf  <http://data.lblod.info/id/subsidie-application-flows/ff2dc49d-b4d6-4684-86da-04544ece1742>;
      dct:source <config://forms/lokaal-bestuurlijk-talent/proposal/versions/20240318151410/form.ttl>.

    # New subsidy step periode from 15 april 2024 (midnight) to 31 mei 2024
    <http://data.lblod.info/id/periodes/bec549e5-1f59-42d1-9325-3c8c8a10c5bb> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "bec549e5-1f59-42d1-9325-3c8c8a10c5bb";
      <http://data.europa.eu/m8g/startTime> "2024-04-14T22:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2024-05-31T21:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.

    # Create new subsidy and link to reeks
    <http://data.lblod.info/id/subsidy-measure-offers/5c4b2890-067e-451e-b4b5-5c616951b65c>
      a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
      mu:uuid "5c4b2890-067e-451e-b4b5-5c616951b65c";
      dct:title """Beurs Lokaal Bestuurlijk Talent""";
      skos:prefLabel """Beurs Lokaal Bestuurlijk Talent""";
      skos:related <https://www.vlaanderen.be/lokaal-bestuur/beurs-lokaal-bestuurlijk-talent>;
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/f5ea0615-0b0a-47db-a38c-6097ff80815d> ; # Add Gemeentes criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/3872dbf9-2b16-4b9e-a3cb-d2bd9b9d86d3> ; # Add Provincie criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/8c32faa4-1167-4fee-932f-3d453e59b09a> ; # Add OCMW criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/ece5bfcf-2c3f-401a-8176-0dac66ecbdad> ; # Add OCMW verenigingen (welzijnvserenigingen) criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/8b9915bc-6668-4388-85ce-ba273a31fd4d> ; # Add Intercommunale criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/72ada772-6e71-4eb3-85a6-c58539a13865> ; # Add autonoom gemeentebedrijf (AGB) criterion
      <http://data.europa.eu/m8g/hasCriterion> <http://data.lblod.info/id/criterions/d496bffa-363e-4c04-a4d1-bb88a71ddfff> ; # Add autonoom provinciebedrijf (APB) criterion
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/f647d85b-9876-42b3-aab8-33d3bda0aade> ;
      lblodSubsidie:heeftReeks <http://data.lblod.info/id/subsidy-measure-offer-series/f575ece7-2e2d-42bd-b307-30b2f90aed9f> .

    # New subsidiemaatergelaanbodreeks Oproep
    <http://data.lblod.info/id/subsidy-measure-offer-series/f575ece7-2e2d-42bd-b307-30b2f90aed9f> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      mu:uuid "f575ece7-2e2d-42bd-b307-30b2f90aed9f";
      dct:title "Oproep"@nl;
      dct:description ""@nl ;
      common:active <http://data.lblod.info/id/subsidie-application-flows/ff2dc49d-b4d6-4684-86da-04544ece1742> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/08a297a6-cb71-462e-94cc-2a9d462f520c> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/f647d85b-9876-42b3-aab8-33d3bda0aade>.

    # New subsidy periode from 15 april 2024 (midnight) to 31 mei 2024
    <http://data.lblod.info/id/periodes/08a297a6-cb71-462e-94cc-2a9d462f520c> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "08a297a6-cb71-462e-94cc-2a9d462f520c";
      <http://data.europa.eu/m8g/startTime> "2024-04-14T22:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2024-05-31T21:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "3f514a6a-094c-4a33-b1d1-c97e59e2844a" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Opleidingen | Beurs Lokaal Bestuurlijk Talent" ;
      <http://www.w3.org/2004/02/skos/core#note> "Deze lijst met opleidingen wordt gebruikt voor het formulier: Beurs Lokaal Bestuurlijk Talent" .

    <http://lblod.data.gift/concepts/9d07c5c1-e5c3-4f67-b5ee-e1802db8869a>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9d07c5c1-e5c3-4f67-b5ee-e1802db8869a" ;
      <http://purl.org/linked-data/cube#order> 1 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Executive Master in Public Governance & Leadership aan de Antwerp Management School" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a> .

    <http://lblod.data.gift/concepts/ac63d1c0-e89b-494d-b823-d3eb51094b59>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "ac63d1c0-e89b-494d-b823-d3eb51094b59" ;
      <http://purl.org/linked-data/cube#order> 2 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Master in de bestuurskunde en het publiek management aan de Universiteit van Gent" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a> .

    <http://lblod.data.gift/concepts/c33fdc82-e653-42a5-a81c-d945a71a3d3f>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "c33fdc82-e653-42a5-a81c-d945a71a3d3f" ;
      <http://purl.org/linked-data/cube#order> 3 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Master in de politieke wetenschappen: democratie en leiderschap aan de VUB." ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a> .

    <http://lblod.data.gift/concepts/76e88e6b-1863-4841-b439-ef92e0b2522d>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "76e88e6b-1863-4841-b439-ef92e0b2522d" ;
      <http://purl.org/linked-data/cube#order> 4 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Master in het publiek management en beleid aan de KU Leuven" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a> .

    <http://lblod.data.gift/concepts/81172753-a547-44ad-8d7a-c98af5fc528d>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "81172753-a547-44ad-8d7a-c98af5fc528d" ;
      <http://purl.org/linked-data/cube#order> 5 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Andere" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3f514a6a-094c-4a33-b1d1-c97e59e2844a> .
  }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/e311b861-d8aa-47a1-80e9-7f4a1fb3de09>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e311b861-d8aa-47a1-80e9-7f4a1fb3de09" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Onderzoeksvraag ja/nee" ;
      <http://www.w3.org/2004/02/skos/core#note> "Deze lijst geeft de mogelijkheid om te kunnen antwoorden met ja of nee." .

    <http://lblod.data.gift/concepts/7049d9db-de0f-4fb1-88e0-e1dc225258c1>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "7049d9db-de0f-4fb1-88e0-e1dc225258c1" ;
      <http://purl.org/linked-data/cube#order> 1 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Ja" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/e311b861-d8aa-47a1-80e9-7f4a1fb3de09> .

    <http://lblod.data.gift/concepts/f55e19a7-2564-4625-aac5-d7e135842fb8>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f55e19a7-2564-4625-aac5-d7e135842fb8" ;
      <http://purl.org/linked-data/cube#order> 2 ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Nee" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/e311b861-d8aa-47a1-80e9-7f4a1fb3de09> .
  }
}
