# ACCOUNTABILITY NOTE UPLOAD
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/accountability-note-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/accountabilityNoteUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}Z
;
# ACCOUNTABILITY PROOF
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/ukraine-nooddorpen/accountability-proof/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/accountabilityProof> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/ukraine-nooddorpen/accountability-summary/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/accountabilitySummary> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/award-report-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/awardReportUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/contact-tracing/contact-and-source-tracking-objective-four/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/contactAndSourceTrackingObjectiveFour> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/contact-tracing/contact-and-source-tracking-objective-one/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/contactAndSourceTrackingObjectiveOne> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/contact-tracing/contact-and-source-tracking-objective-three/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/contactAndSourceTrackingObjectiveThree> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/contact-tracing/contact-and-source-tracking-objective-two/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/contactAndSourceTrackingObjectiveTwo> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?contactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/ContactPoint> .
  }
}
WHERE {
  GRAPH ?g {
    ?s <http://schema.org/contactPoint> ?contactPoint .
    ?contactPoint ?p_c ?o_c .
  }

  FILTER NOT EXISTS {
    ?contactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/decision-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/decisionUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/invoice-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/invoiceUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/justification-costs-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/justificationCostsUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/justification-expropriations-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/justificationExpropriationsUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/pictures-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/picturesUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?politicalReferenceContactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://mu.semte.ch/vocabularies/ext/PoliticalReferenceContactPoint> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://mu.semte.ch/vocabularies/ext/politicalReferenceContactPoint> ?politicalReferenceContactPoint .
    ?politicalReferenceContactPoint ?p_p ?o_p .
  }

  FILTER NOT EXISTS {
    ?politicalReferenceContactPoint <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/report-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/reportUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/climate/signed-pact/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/signedPact> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT 
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/urban-renewal/urban-renewal-application-form/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/urbanRenewalApplicationForm> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/urban-renewal/urban-renewal-attachments/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/urbanRenewalAttachments> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
# ------------------
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/BankAccount> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://schema.org/bankAccount> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/climate/attachment/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/attachment> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
;
INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/climate/attachment/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/attachmentLEKPReport> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}