PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

# Their URIs have been created differently in OP and in Loket. To make it simple, I flush them and re add them.
# No big impact as it's not on prod yet.

DELETE {
  GRAPH ?g {
    ?orgaanInTime org:hasPost ?lidVanRechtswege .
    ?lidVanRechtswege ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?worshipService a ere:BestuurVanDeEredienst .
    ?orgaan besluit:bestuurt ?worshipService .

    ?orgaanInTime mandaat:isTijdspecialisatieVan ?orgaan ;
      org:hasPost ?lidVanRechtswege .

    ?lidVanRechtswege org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5972fccd87f864c4ec06bfbd20b5008b> ;
      ?p ?o .
  }
}
