PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX lblodOrg: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .

    ?ministerPosition a ere:PositieBedienaar ;
      mu:uuid ?ministerPositionUUID ;
      ere:functie ?ministerFunctie .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?type {
      ere:BestuurVanDeEredienst
      ere:CentraalBestuurVanDeEredienst
    }

    ?bestuurseenheid a ?type ;
      ere:wordtBediendDoor ?ministerPosition .

    ?ministerPosition a ere:PositieBedienaar ;
      mu:uuid ?ministerPositionUUID ;
      ere:functie ?ministerFunctie .
  }
}

;

DELETE {
  GRAPH ?g {
    ?ministerFunctie a lblodOrg:EredienstBeroepen ;
      mu:uuid ?ministerFunctieUUID ;
      skos:prefLabel ?ministerFunctieLabel ;
      skos:topConceptOf ?ministerFunctieTopConcept ;
      skos:inScheme ?ministerFunctieInScheme .
  }
} WHERE {
  GRAPH ?g {
    ?ministerFunctie a lblodOrg:EredienstBeroepen ;
      mu:uuid ?ministerFunctieUUID ;
      skos:prefLabel ?ministerFunctieLabel ;
      skos:topConceptOf ?ministerFunctieTopConcept ;
      skos:inScheme ?ministerFunctieInScheme .
  }
}
