PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

# For some reason I'm not able to change the start date to a date instead of datetime,
# so I do it in two steps

DELETE {
  GRAPH ?g {
    ?bestuursorgaanInTime
      mandaat:bindingStart "2023-04-02"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTime
      mandaat:bindingStart "2023-04-01"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?type {
      ere:BestuurVanDeEredienst
      ere:CentraalBestuurVanDeEredienst
    }

    ?bestuurseenheid a ?type .

    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid .

    ?bestuursorgaanInTime mandaat:isTijdspecialisatieVan ?bestuursorgaan ;
      mandaat:bindingStart "2023-04-02"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

DELETE {
  GRAPH ?g {
    ?bestuursorgaanInTime
      mandaat:bindingStart "2026-04-02"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTime
      mandaat:bindingStart "2026-04-01"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?type {
      ere:BestuurVanDeEredienst
      ere:CentraalBestuurVanDeEredienst
    }

    ?bestuurseenheid a ?type .

    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid .

    ?bestuursorgaanInTime mandaat:isTijdspecialisatieVan ?bestuursorgaan ;
      mandaat:bindingStart "2026-04-02"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}
