PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20220224134509-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "84cf3440-19d1-4af3-b843-1cbe9188581b" ;
      nfo:fileName "20220224134509-forms.ttl" ;
      dct:created "2022-02-24T13:45:09"^^xsd:dateTime ;
      dct:modified "2022-02-24T13:45:09"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "293741"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    