DELETE {
  GRAPH ?g {
   ?s ?p ?o.
  }
}
WHERE {

  GRAPH ?g {
    ?s <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>.
    ?s ?p ?o.
  }

}
