PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    #Voorzitter van het Bijzonder Comité voor de Sociale Dienst Aalter
    <http://data.lblod.info/id/bestuursorganen/c3eae08f-50f9-4a83-a25e-2705626a5681> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
    <http://mu.semte.ch/vocabularies/core/uuid> "c3eae08f-50f9-4a83-a25e-2705626a5681";
    <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2018-01-01"^^xsd:date;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/25958c1afdf1d35585ad2a68b6e7af2cb92e2a329e736d41ea1d223b68bfb888>.

   #Algemene vergadering Zorgbedrijf Vilvoorde
    <http://data.lblod.info/id/bestuursorganen/8ac3d8fa-14fb-4bf9-9068-173c4e5f6bcf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
    <http://mu.semte.ch/vocabularies/core/uuid> "8ac3d8fa-14fb-4bf9-9068-173c4e5f6bcf";
    <http://data.vlaanderen.be/ns/mandaat#bindingStart> "1971-11-03"^^xsd:date;
    <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/d46795a1-b4d9-48ac-89db-e6ae36681995>.
    }
}