PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/automatic-submission> {
    <http://data.lblod.info/vendors/30881a2c-b758-4c19-bf4b-0094a5fdfc97> a ext:Vendor .
    <http://data.lblod.info/vendors/1a13ae8e-0f6a-4488-a6c0-2800bf8efa30> a ext:Vendor .
    <http://data.lblod.info/vendors/95f7531f-692b-44ad-b155-6a5e6210d811> a ext:Vendor .
    <http://data.lblod.info/vendors/3ed51b05-6dc8-4268-be0d-6f28d16c3ecb> a ext:Vendor .
    <http://data.lblod.info/vendors/42edb420-08c7-4ede-9961-bc0e527d0f3b> a ext:Vendor .
    <http://data.lblod.info/vendors/de046718-28cb-4d8e-999a-6f5e32c20734> a ext:Vendor .
    <http://data.lblod.info/vendors/ddcd40c0-dfd6-437a-a7a4-37902150f260> a ext:Vendor .
    <http://data.lblod.info/vendors/6affe550-294a-4fed-b5e5-008714f682d2> a ext:Vendor .
    <http://data.lblod.info/vendors/c144e921-6a03-4be9-a5ee-27d2560f5c60> a ext:Vendor .
    <http://data.lblod.info/vendors/dc62419e-1267-44e7-9562-0114e2708b6f> a ext:Vendor .
    <http://data.lblod.info/vendors/46241353-de8a-4428-8f31-187ce713e60e> a ext:Vendor .
    <http://data.lblod.info/vendors/lblod-as-vendor/993b42f4-bd97-44ab-9719-667146a78f86> a ext:Vendor .
  }
}
