DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/f35571110db650b4322efe2edd8d7181e43426cd29afd4cb2a765cb78cd750d7> skos:prefLabel ?label
  }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/f35571110db650b4322efe2edd8d7181e43426cd29afd4cb2a765cb78cd750d7> skos:prefLabel "Verslag lokale betrokkenheid eredienstbesturen"
  }
}
