PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
     ?submissionDocument dct:source <share://semantic-forms/20200508151443-forms.ttl> .
  }
}
WHERE {
  GRAPH ?h {
     ?submissionDocument a ext:SubmissionDocument . 
  }
  BIND(?h as ?g)
}
