INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
                                                                                  <http://www.w3.org/2004/02/skos/core#prefLabel> "Type belasting"@nl, "Tax Type"@en .
    <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6> <http://mu.semte.ch/vocabularies/core/uuid> "3037c4f4-1c63-43ac-bfc4-b41d098b15a6" .

<https://data.vlaanderen.be/id/concept/BesluitType/b2d0734d-13d0-44b4-9af8-1722933c5288> a <http://www.w3.org/2004/02/skos/core#Concept>,
    <http://www.w3.org/2000/01/rdf-schema#Class>;
  <http://www.w3.org/2004/02/skos/core#broader> <https://data.vlaanderen.be/id/concept/BesluitType/efa4ec5a-b006-453f-985f-f986ebae11bc>;
  <http://www.w3.org/2004/02/skos/core#definition> "Besluit van de gemeenteraad tot heffing, wijziging of opheffing van een aanvullende belasting of opcentiem.";
  <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "Aanvullende belasting of opcentiem" .

<https://data.vlaanderen.be/id/concept/BesluitType/4c22ef0a-f808-41dd-9c9f-2aff17fd851f> a <http://www.w3.org/2004/02/skos/core#Concept>,
    <http://www.w3.org/2000/01/rdf-schema#Class>;
  <http://www.w3.org/2004/02/skos/core#broader> <https://data.vlaanderen.be/id/concept/BesluitType/efa4ec5a-b006-453f-985f-f986ebae11bc>;
  <http://www.w3.org/2004/02/skos/core#definition> "Besluit van de gemeenteraad tot heffing, wijziging of opheffing van een contantbelasting.";
  <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "Contantbelasting" .

<https://data.vlaanderen.be/id/concept/BesluitType/8597e056-b96d-4213-ad4c-37338f2aaf35> a <http://www.w3.org/2004/02/skos/core#Concept>,
    <http://www.w3.org/2000/01/rdf-schema#Class>;
  <http://www.w3.org/2004/02/skos/core#broader> <https://data.vlaanderen.be/id/concept/BesluitType/efa4ec5a-b006-453f-985f-f986ebae11bc>;
  <http://www.w3.org/2004/02/skos/core#definition> "Besluit van de gemeenteraad tot heffing, wijziging of opheffing van een kohierbelasting.";
  <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "Kohierbelasting" .

    
<https://data.vlaanderen.be/id/concept/BesluitType/8597e056-b96d-4213-ad4c-37338f2aaf35> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6> .

<https://data.vlaanderen.be/id/concept/BesluitType/b2d0734d-13d0-44b4-9af8-1722933c5288> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6> .

<https://data.vlaanderen.be/id/concept/BesluitType/4c22ef0a-f808-41dd-9c9f-2aff17fd851f> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6> .

  }

}
