PREFIX lblodBesluit: <http://lblod.data.gift/vocabularies/besluit/> 

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
<https://data.vlaanderen.be/id/concept/BesluitType/bf72e38a-2c73-4484-b82f-c642a4c39d0c> a <http://www.w3.org/2004/02/skos/core#Concept>,
    <http://www.w3.org/2000/01/rdf-schema#Class>;
  <http://www.w3.org/2004/02/skos/core#definition> "Authentieke akte van de statuten (art. 477 DLB)";
  <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "Authentieke akte van de statuten (art. 477 DLB)" ;
  <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://data.vlaanderen.be/id/conceptscheme/BesluitType> .

    <https://data.vlaanderen.be/id/concept/BesluitType/bf72e38a-2c73-4484-b82f-c642a4c39d0c> <http://mu.semte.ch/vocabularies/core/uuid> "bf72e38a-2c73-4484-b82f-c642a4c39d0c" .

<https://data.vlaanderen.be/id/concept/BesluitType/bf72e38a-2c73-4484-b82f-c642a4c39d0c>  lblodBesluit:decidableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089>.

    <https://data.vlaanderen.be/id/concept/BesluitType/bf72e38a-2c73-4484-b82f-c642a4c39d0c>
  <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
  <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5> .

  }
}
