PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20240213180017-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "4ad00c88-69da-4eba-8f7f-46817ffab607" ;
      nfo:fileName "20240213180017-forms.ttl" ;
      dct:created "2024-02-13T18:00:17"^^xsd:dateTime ;
      dct:modified "2024-02-13T18:00:17"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "433327"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    