PREFIX cpsv:  <http://purl.org/vocab/cpsv#>
PREFIX dct:   <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?s dct:description ?description .
  }
}
INSERT {
  GRAPH ?g {
    ?s dct:description ?new_description .
  }
}
WHERE {
  GRAPH ?g {
    ?s a cpsv:PublicService ;
      dct:description ?description .

    BIND(STRLANG(REPLACE(STR(?description), "&nbsp;", " "), LANG(?description)) as ?new_description)
    FILTER(CONTAINS(STR(?description), "&nbsp;"))
  }
}

;

DELETE {
  GRAPH ?g {
    ?s dct:description ?description .
  }
}
INSERT {
  GRAPH ?g {
    ?s dct:description ?new_description .
  }
}
WHERE {
  GRAPH ?g {
    ?service a cpsv:PublicService ;
      ?link ?s.

     ?s dct:description ?description .

    BIND(STRLANG(REPLACE(STR(?description), "&nbsp;", " "), LANG(?description)) as ?new_description)
    FILTER(CONTAINS(STR(?description), "&nbsp;"))
  }
}

;

DELETE {
  GRAPH ?g {
    ?s dct:description ?description .
  }
}
INSERT {
  GRAPH ?g {
    ?s dct:description ?new_description .
  }
}

WHERE {
  GRAPH ?g {
    ?service a cpsv:PublicService ;
      ?link ?hop.

     ?hop ?link_1 ?s.

     ?s dct:description ?description .

    BIND(STRLANG(REPLACE(STR(?description), "&nbsp;", " "), LANG(?description)) as ?new_description)
    FILTER(CONTAINS(STR(?description), "&nbsp;"))
  }
}