PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX m8g: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2697fbe1-4226-4325-807b-5dfa58e40a95>
      lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/2a25de4e-126a-4eeb-ae27-fbdee1a5b6a4> ;
      cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/17dff916-16a3-4239-b74d-36890145336a> .

    <http://lblod.data.info/id/subsidy-measure-offer-series/2a25de4e-126a-4eeb-ae27-fbdee1a5b6a4>
      a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
      mu:uuid "2a25de4e-126a-4eeb-ae27-fbdee1a5b6a4" ;
      dct:title "Nazomer 2021"@nl ;
      dct:description "Nazomer 2021 (1 september 2021 — 15 oktober 2021)"@nl ;
      common:active <http://lblod.data.info/id/subsidie-application-flows/88ce82c0-4fbf-4c46-930a-163378c475e4> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/dbfc89c3-19f9-4dcc-afdf-b97a388eaf73> ;
      lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/17dff916-16a3-4239-b74d-36890145336a> .

    <http://lblod.data.info/id/subsidie-application-flows/88ce82c0-4fbf-4c46-930a-163378c475e4>
      a lblodSubsidie:ApplicationFlow ;
      mu:uuid "88ce82c0-4fbf-4c46-930a-163378c475e4" ;
      xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/2a25de4e-126a-4eeb-ae27-fbdee1a5b6a4> ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/c30a9e4e-7434-4d92-9630-8320c4559446> .

    <http://lblod.data.info/id/subsidie-application-flow-steps/c30a9e4e-7434-4d92-9630-8320c4559446>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "c30a9e4e-7434-4d92-9630-8320c4559446" ;
      qb:order 0;
      dct:source <config://forms/contact-tracing/versions/20211025194324-after-summer/form.ttl> ;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/17dff916-16a3-4239-b74d-36890145336a> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/88ce82c0-4fbf-4c46-930a-163378c475e4> .

    <http://data.lblod.info/id/periodes/dbfc89c3-19f9-4dcc-afdf-b97a388eaf73>
      a m8g:PeriodOfTime ;
      mu:uuid "dbfc89c3-19f9-4dcc-afdf-b97a388eaf73" ;
      m8g:startTime "2021-09-01T00:00:00"^^xsd:dateTime ;
      m8g:endTime "2021-10-15T00:00:00"^^xsd:dateTime .

    <http://data.lblod.info/id/subsidy-procedural-steps/17dff916-16a3-4239-b74d-36890145336a>
      a subsidie:Subsidieprocedurestap ;
      mu:uuid "17dff916-16a3-4239-b74d-36890145336a" ;
      dct:description """Aanvraag""" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6> ;
      mobiliteit:periode <http://data.lblod.info/id/periodes/2a4d37e6-a75f-4207-88c2-0cb88c95fcbe> .

    <http://data.lblod.info/id/periodes/2a4d37e6-a75f-4207-88c2-0cb88c95fcbe>
      a m8g:PeriodOfTime ;
      mu:uuid "2a4d37e6-a75f-4207-88c2-0cb88c95fcbe" ;
      m8g:startTime "2021-11-01T03:00:00"^^xsd:dateTime ;
      m8g:endTime "2021-12-31T21:59:59"^^xsd:dateTime .
  }
}
