INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "2c0ec673-a430-4cd3-861d-8666991b790f" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> """concept-scheme defining priority-levels"""@en .

    <http://lblod.data.gift/concepts/5572e330-1d6a-4ae9-881d-0cb3cd623977>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "5572e330-1d6a-4ae9-881d-0cb3cd623977" ;
        <http://www.w3.org/2004/02/skos/core#definition> "priority-level: none"@en ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "0 = geen actie ondernomen"@nl .

    <http://lblod.data.gift/concepts/4cd11157-146f-4589-8023-d9c4138e0e81>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "4cd11157-146f-4589-8023-d9c4138e0e81" ;
        <http://www.w3.org/2004/02/skos/core#definition> "priority-level: urgent"@en ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "1 = zeer hoge prioriteit"@nl .

    <http://lblod.data.gift/concepts/1c656d71-419c-4af8-96a0-ee23a9d4ee0b>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "1c656d71-419c-4af8-96a0-ee23a9d4ee0b" ;
        <http://www.w3.org/2004/02/skos/core#definition> "priority-level: high"@en ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "2 = hoge prioriteit"@nl .

    <http://lblod.data.gift/concepts/aca6c496-4fc1-44c6-acab-a4d09a0c1a25>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "aca6c496-4fc1-44c6-acab-a4d09a0c1a25" ;
        <http://www.w3.org/2004/02/skos/core#definition> "priority-level: low"@en ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "3 = lage prioriteit"@nl .

    <http://lblod.data.gift/concepts/0326a5f6-5481-41d8-8e19-b5b156b091c3>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "0326a5f6-5481-41d8-8e19-b5b156b091c3" ;
        <http://www.w3.org/2004/02/skos/core#definition> "priority-level: very-low"@en ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/2c0ec673-a430-4cd3-861d-8666991b790f> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "4 = zeer lage prioriteit"@nl .
  }
}
