INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/af23feb1-a876-4834-9427-947f93b776f2>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://mu.semte.ch/vocabularies/core/uuid> "af23feb1-a876-4834-9427-947f93b776f2" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> """Possible answers to the question: Is this subsidy-application an application for a collaboration"""@en .

    <http://lblod.data.gift/concepts/9ffe7dd4-42b7-4af3-bdba-ccd080195715>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "9ffe7dd4-42b7-4af3-bdba-ccd080195715" ;
        <http://www.w3.org/2004/02/skos/core#definition> "The subsidy-application is for a collaboration"@en;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/af23feb1-a876-4834-9427-947f93b776f2>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Ja"@nl .

    <http://lblod.data.gift/concepts/70fea9a0-9ccc-48e6-bc3e-269a7f070264>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "70fea9a0-9ccc-48e6-bc3e-269a7f070264" ;
        <http://www.w3.org/2004/02/skos/core#definition> "The subsidy-application is not for a collaboration"@en;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/af23feb1-a876-4834-9427-947f93b776f2>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Nee"@nl .
  }
}
