PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

# Remove bestuurseenheid

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/3e529c21-1bf1-487b-8fef-a3d04ff133c0> ?p ?o.
  }
}

WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/3e529c21-1bf1-487b-8fef-a3d04ff133c0> ?p ?o.
  }
}

;

# Remove bestuursorganen, bestuursorganen in tijd and bestuursfuncties

DELETE {
  GRAPH ?g {
    ?bestuursorgaan <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/3e529c21-1bf1-487b-8fef-a3d04ff133c0> ;
      ?boP ?boO .
    ?bestuursorgaanInTijd <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> ?bestuursfunctie ;
      ?botP ?botO .
    ?bestuursfunctie ?beP ?beO .
  }
}

WHERE {
  GRAPH ?g {
    ?bestuursorgaan <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/3e529c21-1bf1-487b-8fef-a3d04ff133c0> ;
      ?boP ?boO ;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanInTijd .
    ?bestuursorgaanInTijd <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> ?bestuursfunctie ;
      ?botP ?botO .
    ?bestuursfunctie ?beP ?beO .
  }
}
