PREFIX person: <http://www.w3.org/ns/person#>

INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dumm/data/b4b54a9c-95c2-40fd-82eb-09c516126c77> <http://dummy/for/workaround> <http://dumm/data/a921e41c-6364-48c2-b2e1-637aaf22fd6c>.
    <http://dumm/data/a921e41c-6364-48c2-b2e1-637aaf22fd6c> owl:sameAs <http://dumm/data/f73c6faf-5e0b-4fa1-a1cb-3dc2c57e6ad1> .
    <http://dumm/data/f73c6faf-5e0b-4fa1-a1cb-3dc2c57e6ad1> a person:Person .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?person .
  }
}
INSERT {
  GRAPH ?g {
    ?s ?p ?masterPerson .
  }
}
WHERE {
  GRAPH ?g {
    ?s ?p ?person .
  }
  GRAPH ?h {
    ?person owl:sameAs ?masterPerson .
  }
  GRAPH ?i {
    ?masterPerson a person:Person .
  }
}

;

DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dumm/data/b4b54a9c-95c2-40fd-82eb-09c516126c77> <http://dummy/for/workaround> <http://dumm/data/a921e41c-6364-48c2-b2e1-637aaf22fd6c>.
    <http://dumm/data/a921e41c-6364-48c2-b2e1-637aaf22fd6c> owl:sameAs <http://dumm/data/f73c6faf-5e0b-4fa1-a1cb-3dc2c57e6ad1> .
    <http://dumm/data/f73c6faf-5e0b-4fa1-a1cb-3dc2c57e6ad1> a person:Person .
  }
}
