PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA{
  GRAPH <http://mu.semte.ch/graphs/public> {
   <share://semantic-forms/20201028125351-forms.ttl> a nfo:FileDataObject ;
 				  dct:type <http://data.lblod.gift/concepts/form-file-type> ;
                                  mu:uuid "899df36a-76d7-438b-a595-898f216fa979" ;
                                  nfo:fileName "20201028125351-forms.ttl" ;
                                  dct:created "2020-10-28Z"^^xsd:dateTime;
                                  dct:modified "2020-10-28Z"^^xsd:dateTime;
                                  dct:format "text/turtle";
                                  nfo:fileSize "248000"^^xsd:integer;
                                  dbpedia:fileExtension "ttl" .
  }
}
