PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/automatic-submission> {
    <http://data.lblod.info/vendors/850017b0-a0ee-499b-9bce-c031ec7a4620> a foaf:Agent, ext:Vendor ;
    foaf:name "Provincie Antwerpen" ;
    mu:uuid "850017b0-a0ee-499b-9bce-c031ec7a4620" .
  }
}
