PREFIX person: <http://www.w3.org/ns/person#>
PREFIX adms: <http://www.w3.org/ns/adms#>

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error ###
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> a <http://www.w3.org/ns/person#Person> .
    <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> <http://www.w3.org/ns/adms#identifier> <http://dumm/data/4403c05f-8c45-4c5e-8d90-5772ef2df412> .
    <http://dumm/data/4403c05f-8c45-4c5e-8d90-5772ef2df412> <http://dumm/data/predicate> "data" .
  }
}
### END OF TRICK ###

;

INSERT {
  GRAPH ?g {
    ?person adms:identifier ?identifier .
    ?identifier ?p ?o .
  }
}
WHERE {
  ?person adms:identifier ?identifier .
  ?identifier ?p ?o .
  GRAPH ?g {
    ?person a person:Person .
  }
}

;

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error ###
DELETE {
  GRAPH ?g {
    <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> ?p ?o.
    ?o ?r ?t.
  }
}
WHERE {
  GRAPH ?g {
    <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> ?p ?o.
    ?o ?r ?t.
 }
}
### END OF TRICK ###
