DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> {
    <http://data.lblod.info/id/bestuurseenheden/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> <http://www.w3.org/2004/02/skos/core#prefLabel> "AUTONOOM GEMEENTEBEDRIJF OPGLABBEEK" .
    <http://data.lblod.info/id/persoon/7fdab5c0bb1445fdc632187af6f5c3db> <http://xmlns.com/foaf/0.1/familyName> "AUTONOOM GEMEENTEBEDRIJF OPGLABBEEK" .
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> <http://www.w3.org/2004/02/skos/core#prefLabel> "AUTONOOM GEMEENTEBEDRIJF OPGLABBEEK" .
    <http://data.lblod.info/id/persoon/7fdab5c0bb1445fdc632187af6f5c3db> <http://xmlns.com/foaf/0.1/familyName> "AUTONOOM GEMEENTEBEDRIJF OPGLABBEEK" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> {
    <http://data.lblod.info/id/bestuurseenheden/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> <http://www.w3.org/2004/02/skos/core#prefLabel> "AUTONOOM GEMEENTEBEDRIJF OUDSBERGEN" .
    <http://data.lblod.info/id/persoon/7fdab5c0bb1445fdc632187af6f5c3db> <http://xmlns.com/foaf/0.1/familyName> "AUTONOOM GEMEENTEBEDRIJF OUDSBERGEN" .
  }
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://data.lblod.info/id/bestuurseenheden/e45e6ad275ae04001029796b3771fa418b32414269ee741a5cf120a580ff673b> <http://www.w3.org/2004/02/skos/core#prefLabel> "AUTONOOM GEMEENTEBEDRIJF OUDSBERGEN" .
    <http://data.lblod.info/id/persoon/7fdab5c0bb1445fdc632187af6f5c3db> <http://xmlns.com/foaf/0.1/familyName> "AUTONOOM GEMEENTEBEDRIJF OUDSBERGEN" .
  }
}




