DELETE {
  GRAPH ?g {
    ?person1 ?personP ?personO .
    ?account1 ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
     ?person2 <http://xmlns.com/foaf/0.1/member> ?bestuurseenheid .
     ?person1 <http://xmlns.com/foaf/0.1/member> ?bestuurseenheid .
     FILTER (?person1 != ?person2)

     ?person1 <http://xmlns.com/foaf/0.1/account> ?account1 .
     ?account1  <http://xmlns.com/foaf/0.1/accountServiceHomepage> <https://github.com/lblod/mock-login-service> .

     ?person2 <http://xmlns.com/foaf/0.1/account> ?account2 .
     ?account2  <http://xmlns.com/foaf/0.1/accountServiceHomepage> <https://github.com/lblod/mock-login-service> .

     ?person1 <http://xmlns.com/foaf/0.1/firstName>  "Intercommunale" .

    ?person1 ?personP ?personO .
    ?account1 ?accountP ?accountO .
  }
}
