PREFIX meb: <http://rdf.myexperiment.org/ontologies/base/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
PREFIX adms: <http://www.w3.org/ns/adms#>

INSERT {
  GRAPH ?g {
    ?s nmo:sentDate ?verzonden
  }
}
WHERE {
  GRAPH ?g {
    ?s a meb:Submission .
    ?s <http://purl.org/dc/terms/modified> ?verzonden.
    ?s adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>.
    FILTER NOT EXISTS {
      ?s nmo:sentDate ?date
    }
  }
}