PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
   ?bestuursorgaan skos:prefLabel ?updatedLabel.
 }
}
WHERE {
  GRAPH ?g {
  ?bestuursorgaan a besluit:Bestuursorgaan.
  ?bestuursorgaan besluit:bestuurt ?bestuurseenheid.
  ?bestuurseenheid a besluit:Bestuurseenheid.
  ?bestuurseenheid skos:prefLabel ?besLabel.

  ?bestuursorgaan besluit:classificatie ?classificatie.
  ?classificatie skos:prefLabel ?classLabel.

  BIND(CONCAT(?classLabel, " ", ?besLabel) as ?updatedLabel)

  FILTER NOT EXISTS {
    ?bestuursorgaan skos:prefLabel ?label.
  }
 }
}