# Avoid sprintf error

INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> <http://mu.semte.ch/vocabularies/ext/notificatieEmail> <http://dummy/data/email> .
    <http://dummy/data/subject> <http://dummy/data/predicate> <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> .
    <http://dummy/data/email> <http://dummy/data/email/predicate> <http://dummy/data/email/object> .
  }
}

;

# Deletes the message from a conversation, the related email, and all triples point to them
# Replaces the last message of the conversation

DELETE {
  GRAPH ?g {
    <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> ?pMessage ?oMessage .
    ?sPointToMessage ?sPointToMessage <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> .
    ?sPointToEmail ?pPointToEmail ?email .
  }
  GRAPH ?h {
    ?email ?pEmail ?oEmail .
  }
} 
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/conversaties/db3fcf5c-d187-11ea-bb78-0242c0a8201e> <http://mu.semte.ch/vocabularies/ext/lastMessage>	<https://kalliope.abb.vlaanderen.be/#!/case/detail/b5fffb43-4344-45d3-83e4-0b1ee9984e19/5de7e592-db23-4eab-9702-823cbc0c630d> .
  }
}
WHERE { 
  GRAPH ?g {
    <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> ?pMessage ?oMessage ;
      <http://mu.semte.ch/vocabularies/ext/notificatieEmail> ?email .
    ?sPointToMessage ?pPointToMessage <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> .
    ?sPointToEmail ?pPointToEmail ?email .
  }
  GRAPH ?h {
    ?email ?pEmail ?oEmail .
  }
}

;

# Avoid sprintf error
DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> <http://mu.semte.ch/vocabularies/ext/notificatieEmail> <http://dummy/data/email> .
    <http://dummy/data/subject> <http://dummy/data/predicate> <https://kalliope.abb.vlaanderen.be/#!/case/detail/ce73396a-6e64-4741-846e-a0080015a1b3/2336fd8a-74f0-425f-93b5-b8ac1c54882e> .
    <http://dummy/data/email> <http://dummy/data/email/predicate> <http://dummy/data/email/object> .
  }
}