PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "344ff196-00d6-4d31-8abf-bda1a3c06b23" ;
      skos:prefLabel "Beleefproject" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0751762767" ;
      dcterms:identifier "OVO047855", "0751762767" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/1e5bcab004b367f116c729a749dba338>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"1e5bcab004b367f116c729a749dba338" ;
      skos:prefLabel "Directiecomité Beleefproject" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23> .

    <http://data.lblod.info/id/bestuursorganen/5ddd8f713ee2e6f51946e79047ea5e35>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"5ddd8f713ee2e6f51946e79047ea5e35" ;
      skos:prefLabel "Raad van bestuur Beleefproject" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23> .

    <http://data.lblod.info/id/bestuursorganen/c32c6d75bc1eac5e0c9c3f57161091f8>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"c32c6d75bc1eac5e0c9c3f57161091f8" ;
      skos:prefLabel "Bevoegd beslissingsorgaan Beleefproject" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23> .

    <http://data.lblod.info/id/bestuursorganen/5b0455ef6fb7634648dfd4fafba2f19c>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"5b0455ef6fb7634648dfd4fafba2f19c" ;
      skos:prefLabel "Algemene vergadering Beleefproject" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23> .

    <http://data.lblod.info/id/bestuursorganen/1b64057605a1307d3e8475bb90f94fcc>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"1b64057605a1307d3e8475bb90f94fcc" ;
      skos:prefLabel "Leidend Ambtenaar Beleefproject" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/d85af77f147b70e2d3571a60739cb571>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"d85af77f147b70e2d3571a60739cb571" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/1e5bcab004b367f116c729a749dba338> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/eb03e1168a1df3f2edda8339b8cb2469>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "eb03e1168a1df3f2edda8339b8cb2469" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/5ddd8f713ee2e6f51946e79047ea5e35> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/c3877ab04f6ce5e714f6f6956959632f>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"c3877ab04f6ce5e714f6f6956959632f" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/c32c6d75bc1eac5e0c9c3f57161091f8> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/0fc0ef221f65a54f0e286c5aa7bbee0c>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"0fc0ef221f65a54f0e286c5aa7bbee0c" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/5b0455ef6fb7634648dfd4fafba2f19c> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/44124e40aa5407feb5799eca0d82be1f>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"44124e40aa5407feb5799eca0d82be1f" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/1b64057605a1307d3e8475bb90f94fcc> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
