PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

DELETE {
  GRAPH ?g {
    ?person ?personP ?personO .
    ?geboorte ?geboorteP ?geboorteO .
    ?mandataris ?mandatarisP ?mandatarisO .
  }
} WHERE {
  GRAPH ?g {
    ?person a person:Person ;
       persoon:gebruikteVoornaam "Dummy" ; 
       foaf:familyName "Dummy" ; 
       persoon:geslacht ?geslacht ;
       persoon:heeftGeboorte ?geboorte ;
       ?personP ?personO .

    ?geboorte ?geboorteP ?geboorteO .
 
    ?mandataris mandaat:isBestuurlijkeAliasVan ?person ;
       ?mandatarisP ?mandatarisO .
  }
}
