PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

# New bestuursorganen in tijd have been disabled in previous migration.
# Now we restore them only for provincies

DELETE {
  GRAPH ?g {
     ?orgaan ext:isTijdspecialisatieVan ?bestuursorgaan .
  }

}
INSERT {
  GRAPH ?g {
      ?orgaan mandaat:isTijdspecialisatieVan ?bestuursorgaan .
  }
}
WHERE {
  GRAPH ?g {
    ?orgaan ext:isTijdspecialisatieVan ?bestuursorgaan;
            mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
    ?bestuursorgaan besluit:bestuurt ?eenheid .
    ?eenheid besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000> .
  }
}