WITH <http://mu.semte.ch/application>

INSERT {
  ?group <http://purl.org/dc/terms/identifier> "0207437468"
} WHERE {
  ?group a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
    <http://www.w3.org/2004/02/skos/core#prefLabel> "Aalst" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie> ?classificatie .

  ?classificatie  <http://www.w3.org/2004/02/skos/core#prefLabel> "Gemeente"
}

;

INSERT {
  ?group <http://purl.org/dc/terms/identifier> "0212237186"
} WHERE {
  ?group a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
    <http://www.w3.org/2004/02/skos/core#prefLabel> "Aalst" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie> ?classificatie .

  ?classificatie  <http://www.w3.org/2004/02/skos/core#prefLabel> "OCMW"
}

;

INSERT {
  ?group <http://purl.org/dc/terms/identifier> "0207439448"
} WHERE {
  ?group a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
    <http://www.w3.org/2004/02/skos/core#prefLabel> "Herzele" ;
    <http://data.vlaanderen.be/ns/besluit#classificatie> ?classificatie .

  ?classificatie  <http://www.w3.org/2004/02/skos/core#prefLabel> "Gemeente"
}

