PREFIX nmo: <http://oscaf.sourceforge.net/nmo.html#>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX validation: <http://mu.semte.ch/vocabularies/validation/>
PREFIX bbcdr: <http://mu.semte.ch/vocabularies/ext/bbcdr/>
PREFIX export: <http://mu.semte.ch/vocabularies/ext/export/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX pav: <http://purl.org/pav/>
PREFIX nao: <http://www.semanticdesktop.org/ontologies/2007/08/15/nao#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX regorg: <https://www.w3.org/ns/regorg#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX generiek: <http://data.vlaanderen.be/ns/generiek#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX tmp: <http://mu.semte.ch/vocabularies/tmp/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX rm: <http://mu.semte.ch/vocabularies/logical-delete/>
PREFIX typedLiterals: <http://mu.semte.ch/vocabularies/typed-literals/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX app: <http://mu.semte.ch/app/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


INSERT {
  GRAPH ?g {
   ?bestuursorgaan besluit:bestuurt ?bestuurseenheid ;
       a besluit:Bestuursorgaan ;
       mu:uuid ?uuid ;
       skos:prefLabel ?bestuursorgaanLabel ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> .

   ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan ;
       a besluit:Bestuursorgaan ;
       mu:uuid ?uuidInTijd ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089> ;
       skos:prefLabel ?bestuurseenheidLabel .
  }

  BIND(CONCAT("Algemene vergadering ", ?bestuurseenheidLabel) as ?bestuursorgaanLabel)
  BIND(SHA256(CONCAT("9ee51917-8f7f-4823-8225-5c63c0f96ad3", ":", STR(?bestuursorgaanLabel))) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuid))) AS ?bestuursorgaan) .
  BIND(SHA256(CONCAT("9e8a8b0c-9685-4932-86b8-348eae985da7", ":", STR(?bestuursorgaanLabel))) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?bestuursorgaanInTijd) .
}
