PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://data.lblod.info/id/bestuurseenheden/0f316807-839b-4554-a4d8-8656e9f83201> a besluit:Bestuurseenheid ;
       mu:uuid "0f316807-839b-4554-a4d8-8656e9f83201" ;
       skos:prefLabel "APB Gouverneur Kinsbergen Centrum" ;
       dcterms:identifier "0684472976" ;
       ext:kbonummer "0684472976" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d> ;
       besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .

   <http://data.lblod.info/id/bestuursorganen/1da06829-c1f2-4456-b73b-52db1126a4a9> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/0f316807-839b-4554-a4d8-8656e9f83201> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "1da06829-c1f2-4456-b73b-52db1126a4a9" ;
       skos:prefLabel "Bevoegd beslissingsorgaan" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> .

   <http://data.lblod.info/id/bestuursorganen/b5ad0ce1-30ec-47eb-bf03-1891ef4b59c2> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/1da06829-c1f2-4456-b73b-52db1126a4a9> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "b5ad0ce1-30ec-47eb-bf03-1891ef4b59c2" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

INSERT {
  GRAPH ?g {
     ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member <http://data.lblod.info/id/bestuurseenheden/0f316807-839b-4554-a4d8-8656e9f83201> ;
           foaf:account ?account.
     ?account a foaf:OnlineAccount;
           mu:uuid ?uuidAccount;
           foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
           ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker". 
  }
} WHERE {
     <http://data.lblod.info/id/bestuurseenheden/0f316807-839b-4554-a4d8-8656e9f83201> a besluit:Bestuurseenheid;
     skos:prefLabel ?naam;
     besluit:classificatie/skos:prefLabel ?classificatie.
     BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
     BIND(MD5(?volledigeNaam) as ?uuidPersoon)
     BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
     BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
     BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

     VALUES ?g {
        <http://mu.semte.ch/graphs/organizations/0f316807-839b-4554-a4d8-8656e9f83201>
        <http://mu.semte.ch/graphs/public> 
     } 
}
