PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ext:<http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?account ext:sessionRole "LoketLB-berichtenGebruiker", "LoketLB-leidinggevendenGebruiker" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?account a foaf:OnlineAccount;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
  }
}

;

INSERT {
  GRAPH ?g {
    ?account ext:sessionRole "LoketLB-berichtenGebruiker", "LoketLB-leidinggevendenGebruiker" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?account ext:sessionRole "LoketLB-berichtenGebruiker", "LoketLB-leidinggevendenGebruiker" .
  }

  GRAPH ?g {
    ?account a foaf:OnlineAccount;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
  }
}
