PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?provincie .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     besluit:werkingsgebied ?werkingsgebied .
    ?werkingsgebied ext:inProvincie ?provincie .
    ?provincie ext:werkingsgebiedNiveau "Provincie" .
  }
}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?werkingsgebied .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     besluit:werkingsgebied ?werkingsgebied .
    ?werkingsgebied ext:werkingsgebiedNiveau "Provincie" .
  }
}
