PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?s ext:string ?options .
  }
} WHERE {
  GRAPH ?g {
    ?s a ext:FormInput ;
       ext:string ?options .
  }
}
;
INSERT {
  GRAPH ?g {
    ?s ext:options ?options .
  }
} WHERE {
  GRAPH ?g {
    ?s a ext:FormInput ;
       ext:string ?options .
  }
}
