PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
INSERT {
GRAPH ?g {
  ?mandataris org:holds ?nieuwmandaat.
  }
}
WHERE {
GRAPH ?g {
?mandataris a mandaat:Mandataris; 
            org:holds ?oldmandaat;
            mandaat:start ?startMandaat.
}
?oldmandaat org:role ?role.
?oudbestuurorgaan org:hasPost ?oldmandaat;
                  mandaat:isTijdspecialisatieVan ?orgaan;
                  mandaat:bindingStart "2012-10-14"^^xsd:date.
?orgaan besluit:bestuurt/besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>.
?nieuworgaan mandaat:isTijdspecialisatieVan ?orgaan;
             mandaat:bindingStart "2019-01-01"^^xsd:date;
             org:hasPost ?nieuwmandaat.
?nieuwmandaat org:role ?role.
FILTER(DAY(?startMandaat) >= 3)
FILTER(MONTH(?startMandaat) = 12)
FILTER(YEAR(?startMandaat) = 2018)
} ;

PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
DELETE {
GRAPH ?g {
  ?mandataris org:holds ?oldmandaat.
  }
}
WHERE {
GRAPH ?g {
?mandataris a mandaat:Mandataris; 
            org:holds ?oldmandaat;
            mandaat:start ?startMandaat.
}
?oldmandaat org:role ?role.
?oudbestuurorgaan org:hasPost ?oldmandaat;
                  mandaat:isTijdspecialisatieVan ?orgaan;
                  mandaat:bindingStart "2012-10-14"^^xsd:date.
?orgaan besluit:bestuurt/besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>.
?nieuworgaan mandaat:isTijdspecialisatieVan ?orgaan;
             mandaat:bindingStart "2019-01-01"^^xsd:date;
             org:hasPost ?nieuwmandaat.
?nieuwmandaat org:role ?role.
FILTER(DAY(?startMandaat) >= 3)
FILTER(MONTH(?startMandaat) = 12)
FILTER(YEAR(?startMandaat) = 2018)
} ;