PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a> a besluit:Bestuurseenheid ;
       mu:uuid "20ed2789-2e69-47bf-ab84-64433d59fa3a" ;
       skos:prefLabel "AGB Izegem" ;
       dcterms:identifier "0692535557" ;
       ext:kbonummer "0692535557" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721> ;
       besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/> .

   <http://data.lblod.info/id/bestuursorganen/63599242-7875-4562-a937-37d7fcbeadbc> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "63599242-7875-4562-a937-37d7fcbeadbc" ;
       skos:prefLabel "Bevoegd beslissingsorgaan" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> .

   <http://data.lblod.info/id/bestuursorganen/b614faa2-f65d-4017-8e72-6682efd9dd2b> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/63599242-7875-4562-a937-37d7fcbeadbc> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "b614faa2-f65d-4017-8e72-6682efd9dd2b" ;
       mandaat:bindingStart "2017-12-19"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

INSERT {
  GRAPH ?g {
     ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a> ;
           foaf:account ?account.
     ?account a foaf:OnlineAccount;
           mu:uuid ?uuidAccount;
           foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
           ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker". 
  }
} WHERE {
     <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a> a besluit:Bestuurseenheid;
     skos:prefLabel ?naam;
     besluit:classificatie/skos:prefLabel ?classificatie.
     BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
     BIND(MD5(?volledigeNaam) as ?uuidPersoon)
     BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
     BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
     BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

     VALUES ?g {
        <http://mu.semte.ch/graphs/organizations/20ed2789-2e69-47bf-ab84-64433d59fa3a>
        <http://mu.semte.ch/graphs/public> 
     } 
}
