PREFIX schema: <http://schema.org/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

DELETE {
  GRAPH ?g {
    ?s schema:url ?url .
  }
} INSERT {
  GRAPH ?g {
    ?s schema:url <http://www.dilsen-stokkem.be/ocmw> .
  }
} WHERE {
  GRAPH ?g {
    ?s a schema:PostalAddress ;
      mu:uuid "197efc36-6258-4c5a-a626-a768b117c7e1" ;
      schema:url ?url .
  }
}

