PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/3691beca-84ba-40ad-be53-d2b009826f70> a besluit:Bestuurseenheid ;
       mu:uuid "3691beca-84ba-40ad-be53-d2b009826f70" ;
       skos:prefLabel "AGB Schilde" ;
       dcterms:identifier "0693894844" ;
       ext:kbonummer "0693894844" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721> ;
       besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/38ebae958ad280baa6dc99a4a35dfee1b6fec94b257d9a1629e52ce6977576e4> .

   <http://data.lblod.info/id/bestuursorganen/5ffe1546-2a63-40c9-a51d-035596155034> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3691beca-84ba-40ad-be53-d2b009826f70> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "5ffe1546-2a63-40c9-a51d-035596155034" ;
       skos:prefLabel "Bevoegd beslissingsorgaan" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> .

   <http://data.lblod.info/id/bestuursorganen/9d962c37-3c8e-4f3e-b819-87565cc2a5bc> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/5ffe1546-2a63-40c9-a51d-035596155034> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "9d962c37-3c8e-4f3e-b819-87565cc2a5bc" ;
       mandaat:bindingStart "2017-11-20"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

INSERT {
  GRAPH ?g {
     ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member <http://data.lblod.info/id/bestuurseenheden/3691beca-84ba-40ad-be53-d2b009826f70> ;
           foaf:account ?account.
     ?account a foaf:OnlineAccount;
           mu:uuid ?uuidAccount;
           foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
           ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker". 
  }
} WHERE {
     <http://data.lblod.info/id/bestuurseenheden/3691beca-84ba-40ad-be53-d2b009826f70> a besluit:Bestuurseenheid;
     skos:prefLabel ?naam;
     besluit:classificatie/skos:prefLabel ?classificatie.
     BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
     BIND(MD5(?volledigeNaam) as ?uuidPersoon)
     BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
     BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
     BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

     VALUES ?g {
        <http://mu.semte.ch/graphs/organizations/3691beca-84ba-40ad-be53-d2b009826f70>
        <http://mu.semte.ch/graphs/public> 
     } 
}
