PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

INSERT {
  GRAPH ?g { 
    ?bestuurseenheid ext:inProvincie ?provincie .
  }
} WHERE {
  GRAPH ?g { 
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     besluit:werkingsgebied ?werkingsgebied .
    ?werkingsgebied ext:inProvincie* ?provincie .
    ?provincie ext:werkingsgebiedNiveau "Provincie" .
  }
}
