PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX m8g: <http://data.europa.eu/m8g/>

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        # Period of the series
        <http://data.lblod.info/id/periodes/72220070-261e-405c-9234-1876bbd5a0e7>
            a m8g:PeriodOfTime;
            mu:uuid """72220070-261e-405c-9234-1876bbd5a0e7""";
            m8g:startTime "2022-01-10T03:00:00Z"^^xsd:dateTime;
            m8g:endTime "2022-02-25T03:00:00Z"^^xsd:dateTime.

        # Series for Winter 2022
        <http://lblod.data.info/id/subsidy-measure-offer-series/e548807f-c39b-4190-9dc9-e32f21dbb095>
            a lblodSubsidie:SubsidiemaatregelAanbodReeks;
            mu:uuid """e548807f-c39b-4190-9dc9-e32f21dbb095""";
            dct:title """Winter 2022"""@nl;
            dct:description """Winter (10 januari 2022 — 25 februari 2022)"""@nl;
            mobiliteit:periode <http://data.lblod.info/id/periodes/72220070-261e-405c-9234-1876bbd5a0e7>;
            lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/ae857ac3-50b2-4172-b3ea-2c35b3a794a7>;
            common:active <http://lblod.data.info/id/subsidie-application-flows/124d07b9-5b97-4164-97b1-4693fb2e079e>.

        # Link the reeks to the offer
        <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
            lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/e548807f-c39b-4190-9dc9-e32f21dbb095> .

        # The first step
        <http://lblod.data.info/id/subsidie-application-flow-steps/e3febf03-115f-443e-b545-1e5acc2e5bdc>
            a lblodSubsidie:ApplicationStep;
            mu:uuid "e3febf03-115f-443e-b545-1e5acc2e5bdc";
            qb:order 0;
            dct:references <http://data.lblod.info/id/subsidy-procedural-steps/ae857ac3-50b2-4172-b3ea-2c35b3a794a7>;
            dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/124d07b9-5b97-4164-97b1-4693fb2e079e> ;
            dct:source <config://forms/emergency-day-care/versions/20220104181744-no-parental-contribution/form.ttl>.

        # The subsidy submission flow
        <http://lblod.data.info/id/subsidie-application-flows/124d07b9-5b97-4164-97b1-4693fb2e079e>
            a lblodSubsidie:ApplicationFlow;
            mu:uuid "124d07b9-5b97-4164-97b1-4693fb2e079e";
            xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/e548807f-c39b-4190-9dc9-e32f21dbb095>;
            xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/e3febf03-115f-443e-b545-1e5acc2e5bdc>.    
    }
}