PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX m8g: <http://data.europa.eu/m8g/>

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        # Period of the series
        <http://data.lblod.info/id/periodes/6c91ab0f-09d5-4cd1-a1b6-58a30b651cd4>
            a m8g:PeriodOfTime;
            mu:uuid """6c91ab0f-09d5-4cd1-a1b6-58a30b651cd4""";
            m8g:startTime "2022-02-28T03:00:00Z"^^xsd:dateTime;
            m8g:endTime "2022-03-04T03:00:00Z"^^xsd:dateTime.

        # Series for Spring break 2022
        <http://lblod.data.info/id/subsidy-measure-offer-series/4c9e5f09-20d3-4c2e-a167-e959eaccfd40>
            a lblodSubsidie:SubsidiemaatregelAanbodReeks;
            mu:uuid """4c9e5f09-20d3-4c2e-a167-e959eaccfd40""";
            dct:title """Krokusvakantie 2022"""@nl;
            dct:description """Krokusvakantie (28 februari 2022 — 01 maart 2022)"""@nl;
            mobiliteit:periode <http://data.lblod.info/id/periodes/6c91ab0f-09d5-4cd1-a1b6-58a30b651cd4>;
            lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/ae857ac3-50b2-4172-b3ea-2c35b3a794a7>;
            common:active <http://lblod.data.info/id/subsidie-application-flows/f4f3f0eb-7428-4fce-819b-2e361becab1f>.

        # Link the reeks to the offer
        <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
            lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/4c9e5f09-20d3-4c2e-a167-e959eaccfd40> .
    
        # The first step
        <http://lblod.data.info/id/subsidie-application-flow-steps/3b1c6f36-cd06-443f-aaf2-a454e16cfe37>
            a lblodSubsidie:ApplicationStep;
            mu:uuid "3b1c6f36-cd06-443f-aaf2-a454e16cfe37";
            qb:order 0;
            dct:references <http://data.lblod.info/id/subsidy-procedural-steps/ae857ac3-50b2-4172-b3ea-2c35b3a794a7>;
            dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/f4f3f0eb-7428-4fce-819b-2e361becab1f> ;
            dct:source <config://forms/emergency-day-care/versions/20220104181745-parental-contribution/form.ttl>.

        # The subsidy submission flow
        <http://lblod.data.info/id/subsidie-application-flows/f4f3f0eb-7428-4fce-819b-2e361becab1f>
            a lblodSubsidie:ApplicationFlow;
            mu:uuid "f4f3f0eb-7428-4fce-819b-2e361becab1f";
            xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/4c9e5f09-20d3-4c2e-a167-e959eaccfd40>;
            xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/3b1c6f36-cd06-443f-aaf2-a454e16cfe37>.    
    }
}