PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20250909113747-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "35127df2-d22b-4d06-840d-2158851597cf" ;
      nfo:fileName "20250909113747-forms.ttl" ;
      dct:created "2025-09-09T11:37:47"^^xsd:dateTime ;
      dct:modified "2025-09-09T11:37:47"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "480653"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
