PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    #################################################
    ### Concepts used in the e-inclusion form ###
    #################################################

    ########################################################
    ### CONCEPT - Focused population
    ########################################################

    <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "0b058b75-5953-40cf-b2b5-34e23168b370" ;
        skos:prefLabel "Focused/targeted population"@en ;
        skos:definition "Which populations is your action focused on?"@en .

    <http://data.lblod.info/id/subsidies/rules/e913384d-9564-4d9d-ba74-c59c254fb600> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "e913384d-9564-4d9d-ba74-c59c254fb600" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Volwassenen (+18 en -65)'@nl .

    <http://data.lblod.info/id/subsidies/rules/b80edc0f-26cc-4c53-96a0-66b88436c51e> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "b80edc0f-26cc-4c53-96a0-66b88436c51e" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Ouderen (+65)'@nl .

    <http://data.lblod.info/id/subsidies/rules/6c976625-b153-4cfa-a7d5-ac68658a94ab> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "6c976625-b153-4cfa-a7d5-ac68658a94ab" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Kinderen en jongeren (-18)'@nl .

    <http://data.lblod.info/id/subsidies/rules/0e82ad14-34e3-46f3-83b0-27ddd3ce31a7> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "0e82ad14-34e3-46f3-83b0-27ddd3ce31a7" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Laaggeschoolden en/of laaggeletterden'@nl .

    <http://data.lblod.info/id/subsidies/rules/7147401e-73d5-4f74-a98b-67d18d3bf02d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "7147401e-73d5-4f74-a98b-67d18d3bf02d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Personen in kansarmoede'@nl .

    <http://data.lblod.info/id/subsidies/rules/44f81fed-5987-4f36-9967-190c96195f98> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "44f81fed-5987-4f36-9967-190c96195f98" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Personen met buitenlandse herkomst'@nl .

    <http://data.lblod.info/id/subsidies/rules/4489b869-af11-448f-937b-ef595801d6bd> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "4489b869-af11-448f-937b-ef595801d6bd" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Personen met een beperking'@nl .

    <http://data.lblod.info/id/subsidies/rules/8de86080-9bef-4c47-a2d0-af6d7afef70f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "8de86080-9bef-4c47-a2d0-af6d7afef70f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Alleenstaanden'@nl .

    <http://data.lblod.info/id/subsidies/rules/68c86f89-0908-4838-bd73-3051f6e50fb8> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "68c86f89-0908-4838-bd73-3051f6e50fb8" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Anderstaligen'@nl .

    <http://data.lblod.info/id/subsidies/rules/c18df5ef-1db6-4dd1-9350-773ede57f08a> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "c18df5ef-1db6-4dd1-9350-773ede57f08a" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/0b058b75-5953-40cf-b2b5-34e23168b370> ;
        skos:prefLabel 'Alle inwoners'@nl .


    
    ########################################################
    ### CONCEPT - Type of actions
    ########################################################

    <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "2c7ca3db-f61b-4903-8497-245073800ceb" ;
        skos:prefLabel "Types of e-inclusion actions"@en ;
        skos:definition "All types of possible actions about e-inclusion"@en .

    <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "e31c7d36-6e7d-47e0-a749-5011f99d1514" ;
        skos:prefLabel "E-inclusion actions"@en ;
        skos:definition "E-inclusion actions that a local governance can take"@en .
    
    <http://data.lblod.info/id/subsidies/rules/42c63540-f442-41e6-bf59-faf40f2c4d07> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "42c63540-f442-41e6-bf59-faf40f2c4d07" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond individuele toegang tot internet op het thuisadres van kwetsbare gebruikers'@nl .

    <http://data.lblod.info/id/subsidies/rules/83677f96-bfb2-401a-95bd-0cb01388410f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "83677f96-bfb2-401a-95bd-0cb01388410f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond het opzetten van een overkoepelend e-inclusiebeleid binnen het lokaal bestuur'@nl .

    <http://data.lblod.info/id/subsidies/rules/0dd0adc4-8117-4853-9d4b-f31116bc47f6> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "0dd0adc4-8117-4853-9d4b-f31116bc47f6" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond betaalbare en kwaliteitsvolle toegang tot hardware, software en openbaar internet'@nl .

    <http://data.lblod.info/id/subsidies/rules/b8061907-89ce-4246-a490-dfad9d2626d6> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "b8061907-89ce-4246-a490-dfad9d2626d6" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond het versterken van competenties, vaardigheden en attitudes om digitaal mee te zijn'@nl .

    <http://data.lblod.info/id/subsidies/rules/98b90d32-31fb-4bae-aa90-4cd22c50ab0f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "98b90d32-31fb-4bae-aa90-4cd22c50ab0f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond een ondersteuningsnetwerk opzetten waar burgers terecht kunnen met digitale vragen'@nl .

    <http://data.lblod.info/id/subsidies/rules/1c57b86e-251d-4ab2-96a4-06eb94672d14> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "1c57b86e-251d-4ab2-96a4-06eb94672d14" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Actie(s) rond e-inclusion by design (digitale toegankelijkheid en gebruiksvriendelijkheid)'@nl .

    <http://data.lblod.info/id/subsidies/rules/0c7a29a2-8e31-492e-8ce9-010e2e41685f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "0c7a29a2-8e31-492e-8ce9-010e2e41685f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/2c7ca3db-f61b-4903-8497-245073800ceb> ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/e31c7d36-6e7d-47e0-a749-5011f99d1514> ;
        skos:prefLabel 'Het lokaal bestuur organiseert op dit moment nog geen acties rond e-inclusie'@nl .


  }
}
