
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offers/0b5cae58-97fb-4982-9fb7-4cf660f003df> cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/a91a1576-b792-44cd-ab49-91973e4a8e47> .


    <http://data.lblod.info/id/subsidy-procedural-steps/a91a1576-b792-44cd-ab49-91973e4a8e47> a subsidie:Subsidieprocedurestap;
      mu:uuid "a91a1576-b792-44cd-ab49-91973e4a8e47";
      dct:description """Verantwoording""";
      mobiliteit:periode  <http://data.lblod.info/id/periodes/f727d567-e43e-4c1c-bd6a-6071ab83f903>.

    <http://lblod.data.info/id/subsidy-measure-offer-series/666bb466-e0ba-4639-9260-d94e9d67e87f> lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/a91a1576-b792-44cd-ab49-91973e4a8e47>.

    <http://lblod.data.info/id/subsidie-application-flow-steps/c38d4ab1-17b0-4281-81d7-7bd0001f6053> xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/958f92d1-988b-4bcd-8eff-9abe99756582>.

    <http://lblod.data.info/id/subsidie-application-flow-steps/958f92d1-988b-4bcd-8eff-9abe99756582> a lblodSubsidie:ApplicationStep;
      mu:uuid "958f92d1-988b-4bcd-8eff-9abe99756582";
      qb:order 1;
      xkos:previous  <http://lblod.data.info/id/subsidie-application-flow-steps/c38d4ab1-17b0-4281-81d7-7bd0001f6053>;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/a91a1576-b792-44cd-ab49-91973e4a8e47>;
      dct:isPartOf  <http://lblod.data.info/id/subsidie-application-flows/f99b3893-6247-4843-ab7f-c1ee3b8ec3fd>;
      dct:source <config://forms/e-inclusion/accountability/versions/20220824090000/form.ttl>.

    <http://data.lblod.info/id/periodes/f727d567-e43e-4c1c-bd6a-6071ab83f903> a <http://data.europa.eu/m8g/PeriodOfTime>;
      mu:uuid "f727d567-e43e-4c1c-bd6a-6071ab83f903";
      <http://data.europa.eu/m8g/startTime> "2022-12-01T03:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>;
      <http://data.europa.eu/m8g/endTime> "2025-06-30T21:59:58Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}

