PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d" ;
      skos:prefLabel "IGS Cultuur Noordrand" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0740822256" ;
      dcterms:identifier "OVO036446", "0740822256" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/daebd00b2f84977441a8c351883a6ee9>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"daebd00b2f84977441a8c351883a6ee9" ;
      skos:prefLabel "Directiecomité IGS Cultuur Noordrand" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d> .

    <http://data.lblod.info/id/bestuursorganen/b842aff211b165cc85133949f8bb8950>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"b842aff211b165cc85133949f8bb8950" ;
      skos:prefLabel "Raad van bestuur IGS Cultuur Noordrand" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d> .

    <http://data.lblod.info/id/bestuursorganen/58b676190e3fe0e35795d3a26131c402>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"58b676190e3fe0e35795d3a26131c402" ;
      skos:prefLabel "Bevoegd beslissingsorgaan IGS Cultuur Noordrand" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d> .

    <http://data.lblod.info/id/bestuursorganen/13dfca15662940564215b75bab78c753>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"13dfca15662940564215b75bab78c753" ;
      skos:prefLabel "Algemene vergadering IGS Cultuur Noordrand" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d> .

    <http://data.lblod.info/id/bestuursorganen/67a0f5f9137be5be3518f03f0652aa3c>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"67a0f5f9137be5be3518f03f0652aa3c" ;
      skos:prefLabel "Leidend Ambtenaar IGS Cultuur Noordrand" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/f0e5fbf5655dd8a116ea5b5f4603acbc>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"f0e5fbf5655dd8a116ea5b5f4603acbc" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/daebd00b2f84977441a8c351883a6ee9> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/879480ca1914d6c1ca1f20d0cf26f7c2>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "879480ca1914d6c1ca1f20d0cf26f7c2" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/b842aff211b165cc85133949f8bb8950> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/e544d32cd828ee20a8660b60306cad05>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"e544d32cd828ee20a8660b60306cad05" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/58b676190e3fe0e35795d3a26131c402> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/da9f284b677fbf935967a1607042f1e0>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"da9f284b677fbf935967a1607042f1e0" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/13dfca15662940564215b75bab78c753> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/e6191aefeb0b1bce23abe69eb9b88097>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"e6191aefeb0b1bce23abe69eb9b88097" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/67a0f5f9137be5be3518f03f0652aa3c> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
