DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/a7de09df-c62f-4c70-a8fa-b9634112d10e> <http://data.europa.eu/m8g/endTime> "2021-11-30T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/a7de09df-c62f-4c70-a8fa-b9634112d10e> <http://data.europa.eu/m8g/endTime> "2021-10-31T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
