PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX sbc: <http://data.lblod.info/vocabularies/subsidie/climate/>
PREFIX dummy: <http://data.lblod.info/id/climate/dummy/for/>

# Avoid sprintf error
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    dummy:sprintf a <http://data.lblod.info/dummy/Type> .
  }
}

DELETE {
  GRAPH ?g {
    dummy:sprintf a ?dummyType.

    ?sub ext:actionDescription ?description;
          ext:toRealiseUnits ?toRealiseUnitsValue;
          ext:costPerUnit ?costPerUnitValue;
          ext:restitution ?restitutionValue;
          ext:amountPerAction ?amountPerActionValue.

  }
}
INSERT {
  GRAPH ?g {
    ext:sprintf a ?dummyType.

    ?sub sbc:actionDescription ?description;
          sbc:toRealiseUnits ?toRealiseUnitsValue;
          sbc:costPerUnit ?costPerUnitValue;
          sbc:restitution ?restitutionValue;
          sbc:amountPerAction ?amountPerActionValue.
    }
}
WHERE {
  GRAPH ?g {
    dummy:sprintf a ?dummyType.

    OPTIONAL { ?sub ext:actionDescription ?description. }
    OPTIONAL { ?sub ext:toRealiseUnits ?toRealiseUnitsValue. }
    OPTIONAL { ?sub ext:costPerUnit ?costPerUnitValue. }
    OPTIONAL { ?sub ext:restitution ?restitutionValue. }
    OPTIONAL { ?sub ext:amountPerAction ?amountPerActionValue. }
    }
  }
}

# Avoid sprintf error
DELETE {
  GRAPH ?g {
    ext:sprintf ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ext:sprintf ?p ?o .
  }
}
