PREFIX m8g: <http://data.europa.eu/m8g/>

DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            m8g:endTime "2021-09-30T00:00:00"^^xsd:dateTime .
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            m8g:startTime "2021-06-14T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-10-29T00:00:00"^^xsd:dateTime .
    }
}