PREFIX meb: <http://rdf.myexperiment.org/ontologies/base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX melding: <http://lblod.data.gift/vocabularies/automatische-melding/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX erediensten: <http://data.lblod.info/vocabularies/erediensten/>
DELETE {
  GRAPH ?g {
    ?submissionDocument ?submissionDocumentP ?submissionDocumentO.
  }
}
WHERE {
  ?eenheid a erediensten:CentraalBestuurVanDeEredienst.
  GRAPH ?g {
   ?submission a meb:Submission;
     <http://purl.org/pav/createdBy> ?eenheid;
     dct:subject ?submissionDocument;
     adms:status ?status;
     prov:generated ?formData;
     ?submissionP ?submissionO.

     ?submissionDocument a ext:SubmissionDocument;
       ?submissionDocumentP ?submissionDocumentO.
   }
}