PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "d0125202-c4b1-4372-ba12-d6de58b12660" ;
      skos:prefLabel "Jeugdregio Pajottenland" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0746877432" ;
      dcterms:identifier "OVO038771", "0746877432" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/12d0b526a9640df46e3fcb268bcc0e3d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"12d0b526a9640df46e3fcb268bcc0e3d" ;
      skos:prefLabel "Directiecomité Jeugdregio Pajottenland" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660> .

    <http://data.lblod.info/id/bestuursorganen/05b5f3125af902a52014bd77f35d02ae>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"05b5f3125af902a52014bd77f35d02ae" ;
      skos:prefLabel "Raad van bestuur Jeugdregio Pajottenland" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660> .

    <http://data.lblod.info/id/bestuursorganen/6251085e94bfb06b7c8573e018ffcf54>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"6251085e94bfb06b7c8573e018ffcf54" ;
      skos:prefLabel "Bevoegd beslissingsorgaan Jeugdregio Pajottenland" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660> .

    <http://data.lblod.info/id/bestuursorganen/0c864d49c56d3550d94ddf4eba554be5>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"0c864d49c56d3550d94ddf4eba554be5" ;
      skos:prefLabel "Algemene vergadering Jeugdregio Pajottenland" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660> .

    <http://data.lblod.info/id/bestuursorganen/6e48bcec0b3e0434053dfb4715af079f>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"6e48bcec0b3e0434053dfb4715af079f" ;
      skos:prefLabel "Leidend Ambtenaar Jeugdregio Pajottenland" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/3e43b4553c89a17623eea95ed0abdb0d>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"3e43b4553c89a17623eea95ed0abdb0d" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/12d0b526a9640df46e3fcb268bcc0e3d> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/958f511c46745c69ac2e9ee36edc6be6>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "958f511c46745c69ac2e9ee36edc6be6" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/05b5f3125af902a52014bd77f35d02ae> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/d24d81022e280cdb9db2314e8772a38b>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"d24d81022e280cdb9db2314e8772a38b" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/6251085e94bfb06b7c8573e018ffcf54> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/e319724e2a100205de849f1053b7cb3b>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"e319724e2a100205de849f1053b7cb3b" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/0c864d49c56d3550d94ddf4eba554be5> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/af9da25933db9331bd6c02ea5b5e2c8d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"af9da25933db9331bd6c02ea5b5e2c8d" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/6e48bcec0b3e0434053dfb4715af079f> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
