PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX cube: <http://purl.org/linked-data/cube#>

### CREATE NEW FLOW FOR UPDATED CONFIGURATION
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Flow
    <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267>
      a lblodSubsidie:ApplicationFlow ;
      mu:uuid "6d850270-a84b-466d-a572-84a17a734267" ;
      xkos:belongsTo <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/aa5bd359-e7ea-4fb8-9796-b4e9963bf0be> .

    # Proposal step
    <http://lblod.data.info/id/subsidie-application-flow-steps/aa5bd359-e7ea-4fb8-9796-b4e9963bf0be>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "aa5bd359-e7ea-4fb8-9796-b4e9963bf0be" ;
      dct:source <config://forms/bicycle-infrastructure/proposal/versions/20210420163405-initial-version/form.ttl> ;
      cube:order 0 ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/75aa0af5-21e1-44c4-96e9-7f7f013bd1cc> ;
      dct:references <http://data.lblod.info/id/subsidieprocedurestappen/002f93ed-bdb0-4e3a-af13-ef6c00e89651> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267> .

    # Request step
    <http://lblod.data.info/id/subsidie-application-flow-steps/75aa0af5-21e1-44c4-96e9-7f7f013bd1cc>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "75aa0af5-21e1-44c4-96e9-7f7f013bd1cc" ;
      dct:source <config://forms/bicycle-infrastructure/request/versions/20210827112848-fix-estimatedCost-validation/form.ttl> ;
      cube:order 1 ;
      xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/aa5bd359-e7ea-4fb8-9796-b4e9963bf0be> ;
      dct:references <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267> .
  }
}

;
### SET THAT NEW FLOW AS THE ACTIVE ONE
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> common:active <http://lblod.data.info/id/subsidie-application-flows/1a7fb92ca5e7a948c687bda5754233cbb654d1c324dda5dbe9fce6ed4fbad163> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> common:active <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267> .
  }
}
