DELETE {
  GRAPH ?g {
    ?formData <http://purl.org/dc/terms/hasPart> ?remoteDataObject .
    ?remoteDataObject ?p ?o .
    ?file ?pfile ?ofile .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?remoteDataObject {
      <http://data.lblod.info/id/remote-data-objects/017b1550-3fa6-11f0-9619-dd6560b7b0d1>
    }

    ?formData <http://purl.org/dc/terms/hasPart> ?remoteDataObject .

    ?remoteDataObject ?p ?o .

    ?file <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#dataSource> ?remoteDataObject ;
      ?pfile ?ofile .
  }
}
