PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

# Update the reference of the duplicate person to the correct person
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/functionarissen/677CFAAFA0D1558085B90DE6> mandaat:isBestuurlijkeAliasVan ?duplicatePerson .
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/functionarissen/677CFAAFA0D1558085B90DE6> mandaat:isBestuurlijkeAliasVan ?correctPerson .
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/personen/5FCFA65879CE53000800061F> AS ?correctPerson)
  BIND(<http://data.lblod.info/id/personen/677CFA9FA0D1558085B90DE5> AS ?duplicatePerson)

  GRAPH ?g {
    <http://data.lblod.info/id/functionarissen/677CFAAFA0D1558085B90DE6> mandaat:isBestuurlijkeAliasVan ?duplicatePerson .
  }
}

;

# Cleanup the duplicate person
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/677CFA9FA0D1558085B90DE5> ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/677CFA9FA0D1558085B90DE5> ?p ?o .
  }
}

;

# Link from duplicatePerson to correctPerson
INSERT {
  GRAPH ?g {
    ?duplicatePerson owl:sameAs ?correctPerson .
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/personen/5FCFA65879CE53000800061F> AS ?correctPerson)
  BIND(<http://data.lblod.info/id/personen/677CFA9FA0D1558085B90DE5> AS ?duplicatePerson)

  GRAPH ?g {
    ?correctPerson ?p ?o .
  }
}
