PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://lblod.data.gift/vocabularies/besluit/>
PREFIX BestuurseenheidClassificatieCode: <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>
PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX BesluitType: <https://data.vlaanderen.be/id/concept/BesluitType/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    BesluitType:0a8141bc-cf35-43dd-855d-365fa32ad89b
      a skos:Concept ;
      core:uuid "0a8141bc-cf35-43dd-855d-365fa32ad89b" ;
      besluit:decidableBy BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000001 ; # Gemeente
      besluit:decidableBy BestuurseenheidClassificatieCode:5ab0e9b8a3b2ca7c5e000000 ; # Provincie
      skos:prefLabel "Jaarrekening PEVA" ;
      skos:definition "Besluit van gemeente- of provincieraad over de jaarrekening van een extern verzelfstandigd agentschap in privaatrechtelijke vorm." ;
      skos:inScheme <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5> ;
      skos:topConceptOf <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5> ;
      skos:inScheme <https://data.vlaanderen.be/id/conceptscheme/BesluitType> ;
      skos:topConceptOf <https://data.vlaanderen.be/id/conceptscheme/BesluitType> .
   }
}
