PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
  GRAPH ?g {
    ?s ?p ?srtTagged .
  }
}
WHERE {
  GRAPH ?g {
    ?s
      prov:wasGeneratedBy <http://lblod.data.gift/id/app/lblod-harvesting> ;
      ?p ?str ;
      ?p ?srtTagged .
    FILTER (?str = STR(?srtTagged))
    FILTER (lang(?str) = "")
    FILTER (lang(?srtTagged) != "")
  }
}

