PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20231220183130-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "864a92b3-da35-4af4-83b9-f0a02d438f93" ;
      nfo:fileName "20231220183130-forms.ttl" ;
      dct:created "2023-12-20T18:31:30"^^xsd:dateTime ;
      dct:modified "2023-12-20T18:31:30"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "411419"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    