PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/f455172d-3f27-45b1-b2ab-95f5c99d3a5f> mg8:endTime ?end.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/f455172d-3f27-45b1-b2ab-95f5c99d3a5f> mg8:endTime "2022-07-01T21:59:59Z"^^xsd:dateTime .
  }
}