PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX objective: <http://data.lblod.info/vocabularies/plan-samenleven-subsidies/objective/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX range: <http://data.lblod.info/vocabularies/plan-samenleven-subsidies/range/>
PREFIX contribution: <http://data.lblod.info/vocabularies/plan-samenleven-subsidies/contribution/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "646b3381-9a63-48d3-8686-4d877502db8c" ;
        skos:prefLabel "Plan Samenleven doelstellingen rules"@en .

    <http://data.lblod.info/id/subsidies/rules/7f7f1d20-942d-48ac-85a0-748db7f3d835> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "7f7f1d20-942d-48ac-85a0-748db7f3d835" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Veiligheid en leefbaarheid'@nl ;
        dct:description 'Ontwikkelen van een lokaal actieplan voor de aanpak van polarisatie en zetten in op de uitrol ervan.'@nl ;
        range:label "lokaal actieplan";
        range:maximum "1"^^xsd:integer;
        contribution:multiplier "12500"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/f8be95d1-b262-4a7c-8bfb-e77c115d42c6> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "f8be95d1-b262-4a7c-8bfb-e77c115d42c6" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Nederlands'@nl ;
        dct:description 'Volwassen anderstaligen nemen deel aan een oefenkans.'@nl ;
        range:label "volwassen anderstaligen";
        range:maximum "2250"^^xsd:integer;
        contribution:multiplier "60"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/ba162648-8286-4c36-bce3-03b816069b28> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "ba162648-8286-4c36-bce3-03b816069b28" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Competenties'@nl ;
        dct:description 'Begeleiden van personen met een diploma van buiten de EU naar verkorte opleidingstrajecten.'@nl ;
        range:label "begeleide personen";
        range:maximum "23"^^xsd:integer;
        contribution:multiplier "600"^^xsd:integer.
    
    <http://data.lblod.info/id/subsidies/rules/15217ddf-e56a-4529-9352-f0c82d433546> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "15217ddf-e56a-4529-9352-f0c82d433546" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Competenties'@nl ;
        dct:description 'Begeleiden van kwetsbare kinderen naar hogere studies.'@nl ;
        range:label "kwetsbare kinderen";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/55a23203-794a-4680-8223-cae33b01ad8e> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "55a23203-794a-4680-8223-cae33b01ad8e" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Competenties'@nl ;
        dct:description 'Begeleiden van ongekwalificeerde uitstromers naar een kwalificerend traject.'@nl ;
        range:label "ongekwalificeerde uitstromers";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/bd57a052-8744-402b-bdcb-19d0c386ff54> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "bd57a052-8744-402b-bdcb-19d0c386ff54" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Werk'@nl ;
        dct:description 'Begeleiden van nieuwkomers, mensen met een handicap en 55plussers naar de arbeidsmarkt.'@nl ;
        range:label "begeleide nieuwkomers";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.
        

    <http://data.lblod.info/id/subsidies/rules/a7643e23-3eee-477c-baf4-bd1eb93d9aa5> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "a7643e23-3eee-477c-baf4-bd1eb93d9aa5" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "begeleide personen met een handicap";
        range:maximum "38"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/88388d78-f277-43ee-963e-6e111fc28d46> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "88388d78-f277-43ee-963e-6e111fc28d46" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "begeleide 55-plussers";
        range:maximum "75"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/6b8a5a4e-c1f8-40c7-9a23-7b589aede212> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "6b8a5a4e-c1f8-40c7-9a23-7b589aede212" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Werk'@nl ;
        dct:description 'Begeleiden van nieuwkomers, vrouwen en personen met een handicap naar ondernemerschap'@nl ;
        range:label "begeleide nieuwkomers";
        range:maximum "75"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/8bae2cec-4b7c-4e16-acc2-e747d9e3b853> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "8bae2cec-4b7c-4e16-acc2-e747d9e3b853" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "begeleide vrouwen";
        range:maximum "30"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/619edfa8-0004-45d3-af51-7faf71d477d5> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "619edfa8-0004-45d3-af51-7faf71d477d5" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "begeleide personen met een handicap";
        range:maximum "15"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/ec887ea5-83ee-4782-866c-1ddedd6d7ed0> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "ec887ea5-83ee-4782-866c-1ddedd6d7ed0" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Werk'@nl ;
        dct:description 'Inzet van mentoren die jonge personen van buitenlandse herkomst begeleiden naar werk.'@nl ;
        range:label "begeleide personen van buitenlandse herkomst";
        range:maximum "300"^^xsd:integer;
        contribution:multiplier "320"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/80dd881d-9706-40be-8f0b-fe97d69fa00d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "80dd881d-9706-40be-8f0b-fe97d69fa00d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Netwerk'@nl ;
        dct:description 'Jongeren van buitenlandse herkomst en jongeren met een handicap in contact brengen met sport.'@nl ;
        range:label "jongeren van buitenlandse herkomst";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/c5719bb2-e567-433c-ae6b-f99ff5c98897> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "c5719bb2-e567-433c-ae6b-f99ff5c98897" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "personen met een handicap";
        range:maximum "30"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/5faefdda-75aa-45cd-acd4-1ee051e806fd> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "5faefdda-75aa-45cd-acd4-1ee051e806fd" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Netwerk'@nl ;
        dct:description 'Jongeren met een grotere afstand tot de arbeidsmarkt in contact brengen met opleidingen, stages, jobs en ondernemerschap'@nl ;
        range:label "jongeren met grotere afstand tot de arbeidsmarkt";
        range:maximum "180"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/2b415839-747b-4514-a3f2-d02ca4303be4> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "2b415839-747b-4514-a3f2-d02ca4303be4" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Netwerk'@nl ;
        dct:description 'Inzetten van brugfiguren die de brug maken tussen kwetsbare gezinnen en onderwijs.'@nl ;
        range:label "kwetsbare gezinnen";
        range:maximum "300"^^xsd:integer;
        contribution:multiplier "320"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/7fbac258-3c1c-44a1-8db0-ffcdcb6a3113> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "7fbac258-3c1c-44a1-8db0-ffcdcb6a3113" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Non-discriminatie'@nl ;
        dct:description 'Ontwikkelen van lokale actieplannen voor de aanpak van straatintimidatie en de uitrol ervan.'@nl ;
        range:label "lokaal actieplan";
        range:maximum "1"^^xsd:integer;
        contribution:multiplier "25000"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/0b0d5a3a-0c10-4acf-9a94-fd4e881444bc> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "0b0d5a3a-0c10-4acf-9a94-fd4e881444bc" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Non-discriminatie'@nl ;
        dct:description 'Vormen van professionals en burgers volgens het omstaanders-principe'@nl ;
        range:label "gevormde professionals";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "90"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/f7c0a231-e418-4f38-8f73-3815a22f518b> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "f7c0a231-e418-4f38-8f73-3815a22f518b" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "gevormde burgers";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "90"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/a419be41-704b-488d-b7c1-86d50a8a46ce> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "a419be41-704b-488d-b7c1-86d50a8a46ce" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Non-discriminatie'@nl ;
        dct:description 'Ontwikkelen van lokale actieplannen voor de toegankelijkheid van publieke gebouwen en de uitrol ervan.'@nl ;
        range:label "lokaal actieplan";
        range:maximum "1"^^xsd:integer;
        contribution:multiplier "25000"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/fea603c6-dc87-4c09-bb85-3520cc1c495d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "fea603c6-dc87-4c09-bb85-3520cc1c495d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel 'Non-discriminatie'@nl ;
        dct:description 'Inzetten van correspondentietesten om discriminatie te meten'@nl ;
        range:label "bestuur dat correspondentietesten inzet";
        range:maximum "1"^^xsd:integer;
        contribution:multiplier "25000"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/f732ab43-ea22-4590-b3a4-6617cff64777> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "f732ab43-ea22-4590-b3a4-6617cff64777" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel '1 gemeenschap'@nl ;
        dct:description 'Begeleiden van gezinnen om de sociale mix in scholen te bevorderen'@nl ;
        range:label "begeleide gezinnen";
        range:maximum "300"^^xsd:integer;
        contribution:multiplier "170"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/5fcf7a3a-04b7-46e7-9449-2088656c555b> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "5fcf7a3a-04b7-46e7-9449-2088656c555b" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel '1 gemeenschap'@nl ;
        dct:description 'Begeleiden van jongeren van buitenlandse herkomst en personen met een handicap tot een lerarenopleiding.'@nl ;
        range:label "jongeren van buitenlandse herkomst";
        range:maximum "15"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/2f7db13f-b710-4b94-92c8-efcf8eac1ead> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "2f7db13f-b710-4b94-92c8-efcf8eac1ead" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "jongeren met een handicap";
        range:maximum "8"^^xsd:integer;
        contribution:multiplier "650"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/fd1882a8-996c-42a8-8774-0a7a453f5c70> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "fd1882a8-996c-42a8-8774-0a7a453f5c70" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel '1 gemeenschap'@nl ;
        dct:description 'Inzetten van pleinmakers in sociale woonwijken om het sociaal weefsel te versterken.'@nl ;
        range:label "pleinmakers";
        range:maximum "4"^^xsd:integer;
        contribution:multiplier "5800"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/2952c920-fbe5-403a-a267-c94c0813f85f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "2952c920-fbe5-403a-a267-c94c0813f85f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel '1 gemeenschap'@nl ;
        dct:description 'Jongeren van buitenlandse herkomst en jongeren met een handicap in contact brengen met jeugdwerk.'@nl ;
        range:label "jongeren van buitenlandse herkomst";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/17afa0d1-c0be-4800-a9bc-9f48506346eb> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "17afa0d1-c0be-4800-a9bc-9f48506346eb" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "jongeren met een handicap";
        range:maximum "30"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/e4effa35-4453-426a-95af-17767e23ed64> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "e4effa35-4453-426a-95af-17767e23ed64" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        skos:prefLabel '1 gemeenschap'@nl ;
        dct:description 'Jongeren van buitenlandse herkomst en jongeren met een handicap in contact brengen met cultuur.'@nl ;
        range:label "jongeren van buitenlandse herkomst";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.

    <http://data.lblod.info/id/subsidies/rules/56e523bd-ad3c-4648-94b0-df6d9e72c7b0> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://data.lblod.info/vocabularies/plan-living-together-subsidies/PlanLivingTogetherSubsidyWithdrawalRule>;
        mu:uuid "56e523bd-ad3c-4648-94b0-df6d9e72c7b0" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/646b3381-9a63-48d3-8686-4d877502db8c> ;
        range:label "jongeren met een handicap";
        range:maximum "150"^^xsd:integer;
        contribution:multiplier "210"^^xsd:integer.
  }
}