DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://lblod.data.gift/vocabularies/lpdc-ipdc/IPDCLocaties>
    <http://vocab.belgif.be/auth/refnis2019/1000>
    <http://vocab.belgif.be/auth/refnis2019/10000>
    <http://vocab.belgif.be/auth/refnis2019/11000>
    <http://vocab.belgif.be/auth/refnis2019/11001>
    <http://vocab.belgif.be/auth/refnis2019/11002>
    <http://vocab.belgif.be/auth/refnis2019/11004>
    <http://vocab.belgif.be/auth/refnis2019/11005>
    <http://vocab.belgif.be/auth/refnis2019/11007>
    <http://vocab.belgif.be/auth/refnis2019/11008>
    <http://vocab.belgif.be/auth/refnis2019/11009>
    <http://vocab.belgif.be/auth/refnis2019/11013>
    <http://vocab.belgif.be/auth/refnis2019/11016>
    <http://vocab.belgif.be/auth/refnis2019/11018>
    <http://vocab.belgif.be/auth/refnis2019/11021>
    <http://vocab.belgif.be/auth/refnis2019/11022>
    <http://vocab.belgif.be/auth/refnis2019/11023>
    <http://vocab.belgif.be/auth/refnis2019/11024>
    <http://vocab.belgif.be/auth/refnis2019/11025>
    <http://vocab.belgif.be/auth/refnis2019/11029>
    <http://vocab.belgif.be/auth/refnis2019/11030>
    <http://vocab.belgif.be/auth/refnis2019/11035>
    <http://vocab.belgif.be/auth/refnis2019/11037>
    <http://vocab.belgif.be/auth/refnis2019/11038>
    <http://vocab.belgif.be/auth/refnis2019/11039>
    <http://vocab.belgif.be/auth/refnis2019/11040>
    <http://vocab.belgif.be/auth/refnis2019/11044>
    <http://vocab.belgif.be/auth/refnis2019/11050>
    <http://vocab.belgif.be/auth/refnis2019/11052>
    <http://vocab.belgif.be/auth/refnis2019/11053>
    <http://vocab.belgif.be/auth/refnis2019/11054>
    <http://vocab.belgif.be/auth/refnis2019/11055>
    <http://vocab.belgif.be/auth/refnis2019/11056>
    <http://vocab.belgif.be/auth/refnis2019/11057>
    <http://vocab.belgif.be/auth/refnis2019/12000>
    <http://vocab.belgif.be/auth/refnis2019/12002>
    <http://vocab.belgif.be/auth/refnis2019/12005>
    <http://vocab.belgif.be/auth/refnis2019/12007>
    <http://vocab.belgif.be/auth/refnis2019/12009>
    <http://vocab.belgif.be/auth/refnis2019/12014>
    <http://vocab.belgif.be/auth/refnis2019/12021>
    <http://vocab.belgif.be/auth/refnis2019/12025>
    <http://vocab.belgif.be/auth/refnis2019/12026>
    <http://vocab.belgif.be/auth/refnis2019/12029>
    <http://vocab.belgif.be/auth/refnis2019/12035>
    <http://vocab.belgif.be/auth/refnis2019/12040>
    <http://vocab.belgif.be/auth/refnis2019/12041>
    <http://vocab.belgif.be/auth/refnis2019/13000>
    <http://vocab.belgif.be/auth/refnis2019/13001>
    <http://vocab.belgif.be/auth/refnis2019/13002>
    <http://vocab.belgif.be/auth/refnis2019/13003>
    <http://vocab.belgif.be/auth/refnis2019/13004>
    <http://vocab.belgif.be/auth/refnis2019/13006>
    <http://vocab.belgif.be/auth/refnis2019/13008>
    <http://vocab.belgif.be/auth/refnis2019/13010>
    <http://vocab.belgif.be/auth/refnis2019/13011>
    <http://vocab.belgif.be/auth/refnis2019/13012>
    <http://vocab.belgif.be/auth/refnis2019/13013>
    <http://vocab.belgif.be/auth/refnis2019/13014>
    <http://vocab.belgif.be/auth/refnis2019/13016>
    <http://vocab.belgif.be/auth/refnis2019/13017>
    <http://vocab.belgif.be/auth/refnis2019/13019>
    <http://vocab.belgif.be/auth/refnis2019/13021>
    <http://vocab.belgif.be/auth/refnis2019/13023>
    <http://vocab.belgif.be/auth/refnis2019/13025>
    <http://vocab.belgif.be/auth/refnis2019/13029>
    <http://vocab.belgif.be/auth/refnis2019/13031>
    <http://vocab.belgif.be/auth/refnis2019/13035>
    <http://vocab.belgif.be/auth/refnis2019/13036>
    <http://vocab.belgif.be/auth/refnis2019/13037>
    <http://vocab.belgif.be/auth/refnis2019/13040>
    <http://vocab.belgif.be/auth/refnis2019/13044>
    <http://vocab.belgif.be/auth/refnis2019/13046>
    <http://vocab.belgif.be/auth/refnis2019/13049>
    <http://vocab.belgif.be/auth/refnis2019/13053>
    <http://vocab.belgif.be/auth/refnis2019/2000>
    <http://vocab.belgif.be/auth/refnis2019/20001>
    <http://vocab.belgif.be/auth/refnis2019/20002>
    <http://vocab.belgif.be/auth/refnis2019/21000>
    <http://vocab.belgif.be/auth/refnis2019/21001>
    <http://vocab.belgif.be/auth/refnis2019/21002>
    <http://vocab.belgif.be/auth/refnis2019/21003>
    <http://vocab.belgif.be/auth/refnis2019/21004>
    <http://vocab.belgif.be/auth/refnis2019/21005>
    <http://vocab.belgif.be/auth/refnis2019/21006>
    <http://vocab.belgif.be/auth/refnis2019/21007>
    <http://vocab.belgif.be/auth/refnis2019/21008>
    <http://vocab.belgif.be/auth/refnis2019/21009>
    <http://vocab.belgif.be/auth/refnis2019/21010>
    <http://vocab.belgif.be/auth/refnis2019/21011>
    <http://vocab.belgif.be/auth/refnis2019/21012>
    <http://vocab.belgif.be/auth/refnis2019/21013>
    <http://vocab.belgif.be/auth/refnis2019/21014>
    <http://vocab.belgif.be/auth/refnis2019/21015>
    <http://vocab.belgif.be/auth/refnis2019/21016>
    <http://vocab.belgif.be/auth/refnis2019/21017>
    <http://vocab.belgif.be/auth/refnis2019/21018>
    <http://vocab.belgif.be/auth/refnis2019/21019>
    <http://vocab.belgif.be/auth/refnis2019/23000>
    <http://vocab.belgif.be/auth/refnis2019/23002>
    <http://vocab.belgif.be/auth/refnis2019/23003>
    <http://vocab.belgif.be/auth/refnis2019/23009>
    <http://vocab.belgif.be/auth/refnis2019/23016>
    <http://vocab.belgif.be/auth/refnis2019/23023>
    <http://vocab.belgif.be/auth/refnis2019/23024>
    <http://vocab.belgif.be/auth/refnis2019/23025>
    <http://vocab.belgif.be/auth/refnis2019/23027>
    <http://vocab.belgif.be/auth/refnis2019/23032>
    <http://vocab.belgif.be/auth/refnis2019/23033>
    <http://vocab.belgif.be/auth/refnis2019/23038>
    <http://vocab.belgif.be/auth/refnis2019/23039>
    <http://vocab.belgif.be/auth/refnis2019/23044>
    <http://vocab.belgif.be/auth/refnis2019/23045>
    <http://vocab.belgif.be/auth/refnis2019/23047>
    <http://vocab.belgif.be/auth/refnis2019/23050>
    <http://vocab.belgif.be/auth/refnis2019/23052>
    <http://vocab.belgif.be/auth/refnis2019/23060>
    <http://vocab.belgif.be/auth/refnis2019/23062>
    <http://vocab.belgif.be/auth/refnis2019/23064>
    <http://vocab.belgif.be/auth/refnis2019/23077>
    <http://vocab.belgif.be/auth/refnis2019/23081>
    <http://vocab.belgif.be/auth/refnis2019/23086>
    <http://vocab.belgif.be/auth/refnis2019/23088>
    <http://vocab.belgif.be/auth/refnis2019/23094>
    <http://vocab.belgif.be/auth/refnis2019/23096>
    <http://vocab.belgif.be/auth/refnis2019/23097>
    <http://vocab.belgif.be/auth/refnis2019/23098>
    <http://vocab.belgif.be/auth/refnis2019/23099>
    <http://vocab.belgif.be/auth/refnis2019/23100>
    <http://vocab.belgif.be/auth/refnis2019/23101>
    <http://vocab.belgif.be/auth/refnis2019/23102>
    <http://vocab.belgif.be/auth/refnis2019/23103>
    <http://vocab.belgif.be/auth/refnis2019/23104>
    <http://vocab.belgif.be/auth/refnis2019/23105>
    <http://vocab.belgif.be/auth/refnis2019/24000>
    <http://vocab.belgif.be/auth/refnis2019/24001>
    <http://vocab.belgif.be/auth/refnis2019/24007>
    <http://vocab.belgif.be/auth/refnis2019/24008>
    <http://vocab.belgif.be/auth/refnis2019/24009>
    <http://vocab.belgif.be/auth/refnis2019/24011>
    <http://vocab.belgif.be/auth/refnis2019/24014>
    <http://vocab.belgif.be/auth/refnis2019/24016>
    <http://vocab.belgif.be/auth/refnis2019/24020>
    <http://vocab.belgif.be/auth/refnis2019/24028>
    <http://vocab.belgif.be/auth/refnis2019/24033>
    <http://vocab.belgif.be/auth/refnis2019/24038>
    <http://vocab.belgif.be/auth/refnis2019/24041>
    <http://vocab.belgif.be/auth/refnis2019/24043>
    <http://vocab.belgif.be/auth/refnis2019/24045>
    <http://vocab.belgif.be/auth/refnis2019/24048>
    <http://vocab.belgif.be/auth/refnis2019/24054>
    <http://vocab.belgif.be/auth/refnis2019/24055>
    <http://vocab.belgif.be/auth/refnis2019/24059>
    <http://vocab.belgif.be/auth/refnis2019/24062>
    <http://vocab.belgif.be/auth/refnis2019/24066>
    <http://vocab.belgif.be/auth/refnis2019/24086>
    <http://vocab.belgif.be/auth/refnis2019/24094>
    <http://vocab.belgif.be/auth/refnis2019/24104>
    <http://vocab.belgif.be/auth/refnis2019/24107>
    <http://vocab.belgif.be/auth/refnis2019/24109>
    <http://vocab.belgif.be/auth/refnis2019/24130>
    <http://vocab.belgif.be/auth/refnis2019/24133>
    <http://vocab.belgif.be/auth/refnis2019/24134>
    <http://vocab.belgif.be/auth/refnis2019/24135>
    <http://vocab.belgif.be/auth/refnis2019/24137>
    <http://vocab.belgif.be/auth/refnis2019/25000>
    <http://vocab.belgif.be/auth/refnis2019/25005>
    <http://vocab.belgif.be/auth/refnis2019/25014>
    <http://vocab.belgif.be/auth/refnis2019/25015>
    <http://vocab.belgif.be/auth/refnis2019/25018>
    <http://vocab.belgif.be/auth/refnis2019/25023>
    <http://vocab.belgif.be/auth/refnis2019/25031>
    <http://vocab.belgif.be/auth/refnis2019/25037>
    <http://vocab.belgif.be/auth/refnis2019/25043>
    <http://vocab.belgif.be/auth/refnis2019/25044>
    <http://vocab.belgif.be/auth/refnis2019/25048>
    <http://vocab.belgif.be/auth/refnis2019/25050>
    <http://vocab.belgif.be/auth/refnis2019/25068>
    <http://vocab.belgif.be/auth/refnis2019/25072>
    <http://vocab.belgif.be/auth/refnis2019/25084>
    <http://vocab.belgif.be/auth/refnis2019/25091>
    <http://vocab.belgif.be/auth/refnis2019/25105>
    <http://vocab.belgif.be/auth/refnis2019/25107>
    <http://vocab.belgif.be/auth/refnis2019/25110>
    <http://vocab.belgif.be/auth/refnis2019/25112>
    <http://vocab.belgif.be/auth/refnis2019/25117>
    <http://vocab.belgif.be/auth/refnis2019/25118>
    <http://vocab.belgif.be/auth/refnis2019/25119>
    <http://vocab.belgif.be/auth/refnis2019/25120>
    <http://vocab.belgif.be/auth/refnis2019/25121>
    <http://vocab.belgif.be/auth/refnis2019/25122>
    <http://vocab.belgif.be/auth/refnis2019/25123>
    <http://vocab.belgif.be/auth/refnis2019/25124>
    <http://vocab.belgif.be/auth/refnis2019/3000>
    <http://vocab.belgif.be/auth/refnis2019/30000>
    <http://vocab.belgif.be/auth/refnis2019/31000>
    <http://vocab.belgif.be/auth/refnis2019/31003>
    <http://vocab.belgif.be/auth/refnis2019/31004>
    <http://vocab.belgif.be/auth/refnis2019/31005>
    <http://vocab.belgif.be/auth/refnis2019/31006>
    <http://vocab.belgif.be/auth/refnis2019/31012>
    <http://vocab.belgif.be/auth/refnis2019/31022>
    <http://vocab.belgif.be/auth/refnis2019/31033>
    <http://vocab.belgif.be/auth/refnis2019/31040>
    <http://vocab.belgif.be/auth/refnis2019/31042>
    <http://vocab.belgif.be/auth/refnis2019/31043>
    <http://vocab.belgif.be/auth/refnis2019/32000>
    <http://vocab.belgif.be/auth/refnis2019/32003>
    <http://vocab.belgif.be/auth/refnis2019/32006>
    <http://vocab.belgif.be/auth/refnis2019/32010>
    <http://vocab.belgif.be/auth/refnis2019/32011>
    <http://vocab.belgif.be/auth/refnis2019/32030>
    <http://vocab.belgif.be/auth/refnis2019/33000>
    <http://vocab.belgif.be/auth/refnis2019/33011>
    <http://vocab.belgif.be/auth/refnis2019/33016>
    <http://vocab.belgif.be/auth/refnis2019/33021>
    <http://vocab.belgif.be/auth/refnis2019/33029>
    <http://vocab.belgif.be/auth/refnis2019/33037>
    <http://vocab.belgif.be/auth/refnis2019/33039>
    <http://vocab.belgif.be/auth/refnis2019/33040>
    <http://vocab.belgif.be/auth/refnis2019/33041>
    <http://vocab.belgif.be/auth/refnis2019/34000>
    <http://vocab.belgif.be/auth/refnis2019/34002>
    <http://vocab.belgif.be/auth/refnis2019/34003>
    <http://vocab.belgif.be/auth/refnis2019/34009>
    <http://vocab.belgif.be/auth/refnis2019/34013>
    <http://vocab.belgif.be/auth/refnis2019/34022>
    <http://vocab.belgif.be/auth/refnis2019/34023>
    <http://vocab.belgif.be/auth/refnis2019/34025>
    <http://vocab.belgif.be/auth/refnis2019/34027>
    <http://vocab.belgif.be/auth/refnis2019/34040>
    <http://vocab.belgif.be/auth/refnis2019/34041>
    <http://vocab.belgif.be/auth/refnis2019/34042>
    <http://vocab.belgif.be/auth/refnis2019/34043>
    <http://vocab.belgif.be/auth/refnis2019/35000>
    <http://vocab.belgif.be/auth/refnis2019/35002>
    <http://vocab.belgif.be/auth/refnis2019/35005>
    <http://vocab.belgif.be/auth/refnis2019/35006>
    <http://vocab.belgif.be/auth/refnis2019/35011>
    <http://vocab.belgif.be/auth/refnis2019/35013>
    <http://vocab.belgif.be/auth/refnis2019/35014>
    <http://vocab.belgif.be/auth/refnis2019/35029>
    <http://vocab.belgif.be/auth/refnis2019/36000>
    <http://vocab.belgif.be/auth/refnis2019/36006>
    <http://vocab.belgif.be/auth/refnis2019/36007>
    <http://vocab.belgif.be/auth/refnis2019/36008>
    <http://vocab.belgif.be/auth/refnis2019/36010>
    <http://vocab.belgif.be/auth/refnis2019/36011>
    <http://vocab.belgif.be/auth/refnis2019/36012>
    <http://vocab.belgif.be/auth/refnis2019/36015>
    <http://vocab.belgif.be/auth/refnis2019/36019>
    <http://vocab.belgif.be/auth/refnis2019/37000>
    <http://vocab.belgif.be/auth/refnis2019/37002>
    <http://vocab.belgif.be/auth/refnis2019/37007>
    <http://vocab.belgif.be/auth/refnis2019/37010>
    <http://vocab.belgif.be/auth/refnis2019/37011>
    <http://vocab.belgif.be/auth/refnis2019/37012>
    <http://vocab.belgif.be/auth/refnis2019/37015>
    <http://vocab.belgif.be/auth/refnis2019/37017>
    <http://vocab.belgif.be/auth/refnis2019/37018>
    <http://vocab.belgif.be/auth/refnis2019/37020>
    <http://vocab.belgif.be/auth/refnis2019/38000>
    <http://vocab.belgif.be/auth/refnis2019/38002>
    <http://vocab.belgif.be/auth/refnis2019/38008>
    <http://vocab.belgif.be/auth/refnis2019/38014>
    <http://vocab.belgif.be/auth/refnis2019/38016>
    <http://vocab.belgif.be/auth/refnis2019/38025>
    <http://vocab.belgif.be/auth/refnis2019/4000>
    <http://vocab.belgif.be/auth/refnis2019/40000>
    <http://vocab.belgif.be/auth/refnis2019/41000>
    <http://vocab.belgif.be/auth/refnis2019/41002>
    <http://vocab.belgif.be/auth/refnis2019/41011>
    <http://vocab.belgif.be/auth/refnis2019/41018>
    <http://vocab.belgif.be/auth/refnis2019/41024>
    <http://vocab.belgif.be/auth/refnis2019/41027>
    <http://vocab.belgif.be/auth/refnis2019/41034>
    <http://vocab.belgif.be/auth/refnis2019/41048>
    <http://vocab.belgif.be/auth/refnis2019/41063>
    <http://vocab.belgif.be/auth/refnis2019/41081>
    <http://vocab.belgif.be/auth/refnis2019/41082>
    <http://vocab.belgif.be/auth/refnis2019/42000>
    <http://vocab.belgif.be/auth/refnis2019/42003>
    <http://vocab.belgif.be/auth/refnis2019/42004>
    <http://vocab.belgif.be/auth/refnis2019/42006>
    <http://vocab.belgif.be/auth/refnis2019/42008>
    <http://vocab.belgif.be/auth/refnis2019/42010>
    <http://vocab.belgif.be/auth/refnis2019/42011>
    <http://vocab.belgif.be/auth/refnis2019/42023>
    <http://vocab.belgif.be/auth/refnis2019/42025>
    <http://vocab.belgif.be/auth/refnis2019/42026>
    <http://vocab.belgif.be/auth/refnis2019/42028>
    <http://vocab.belgif.be/auth/refnis2019/43000>
    <http://vocab.belgif.be/auth/refnis2019/43002>
    <http://vocab.belgif.be/auth/refnis2019/43005>
    <http://vocab.belgif.be/auth/refnis2019/43007>
    <http://vocab.belgif.be/auth/refnis2019/43010>
    <http://vocab.belgif.be/auth/refnis2019/43014>
    <http://vocab.belgif.be/auth/refnis2019/43018>
    <http://vocab.belgif.be/auth/refnis2019/44000>
    <http://vocab.belgif.be/auth/refnis2019/44012>
    <http://vocab.belgif.be/auth/refnis2019/44013>
    <http://vocab.belgif.be/auth/refnis2019/44019>
    <http://vocab.belgif.be/auth/refnis2019/44020>
    <http://vocab.belgif.be/auth/refnis2019/44021>
    <http://vocab.belgif.be/auth/refnis2019/44034>
    <http://vocab.belgif.be/auth/refnis2019/44040>
    <http://vocab.belgif.be/auth/refnis2019/44043>
    <http://vocab.belgif.be/auth/refnis2019/44045>
    <http://vocab.belgif.be/auth/refnis2019/44048>
    <http://vocab.belgif.be/auth/refnis2019/44052>
    <http://vocab.belgif.be/auth/refnis2019/44064>
    <http://vocab.belgif.be/auth/refnis2019/44073>
    <http://vocab.belgif.be/auth/refnis2019/44081>
    <http://vocab.belgif.be/auth/refnis2019/44083>
    <http://vocab.belgif.be/auth/refnis2019/44084>
    <http://vocab.belgif.be/auth/refnis2019/44085>
    <http://vocab.belgif.be/auth/refnis2019/45000>
    <http://vocab.belgif.be/auth/refnis2019/45035>
    <http://vocab.belgif.be/auth/refnis2019/45041>
    <http://vocab.belgif.be/auth/refnis2019/45059>
    <http://vocab.belgif.be/auth/refnis2019/45060>
    <http://vocab.belgif.be/auth/refnis2019/45061>
    <http://vocab.belgif.be/auth/refnis2019/45062>
    <http://vocab.belgif.be/auth/refnis2019/45063>
    <http://vocab.belgif.be/auth/refnis2019/45064>
    <http://vocab.belgif.be/auth/refnis2019/45065>
    <http://vocab.belgif.be/auth/refnis2019/45068>
    <http://vocab.belgif.be/auth/refnis2019/46000>
    <http://vocab.belgif.be/auth/refnis2019/46003>
    <http://vocab.belgif.be/auth/refnis2019/46013>
    <http://vocab.belgif.be/auth/refnis2019/46014>
    <http://vocab.belgif.be/auth/refnis2019/46020>
    <http://vocab.belgif.be/auth/refnis2019/46021>
    <http://vocab.belgif.be/auth/refnis2019/46024>
    <http://vocab.belgif.be/auth/refnis2019/46025>
    <http://vocab.belgif.be/auth/refnis2019/50000>
    <http://vocab.belgif.be/auth/refnis2019/51000>
    <http://vocab.belgif.be/auth/refnis2019/51004>
    <http://vocab.belgif.be/auth/refnis2019/51008>
    <http://vocab.belgif.be/auth/refnis2019/51009>
    <http://vocab.belgif.be/auth/refnis2019/51012>
    <http://vocab.belgif.be/auth/refnis2019/51014>
    <http://vocab.belgif.be/auth/refnis2019/51017>
    <http://vocab.belgif.be/auth/refnis2019/51019>
    <http://vocab.belgif.be/auth/refnis2019/51065>
    <http://vocab.belgif.be/auth/refnis2019/51067>
    <http://vocab.belgif.be/auth/refnis2019/51068>
    <http://vocab.belgif.be/auth/refnis2019/51069>
    <http://vocab.belgif.be/auth/refnis2019/52000>
    <http://vocab.belgif.be/auth/refnis2019/52010>
    <http://vocab.belgif.be/auth/refnis2019/52011>
    <http://vocab.belgif.be/auth/refnis2019/52012>
    <http://vocab.belgif.be/auth/refnis2019/52015>
    <http://vocab.belgif.be/auth/refnis2019/52018>
    <http://vocab.belgif.be/auth/refnis2019/52021>
    <http://vocab.belgif.be/auth/refnis2019/52022>
    <http://vocab.belgif.be/auth/refnis2019/52025>
    <http://vocab.belgif.be/auth/refnis2019/52048>
    <http://vocab.belgif.be/auth/refnis2019/52055>
    <http://vocab.belgif.be/auth/refnis2019/52074>
    <http://vocab.belgif.be/auth/refnis2019/52075>
    <http://vocab.belgif.be/auth/refnis2019/53000>
    <http://vocab.belgif.be/auth/refnis2019/53014>
    <http://vocab.belgif.be/auth/refnis2019/53020>
    <http://vocab.belgif.be/auth/refnis2019/53028>
    <http://vocab.belgif.be/auth/refnis2019/53039>
    <http://vocab.belgif.be/auth/refnis2019/53044>
    <http://vocab.belgif.be/auth/refnis2019/53046>
    <http://vocab.belgif.be/auth/refnis2019/53053>
    <http://vocab.belgif.be/auth/refnis2019/53065>
    <http://vocab.belgif.be/auth/refnis2019/53068>
    <http://vocab.belgif.be/auth/refnis2019/53070>
    <http://vocab.belgif.be/auth/refnis2019/53082>
    <http://vocab.belgif.be/auth/refnis2019/53083>
    <http://vocab.belgif.be/auth/refnis2019/53084>
    <http://vocab.belgif.be/auth/refnis2019/55000>
    <http://vocab.belgif.be/auth/refnis2019/55004>
    <http://vocab.belgif.be/auth/refnis2019/55035>
    <http://vocab.belgif.be/auth/refnis2019/55040>
    <http://vocab.belgif.be/auth/refnis2019/55050>
    <http://vocab.belgif.be/auth/refnis2019/55085>
    <http://vocab.belgif.be/auth/refnis2019/55086>
    <http://vocab.belgif.be/auth/refnis2019/56000>
    <http://vocab.belgif.be/auth/refnis2019/56001>
    <http://vocab.belgif.be/auth/refnis2019/56005>
    <http://vocab.belgif.be/auth/refnis2019/56016>
    <http://vocab.belgif.be/auth/refnis2019/56022>
    <http://vocab.belgif.be/auth/refnis2019/56029>
    <http://vocab.belgif.be/auth/refnis2019/56044>
    <http://vocab.belgif.be/auth/refnis2019/56049>
    <http://vocab.belgif.be/auth/refnis2019/56051>
    <http://vocab.belgif.be/auth/refnis2019/56078>
    <http://vocab.belgif.be/auth/refnis2019/56086>
    <http://vocab.belgif.be/auth/refnis2019/56088>
    <http://vocab.belgif.be/auth/refnis2019/57000>
    <http://vocab.belgif.be/auth/refnis2019/57003>
    <http://vocab.belgif.be/auth/refnis2019/57018>
    <http://vocab.belgif.be/auth/refnis2019/57027>
    <http://vocab.belgif.be/auth/refnis2019/57062>
    <http://vocab.belgif.be/auth/refnis2019/57064>
    <http://vocab.belgif.be/auth/refnis2019/57072>
    <http://vocab.belgif.be/auth/refnis2019/57081>
    <http://vocab.belgif.be/auth/refnis2019/57093>
    <http://vocab.belgif.be/auth/refnis2019/57094>
    <http://vocab.belgif.be/auth/refnis2019/57095>
    <http://vocab.belgif.be/auth/refnis2019/57096>
    <http://vocab.belgif.be/auth/refnis2019/57097>
    <http://vocab.belgif.be/auth/refnis2019/58000>
    <http://vocab.belgif.be/auth/refnis2019/58001>
    <http://vocab.belgif.be/auth/refnis2019/58002>
    <http://vocab.belgif.be/auth/refnis2019/58003>
    <http://vocab.belgif.be/auth/refnis2019/58004>
    <http://vocab.belgif.be/auth/refnis2019/60000>
    <http://vocab.belgif.be/auth/refnis2019/61000>
    <http://vocab.belgif.be/auth/refnis2019/61003>
    <http://vocab.belgif.be/auth/refnis2019/61010>
    <http://vocab.belgif.be/auth/refnis2019/61012>
    <http://vocab.belgif.be/auth/refnis2019/61019>
    <http://vocab.belgif.be/auth/refnis2019/61024>
    <http://vocab.belgif.be/auth/refnis2019/61028>
    <http://vocab.belgif.be/auth/refnis2019/61031>
    <http://vocab.belgif.be/auth/refnis2019/61039>
    <http://vocab.belgif.be/auth/refnis2019/61041>
    <http://vocab.belgif.be/auth/refnis2019/61043>
    <http://vocab.belgif.be/auth/refnis2019/61048>
    <http://vocab.belgif.be/auth/refnis2019/61063>
    <http://vocab.belgif.be/auth/refnis2019/61068>
    <http://vocab.belgif.be/auth/refnis2019/61072>
    <http://vocab.belgif.be/auth/refnis2019/61079>
    <http://vocab.belgif.be/auth/refnis2019/61080>
    <http://vocab.belgif.be/auth/refnis2019/61081>
    <http://vocab.belgif.be/auth/refnis2019/62000>
    <http://vocab.belgif.be/auth/refnis2019/62003>
    <http://vocab.belgif.be/auth/refnis2019/62006>
    <http://vocab.belgif.be/auth/refnis2019/62009>
    <http://vocab.belgif.be/auth/refnis2019/62011>
    <http://vocab.belgif.be/auth/refnis2019/62015>
    <http://vocab.belgif.be/auth/refnis2019/62022>
    <http://vocab.belgif.be/auth/refnis2019/62026>
    <http://vocab.belgif.be/auth/refnis2019/62027>
    <http://vocab.belgif.be/auth/refnis2019/62032>
    <http://vocab.belgif.be/auth/refnis2019/62038>
    <http://vocab.belgif.be/auth/refnis2019/62051>
    <http://vocab.belgif.be/auth/refnis2019/62060>
    <http://vocab.belgif.be/auth/refnis2019/62063>
    <http://vocab.belgif.be/auth/refnis2019/62079>
    <http://vocab.belgif.be/auth/refnis2019/62093>
    <http://vocab.belgif.be/auth/refnis2019/62096>
    <http://vocab.belgif.be/auth/refnis2019/62099>
    <http://vocab.belgif.be/auth/refnis2019/62100>
    <http://vocab.belgif.be/auth/refnis2019/62108>
    <http://vocab.belgif.be/auth/refnis2019/62118>
    <http://vocab.belgif.be/auth/refnis2019/62119>
    <http://vocab.belgif.be/auth/refnis2019/62120>
    <http://vocab.belgif.be/auth/refnis2019/62121>
    <http://vocab.belgif.be/auth/refnis2019/62122>
    <http://vocab.belgif.be/auth/refnis2019/63000>
    <http://vocab.belgif.be/auth/refnis2019/63001>
    <http://vocab.belgif.be/auth/refnis2019/63003>
    <http://vocab.belgif.be/auth/refnis2019/63004>
    <http://vocab.belgif.be/auth/refnis2019/63012>
    <http://vocab.belgif.be/auth/refnis2019/63013>
    <http://vocab.belgif.be/auth/refnis2019/63020>
    <http://vocab.belgif.be/auth/refnis2019/63023>
    <http://vocab.belgif.be/auth/refnis2019/63035>
    <http://vocab.belgif.be/auth/refnis2019/63038>
    <http://vocab.belgif.be/auth/refnis2019/63040>
    <http://vocab.belgif.be/auth/refnis2019/63045>
    <http://vocab.belgif.be/auth/refnis2019/63046>
    <http://vocab.belgif.be/auth/refnis2019/63048>
    <http://vocab.belgif.be/auth/refnis2019/63049>
    <http://vocab.belgif.be/auth/refnis2019/63057>
    <http://vocab.belgif.be/auth/refnis2019/63058>
    <http://vocab.belgif.be/auth/refnis2019/63061>
    <http://vocab.belgif.be/auth/refnis2019/63067>
    <http://vocab.belgif.be/auth/refnis2019/63072>
    <http://vocab.belgif.be/auth/refnis2019/63073>
    <http://vocab.belgif.be/auth/refnis2019/63075>
    <http://vocab.belgif.be/auth/refnis2019/63076>
    <http://vocab.belgif.be/auth/refnis2019/63079>
    <http://vocab.belgif.be/auth/refnis2019/63080>
    <http://vocab.belgif.be/auth/refnis2019/63084>
    <http://vocab.belgif.be/auth/refnis2019/63086>
    <http://vocab.belgif.be/auth/refnis2019/63087>
    <http://vocab.belgif.be/auth/refnis2019/63088>
    <http://vocab.belgif.be/auth/refnis2019/63089>
    <http://vocab.belgif.be/auth/refnis2019/64000>
    <http://vocab.belgif.be/auth/refnis2019/64008>
    <http://vocab.belgif.be/auth/refnis2019/64015>
    <http://vocab.belgif.be/auth/refnis2019/64021>
    <http://vocab.belgif.be/auth/refnis2019/64023>
    <http://vocab.belgif.be/auth/refnis2019/64025>
    <http://vocab.belgif.be/auth/refnis2019/64029>
    <http://vocab.belgif.be/auth/refnis2019/64034>
    <http://vocab.belgif.be/auth/refnis2019/64047>
    <http://vocab.belgif.be/auth/refnis2019/64056>
    <http://vocab.belgif.be/auth/refnis2019/64063>
    <http://vocab.belgif.be/auth/refnis2019/64065>
    <http://vocab.belgif.be/auth/refnis2019/64074>
    <http://vocab.belgif.be/auth/refnis2019/64075>
    <http://vocab.belgif.be/auth/refnis2019/64076>
    <http://vocab.belgif.be/auth/refnis2019/70000>
    <http://vocab.belgif.be/auth/refnis2019/71000>
    <http://vocab.belgif.be/auth/refnis2019/71002>
    <http://vocab.belgif.be/auth/refnis2019/71004>
    <http://vocab.belgif.be/auth/refnis2019/71011>
    <http://vocab.belgif.be/auth/refnis2019/71016>
    <http://vocab.belgif.be/auth/refnis2019/71017>
    <http://vocab.belgif.be/auth/refnis2019/71020>
    <http://vocab.belgif.be/auth/refnis2019/71022>
    <http://vocab.belgif.be/auth/refnis2019/71024>
    <http://vocab.belgif.be/auth/refnis2019/71034>
    <http://vocab.belgif.be/auth/refnis2019/71037>
    <http://vocab.belgif.be/auth/refnis2019/71045>
    <http://vocab.belgif.be/auth/refnis2019/71053>
    <http://vocab.belgif.be/auth/refnis2019/71057>
    <http://vocab.belgif.be/auth/refnis2019/71066>
    <http://vocab.belgif.be/auth/refnis2019/71067>
    <http://vocab.belgif.be/auth/refnis2019/71069>
    <http://vocab.belgif.be/auth/refnis2019/71070>
    <http://vocab.belgif.be/auth/refnis2019/72000>
    <http://vocab.belgif.be/auth/refnis2019/72003>
    <http://vocab.belgif.be/auth/refnis2019/72004>
    <http://vocab.belgif.be/auth/refnis2019/72018>
    <http://vocab.belgif.be/auth/refnis2019/72020>
    <http://vocab.belgif.be/auth/refnis2019/72021>
    <http://vocab.belgif.be/auth/refnis2019/72030>
    <http://vocab.belgif.be/auth/refnis2019/72037>
    <http://vocab.belgif.be/auth/refnis2019/72038>
    <http://vocab.belgif.be/auth/refnis2019/72039>
    <http://vocab.belgif.be/auth/refnis2019/72041>
    <http://vocab.belgif.be/auth/refnis2019/72042>
    <http://vocab.belgif.be/auth/refnis2019/72043>
    <http://vocab.belgif.be/auth/refnis2019/73000>
    <http://vocab.belgif.be/auth/refnis2019/73001>
    <http://vocab.belgif.be/auth/refnis2019/73006>
    <http://vocab.belgif.be/auth/refnis2019/73009>
    <http://vocab.belgif.be/auth/refnis2019/73022>
    <http://vocab.belgif.be/auth/refnis2019/73028>
    <http://vocab.belgif.be/auth/refnis2019/73032>
    <http://vocab.belgif.be/auth/refnis2019/73040>
    <http://vocab.belgif.be/auth/refnis2019/73042>
    <http://vocab.belgif.be/auth/refnis2019/73066>
    <http://vocab.belgif.be/auth/refnis2019/73083>
    <http://vocab.belgif.be/auth/refnis2019/73098>
    <http://vocab.belgif.be/auth/refnis2019/73107>
    <http://vocab.belgif.be/auth/refnis2019/73109>
    <http://vocab.belgif.be/auth/refnis2019/80000>
    <http://vocab.belgif.be/auth/refnis2019/81000>
    <http://vocab.belgif.be/auth/refnis2019/81001>
    <http://vocab.belgif.be/auth/refnis2019/81003>
    <http://vocab.belgif.be/auth/refnis2019/81004>
    <http://vocab.belgif.be/auth/refnis2019/81013>
    <http://vocab.belgif.be/auth/refnis2019/81015>
    <http://vocab.belgif.be/auth/refnis2019/82000>
    <http://vocab.belgif.be/auth/refnis2019/82003>
    <http://vocab.belgif.be/auth/refnis2019/82005>
    <http://vocab.belgif.be/auth/refnis2019/82009>
    <http://vocab.belgif.be/auth/refnis2019/82014>
    <http://vocab.belgif.be/auth/refnis2019/82032>
    <http://vocab.belgif.be/auth/refnis2019/82036>
    <http://vocab.belgif.be/auth/refnis2019/82037>
    <http://vocab.belgif.be/auth/refnis2019/82038>
    <http://vocab.belgif.be/auth/refnis2019/83000>
    <http://vocab.belgif.be/auth/refnis2019/83012>
    <http://vocab.belgif.be/auth/refnis2019/83013>
    <http://vocab.belgif.be/auth/refnis2019/83028>
    <http://vocab.belgif.be/auth/refnis2019/83031>
    <http://vocab.belgif.be/auth/refnis2019/83034>
    <http://vocab.belgif.be/auth/refnis2019/83040>
    <http://vocab.belgif.be/auth/refnis2019/83044>
    <http://vocab.belgif.be/auth/refnis2019/83049>
    <http://vocab.belgif.be/auth/refnis2019/83055>
    <http://vocab.belgif.be/auth/refnis2019/84000>
    <http://vocab.belgif.be/auth/refnis2019/84009>
    <http://vocab.belgif.be/auth/refnis2019/84010>
    <http://vocab.belgif.be/auth/refnis2019/84016>
    <http://vocab.belgif.be/auth/refnis2019/84029>
    <http://vocab.belgif.be/auth/refnis2019/84033>
    <http://vocab.belgif.be/auth/refnis2019/84035>
    <http://vocab.belgif.be/auth/refnis2019/84043>
    <http://vocab.belgif.be/auth/refnis2019/84050>
    <http://vocab.belgif.be/auth/refnis2019/84059>
    <http://vocab.belgif.be/auth/refnis2019/84068>
    <http://vocab.belgif.be/auth/refnis2019/84075>
    <http://vocab.belgif.be/auth/refnis2019/84077>
    <http://vocab.belgif.be/auth/refnis2019/85000>
    <http://vocab.belgif.be/auth/refnis2019/85007>
    <http://vocab.belgif.be/auth/refnis2019/85009>
    <http://vocab.belgif.be/auth/refnis2019/85011>
    <http://vocab.belgif.be/auth/refnis2019/85024>
    <http://vocab.belgif.be/auth/refnis2019/85026>
    <http://vocab.belgif.be/auth/refnis2019/85034>
    <http://vocab.belgif.be/auth/refnis2019/85039>
    <http://vocab.belgif.be/auth/refnis2019/85045>
    <http://vocab.belgif.be/auth/refnis2019/85046>
    <http://vocab.belgif.be/auth/refnis2019/85047>
    <http://vocab.belgif.be/auth/refnis2019/90000>
    <http://vocab.belgif.be/auth/refnis2019/91000>
    <http://vocab.belgif.be/auth/refnis2019/91005>
    <http://vocab.belgif.be/auth/refnis2019/91013>
    <http://vocab.belgif.be/auth/refnis2019/91015>
    <http://vocab.belgif.be/auth/refnis2019/91030>
    <http://vocab.belgif.be/auth/refnis2019/91034>
    <http://vocab.belgif.be/auth/refnis2019/91054>
    <http://vocab.belgif.be/auth/refnis2019/91059>
    <http://vocab.belgif.be/auth/refnis2019/91064>
    <http://vocab.belgif.be/auth/refnis2019/91072>
    <http://vocab.belgif.be/auth/refnis2019/91103>
    <http://vocab.belgif.be/auth/refnis2019/91114>
    <http://vocab.belgif.be/auth/refnis2019/91120>
    <http://vocab.belgif.be/auth/refnis2019/91141>
    <http://vocab.belgif.be/auth/refnis2019/91142>
    <http://vocab.belgif.be/auth/refnis2019/91143>
    <http://vocab.belgif.be/auth/refnis2019/92000>
    <http://vocab.belgif.be/auth/refnis2019/92003>
    <http://vocab.belgif.be/auth/refnis2019/92006>
    <http://vocab.belgif.be/auth/refnis2019/92035>
    <http://vocab.belgif.be/auth/refnis2019/92045>
    <http://vocab.belgif.be/auth/refnis2019/92048>
    <http://vocab.belgif.be/auth/refnis2019/92054>
    <http://vocab.belgif.be/auth/refnis2019/92087>
    <http://vocab.belgif.be/auth/refnis2019/92094>
    <http://vocab.belgif.be/auth/refnis2019/92097>
    <http://vocab.belgif.be/auth/refnis2019/92101>
    <http://vocab.belgif.be/auth/refnis2019/92114>
    <http://vocab.belgif.be/auth/refnis2019/92137>
    <http://vocab.belgif.be/auth/refnis2019/92138>
    <http://vocab.belgif.be/auth/refnis2019/92140>
    <http://vocab.belgif.be/auth/refnis2019/92141>
    <http://vocab.belgif.be/auth/refnis2019/92142>
    <http://vocab.belgif.be/auth/refnis2019/93000>
    <http://vocab.belgif.be/auth/refnis2019/93010>
    <http://vocab.belgif.be/auth/refnis2019/93014>
    <http://vocab.belgif.be/auth/refnis2019/93018>
    <http://vocab.belgif.be/auth/refnis2019/93022>
    <http://vocab.belgif.be/auth/refnis2019/93056>
    <http://vocab.belgif.be/auth/refnis2019/93088>
    <http://vocab.belgif.be/auth/refnis2019/93090>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
