PREFIX dvcs: <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    dvcs:Taal
    <http://publications.europa.eu/resource/authority/language/NLD>
    <http://publications.europa.eu/resource/authority/language/FRA>
    <http://publications.europa.eu/resource/authority/language/DEU>
    <http://publications.europa.eu/resource/authority/language/ENG>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
