DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://lblod.data.gift/concept-schemes/9cf6fa63-1f49-4d53-af06-e1c235ece10b>
    <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd>
    <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
