PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    dvcs:YourEuropeCategorie
    dvc:Reizen
    dvc:ReizenDocumenten
    dvc:ReizenRechtenVerplichtingen
    dvc:ReizenOndersteuningBeperkteMobiliteit
    dvc:ReizenGoederen
    dvc:ReizenElektronischeGegevens
    dvc:WerkEnPensionering
    dvc:WerkEnPensioneringWerkZoeken
    dvc:WerkEnPensioneringGaanWerken
    dvc:WerkEnPensioneringErkenningKwalificaties
    dvc:WerkEnPensioneringBelastingheffing
    dvc:WerkEnPensioneringAansprakelijkheidEnVerzekeringen
    dvc:WerkEnPensioneringArbeidsvoorwaarden
    dvc:WerkEnPensioneringGelijkeBehandeling
    dvc:WerkEnPensioneringGezondheidEnVeiligheid
    dvc:WerkEnPensioneringSocialezekerheidsrechten
    dvc:Voertuigen
    dvc:VoertuigenVerplaatsing
    dvc:VoertuigenVerleningRijbewijzen
    dvc:VoertuigenVerplichteVerzekering
    dvc:VoertuigenKoopVerkoop
    dvc:VoertuigenVerkeersregels
    dvc:Verblijf
    dvc:VerblijfVerhuizing
    dvc:VerblijfKoopVerkoop
    dvc:VerblijfVerkiezingen
    dvc:VerblijfVerblijfskaarten
    dvc:VerblijfNaturalisatie
    dvc:VerblijfOverlijden
    dvc:OnderwijsOfStage
    dvc:OnderwijsOfStageOnderwijsstelsel
    dvc:OnderwijsOfStageVrijwilligerswerk
    dvc:OnderwijsOfStageStage
    dvc:OnderwijsOfStageOnderzoek
    dvc:Gezondheidszorg
    dvc:GezondheidszorgMedischeBehandeling
    dvc:GezondheidszorgGeneesmiddelenKopen
    dvc:GezondheidszorgZiekteverzekering
    dvc:GezondheidszorgPreventieveOpenbareGezondheidsmaatregelen
    dvc:GezondheidszorgNoodnummers
    dvc:GezondheidszorgWoonzorgcentrum
    dvc:BurgerEnFamilieRechten
    dvc:BurgerEnFamilieRechtenKinderen
    dvc:BurgerEnFamilieRechtenPartners
    dvc:BurgerEnFamilieRechtenGenderIdentiteit
    dvc:BurgerEnFamilieRechtenErfrechtenEnPlichten
    dvc:BurgerEnFamilieRechtenOntvoeringKinderen
    dvc:Consumentenrechten
    dvc:ConsumentenrechtenAankoop
    dvc:ConsumentenrechtenBankrekening
    dvc:ConsumentenrechtenNutsvoorzieningen
    dvc:ConsumentenrechtenBetalingen
    dvc:ConsumentenrechtenConsumentenrechten
    dvc:ConsumentenrechtenVeiligheid
    dvc:ConsumentenrechtenHuurMotorvoertuigen
    dvc:BeschermingPersoonsgegevens
    dvc:BeschermingPersoonsgegevensUitoefeningRechten
    dvc:Bedrijf
    dvc:BedrijfRegistratieproceduresRechtsvormen
    dvc:BedrijfVerplaatsing
    dvc:BedrijfIntellectueleEigendomsrechten
    dvc:BedrijfTransparantie
    dvc:BedrijfOnlineBetaalFuncties
    dvc:BedrijfOvereenkomstenrecht
    dvc:BedrijfInsolventieLiquidatie
    dvc:BedrijfKredietVerzekering
    dvc:BedrijfFusieVerkoop
    dvc:BedrijfAansprakelijkheidBestuurders
    dvc:BedrijfPersoonsgegevens
    dvc:Werknemers
    dvc:WerknemersArbeidsvoorwaarden
    dvc:WerknemersSocialezekerheid
    dvc:WerknemersTewerkstelling
    dvc:WerknemersGelijkeBehandeling
    dvc:WerknemersPersoneelsvertegenwoordiging
    dvc:Belastingen
    dvc:BelastingenBTW
    dvc:BelastingenAccijnzen
    dvc:BelastingenDouanerechten
    dvc:BelastingenDouaneprocedures
    dvc:BelastingenOverigeBelastingen
    dvc:Goederen
    dvc:GoederenCEMarkering
    dvc:GoederenVoorschriftenVereisten
    dvc:GoederenNormenSpecificatiesCertificering
    dvc:GoederenErkenningZonderSpecificaties
    dvc:GoederenGevaarlijkeStoffen
    dvc:GoederenVerkoopOpAfstand
    dvc:GoederenProductenMetGebreken
    dvc:GoederenKeurmerken
    dvc:GoederenRecyclage
    dvc:Diensten
    dvc:DienstenLicentiesVergunningen
    dvc:DienstenKennisgevingGrensoverschrijdendeActiviteiten
    dvc:DienstenErkenningBeroepskwalificaties
    dvc:Bedrijfsfinanciering
    dvc:BedrijfsfinancieringFinancieringUnie
    dvc:BedrijfsfinancieringFinancieringNationaal
    dvc:BedrijfsfinancieringOndernemersInitiatieven
    dvc:Overheidsopdrachten
    dvc:OverheidsopdrachtenDeelname
    dvc:OverheidsopdrachtenOnlineInschrijving
    dvc:OverheidsopdrachtenMeldingOnregelmatigheden
    dvc:GezondheidVeiligheidWerk
    dvc:GezondheidVeiligheidWerkVerplichtingen
    dvc:ProcedureGeboorte
    dvc:ProcedureGeboorteBewijs
    dvc:ProcedureVerblijf
    dvc:ProcedureVerblijfBewijs
    dvc:ProcedureStudie
    dvc:ProcedureStudieAanvraagTertiairOnderwijs
    dvc:ProcedureStudieVerzoekToelatingTertiairOnderwijs
    dvc:ProcedureStudieVerzoekErkenningDiploma
    dvc:ProcedureWerk
    dvc:ProcedureWerkVerzoek
    dvc:ProcedureWerkWijzigingBeroepssituatie
    dvc:ProcedureWerkAanvraagZiekteverzekeringskaart
    dvc:ProcedureWerkAangifteInkomstenbelasting
    dvc:ProcedureVerhuizing
    dvc:ProcedureVerhuizingAdreswijziging
    dvc:ProcedureVerhuizingInschrijvingMotorvoertuig
    dvc:ProcedureVerhuizingStickersWegeninfrastructuur
    dvc:ProcedureVerhuizingEmissiestickers
    dvc:ProcedurePensionering
    dvc:ProcedurePensioneringAanvraagUitkering
    dvc:ProcedurePensioneringVerzoekOmInformatie
    dvc:ProcedureStartenExploiterenSluitenBedrijf
    dvc:ProcedureStartenExploiterenSluitenBedrijfKennisgeving
    dvc:ProcedureStartenExploiterenSluitenBedrijfPensioenEnVerzekeringsregelingenWerkgever
    dvc:ProcedureStartenExploiterenSluitenBedrijfPensioenEnVerzekeringsregelingenWerknemer
    dvc:ProcedureStartenExploiterenSluitenBedrijfAangifteVennootschapsbelasting
    dvc:ProcedureStartenExploiterenSluitenBedrijfBeeindigingArbeidsovereenkomst
    dvc:ProcedureStartenExploiterenSluitenBedrijfBeeindigingArbeidsovereenkomst
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
