DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <https://data.vlaanderen.be/id/organisatie/OVO027249>
    <https://data.vlaanderen.be/id/organisatie/OVO027247>
    <https://data.vlaanderen.be/id/organisatie/OVO003988>
    <https://data.vlaanderen.be/id/organisatie/OVO027312>
    <https://data.vlaanderen.be/id/organisatie/OVO027227>
    <https://data.vlaanderen.be/id/organisatie/OVO024762>
    <https://data.vlaanderen.be/id/organisatie/OVO003118>
    <https://data.vlaanderen.be/id/organisatie/OVO009025>
    <https://data.vlaanderen.be/id/organisatie/OVO010087>
    <https://data.vlaanderen.be/id/organisatie/OVO001601>
    <https://data.vlaanderen.be/id/organisatie/OVO003953>
    <https://data.vlaanderen.be/id/organisatie/OVO003323>
    <https://data.vlaanderen.be/id/organisatie/OVO000090>
    <https://data.vlaanderen.be/id/organisatie/OVO000094>
    <https://data.vlaanderen.be/id/organisatie/OVO009023>
    <https://data.vlaanderen.be/id/organisatie/OVO001846>
    <https://data.vlaanderen.be/id/organisatie/OVO010516>
    <https://data.vlaanderen.be/id/organisatie/OVO003898>
    <https://data.vlaanderen.be/id/organisatie/OVO028966>
    <https://data.vlaanderen.be/id/organisatie/OVO008237>
    <https://data.vlaanderen.be/id/organisatie/OVO024763>
    <https://data.vlaanderen.be/id/organisatie/OVO000176>
    <https://data.vlaanderen.be/id/organisatie/OVO001843>
    <https://data.vlaanderen.be/id/organisatie/OVO049152>
    <https://data.vlaanderen.be/id/organisatie/OVO000706>
    <https://data.vlaanderen.be/id/organisatie/OVO003944>
    <https://data.vlaanderen.be/id/organisatie/OVO000058>
    <https://data.vlaanderen.be/id/organisatie/OVO000063>
    <https://data.vlaanderen.be/id/organisatie/OVO019809>
    <https://data.vlaanderen.be/id/organisatie/OVO000177>
    <https://data.vlaanderen.be/id/organisatie/OVO008225>
    <https://data.vlaanderen.be/id/organisatie/OVO008214>
    <https://data.vlaanderen.be/id/organisatie/OVO000237>
    <https://data.vlaanderen.be/id/organisatie/OVO000103>
    <https://data.vlaanderen.be/id/organisatie/OVO006466>
    <https://data.vlaanderen.be/id/organisatie/OVO000061>
    <https://data.vlaanderen.be/id/organisatie/OVO000106>
    <https://data.vlaanderen.be/id/organisatie/OVO009045>
    <https://data.vlaanderen.be/id/organisatie/OVO009027>
    <https://data.vlaanderen.be/id/organisatie/OVO001845>
    <https://data.vlaanderen.be/id/organisatie/OVO008202>
    <https://data.vlaanderen.be/id/organisatie/OVO000092>
    <https://data.vlaanderen.be/id/organisatie/OVO001831>
    <https://data.vlaanderen.be/id/organisatie/OVO000089>
    <https://data.vlaanderen.be/id/organisatie/OVO000210>
    <https://data.vlaanderen.be/id/organisatie/OVO000795>
    <https://data.vlaanderen.be/id/organisatie/OVO008229>
    <https://data.vlaanderen.be/id/organisatie/OVO009024>
    <https://data.vlaanderen.be/id/organisatie/OVO008218>
    <https://data.vlaanderen.be/id/organisatie/OVO005190>
    <https://data.vlaanderen.be/id/organisatie/OVO027169>
    <https://data.vlaanderen.be/id/organisatie/OVO038766>
    <https://data.vlaanderen.be/id/organisatie/OVO000059>
    <https://data.vlaanderen.be/id/organisatie/OVO009030>
    <https://data.vlaanderen.be/id/organisatie/OVO008643>
    <https://data.vlaanderen.be/id/organisatie/OVO008238>
    <https://data.vlaanderen.be/id/organisatie/OVO000174>
    <https://data.vlaanderen.be/id/organisatie/OVO009029>
    <https://data.vlaanderen.be/id/organisatie/OVO000080>
    <https://data.vlaanderen.be/id/organisatie/OVO008217>
    <https://data.vlaanderen.be/id/organisatie/OVO009031>
    <https://data.vlaanderen.be/id/organisatie/OVO000107>
    <https://data.vlaanderen.be/id/organisatie/OVO025860>
    <https://data.vlaanderen.be/id/organisatie/OVO014006>
    <https://data.vlaanderen.be/id/organisatie/OVO001835>
    <https://data.vlaanderen.be/id/organisatie/OVO001847>
    <https://data.vlaanderen.be/id/organisatie/OVO002300>
    <https://data.vlaanderen.be/id/organisatie/OVO003139>
    <https://data.vlaanderen.be/id/organisatie/OVO000175>
    <https://data.vlaanderen.be/id/organisatie/OVO000088>
    <https://data.vlaanderen.be/id/organisatie/OVO002949>
    <https://data.vlaanderen.be/id/organisatie/OVO000073>
    <https://data.vlaanderen.be/id/organisatie/OVO001729>
    <https://data.vlaanderen.be/id/organisatie/OVO024760>
    <https://data.vlaanderen.be/id/organisatie/OVO004539>
    <https://data.vlaanderen.be/id/organisatie/OVO003884>
    <https://data.vlaanderen.be/id/organisatie/OVO000098>
    <https://data.vlaanderen.be/id/organisatie/OVO001951>
    <https://data.vlaanderen.be/id/organisatie/OVO009026>
    <https://data.vlaanderen.be/id/organisatie/OVO000158>
    <https://data.vlaanderen.be/id/organisatie/OVO027160>
    <https://data.vlaanderen.be/id/organisatie/OVO000082>
    <https://data.vlaanderen.be/id/organisatie/OVO000857>
    <https://data.vlaanderen.be/id/organisatie/OVO000104>
    <https://data.vlaanderen.be/id/organisatie/OVO019876>
    <https://data.vlaanderen.be/id/organisatie/OVO009746>
    <https://data.vlaanderen.be/id/organisatie/OVO000110>
    <https://data.vlaanderen.be/id/organisatie/OVO001688>
    <https://data.vlaanderen.be/id/organisatie/OVO001834>
    <https://data.vlaanderen.be/id/organisatie/OVO003747>
    <https://data.vlaanderen.be/id/organisatie/OVO025085>
    <https://data.vlaanderen.be/id/organisatie/OVO003735>
    <https://data.vlaanderen.be/id/organisatie/OVO003954>
    <https://data.vlaanderen.be/id/organisatie/OVO025178>
    <https://data.vlaanderen.be/id/organisatie/OVO000084>
    <https://data.vlaanderen.be/id/organisatie/OVO000078>
    <https://data.vlaanderen.be/id/organisatie/OVO002410>
    <https://data.vlaanderen.be/id/organisatie/OVO000100>
    <https://data.vlaanderen.be/id/organisatie/OVO000076>
    <https://data.vlaanderen.be/id/organisatie/OVO002411>
    <https://data.vlaanderen.be/id/organisatie/OVO003117>
    <https://data.vlaanderen.be/id/organisatie/OVO003119>
    <https://data.vlaanderen.be/id/organisatie/OVO001841>
    <https://data.vlaanderen.be/id/organisatie/OVO000045>
    <https://data.vlaanderen.be/id/organisatie/OVO001002>
    <https://data.vlaanderen.be/id/organisatie/OVO000042>
    <https://data.vlaanderen.be/id/organisatie/OVO000184>
    <https://data.vlaanderen.be/id/organisatie/OVO000060>
    <https://data.vlaanderen.be/id/organisatie/OVO000062>
    <https://data.vlaanderen.be/id/organisatie/OVO004066>
    <https://data.vlaanderen.be/id/organisatie/OVO001833>
    <https://data.vlaanderen.be/id/organisatie/OVO001832>
    <https://data.vlaanderen.be/id/organisatie/OVO000067>
    <https://data.vlaanderen.be/id/organisatie/OVO006465>
    <https://data.vlaanderen.be/id/organisatie/OVO000142>
    <https://data.vlaanderen.be/id/organisatie/OVO000146>
    <https://data.vlaanderen.be/id/organisatie/OVO027149>
    <https://data.vlaanderen.be/id/organisatie/OVO004530>
    <https://data.vlaanderen.be/id/organisatie/OVO004018>
    <https://data.vlaanderen.be/id/organisatie/OVO006467>
    <https://data.vlaanderen.be/id/organisatie/OVO001689>
    <https://data.vlaanderen.be/id/organisatie/OVO001523>
    <https://data.vlaanderen.be/id/organisatie/OVO002305>
    <https://data.vlaanderen.be/id/organisatie/OVO000071>
    <https://data.vlaanderen.be/id/organisatie/OVO000112>
    <https://data.vlaanderen.be/id/organisatie/OVO000039>
    <https://data.vlaanderen.be/id/organisatie/OVO000474>
    <https://data.vlaanderen.be/id/organisatie/OVO000733>
    <https://data.vlaanderen.be/id/organisatie/OVO000049>
    <https://data.vlaanderen.be/id/organisatie/OVO000157>
    <https://data.vlaanderen.be/id/organisatie/OVO000029>
    <https://data.vlaanderen.be/id/organisatie/OVO000013>
    <https://data.vlaanderen.be/id/organisatie/OVO000095>
    <https://data.vlaanderen.be/id/organisatie/OVO000072>
    <https://data.vlaanderen.be/id/organisatie/OVO000038>
    <https://data.vlaanderen.be/id/organisatie/OVO000182>
    <https://data.vlaanderen.be/id/organisatie/OVO000054>
    <https://data.vlaanderen.be/id/organisatie/OVO001680>
    <https://data.vlaanderen.be/id/organisatie/OVO000043>
    <https://data.vlaanderen.be/id/organisatie/OVO000236>
    <https://data.vlaanderen.be/id/organisatie/OVO001842>
    <https://data.vlaanderen.be/id/organisatie/OVO000070>
    <https://data.vlaanderen.be/id/organisatie/OVO000044>
    <https://data.vlaanderen.be/id/organisatie/OVO000035>
    <https://data.vlaanderen.be/id/organisatie/OVO000096>
    <https://data.vlaanderen.be/id/organisatie/OVO000041>
    <https://data.vlaanderen.be/id/organisatie/OVO000031>
    <https://data.vlaanderen.be/id/organisatie/OVO000053>
    <https://data.vlaanderen.be/id/organisatie/OVO000056>
    <https://data.vlaanderen.be/id/organisatie/OVO000009>
    <https://data.vlaanderen.be/id/organisatie/OVO000034>
    <https://data.vlaanderen.be/id/organisatie/OVO000097>
    <https://data.vlaanderen.be/id/organisatie/OVO000707>
    <https://data.vlaanderen.be/id/organisatie/OVO000050>
    <https://data.vlaanderen.be/id/organisatie/OVO000091>
    <https://data.vlaanderen.be/id/organisatie/OVO000032>
    <https://data.vlaanderen.be/id/organisatie/OVO000001>
    <https://data.vlaanderen.be/id/organisatie/OVO027305>
    <https://data.vlaanderen.be/id/organisatie/OVO001708>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
