PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    dvcs:Type
    dvc:FinancieleVerplichting
    dvc:Toelating
    dvc:Bewijs
    dvc:Voorwerp
    dvc:AdviesBegeleiding
    dvc:InfrastructuurMateriaal
    dvc:FinancieelVoordeel
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
