PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    dvcs:PublicatieKanaal
    dvc:YourEurope
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}
