# We had a problem with performance with the previous migrations.
# So we had to re-write them.
#
# Please check:
#   20260416102540-prepare-gemeentewegen-attachments-haspart.sparql
#     -> ?submission nie:hasPart ?attachment
#   20260416102541-prepare-gemeentewegen-attachments-haspart-source.sparql
#     -> ?submission nie:hasPart/^nie:dataSource ?attachment
#   20260416102542-prepare-gemeentewegen-attachments-dct-haspart-source.sparql
#     -> ?submission dct:hasPart/^nie:dataSource ?attachment
#   20260416102543-prepare-gemeentewegen-attachments-haspart-source-source.sparql
#     -> ?submission nie:hasPart/^nie:dataSource/^nie:dataSource ?attachment
#   20260416102544-prepare-gemeentewegen-attachments-generated-haspart.sparql
#     -> ?submission prov:generated/dct:hasPart ?attachment
#   20260416102545-prepare-gemeentewegen-attachments-generated-haspart-source.sparql
#     -> ?submission prov:generated/dct:hasPart/nie:dataSource ?attachment
#   20260416102546-prepare-gemeentewegen-attachments-subject-source.sparql
#     -> ?submission dct:subject/dct:source ?attachment (with dct:type filter)
