PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://data.lblod.info/id/criterions/f5ea0615-0b0a-47db-a38c-6097ff80815d>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "f5ea0615-0b0a-47db-a38c-6097ff80815d" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep gemeentebesturen" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/f98e7cf5-2dbb-447a-a119-5b121cf99ee5> .

    <http://data.lblod.info/id/requirement-groups/f98e7cf5-2dbb-447a-a119-5b121cf99ee5>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "f98e7cf5-2dbb-447a-a119-5b121cf99ee5" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een gemeentebestuur." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/baeba95d-52a7-4d76-9ccb-69f397b2936d> .

    <http://data.lblod.info/id/criterion-requirement/baeba95d-52a7-4d76-9ccb-69f397b2936d>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "baeba95d-52a7-4d76-9ccb-69f397b2936d" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode gemeentebestuur." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .

   <http://data.lblod.info/id/criterions/8c32faa4-1167-4fee-932f-3d453e59b09a>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "8c32faa4-1167-4fee-932f-3d453e59b09a" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep OCMW" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/f0294a39-4157-4e6c-9901-551cfa266891> .

   <http://data.lblod.info/id/requirement-groups/f0294a39-4157-4e6c-9901-551cfa266891>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "f0294a39-4157-4e6c-9901-551cfa266891" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een OCMW." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/1f72df20-e6fd-4d59-8c36-047951f8b104> .

    <http://data.lblod.info/id/criterion-requirement/1f72df20-e6fd-4d59-8c36-047951f8b104>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "1f72df20-e6fd-4d59-8c36-047951f8b104" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode OCMW." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/criterions/72ada772-6e71-4eb3-85a6-c58539a13865>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "72ada772-6e71-4eb3-85a6-c58539a13865" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep AGB" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/feb58809-bacb-4d58-8ee1-3b79c37d4926> .

    <http://data.lblod.info/id/requirement-groups/feb58809-bacb-4d58-8ee1-3b79c37d4926>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "feb58809-bacb-4d58-8ee1-3b79c37d4926" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een AGB." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/df46ae03-4e7e-45f1-8a77-3467fd0aa460> .

    <http://data.lblod.info/id/criterion-requirement/df46ae03-4e7e-45f1-8a77-3467fd0aa460>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "df46ae03-4e7e-45f1-8a77-3467fd0aa460" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode AGB." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721> .

    <http://data.lblod.info/id/criterions/3872dbf9-2b16-4b9e-a3cb-d2bd9b9d86d3>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "3872dbf9-2b16-4b9e-a3cb-d2bd9b9d86d3" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep Provincie" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/f500c1b6-1e66-4515-992c-65d61fbbf34d> .

    <http://data.lblod.info/id/requirement-groups/f500c1b6-1e66-4515-992c-65d61fbbf34d>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "f500c1b6-1e66-4515-992c-65d61fbbf34d" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een Provincie." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/f618b39e-e5e9-4189-bd05-573dc8b78e16> .

    <http://data.lblod.info/id/criterion-requirement/f618b39e-e5e9-4189-bd05-573dc8b78e16>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "f618b39e-e5e9-4189-bd05-573dc8b78e16" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode Provincie." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000> .

    <http://data.lblod.info/id/criterions/80301a63-927c-48e5-8678-048c87c25847>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "80301a63-927c-48e5-8678-048c87c25847" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep VGC" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/43711c65-069c-4b88-8947-194a6e34b314> .

    <http://data.lblod.info/id/requirement-groups/43711c65-069c-4b88-8947-194a6e34b314>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "43711c65-069c-4b88-8947-194a6e34b314" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een VGC." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/dcd2e359-fa3a-467f-9df9-2d606700db1b> .

    <http://data.lblod.info/id/criterion-requirement/dcd2e359-fa3a-467f-9df9-2d606700db1b>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "dcd2e359-fa3a-467f-9df9-2d606700db1b" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode VGC." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d90c511e-f827-488c-84ba-432c8f69561c> .

    <http://data.lblod.info/id/criterions/2c9ee9c7-ea98-4596-85a5-3b83b77b3606>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "2c9ee9c7-ea98-4596-85a5-3b83b77b3606" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep IGS" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/11651f7d-487e-4f29-8711-d2cd1aff179a> .

    <http://data.lblod.info/id/requirement-groups/11651f7d-487e-4f29-8711-d2cd1aff179a>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "11651f7d-487e-4f29-8711-d2cd1aff179a" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een IGS." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement>
        <http://data.lblod.info/id/criterion-requirement/730d4639-d2ab-47a7-a779-79ebd74f5b1c> ,
        <http://data.lblod.info/id/criterion-requirement/8b21f1e1-76d8-43d2-85f7-126e1193ef36> ,
        <http://data.lblod.info/id/criterion-requirement/b221f8c7-3a80-410b-976d-58f3ab9902e0> .

    <http://data.lblod.info/id/criterion-requirement/730d4639-d2ab-47a7-a779-79ebd74f5b1c>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "730d4639-d2ab-47a7-a779-79ebd74f5b1c" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode Opdrachthoudende vereniging." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d> .

    <http://data.lblod.info/id/criterion-requirement/8b21f1e1-76d8-43d2-85f7-126e1193ef36>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "8b21f1e1-76d8-43d2-85f7-126e1193ef36" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode Dienstverlenende vereniging." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .

    <http://data.lblod.info/id/criterion-requirement/b221f8c7-3a80-410b-976d-58f3ab9902e0>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "b221f8c7-3a80-410b-976d-58f3ab9902e0" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode Projectvereniging." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
  }
}