INSERT {
  GRAPH ?h {
    ?s <http://mu.semte.ch/vocabularies/ext/sessionRole> "LoketLB-bedienarenbeheer" .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://xmlns.com/foaf/0.1/OnlineAccount> ;
      <http://xmlns.com/foaf/0.1/accountServiceHomepage> <https://github.com/lblod/mock-login-service> .
  }
  BIND(?g as ?h)
}
