PREFIX org: <http://www.w3.org/ns/org#>
PREFIX schema: <http://schema.org/>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX locn: <http://www.w3.org/ns/locn#>

INSERT {
  GRAPH ?orgGraph {
    ?worshipAgentInPosition ?pworshipAgentInPosition ?oworshipAgentInPosition .
  }
}
WHERE {
    ?worshipAgentInPosition a <http://data.lblod.info/vocabularies/erediensten/EredienstMandataris> ;
      org:holds ?position ;
      ?pworshipAgentInPosition ?oworshipAgentInPosition .

    ?orgaanInTime org:hasPost ?position ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan .
    
    ?orgaan <http://data.vlaanderen.be/ns/besluit#bestuurt> ?eenheid .

    ?eenheid <http://mu.semte.ch/vocabularies/core/uuid> ?uuid .

    BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?uuid)) AS ?orgGraph)
}
