DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/e98dfdd6-f696-41cb-86d1-beff5bea9641> <http://data.europa.eu/m8g/endTime> "2021-11-28T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/e98dfdd6-f696-41cb-86d1-beff5bea9641> <http://data.europa.eu/m8g/endTime> "2021-11-12T21:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
