INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d>
            a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "fffb9b3a-21ba-4050-b171-0d9b84d1927d" ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> """concept-scheme defining project types"""@en .

        <http://lblod.data.gift/concepts/446ac005-7342-4f3a-b7a0-2b3c929d73ba>
            a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "446ac005-7342-4f3a-b7a0-2b3c929d73ba" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Innovative services"@en ;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d> ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Innovatieve dienstverlening"@nl .

        <http://lblod.data.gift/concepts/6eca0908-de74-400e-9f6b-2ea0202ac05b>
            a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "6eca0908-de74-400e-9f6b-2ea0202ac05b" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Digital democracy"@en ;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d> ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Digitale democratie"@nl .

        <http://lblod.data.gift/concepts/9fb0732f-e779-4d2b-b53d-159e7088c678>
            a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "9fb0732f-e779-4d2b-b53d-159e7088c678" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Workplace of the future"@en ;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d> ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Werkplek van de toekomst"@nl .
    }
}
