PREFIX regorg: <http://www.w3.org/ns/regorg#RegisteredOrganization>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?s ?p ?oString .
} WHERE {
  ?s a regorg:RegisteredOrganization;
    ?p ?o.

  FILTER (?p IN (
    skos:altLabel
  ))

  BIND(STR(?o) AS ?oString)
}
