PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a regorg:RegisteredOrganization;
    ?p ?o.

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    dcterms:identifier,
    regorg:orgStatus,
    org:hasPrimarySite,
    org:hasSite,
    org:changedBy,
    org:resultedFrom
  ))
}
