DELETE {
  GRAPH ?g {
    ?s skos:prefLabel ?label.
  }
}
INSERT {
  GRAPH ?g {
    ?s skos:prefLabel ?dutchLabel.
  }
}
WHERE {
  VALUES ?scheme {
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/BevoegdBestuursniveau>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/ConceptTag>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Doelgroep>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/InstantieTag>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/PublicatieKanaal>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/SnapshotType>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Taal>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Thema>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/Type>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/UitvoerendBestuursniveau>
    <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/YourEuropeCategori>
  }

  GRAPH ?g {
    ?s skos:inScheme ?scheme;
      skos:prefLabel ?dutchLabel;
      skos:prefLabel ?label;
    FILTER(LANG(?dutchLabel) = "nl")
  }
}