PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dvcs: <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# remove obsolete data
DELETE WHERE {
  GRAPH ?g {
    <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>,
      <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept-Scheme>;
      mu:uuid "b790e1d2-fd96-4476-8c07-c76a017fed09";
      <http://www.w3.org/2004/02/skos/core#definition> "Publieke organisaties LPDC/IPDC";
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Publieke organisaties LPDC/IPDC".

    <http://data.lblod.info/id/concept/organisatie/0044d2a642463bb24e7500ce9793c896> a <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>,
            skos:Concept, <http://data.europa.eu/m8g/PublicOrganisation>;
        skos:inScheme <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        skos:topConceptOf <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        mu:uuid "0044d2a642463bb24e7500ce9793c896" ;
        skos:prefLabel "Vlaamse overheid"@nl .

    <http://data.lblod.info/id/concept/organisatie/3b2c68d762d998533208dc3d3d78c6c7> a <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>,
            skos:Concept, <http://data.europa.eu/m8g/PublicOrganisation>;
        skos:inScheme <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        skos:topConceptOf <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        mu:uuid "3b2c68d762d998533208dc3d3d78c6c7" ;
        skos:prefLabel "Derden"@nl .

    <http://data.lblod.info/id/concept/organisatie/e3b06565249fb4273d056f4e4e0c8cc7> a <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>,
            skos:Concept, <http://data.europa.eu/m8g/PublicOrganisation>;
        skos:inScheme <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        skos:topConceptOf <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        mu:uuid "e3b06565249fb4273d056f4e4e0c8cc7" ;
        skos:prefLabel "Federale overheid"@nl .

    <http://data.lblod.info/id/concept/organisatie/f1b93b876fb40c4c4f49aa558480a7ac> a <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>,
            skos:Concept, <http://data.europa.eu/m8g/PublicOrganisation>;
        skos:inScheme <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        skos:topConceptOf <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
        mu:uuid "f1b93b876fb40c4c4f49aa558480a7ac" ;
        skos:prefLabel "Europese overheid"@nl .
   }
}

;


# This adds all gemeentes to public organisations as well. This makes it easier to manage select boxes
# For later migrations with new eenheden, some stuff will need to be added
DELETE {
  GRAPH ?g {
    ?s a <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>, <http://data.europa.eu/m8g/PublicOrganisation>;
      skos:inScheme <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>;
      skos:topConceptOf <http://data.lblod.info/concept-schemes/id/b790e1d2-fd96-4476-8c07-c76a017fed09>.
  }
}
INSERT {
  GRAPH ?g {
  ?s skos:inScheme dvcs:IPDCOrganisaties;
    skos:topConceptOf dvcs:IPDCOrganisaties;
    rdfs:seeAlso <http://centrale-vindplaats.lblod.info>.
  }
}
WHERE {
  GRAPH ?g {
    # gemeente; provincie
    VALUES ?class {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>
    }

    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>,
         <http://lblod.data.gift/vocabularies/lpdc-ipdc/LPDC-Concept>,
         <http://data.europa.eu/m8g/PublicOrganisation>;
      <http://data.vlaanderen.be/ns/besluit#classificatie> ?class.
  }
}