PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/PublicatieKanaal/>
PREFIX lpdcExt: <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>

DELETE {
  GRAPH ?g {
  	?service lpdcExt:target ?audience.
  }
}
INSERT {
  GRAPH ?g{
    ?service lpdcExt:targetAudience ?targetAudience.
  }
}
WHERE {
  VALUES ?targetAudience {
    dvc:Onderneming
  }
  GRAPH ?g {
    ?service
      a cpsv:PublicService;
      lpdcExt:targetAudience ?audience.
  }

  # audience is not necessarily in the same graph than service.
  ?audience
    a skos:Concept;
    skos:broader ?targetAudience.
}

