PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/Doelgroep/>

# removes the inScheme link in order to remove codelists from conceptSelector
DELETE {
  GRAPH ?g {
  	?grp skos:inScheme dvcs:Doelgroep.
  }
}
WHERE {
  GRAPH ?g {
   ?grp
    a skos:Concept;
    skos:broader dvc:Onderneming;
    skos:inScheme dvcs:Doelgroep.
  }
} 
