PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX dvcs:  <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/PublicatieKanaal/>
PREFIX mu:    <http://mu.semte.ch/vocabularies/core/>

DELETE {
  GRAPH ?g {
    ?s1 ?p1 ?o1.
    ?s2 ?p2 ?o2.
  }
}
WHERE {
  GRAPH ?g {

    # for Rechtenverkenner
    VALUES ?s1 {
      dvc:Rechtenverkenner
    }
    ?s1
      a skos:Concept ;
      skos:topConceptOf dvcs:PublicatieKanaal ;
      mu:uuid "79bf2b83-f087-4a87-86dd-e962dbca16e4" ;
      ?p1 ?o1.

    # for VLoket
    VALUES ?s2 {
      dvc:VLoket
    }
    ?s2
      a skos:Concept ;
      skos:topConceptOf dvcs:PublicatieKanaal ;
      mu:uuid "74016a22-e2aa-41da-9313-798a8129d010" ;
      ?p2 ?o2.
  }
}
