DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Herfsvakantie"@nl .
   }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Herfstvakantie"@nl .
   }
}
