INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
        <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/concepts/957d98bc-cccf-4e12-b58a-faf9b2eff150>.

    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257>
        <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/concepts/9c656ab1-a17f-4e4a-b6a0-093c1773a941>.

    <http://lblod.data.gift/concepts/957d98bc-cccf-4e12-b58a-faf9b2eff150>
        a <http://www.w3.org/2000/01/rdf-schema#Class>, <https://www.gleif.org/ontology/Base/Period>;
        <http://mu.semte.ch/vocabularies/core/uuid> "957d98bc-cccf-4e12-b58a-faf9b2eff150" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Autumn break 2020 Belgium Submission Period"@en;
        <https://www.gleif.org/ontology/Base/hasStart> "2020-12-14"^^<http://www.w3.org/2001/XMLSchema#date>;
        <https://www.gleif.org/ontology/Base/hasEnd> "2021-07-31"^^<http://www.w3.org/2001/XMLSchema#date>.

    <http://lblod.data.gift/concepts/9c656ab1-a17f-4e4a-b6a0-093c1773a941>
        a <http://www.w3.org/2000/01/rdf-schema#Class>, <https://www.gleif.org/ontology/Base/Period>;
        <http://mu.semte.ch/vocabularies/core/uuid> "9c656ab1-a17f-4e4a-b6a0-093c1773a941" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Christmas break 2020 Belgium Submission Period"@en;
        <https://www.gleif.org/ontology/Base/hasStart> "2020-12-14"^^<http://www.w3.org/2001/XMLSchema#date>;
        <https://www.gleif.org/ontology/Base/hasEnd> "2021-07-31"^^<http://www.w3.org/2001/XMLSchema#date>.
  }
}
