INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://mu.semte.ch/vocabularies/core/uuid> "a3293c46-06b7-458d-a15c-2f312294773f" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Subsidy time-blocks"@en .

    <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <https://www.gleif.org/ontology/Base/Period>;
        <http://mu.semte.ch/vocabularies/core/uuid> "ef073502-d7c4-4b0c-b399-a73b429f877d" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Autumn break 2020 Belgium"@en;
        <https://www.gleif.org/ontology/Base/hasStart> "2020-11-02"^^<http://www.w3.org/2001/XMLSchema#datetime>;
        <https://www.gleif.org/ontology/Base/hasEnd> "2020-11-08"^^<http://www.w3.org/2001/XMLSchema#datetime>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Herfsvakantie"@nl .

    <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <https://www.gleif.org/ontology/Base/Period>;
        <http://mu.semte.ch/vocabularies/core/uuid> "5e1474df-dfc2-432c-94af-039298222257" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Christmas break 2020 Belgium"@en;
        <https://www.gleif.org/ontology/Base/hasStart> "2020-12-21"^^<http://www.w3.org/2001/XMLSchema#datetime>;
        <https://www.gleif.org/ontology/Base/hasEnd> "2021-01-03"^^<http://www.w3.org/2001/XMLSchema#datetime>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/a3293c46-06b7-458d-a15c-2f312294773f>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Kerstvakantie"@nl .
  }
}
