PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?bestuurseenheid ext:isTrailUser "true"^^xsd:boolean .
  }
}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?bestuurseenheid ext:isTrailUser "true"^^xsd:boolean .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?bestuurseenheid a besluit:Bestuurseenheid ;
     ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/9c503a712d448bc8b89c1f8802c207e30bd192bc8da3bf22509a547949a45301> ;
      besluit:classificatie ?classificatie .
     FILTER(?classificatie IN (<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> , <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>))
  }
}
