DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://versions/2021011315032436-form> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "2021011315032436-form" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://versions/2021011315032436-form> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "20210113150324-form" .
  }
}

;

# Avoid sprintf error
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <share://versions/2021011315032436-form> <http://dummy/data/predicate> <http://dummy/data/object> .
    <http://dummy/data/subject> <http://dummy/data/other-predicate> <share://versions/2021011315032436-form> .
  }
}
;
DELETE {
  GRAPH ?g {
    ?a ?b <share://versions/2021011315032436-form> .
  }
  GRAPH ?h {
    <share://versions/2021011315032436-form> ?p ?o .
  }
} INSERT {
  GRAPH ?g {
    ?a ?b <share://versions/20210113150324-form> .
  }
  GRAPH ?h {
    <share://versions/20210113150324-form> ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?a ?b <share://versions/2021011315032436-form> .
  }
  GRAPH ?h {
    <share://versions/2021011315032436-form> ?p ?o .
  }
}
;
# Avoid sprintf error
DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <share://versions/2021011315032436-form> <http://dummy/data/predicate> <http://dummy/data/object> .
    <http://dummy/data/subject> <http://dummy/data/other-predicate> <share://versions/2021011315032436-form> .
  }
}