PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>

# Avoid sprintf error: adding dummy data
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dummy/data/form> a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
            dct:source <share://form-files/2020/20201207135752-form.ttl>, <share://form-files/2020/20201130150729-form.ttl> .
  }
}

;

# Updating source to link to directory-folder instead of form-file
DELETE {
  GRAPH ?g {
    ?form dct:source <share://form-files/2020/20201207135752-form.ttl> .
  }
}
INSERT {
  GRAPH ?g {
   ?form dct:source <share://versions/20201207135752-form> .
  }
}
WHERE {
  GRAPH ?g {
     ?form a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
        dct:source <share://form-files/2020/20201207135752-form.ttl> .
  }
}
;
DELETE {
  GRAPH ?g {
    ?form dct:source <share://form-files/2020/20201130150729-form.ttl> .
  }
}
INSERT {
  GRAPH ?g {
   ?form dct:source <share://versions/20201130150729-form> .
  }
}
WHERE {
  GRAPH ?g {
     ?form a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
        dct:source <share://form-files/2020/20201130150729-form.ttl> .
  }
}

;

# Deleting old form-files from the store
DELETE {
  GRAPH ?g {
    ?file ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
     VALUES ?file {
           <share://form-files/2020/20201207135752-form.ttl> <share://form-files/2020/20201130150729-form.ttl>
     }
     ?file ?p ?o .
  }
}

;

# Avoid sprintf error: delete dummy data
DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dummy/data/form> a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
            dct:source <share://form-files/2020/20201207135752-form.ttl>, <share://form-files/2020/20201130150729-form.ttl> .
  }
}
