INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://lblod.data.gift/concept-schemes/4e719768-d43b-4ca1-ab92-b463e15721f5> <http://mu.semte.ch/vocabularies/core/uuid> "4e719768-d43b-4ca1-ab92-b463e15721f5" .

    <http://lblod.data.gift/concepts/19ae2617-6ffd-4c3d-8c41-4afd618ddfdf> a <http://lblod.data.gift/vocabularies/submissions/ReportingPeriod>;
        <http://mu.semte.ch/vocabularies/core/uuid> "19ae2617-6ffd-4c3d-8c41-4afd618ddfdf" .

    <http://lblod.data.gift/concept-schemes/4e719768-d43b-4ca1-ab92-b463e15721f5> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Reporting period long term plan worship services"@en, "Rapportperiode meerjarenplan erediensten"@nl .

    <http://lblod.data.gift/concepts/19ae2617-6ffd-4c3d-8c41-4afd618ddfdf>
      a <http://www.w3.org/2004/02/skos/core#Concept>, <http://data.europa.eu/m8g/PeriodOfTime>;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/4e719768-d43b-4ca1-ab92-b463e15721f5> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "2020-2025"@nl ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/4e719768-d43b-4ca1-ab92-b463e15721f5>;
      <http://data.europa.eu/m8g/endTime> "2025-12-31T22:59:59Z"^^xsd:dateTime;
      <http://data.europa.eu/m8g/startTime> "2019-12-31T22:59:59Z"^^xsd:dateTime. # To account for CET.

  }

}