PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX cube: <http://purl.org/linked-data/cube#>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

      # Remove new description to "old" "Aanvraag" step
      <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d>
          dct:description """Aanvraag""";
          # NOTE: remove FINAL mark
          subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # Add new description to "old" "Aanvraag" step
    <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d>
        dct:description """Aanvraag uitbetaling""".

    # Submission period for the "Aanvraag Saldo" step
    <http://data.lblod.info/id/periodes/d1d600fb-4cd1-4188-bcbc-bd4df721ad1e>
        a m8g:PeriodOfTime;
        mu:uuid """d1d600fb-4cd1-4188-bcbc-bd4df721ad1e""";
        # TODO build a cool simple feature to activate or de-activate steps
        m8g:startTime "2022-01-01T03:00:00Z"^^xsd:dateTime;
        m8g:endTime "2025-09-15T21:59:59Z"^^xsd:dateTime.

    # The subsidy-procedural-step for "Aanvraag Saldo"
    <http://data.lblod.info/id/subsidy-procedural-steps/ac33d0fe-ff5a-41ea-8730-1d655cca8cce>
        a subsidie:Subsidieprocedurestap;
        # NOTE: mark as FINAL
        subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6>;
        mu:uuid "ac33d0fe-ff5a-41ea-8730-1d655cca8cce";
        dct:description """Aanvraag saldo""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/d1d600fb-4cd1-4188-bcbc-bd4df721ad1e>.

    # Add the new "Aanvraag Saldo" step
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f>
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/ac33d0fe-ff5a-41ea-8730-1d655cca8cce>.

    # Update the second step
    <http://lblod.data.info/id/subsidie-application-flow-steps/75aa0af5-21e1-44c4-96e9-7f7f013bd1cc>
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/85e66a24-4bf5-4cff-ac70-6af49e29e693>.

    # The third step
    <http://lblod.data.info/id/subsidie-application-flow-steps/85e66a24-4bf5-4cff-ac70-6af49e29e693>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "85e66a24-4bf5-4cff-ac70-6af49e29e693" ;
      # TODO update to correct config
      dct:source <config://forms/bicycle-infrastructure/request-balance/versions/20220110162327-initial-version/form.ttl> ;
      cube:order 2 ;
      xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/75aa0af5-21e1-44c4-96e9-7f7f013bd1cc> ;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/ac33d0fe-ff5a-41ea-8730-1d655cca8cce> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267> .
  }
}