INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <https://data.vlaanderen.be/id/concept/BesluitDocumentType/18833df2-8c9e-4edd-87fd-b5c252337349>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "18833df2-8c9e-4edd-87fd-b5c252337349";

        # Only visible for "Centraal bestuur van de eredienst"
        <http://lblod.data.gift/vocabularies/besluit/decidableBy> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/f9cac08a-13c1-49da-9bcb-f650b0604054>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#definition> "Gecoördineerd indienen van de budgetten en budgetwijzigingen van de besturen van de eredienst door het centraal bestuur van de eredienst.";
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Budgetten(wijzigingen) van besturen van de eredienst"@nl.
  }
} 