INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

<http://lblod.data.gift/concepts/2e2a4aeb13f4348e035c4ade7fc9bc354eaa31ab8a075deb518da05f28e3cd05> # origineel
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/91655ebf-5ab7-43c4-b587-094536baf737>;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/91655ebf-5ab7-43c4-b587-094536baf737> .

<http://lblod.data.gift/concepts/acccc9cb-7628-4f42-b627-e94bd0b30532> a <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/91655ebf-5ab7-43c4-b587-094536baf737>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Wijziging"@nl;
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/91655ebf-5ab7-43c4-b587-094536baf737> .

<http://lblod.data.gift/concept-schemes/91655ebf-5ab7-43c4-b587-094536baf737> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Document authenticity type (worship services)"@en,
     "Type authenticiteit van het document (erediensten)"@nl .

<http://lblod.data.gift/concepts/acccc9cb-7628-4f42-b627-e94bd0b30532> <http://mu.semte.ch/vocabularies/core/uuid> "acccc9cb-7628-4f42-b627-e94bd0b30532" .

  }
}