PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "26009b3c-256e-4a6c-aa3f-48e37b5d5c64" ;
      skos:prefLabel "Zennevallei Hergist" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0786436408" ;
      dcterms:identifier "OVO050000", "0786436408" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/5b0fd6505cf6157499a0ca23417f7cda>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"5b0fd6505cf6157499a0ca23417f7cda" ;
      skos:prefLabel "Directiecomité Zennevallei Hergist" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64> .

    <http://data.lblod.info/id/bestuursorganen/3cfeade7339fbcd28e4ab2d8fde11303>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"3cfeade7339fbcd28e4ab2d8fde11303" ;
      skos:prefLabel "Raad van bestuur Zennevallei Hergist" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64> .

    <http://data.lblod.info/id/bestuursorganen/689931f2a0ffaedad0f70bb3cf241eba>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"689931f2a0ffaedad0f70bb3cf241eba" ;
      skos:prefLabel "Bevoegd beslissingsorgaan Zennevallei Hergist" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64> .

    <http://data.lblod.info/id/bestuursorganen/fd363ef63ea17b26c98779f444cd80a4>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"fd363ef63ea17b26c98779f444cd80a4" ;
      skos:prefLabel "Algemene vergadering Zennevallei Hergist" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64> .

    <http://data.lblod.info/id/bestuursorganen/2d0018cc9fd3744ee9005dc37e989de5>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"2d0018cc9fd3744ee9005dc37e989de5" ;
      skos:prefLabel "Leidend Ambtenaar Zennevallei Hergist" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/44bfc0f93fc3b821b353df1753a8c073>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"44bfc0f93fc3b821b353df1753a8c073" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/5b0fd6505cf6157499a0ca23417f7cda> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/8551b7ccfff572f66967cce8bd331527>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8551b7ccfff572f66967cce8bd331527" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/3cfeade7339fbcd28e4ab2d8fde11303> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/53530e95ad13bca7e4810c4d3a33f91d>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"53530e95ad13bca7e4810c4d3a33f91d" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/689931f2a0ffaedad0f70bb3cf241eba> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/18e88a083042479e95605c4375a54554>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"18e88a083042479e95605c4375a54554" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/fd363ef63ea17b26c98779f444cd80a4> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/fe15f397e68798ada8516954a8ded0af>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"fe15f397e68798ada8516954a8ded0af" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/2d0018cc9fd3744ee9005dc37e989de5> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
