PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX schema: <http://schema.org/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>

# Create Subsidieprocedurestappen
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/subsidieprocedurestappen/457c23ba-4d54-4092-9f9c-e575cc7bd880>
      a subsidie:Subsidieprocedurestap ;
      mu:uuid "457c23ba-4d54-4092-9f9c-e575cc7bd880" ;
      dct:description "Aanvraag" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/957d98bc-cccf-4e12-b58a-faf9b2eff150> ; # Autumn break 2020 Belgium Submission Period
      mobiliteit:periode <http://data.lblod.info/perioden/0f592b52-ac02-44fc-b3b3-68bfc8e50931> .

    <http://data.lblod.info/perioden/0f592b52-ac02-44fc-b3b3-68bfc8e50931>
      a m8g:PeriodOfTime ;
      mu:uuid "0f592b52-ac02-44fc-b3b3-68bfc8e50931" ;
      m8g:startTime "2020-11-16T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
      m8g:endTime "2021-06-30T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/subsidieprocedurestappen/7b34a0e3-5a0d-4685-9d00-97cfb1b2e983>
      a subsidie:Subsidieprocedurestap ;
      mu:uuid "7b34a0e3-5a0d-4685-9d00-97cfb1b2e983" ;
      dct:description "Aanvraag" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/9c656ab1-a17f-4e4a-b6a0-093c1773a941> ; # Christmas break 2020 Belgium Submission Period
      mobiliteit:periode <http://data.lblod.info/perioden/3abadbb5-4554-4482-9cc3-1d22d5887adb> .

    <http://data.lblod.info/perioden/3abadbb5-4554-4482-9cc3-1d22d5887adb>
      a m8g:PeriodOfTime ;
      mu:uuid "3abadbb5-4554-4482-9cc3-1d22d5887adb" ;
      m8g:startTime "2021-01-04T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
      m8g:endTime "2021-06-30T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
}

;

# Create Criterions
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/criteriums/d24b6ac6-afa7-4f23-b5aa-ade16ed505ae>
      a m8g:Criterion ;
      mu:uuid "d24b6ac6-afa7-4f23-b5aa-ade16ed505ae" ;
      dct:title "Herfsvakantie"@nl ;
      m8g:criterionType <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d> ;
      dct:isPartOf <http://data.lblod.info/subsidieprocedurestappen/457c23ba-4d54-4092-9f9c-e575cc7bd880> ;
      m8g:fulfilledByRequirementGroup <http://data.lblod.info/vereistengroepen/a91a1d04-9e84-4ebd-81eb-12f1ea5b6bdc> .

    <http://data.lblod.info/vereistengroepen/a91a1d04-9e84-4ebd-81eb-12f1ea5b6bdc>
      a m8g:RequirementGroup ;
      mu:uuid "a91a1d04-9e84-4ebd-81eb-12f1ea5b6bdc" ;
      m8g:hasCriterionRequirement <http://data.lblod.info/criteriumvereisten/02cd7740-15f0-43b9-ad1f-64eab7a5be64> .

    <http://data.lblod.info/criteriumvereisten/02cd7740-15f0-43b9-ad1f-64eab7a5be64>
      a m8g:CriterionRequirement ;
      mu:uuid "02cd7740-15f0-43b9-ad1f-64eab7a5be64" ;
      m8g:applicableInPeriodOfTime <http://data.lblod.info/perioden/356b3392-7131-433a-8f3c-056842ec4063> .

    <http://data.lblod.info/perioden/356b3392-7131-433a-8f3c-056842ec4063>
      a m8g:PeriodOfTime ;
      mu:uuid "356b3392-7131-433a-8f3c-056842ec4063" ;
      m8g:startTime "2020-11-09T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
      m8g:endTime "2020-11-13T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/criteriums/fac72fed-1b56-4a80-8eca-f21cccd15a1a>
      a m8g:Criterion ;
      mu:uuid "fac72fed-1b56-4a80-8eca-f21cccd15a1a" ;
      dct:title "Kerstvakantie"@nl ;
      m8g:criterionType <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257> ;
      dct:isPartOf <http://data.lblod.info/subsidieprocedurestappen/7b34a0e3-5a0d-4685-9d00-97cfb1b2e983> ;
      m8g:fulfilledByRequirementGroup <http://data.lblod.info/vereistengroepen/0952a42e-9523-4986-9e75-d2240b9c6578> .

    <http://data.lblod.info/vereistengroepen/0952a42e-9523-4986-9e75-d2240b9c6578>
      a m8g:RequirementGroup ;
      mu:uuid "0952a42e-9523-4986-9e75-d2240b9c6578>" ;
      m8g:hasCriterionRequirement <http://data.lblod.info/criteriumvereisten/612a1419-e347-448f-8708-862d81b84d24> .

    <http://data.lblod.info/criteriumvereisten/612a1419-e347-448f-8708-862d81b84d24>
      a m8g:CriterionRequirement ;
      mu:uuid "612a1419-e347-448f-8708-862d81b84d24" ;
      m8g:applicableInPeriodOfTime <http://data.lblod.info/perioden/6ad9ff27-4877-440b-a22a-5a9095f74480> .

    <http://data.lblod.info/perioden/6ad9ff27-4877-440b-a22a-5a9095f74480>
      a m8g:PeriodOfTime ;
      mu:uuid "6ad9ff27-4877-440b-a22a-5a9095f74480" ;
      m8g:startTime "2020-12-21T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
      m8g:endTime "2021-01-03T00:00:00.000Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
}

;

# Link aanboden to Subsidieprocedurestappen and Criterions
# It can only be Herfsvakantie, the only available one on subsidies until now
INSERT {
  GRAPH ?h {
    ?aanbod
      m8g:hasCriterion <http://data.lblod.info/criteriums/d24b6ac6-afa7-4f23-b5aa-ade16ed505ae> ;
      cpsv:follows <http://data.lblod.info/subsidieprocedurestappen/457c23ba-4d54-4092-9f9c-e575cc7bd880> .
  }
}
WHERE {
  GRAPH ?g {
    ?aanbod a subsidie:SubsidiemaatregelAanbod .
  }
  BIND (?g as ?h)
}
