PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA{
  GRAPH <http://mu.semte.ch/graphs/public> {
   <share://semantic-forms/20220119123200-forms.ttl> a nfo:FileDataObject ;
 				  dct:type <http://data.lblod.gift/concepts/form-file-type> ;
                                  mu:uuid "01d0f791-faa6-4564-a3a0-72a124676969" ;
                                  nfo:fileName "20220119123200-forms.ttl" ;
                                  dct:created "2022-01-19Z"^^xsd:dateTime ;
                                  dct:modified "2022-01-19Z"^^xsd:dateTime ;
                                  dct:format "text/turtle";
                                  nfo:fileSize "279667"^^xsd:integer;
                                  dbpedia:fileExtension "ttl" .
  }
}