DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/Nomenclature/6c8132fc24e1be8b0134380e308eef3adb1357f0fb8bbfa62eea8197916580fd> <http://www.w3.org/2004/02/skos/core#prefLabel> ?label
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/Nomenclature/6c8132fc24e1be8b0134380e308eef3adb1357f0fb8bbfa62eea8197916580fd> <http://www.w3.org/2004/02/skos/core#prefLabel> "MAR7304 - Gewestelijke belasting op ongeschikt en onbewoonbare woningen" .
  }
}
