DELETE {
  GRAPH ?g {
    ?s a <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#ConceptDisplayConfiguration>;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptIsNew> ?isNew;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptInstantiated> ?instantiated.
  }
}
INSERT {
  GRAPH ?g {
    ?s a <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#ConceptDisplayConfiguration>;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptIsNew> "false"^^<http://mu.semte.ch/vocabularies/typed-literals/boolean>;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptInstantiated> "false"^^<http://mu.semte.ch/vocabularies/typed-literals/boolean>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#ConceptDisplayConfiguration>;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptIsNew> ?isNew;
      <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#conceptInstantiated> ?instantiated.
  }
}