PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20221205144552-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "fb5f97b3-73ae-4130-840d-35083542540f" ;
      nfo:fileName "20221205144552-forms.ttl" ;
      dct:created "2022-12-05T14:45:52"^^xsd:dateTime ;
      dct:modified "2022-12-05T14:45:52"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "336271"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    