PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{

    # Period of the Series/Step
    <http://data.lblod.info/id/periodes/d184580a-a7a8-447b-b510-f8da50e440ce>
        a mg8:PeriodOfTime ;
        mu:uuid "d184580a-a7a8-447b-b510-f8da50e440ce" ;
        mg8:startTime "2021-11-22T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2022-02-04T21:59:59Z"^^xsd:dateTime .

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/017fe3be-07c7-4341-9c1d-e322d6c41fa1>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "017fe3be-07c7-4341-9c1d-e322d6c41fa1";
        dct:description """Indienen voorstel""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/d184580a-a7a8-447b-b510-f8da50e440ce>.

    # Create Series for call up 2
    <http://lblod.data.info/id/subsidy-measure-offer-series/51e938fb-c841-4df4-89f5-7216b75a5348>
        a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
        mu:uuid "51e938fb-c841-4df4-89f5-7216b75a5348" ;
        dct:title "Oproep 2"@nl ;
        dct:description "22/11/2021 — 04/02/2022"@nl ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/d184580a-a7a8-447b-b510-f8da50e440ce> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/017fe3be-07c7-4341-9c1d-e322d6c41fa1> ;
        common:active <http://lblod.data.info/id/subsidie-application-flows/9d32100d-7901-463b-ad26-8ee7661a97ab> .

    # Link to existing Subsidy Offer for GZG
    <http://lblod.data.info/id/subsidy-measure-offers/8379a4ea-fd83-47cc-89fa-1a72ee4fbaff>
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/017fe3be-07c7-4341-9c1d-e322d6c41fa1> ;
        lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/51e938fb-c841-4df4-89f5-7216b75a5348> .

    # Subsidy Active Submission Flow Step 0
    <http://lblod.data.info/id/subsidie-application-flow-steps/308ce97d-3647-4371-9459-0da32ef1872e>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "308ce97d-3647-4371-9459-0da32ef1872e" ;
        qb:order 0 ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/017fe3be-07c7-4341-9c1d-e322d6c41fa1> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/9d32100d-7901-463b-ad26-8ee7661a97ab> ;
        dct:source <config://forms/GZG/proposal/versions/20211025162829-callup-2/form.ttl> .

    # Subsidy Active Submission Flow
    <http://lblod.data.info/id/subsidie-application-flows/9d32100d-7901-463b-ad26-8ee7661a97ab>
        a lblodSubsidie:ApplicationFlow ;
        mu:uuid "9d32100d-7901-463b-ad26-8ee7661a97ab" ;
        xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/51e938fb-c841-4df4-89f5-7216b75a5348> ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/308ce97d-3647-4371-9459-0da32ef1872e> .
  }
}