PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{

    # Period of the Series/Step
    <http://data.lblod.info/id/periodes/09af0425-12cc-411c-abcf-16ace6af3cfe>
        a mg8:PeriodOfTime ;
        mu:uuid "09af0425-12cc-411c-abcf-16ace6af3cfe" ;
        mg8:startTime "2021-11-22T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2022-02-04T21:59:59Z"^^xsd:dateTime .

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/f61dc47f-e7f8-46f3-b37d-27730c440ec0>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "f61dc47f-e7f8-46f3-b37d-27730c440ec0";
        dct:description """Indienen voorstel""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/09af0425-12cc-411c-abcf-16ace6af3cfe>.

    # Create Series for call up 2
    <http://lblod.data.info/id/subsidy-measure-offer-series/4cebd644-d172-4bea-a38a-fc1f4449946e>
        a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
        mu:uuid "4cebd644-d172-4bea-a38a-fc1f4449946e" ;
        dct:title "Oproep 3"@nl ;
        dct:description "22/11/2021 — 04/02/2022"@nl ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/09af0425-12cc-411c-abcf-16ace6af3cfe> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/f61dc47f-e7f8-46f3-b37d-27730c440ec0> ;
        common:active <http://lblod.data.info/id/subsidie-application-flows/98d555e9-99d7-48cf-8e17-bc4a6c39aa81> .

    # Link to existing Subsidy Offer for GZG
    <http://lblod.data.info/id/subsidy-measure-offers/8379a4ea-fd83-47cc-89fa-1a72ee4fbaff>
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/f61dc47f-e7f8-46f3-b37d-27730c440ec0> ;
        lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/4cebd644-d172-4bea-a38a-fc1f4449946e> .

    # Subsidy Active Submission Flow Step 0
    <http://lblod.data.info/id/subsidie-application-flow-steps/66ee0cd6-51f1-43f2-9945-2ef4dfdd895a>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "66ee0cd6-51f1-43f2-9945-2ef4dfdd895a" ;
        qb:order 0 ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/f61dc47f-e7f8-46f3-b37d-27730c440ec0> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/98d555e9-99d7-48cf-8e17-bc4a6c39aa81> ;
        dct:source <config://forms/GZG/proposal/versions/20211025162830-third-call/form.ttl> .

    # Subsidy Active Submission Flow
    <http://lblod.data.info/id/subsidie-application-flows/98d555e9-99d7-48cf-8e17-bc4a6c39aa81>
        a lblodSubsidie:ApplicationFlow ;
        mu:uuid "98d555e9-99d7-48cf-8e17-bc4a6c39aa81" ;
        xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/4cebd644-d172-4bea-a38a-fc1f4449946e> ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/66ee0cd6-51f1-43f2-9945-2ef4dfdd895a> .
  }
}