PREFIX dct: <http://purl.org/dc/terms/>

###
# START WORKAROUND SPRINTF
###
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    <http://data.lblod.info/id/application-form/dummy/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> dct:source
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.json> ,
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.ttl> .
  }
}

;

# DELETE/INSERT NEW FORM CONFIG.
DELETE {
    GRAPH ?g {
     ?s ?p ?o .
    }
} INSERT {
    GRAPH ?g {
     ?s ?p <config://forms/GZG/proposal/versions/20210721111449-first-call/form.json> .
    }
} WHERE {
    VALUES ?o {
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.json>
    }
    GRAPH ?g {
     ?s ?p ?o .
    }
}
;
# DELETE/INSERT NEW FORM SPEC.
DELETE {
    GRAPH ?g {
     ?s ?p ?o .
    }
} INSERT {
    GRAPH ?g {
     ?s ?p <config://forms/GZG/proposal/versions/20210721111449-first-call/form.ttl> .
    }
} WHERE {
    VALUES ?o {
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.ttl>
    }
    GRAPH ?g {
     ?s ?p ?o .
    }
}
;
# DELETE OLD FORM SPEC. LOCATION
DELETE {
    GRAPH ?g {
     ?s ?p ?o .
    }
} WHERE {
    VALUES ?s {
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.ttl>
        <http://data.lblod.info/files/f4b654d6-9d39-539d-b18a-d0503da51607>
        <config://forms/city-without-townhall/proposal/versions/20210721111449-inital-version/form.json>
        <http://data.lblod.info/files/27a78c2e-9853-5c23-8f6e-ab770044876e>
    }
    GRAPH ?g {
     ?s ?p ?o .
    }
}

;

###
# START WORKAROUND SPRINTF
###
DELETE {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    ?s ?p ?o.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    ?s ?p ?o.
  }
}