PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/ea7a018d-aa72-47df-a62d-185cee5d03b2> mg8:endTime "2022-05-27T21:59:59Z"^^xsd:dateTime .
    <http://lblod.data.info/id/subsidy-measure-offer-series/f2db06a1-13cf-460e-9a2f-51658b7d41d1> dct:description "21/03/2022 — 27/05/2022"@nl .
    
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/ea7a018d-aa72-47df-a62d-185cee5d03b2> mg8:endTime "2022-07-01T21:59:59Z"^^xsd:dateTime .
    <http://lblod.data.info/id/subsidy-measure-offer-series/f2db06a1-13cf-460e-9a2f-51658b7d41d1> dct:description "21/03/2022 — 01/07/2022"@nl .
  }
}