PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX org: <http://www.w3.org/ns/org#>

INSERT  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public/> {
    ?s ?p ?o.
  }
}

DROP SILENT GRAPH <http://mu.semte.ch/graphs/public/>;


#########################################################
# GEMEENTEBESTUUR ADD adjunct financieel directeur again
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(?bestuursorgaan), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
    (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789>) # adjunct financieel directeur
  }
}

;


#########################################################
# Provincie Add griffier again
########################################################
INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(?bestuursorgaan), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
      (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab19107-82d2-4273-a986-3da86fda050d> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/63195ec6-02cb-4f86-ac8e-29c5183a11dc>) # Grifier
  }
};