PREFIX    mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX    besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX    persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX    foaf: <http://xmlns.com/foaf/0.1/>
PREFIX    org: <http://www.w3.org/ns/org#>
PREFIX    skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX    rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX    ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX    regorg: <https://www.w3.org/ns/regorg#>
PREFIX    person: <http://www.w3.org/ns/person#>
PREFIX    schema: <http://schema.org/>
PREFIX    prov: <http://www.w3.org/ns/prov#>
PREFIX    adms: <http://www.w3.org/ns/adms#>
PREFIX    mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX    lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>


##################################
# To run in Loket
# Updates broken label
# removes double label
#################################

# update label
DELETE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> <http://www.w3.org/2004/02/skos/core#prefLabel> ?o.
  }
}
INSERT {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> <http://www.w3.org/2004/02/skos/core#prefLabel> "Adjunct Algemeen Directeur".
   }
}
WHERE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> <http://www.w3.org/2004/02/skos/core#prefLabel> ?o.
  }
}

;


DELETE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789> <http://www.w3.org/2004/02/skos/core#prefLabel> ?o.
  }
}
INSERT {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789> <http://www.w3.org/2004/02/skos/core#prefLabel> "Adjunct Financieel Directeur".
   }
}
WHERE {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789> <http://www.w3.org/2004/02/skos/core#prefLabel> ?o.
  }
}
