INSERT {
  GRAPH ?h {
    ?account <http://mu.semte.ch/vocabularies/ext/sessionRole> "LoketLB-eredienstMandaatGebruiker", "LoketLB-eredienstBedienaarGebruiker" .
  }
} WHERE {
  GRAPH ?g {
    ?account a <http://xmlns.com/foaf/0.1/OnlineAccount> ;
      <http://xmlns.com/foaf/0.1/accountServiceHomepage> <https://github.com/lblod/mock-login-service> .

    ?person <http://xmlns.com/foaf/0.1/account> ?account ;
      <http://xmlns.com/foaf/0.1/member> ?bestuurseenheid .

    ?bestuurseenheid a ?type .

    FILTER (?type IN (
      <http://data.lblod.info/vocabularies/erediensten/CentraalBestuurVanDeEredienst>,
      <http://data.lblod.info/vocabularies/erediensten/BestuurVanDeEredienst>
    ))
  }
  BIND(?g as ?h)
}
