PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

<http://lblod.data.gift/concepts/84fd72f7fe3f85ff81797fcf5c9d965f> a <http://lblod.data.gift/vocabularies/organisatie/HelftVerkiezing> ;
    mu:uuid "84fd72f7fe3f85ff81797fcf5c9d965f" ;
    skos:inScheme <http://lblod.data.gift/concept-schemes/1644ef16fae0a2590321f9cd02635c2f> ;
    skos:prefLabel "Kleine helft" ;
    skos:topConceptOf <http://lblod.data.gift/concept-schemes/1644ef16fae0a2590321f9cd02635c2f> .

<http://lblod.data.gift/concepts/a8d9605b23994c25fb2c2b42ef0d817e> a <http://lblod.data.gift/vocabularies/organisatie/HelftVerkiezing> ;
    mu:uuid "a8d9605b23994c25fb2c2b42ef0d817e" ;
    skos:inScheme <http://lblod.data.gift/concept-schemes/1644ef16fae0a2590321f9cd02635c2f> ;
    skos:prefLabel "Grote helft" ;
    skos:topConceptOf <http://lblod.data.gift/concept-schemes/1644ef16fae0a2590321f9cd02635c2f> .
    }
}