PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>

DELETE {
  GRAPH ?g {
    ?s a <http://mu.semte.ch/vocabularies/ext/EredienstBeroepen>.
  }
}
INSERT {
  GRAPH ?g {
    ?s a code:EredienstBeroepen.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://mu.semte.ch/vocabularies/ext/EredienstBeroepen>.
  }
}
