PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE {
  GRAPH ?g {
  ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member ?bestuurseenheid ;
           foaf:account <http://data.lblod.info/id/account/411c514f1c262cb86aa0459dcca49dc4>.
   <http://data.lblod.info/id/account/411c514f1c262cb86aa0459dcca49dc4> a foaf:OnlineAccount;
                                                                        ?accP ?accO.
  }
}
WHERE {
  GRAPH ?g {
  ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member ?bestuurseenheid ;
           foaf:account <http://data.lblod.info/id/account/411c514f1c262cb86aa0459dcca49dc4>.
   <http://data.lblod.info/id/account/411c514f1c262cb86aa0459dcca49dc4> a foaf:OnlineAccount;
                                                                        ?accP ?accO.
  }
}