PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE {
  GRAPH ?g {
  ?persoon foaf:familyName ?oldNaam;
      foaf:firstName ?oldClassificatie.
  }
}
INSERT {
  GRAPH ?g {
      ?persoon foaf:familyName ?naam;
          foaf:firstName ?classificatie.
  }
}
WHERE {
  GRAPH ?g {
     ?persoon a foaf:Person;
          mu:uuid "a4f5084a0e64cdff883599a2ec36f96c";
          foaf:familyName ?oldNaam;
          foaf:firstName ?oldClassificatie.
  }
  GRAPH ?h {
      <http://data.lblod.info/id/bestuurseenheden/0cbfce1ee17fb64428e643c966464a4c3411180b30c10cb22ff51184a08b5b37> a besluit:Bestuurseenheid;
          skos:prefLabel ?naam;
          besluit:classificatie/skos:prefLabel ?classificatie.
  }
}
