DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/934917cdce95b7d47219ca88ba5dfaf99d41d1580985a3ff521650c115905da1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Fluvius West" .
    <http://data.lblod.info/id/bestuurseenheden/934917cdce95b7d47219ca88ba5dfaf99d41d1580985a3ff521650c115905da1> <http://www.w3.org/2004/02/skos/core#altLabel> "Infrax West" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/934917cdce95b7d47219ca88ba5dfaf99d41d1580985a3ff521650c115905da1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Infrax West" .
  }
}
