DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/19877d8078eeedf77e4501754683691c516b007c67a650f3c052845328d60577> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/21b4ce7fe62be7ff933d91616b54b79427dd96026626c75ae2a5b660ac90581c> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/44b84fe12963c437a7d29d16be7b6692d5bb0d00cec58175bd7239286af86a1b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/5862e658553517377cbb93414fab16bffa3f79c86e24efc0217f19ae0d328a69> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/8ceaf793863638005ae441d76e37b93a1c122bc5d112bec9c40cbaf9d6c0b890> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/9af828073bb4c53989fe0693526a31aec47d85a4bc6ac9d485ca6878eb3b3f1c> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/9e1a43e3eea9453e9141292a3d28aa82e41b65ec7089208c3bbe2aca902ec640> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/aca61374bd3a42658f92cdf9cbabc9640c64c4fbf738cb56487d633f47fed7be> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/ad5b386c0cb68ca51133b8e689e21ba6d3dc94726f2578f14631a61caaeaf8ac> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/ade6a3d0e031660258649f141b8f17015da01557581f74122147c738af83b0c4> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/c5774766b2549ebd3590b1c9ae955636a8f1b90f01b06c1713aeb0a9ccd0845b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/ca36d344f695ee5ab2b21659db5d54a68b55e7c36d5ff1c3669793c241746d94> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/f32f26f5ec821f929cac02fa27907f200c08db6edcfd21a3ee81bebad372d43a> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/ba8ffc97-5490-4ecc-b24e-aab26b23c026> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/cadbde55-c68c-47c1-8da1-905a171b844b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/71dc3947-975f-4540-bd50-1f50f29d7567> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/2559a855-a1c9-489d-964b-1d3c9bada85b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/d1d94ffd-77f3-44d8-95f4-bed5db822ef9> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
    <http://data.lblod.info/id/bestuurseenheden/894c9265-c1fe-4db3-a5d7-104f34f2cf18> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/19877d8078eeedf77e4501754683691c516b007c67a650f3c052845328d60577> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/21b4ce7fe62be7ff933d91616b54b79427dd96026626c75ae2a5b660ac90581c> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/44b84fe12963c437a7d29d16be7b6692d5bb0d00cec58175bd7239286af86a1b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/5862e658553517377cbb93414fab16bffa3f79c86e24efc0217f19ae0d328a69> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/8ceaf793863638005ae441d76e37b93a1c122bc5d112bec9c40cbaf9d6c0b890> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/9af828073bb4c53989fe0693526a31aec47d85a4bc6ac9d485ca6878eb3b3f1c> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d> .
    <http://data.lblod.info/id/bestuurseenheden/9e1a43e3eea9453e9141292a3d28aa82e41b65ec7089208c3bbe2aca902ec640> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/aca61374bd3a42658f92cdf9cbabc9640c64c4fbf738cb56487d633f47fed7be> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/ad5b386c0cb68ca51133b8e689e21ba6d3dc94726f2578f14631a61caaeaf8ac> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/ade6a3d0e031660258649f141b8f17015da01557581f74122147c738af83b0c4> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/c5774766b2549ebd3590b1c9ae955636a8f1b90f01b06c1713aeb0a9ccd0845b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/ca36d344f695ee5ab2b21659db5d54a68b55e7c36d5ff1c3669793c241746d94> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/f32f26f5ec821f929cac02fa27907f200c08db6edcfd21a3ee81bebad372d43a> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/bestuurseenheden/ba8ffc97-5490-4ecc-b24e-aab26b23c026> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/cadbde55-c68c-47c1-8da1-905a171b844b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d> .
    <http://data.lblod.info/id/bestuurseenheden/71dc3947-975f-4540-bd50-1f50f29d7567> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/2559a855-a1c9-489d-964b-1d3c9bada85b> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d01bb1f6-2439-4e33-9c25-1fc295de2e71> .
    <http://data.lblod.info/id/bestuurseenheden/d1d94ffd-77f3-44d8-95f4-bed5db822ef9> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d> .
    <http://data.lblod.info/id/bestuurseenheden/894c9265-c1fe-4db3-a5d7-104f34f2cf18> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
  }
}
