PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX org: <http://www.w3.org/ns/org#>

INSERT {
  GRAPH ?g {
    ?bestuursorgaanInTijd lblodlg:heeftBestuursfunctie ?bestuursfunctie.
    ?bestuursfunctie a lblodlg:Bestuursfunctie;
                     mu:uuid ?uuid ;
                     skos:prefLabel ?naam;
                     org:role ?bestuursfunctieRol.

  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuursorganen/2e2b3ae3-6b57-470f-bfaf-3e4d94d09b81> a besluit:Bestuursorgaan;
       besluit:classificatie ?classificatie;
       besluit:bestuurt/skos:prefLabel ?eenheidNaam.
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/2e2b3ae3-6b57-470f-bfaf-3e4d94d09b81>.
    ?bestuursfunctieRol skos:prefLabel ?rolNaam.
  }
  BIND(CONCAT(?eenheidNaam, " ", ?rolNaam) AS ?naam)
  BIND(SHA256(CONCAT("eiqueizu4caiShano6ee dahr6iejah4oorisahVa eesaemaiDuo1Aocaipho", ":", STR(<http://data.lblod.info/id/bestuursorganen/2e2b3ae3-6b57-470f-bfaf-3e4d94d09b81>), STR(?classificatie) )) AS ?uuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", STR(?uuid))) AS ?bestuursfunctie) .
  VALUES (?classificatie ?bestuursfunctieRol) {
  (<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f>) # leidend ambtenaar
  }
}
