# 1. Fix werkingsgebieden

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?werkingsgebied <http://www.w3.org/2004/02/skos/core#prefLabel> "Voer en Dijle" .
    ?werkingsgebied <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> . # Vlaams-Brabant
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?werkingsgebied a <http://www.w3.org/ns/prov#Location> .
    ?werkingsgebied <http://mu.semte.ch/vocabularies/core/uuid> "f693cfc7-cff0-45ba-b14e-5909fa44f53e" .
  }
}

;

# 2. Fix bestuurseenheden

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> . # Vlaams-Brabant
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
    ?bestuurseenheid <http://mu.semte.ch/vocabularies/core/uuid> "cdcd4403-d4cd-4400-80a3-9882d79933f4"
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/d0ec3d07-a15c-4e04-bcbb-b05083262544> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> . # Vlaams-Brabant
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/d0ec3d07-a15c-4e04-bcbb-b05083262544> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/50ede269-5c49-41cd-be68-ac135314019c> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> . # Antwerp
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/50ede269-5c49-41cd-be68-ac135314019c> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/1bbd0f7a-664c-46bd-8ca0-891801b81962> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/b6868be9ca6881b1020e6cff8d431531a1cff64b39dc92646a5173b3ee144516> . # Limburg
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/1bbd0f7a-664c-46bd-8ca0-891801b81962> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>.
  }
}
