PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH ?g {
    ?mandataris mandaat:start ?startDate ;
      mandaat:einde ?endDate .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris ext:startDateDT ?startDateDT ;
      ext:endDateDT ?endDateDT .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris a mandaat:Mandataris ;
      mandaat:start ?startDate ;
      mandaat:einde ?endDate .
    BIND (if(regex(str(?startDate), '\\d{4}-\\d\\d-\\d\\d'), xsd:dateTime(?startDate), ?startDate) AS ?startDateDT)
    BIND (if(regex(str(?endDate), '\\d{4}-\\d\\d-\\d\\d'), xsd:dateTime(?endDate), ?endDate) AS ?endDateDT)
  }
}
