PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# Deletes the start dates and format them to a new temporary property (didn't work without)
DELETE {
  GRAPH ?g {
    ?mandataris mandaat:start ?startDate .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris ext:startDateDT ?startDateDT .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris a mandaat:Mandataris ;
      mandaat:start ?startDate .
    BIND (if(regex(str(?startDate), '\\d{4}-\\d\\d-\\d\\d'), xsd:dateTime(?startDate), ?startDate) AS ?startDateDT)
  }
}
