PREFIX schema: <http://schema.org/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

DELETE {
  GRAPH ?g {
    ?bestuurseeheid skos:prefLabel ?bestuurseenheidLabel .
  }
}
INSERT {
  GRAPH ?g {
    ?bestuurseeheid skos:prefLabel "Autonoom Gemeentebedrijf Evergem" .
  }
}
WHERE {
  GRAPH ?g {
     ?bestuurseeheid a besluit:Bestuurseenheid ;
         <http://mu.semte.ch/vocabularies/core/uuid> "0cbfce1ee17fb64428e643c966464a4c3411180b30c10cb22ff51184a08b5b37" ;
         skos:prefLabel ?bestuurseenheidLabel .
  }
}
