DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> .
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> <http://mu.semte.ch/vocabularies/core/uuid> "3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8" .
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> <http://www.w3.org/2004/02/skos/core#prefLabel> "Rechtspositieregeling" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/e9612bfd21b5b805074e751d03224dae38f8c4c91a89fd34f1f4007c3978ba91/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/c5b561ff9656b79531665343c52b69b5ff26d66ed234d315987b8add97364fd9/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/c5b561ff9656b79531665343c52b69b5ff26d66ed234d315987b8add97364fd9/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/6a178c83fcb1a0161b3ed62616eac8ea5442737d2d8259ed6f46e07c03241238/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/21a70e74dbb297ec42d5cc72ab810178b298d12fc8f679c742d2501f7ce5b6a3/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/6a178c83fcb1a0161b3ed62616eac8ea5442737d2d8259ed6f46e07c03241238/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/3abcf1a2f490ee09c9f0bbc0865ccb6c421dd87b9dd79933465df7095ab30940/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/0cbfce1ee17fb64428e643c966464a4c3411180b30c10cb22ff51184a08b5b37/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/3abcf1a2f490ee09c9f0bbc0865ccb6c421dd87b9dd79933465df7095ab30940/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/e2bf9406-8c70-4dda-bb88-5771480d9155/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8>
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D5B898360D00090004BB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D60F98360D00090004BF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/e9612bfd21b5b805074e751d03224dae38f8c4c91a89fd34f1f4007c3978ba91/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C08F81398360D00090003A7> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/c5b561ff9656b79531665343c52b69b5ff26d66ed234d315987b8add97364fd9/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E2EB98360D00090004CB> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/c5b561ff9656b79531665343c52b69b5ff26d66ed234d315987b8add97364fd9/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18E33098360D00090004CD> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C51649DD5BECA00090000CF> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/6a178c83fcb1a0161b3ed62616eac8ea5442737d2d8259ed6f46e07c03241238/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BC742CD98360D0009000354> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/21a70e74dbb297ec42d5cc72ab810178b298d12fc8f679c742d2501f7ce5b6a3/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BAB4BEB98360D00090000F0> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/6a178c83fcb1a0161b3ed62616eac8ea5442737d2d8259ed6f46e07c03241238/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BB22DC298360D000900030B> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/3abcf1a2f490ee09c9f0bbc0865ccb6c421dd87b9dd79933465df7095ab30940/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C091EC598360D0009000403> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/29288f0ca7906536e4eaca09e9a12b258f91c41006fbc490eb6baa38eb958c8c/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C18D7BA98360D00090004C1> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/0cbfce1ee17fb64428e643c966464a4c3411180b30c10cb22ff51184a08b5b37/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C2DB84C9E5B640009000089> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/3abcf1a2f490ee09c9f0bbc0865ccb6c421dd87b9dd79933465df7095ab30940/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5BA2193C98360D00090000DC> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }

  GRAPH <http://mu.semte.ch/graphs/organizations/e2bf9406-8c70-4dda-bb88-5771480d9155/LoketLB-toezichtGebruiker> {
    <http://data.lblod.info/inzendingen-voor-toezicht/5C0F995998360D0009000090> <http://mu.semte.ch/vocabularies/ext/supervision/decisionType> <http://data.lblod.info/DecisionType/02e210746b795a80ec114d09d5f372cd77be01b5f813776e09409c6044d39ef6>
  }
}
