PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# Trick here with the BIND, wihout it it gave a strange indexing error.
DELETE {
  GRAPH ?h {
    ?mandataris ext:startDateDT ?startDateDT ;
      ext:endDateDT ?endDateDT .
  }
}
INSERT {
  GRAPH ?h {
    ?mandataris mandaat:start ?tmpStartDateDT ;
      mandaat:einde ?tmpEndDateDT .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris a mandaat:Mandataris ;
      ext:startDateDT ?startDateDT ;
      ext:endDateDT ?endDateDT .
  }
  BIND(?g as ?h)
  BIND(?startDateDT as ?tmpStartDateDT)
  BIND(?endDateDT as ?tmpEndDateDT)
}
