DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/bd74ee38a4b1e296821a11729c1f704cf439576c7ab2c910c95b067cf183d923/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/geboortes/5C5AD288D5BECA000B00043B> <http://data.vlaanderen.be/ns/persoon#datum> "2001-01-03"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/bd74ee38a4b1e296821a11729c1f704cf439576c7ab2c910c95b067cf183d923/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/geboortes/5C5AD288D5BECA000B00043B> <http://data.vlaanderen.be/ns/persoon#datum> "1960-10-20"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}
