DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode> .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> <http://www.w3.org/2004/02/skos/core#prefLabel> "Intercommunale" .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> <http://www.w3.org/2004/02/skos/core#topConceptOf>	<http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .

    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/0657f97f-3ad2-4f72-a61c-abb10c206249> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode> .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/0657f97f-3ad2-4f72-a61c-abb10c206249> <http://www.w3.org/2004/02/skos/core#prefLabel> "Interlokaal samenwerkingsverband zonder rechtspersoonlijkheid" .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/0657f97f-3ad2-4f72-a61c-abb10c206249> <http://www.w3.org/2004/02/skos/core#topConceptOf>	<http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .

    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/a30f5e3f-7e6a-4352-a9da-57ea46a5e98d> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode> .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/a30f5e3f-7e6a-4352-a9da-57ea46a5e98d> <http://www.w3.org/2004/02/skos/core#prefLabel> "(Intergemeentelijk) Samenwerkingsverband zonder rechtspersoonlijkheid" .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/a30f5e3f-7e6a-4352-a9da-57ea46a5e98d> <http://www.w3.org/2004/02/skos/core#topConceptOf>	<http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .

    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d46b2acb-4763-4532-9aff-fdede39e9520> a <http://mu.semte.ch/vocabularies/ext/BestuurseenheidClassificatieCode> .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d46b2acb-4763-4532-9aff-fdede39e9520> <http://www.w3.org/2004/02/skos/core#prefLabel> "Opdrachthoudende vereniging met private deelname" .
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d46b2acb-4763-4532-9aff-fdede39e9520> <http://www.w3.org/2004/02/skos/core#topConceptOf>	<http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .
  }
}
