PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?provincie.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid;
        skos:prefLabel "Nieuwpoort".
    ?bestuurseenheid ext:inProvincie ?provincie.
    ?provincie rdfs:label "Vlaams-Brabant".
  }
}
