PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
PREFIX nie:     <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ext:     <http://mu.semte.ch/vocabularies/ext/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX pav:  <http://purl.org/pav/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX dct: <http://purl.org/dc/terms/>

####
# link mandataris and lidmaatschap
###
INSERT {
  GRAPH ?eenheidGraph {
    ?mandataris <http://www.w3.org/ns/org#hasMembership> ?lidmaatschap.
    ?lidmaatschap <http://www.w3.org/ns/org#organisation> ?fractie.
   }
}

WHERE {
  ?fractie a mandaat:Fractie.
  ?fractie <http://www.w3.org/ns/org#linkedTo> ?eenheid.
  ?mandataris <http://www.w3.org/ns/org#hasMembership> ?lidmaatschap.
  ?lidmaatschap <http://www.w3.org/ns/org#organisation> ?fractie.
  ?mandataris ext:generatedFrom ext:mandatenExtractorService.

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?eenheid mu:uuid ?eenheidUuid.
  }
  BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-mandaatGebruiker")) AS ?eenheidGraph).

}