PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid skos:prefLabel "Autonoom Gemeentebedrijf Sport Huishout".
  }
}
INSERT  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid skos:prefLabel "Autonoom Gemeentebedrijf Sport Hulshout".
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel "Autonoom Gemeentebedrijf Sport Huishout".
  }
}
