DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/216b8dc9cccfd5a89365a48b391a9c2701b209a893662bb6abb9fe57ad1a9492> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Handeling" .
    <http://data.lblod.info/DecisionType/3d37e79a6bbf092893d62aa3ced229ae1ae1ccde24625a0af1afccce45e989e4> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Kennisgeving van structurele onbestuurbaarheid" .
    <http://data.lblod.info/DecisionType/4cbd555f0de065ec44f5470e1fe56d777706ca112ad45c9f46e3f7d501c9c1d6> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Overig" .
    <http://data.lblod.info/DecisionType/59ca4f3803eb48392ca83534676a98330c5ea5777efe15ea4dab55ef24486e6a> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Goedkeuringstoezicht overheidsopdrachten Voeren" .
    <http://data.lblod.info/DecisionType/74fe03887be874e501f18479e5265b1509b1b43d52419f5284a5c20bc2218339> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit van de gemeenteraad houdende de principiële beslissing tot samenvoeging" .
    <http://data.lblod.info/DecisionType/8080ca54474be408fe1d952f2ec08e8087e0630460d5e5cc0163cac35bda8b7d> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Ontbinding vereniging" .
    <http://data.lblod.info/DecisionType/99f219a6330a3a812a13b3c92ed429fc418a3e4d3e06d13ac9b56724b19ced9b> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit Raad over jaarrekening en uitgavenstaat van Bedrijf" .
    <http://data.lblod.info/DecisionType/b1f2b7391aa9e4a04871186973aff527ab7abbc934eb2a5b53d1ad9d6f3475ad> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit van de gemeenteraad houdende het gezamenlijk voorstel tot samenvoeging" .
    <http://data.lblod.info/DecisionType/c06eef45655936931497bf3d15da47eb83267de6627d6cb4cd9d7841b140af1c> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Standpunt" .
    <http://data.lblod.info/DecisionType/c689378d878f32298e5177db67ba4c70f1c2e4d7848ea0f5368926c8390136e3> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Vraag" .
    <http://data.lblod.info/DecisionType/f8705e39a8af1666261d4e6b64cbb351445c79a690b1f4cd41c74115290485ee> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Klacht" .
    <http://data.lblod.info/DecisionType/cfc9ce299466efd1dfa7a662ecca1c0eb08e113ca4e1848ec93b5a547b987f5f> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit overruling betaling" .
    <http://data.lblod.info/DecisionType/745976e4387055028197a168132d2776b625fff6eb7df85a6791d7fd6154ba19> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Lening ter sanering financiën" .
    <http://data.lblod.info/DecisionType/3f305e68d741ebf3effca57aaca6737c869b358a6e7ecd5d7bc42be617958fc8> a <http://mu.semte.ch/vocabularies/ext/supervision/DecisionType> ; <http://www.w3.org/2004/02/skos/core#prefLabel> "Rechtspositieregeling" .
  }
}
