PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ns1: <http://data.lblod.info/vocabularies/lpdc-ipdc/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lpdcExt: <http://lblod.data.gift/vocabularies/lpdc-ipdc/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX lblodLpdc: <http://data.lblod.info/id/public-services/>
PREFIX lblodIpdcLpdc: <http://lblod.data.gift/vocabularies/lpdc-ipdc/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX lang: <http://publications.europa.eu/resource/authority/language/>
PREFIX lblodOrg: <http://data.lblod.info/id/concept/organisatie/>
PREFIX lblodIpdcThema: <http://data.lblod.info/id/concept/ipdc-thema/>
PREFIX belgif: <http://vocab.belgif.be/ns/publicservice#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ps: <http://vocab.belgif.be/ns/publicservice#>
PREFIX locn: <http://www.w3.org/ns/locn>

DELETE {
   GRAPH ?g {
     ?s ?p ?o.
   }
}
WHERE {
  GRAPH ?g {
    {
      ?s a cpsv:PublicService;
        mu:uuid ?uuid ;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        belgif:hasRequirement ?requirement.

      ?requirement a m8g:Requirement;
        m8g:hasSupportingEvidence ?s.

      ?s a m8g:Evidence;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        belgif:hasRequirement ?s.

      ?s a m8g:Requirement;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        cpsv:follows ?rule.

      ?rule a cpsv:Rule;
        lpdcExt:hasOnlineProcedure ?s.

      ?s a schema:Website;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        cpsv:follows ?s.

      ?s a cpsv:Rule;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        m8g:hasCost ?s.

       ?s a m8g:Cost;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        cpsv:produces ?s.

       ?s a lpdcExt:FinancialAdvantage;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        m8g:hasContactPoint ?s.

       ?s a schema:ContactPoint;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        m8g:hasContactPoint ?contactPoint.
      ?contactPoint a schema:ContactPoint;
        lpdcExt:address ?s.
      ?s a locn:Address;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        lpdcExt:attachment ?s.

       ?s a foaf:Document;
        ?p ?o.
    }
    UNION {
      ?service a cpsv:PublicService;
        mu:uuid ?uuid;
        rdfs:seeAlso ?s.

      ?s a schema:Website;
        ?p ?o.
    }
  }
}