PREFIX dct: <http://purl.org/dc/terms/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
      <http://lblod.data.info/id/subsidie-application-flow-steps/c38d4ab1-17b0-4281-81d7-7bd0001f6053> dct:source <config://forms/e-inclusion/proposal/versions/20220829090000-textual-adjustments/form.ttl>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
      <http://lblod.data.info/id/subsidie-application-flow-steps/c38d4ab1-17b0-4281-81d7-7bd0001f6053> dct:source <config://forms/e-inclusion/proposal/versions/20220904090000-max-validator-component/form.ttl> .                                                         
  }
}