PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20230123123436-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "3243878e-b012-4b1d-9516-e06215e92fc5" ;
      nfo:fileName "20230123123436-forms.ttl" ;
      dct:created "2023-01-23T12:34:36"^^xsd:dateTime ;
      dct:modified "2023-01-23T12:34:36"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "349535"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    