INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure/justification-expropriations-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/justificationExpropriationsUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER(REGEX(STR(?g)), "http://mu.semte.ch/graphs/organizations/.*/LoketLB-subsidies")

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
