PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20230126155111-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "16003315-17ad-43bc-b515-2899b81c3b6b" ;
      nfo:fileName "20230126155111-forms.ttl" ;
      dct:created "2023-01-26T15:51:11"^^xsd:dateTime ;
      dct:modified "2023-01-26T15:51:11"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "353469"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    