PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "ab64b799-fc73-417a-9fde-ad15da02944e" ;
      skos:prefLabel "Viertoren" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0744514689" ;
      dcterms:identifier "OVO036512", "0744514689" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/a192bd4a7552da2ce8f7b6da3764a534>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"a192bd4a7552da2ce8f7b6da3764a534" ;
      skos:prefLabel "Directiecomité Viertoren" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e> .

    <http://data.lblod.info/id/bestuursorganen/e4a5ff53e10a8cae9ccafec80d799cc0>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"e4a5ff53e10a8cae9ccafec80d799cc0" ;
      skos:prefLabel "Raad van bestuur Viertoren" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e> .

    <http://data.lblod.info/id/bestuursorganen/efc83dc6b109480fe5af741da44e4588>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"efc83dc6b109480fe5af741da44e4588" ;
      skos:prefLabel "Bevoegd beslissingsorgaan Viertoren" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e> .

    <http://data.lblod.info/id/bestuursorganen/14d81710612a24a8672003cfe4d9591e>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"14d81710612a24a8672003cfe4d9591e" ;
      skos:prefLabel "Algemene vergadering Viertoren" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e> .

    <http://data.lblod.info/id/bestuursorganen/8533cfd266c38244011d91276c13b526>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"8533cfd266c38244011d91276c13b526" ;
      skos:prefLabel "Leidend Ambtenaar Viertoren" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/4ad3ca9686cb7daae1550a023d1bd09b>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"4ad3ca9686cb7daae1550a023d1bd09b" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/a192bd4a7552da2ce8f7b6da3764a534> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/8c2bbfaf7529d285588c0ada99d726a6>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8c2bbfaf7529d285588c0ada99d726a6" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/e4a5ff53e10a8cae9ccafec80d799cc0> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/0b13f64db9ba74e50def46125546dc20>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"0b13f64db9ba74e50def46125546dc20" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/efc83dc6b109480fe5af741da44e4588> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/9b7ac3a0edde92560146954b54666a09>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"9b7ac3a0edde92560146954b54666a09" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/14d81710612a24a8672003cfe4d9591e> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/382b2aa66000775ab1c1d22d5b10fdf4>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"382b2aa66000775ab1c1d22d5b10fdf4" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/8533cfd266c38244011d91276c13b526> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
