PREFIX email: <http://mu.semte.ch/vocabularies/ext/email/>
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
PREFIX toezichtReport: <http://mu.semte.ch/vocabularies/ext/supervision/reporting/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX validation: <http://mu.semte.ch/vocabularies/validation/>
PREFIX bbcdr: <http://mu.semte.ch/vocabularies/ext/bbcdr/>
PREFIX export: <http://mu.semte.ch/vocabularies/ext/export/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX schema: <http://schema.org/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX pav: <http://purl.org/pav/>
PREFIX nao: <http://www.semanticdesktop.org/ontologies/2007/08/15/nao#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX regorg: <https://www.w3.org/ns/regorg#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX lblod: <http://data.lblod.info/vocabularies/lblod/>
PREFIX generiek: <http://data.vlaanderen.be/ns/generiek#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX tmp: <http://mu.semte.ch/vocabularies/tmp/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX rm: <http://mu.semte.ch/vocabularies/logical-delete/>
PREFIX typedLiterals: <http://mu.semte.ch/vocabularies/typed-literals/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX app: <http://mu.semte.ch/app/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


#########################################################
# GEMEENTEBESTUUR
########################################################
# algemeen directeur
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/45dff078-95f3-4b5f-a475-aa9dd857ae0a>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "ab977fe2-f3ff-4945-b2cf-af00acd8586c", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

# adjunct algemeen directeur
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/783917b6-89ca-4ab2-8656-9ca960061ab1>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "deb8380d-2362-41e1-9e4f-38afd1a4e76d", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

# financieel directeur
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/f0bf6754-e5e2-479c-824f-865cbca19241>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "77ec3d21-fbed-4e43-b9a1-79b78962ea7e", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

# financieel directeur
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/1dd348cd-ce46-4aa3-8ad1-16a6e35dc81a>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "16dc0d44-1b62-4304-9920-cf2f1fc068a7", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

#########################################################
# AGB
########################################################
# leidend ambtenaar
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/9ece500e-ed34-4e8b-8c77-40fa68c1c240>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "dcea860a-76db-4cb6-974c-c20aa5db8005", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

#########################################################
# INTERCOMMUNALE
########################################################
# leidend ambtenaar
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/9ece500e-ed34-4e8b-8c77-40fa68c1c240>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "8809643c-d774-4aad-9109-2c48cc957cc6", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

#########################################################
# OCMWV
########################################################
# leidend ambtenaar
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/9ece500e-ed34-4e8b-8c77-40fa68c1c240>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "512ba5f2-2307-4870-9548-e36d1761c0d1", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

#########################################################
# Provincie
########################################################
# griffier
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/ae519a4c-0bb7-4278-91a8-a09967ef535b>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "06bc5a74-9b0c-43c9-9528-3676654d8a7b", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

# financieel beheerder
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/cb447355-f7c1-4406-88aa-081d529ad2d5>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "05c73e98-4a6e-42de-b297-4c8fcd153892", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;

#########################################################
# Autonoom provinciebedrijf
########################################################
# leidend ambtenaar
INSERT {

  GRAPH ?eenheidGraph {

    ?pUri a org:Post;
      mu:uuid ?pUuid;
      org:role <http://data.vlaanderen.be/id/concept/functionarisRol/9ece500e-ed34-4e8b-8c77-40fa68c1c240>.

    ?eenheid org:hasPost ?pUri.

  }

}
 WHERE {
 ?eenheid a besluit:Bestuurseenheid;
   mu:uuid ?eenheidUuid;
   besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>.

   #hack
   BIND(SHA256(CONCAT(STR(?eenheid), "287febed-2ff8-4fa5-a603-619342256686", STR(RAND()), STRUUID())) as ?pUuid).

   BIND(IRI(CONCAT("http://data.lblod.info/id/positie/", STR(?pUuid))) AS ?pUri).
   BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?eenheidUuid),"/LoketLB-leidinggevendenGebruiker")) AS ?eenheidGraph).

}

;