###############################################
# Removes old organisation data
###############################################
DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?src ?refers ?s.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/org#Site>.
    ?s ?p ?o.
    OPTIONAL { ?src ?refers ?s }
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?src ?refers ?s.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://schema.org/PostalAddress>.
    ?s ?p ?o.
    OPTIONAL { ?src ?refers ?s }
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?src ?refers ?s.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/org#Post>.
    ?s ?p ?o.
    OPTIONAL { ?src ?refers ?s }
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?src ?refers ?s.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/org#Role>.
    ?s ?p ?o.
    OPTIONAL { ?src ?refers ?s }
  }
}
