PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://data.lblod.info/id/criterions/ece5bfcf-2c3f-401a-8176-0dac66ecbdad>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "ece5bfcf-2c3f-401a-8176-0dac66ecbdad" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep OCMW verenigingen" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/e7e604fc-a3e7-4474-9edf-fb71b12c56b7> .

    <http://data.lblod.info/id/requirement-groups/e7e604fc-a3e7-4474-9edf-fb71b12c56b7>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "e7e604fc-a3e7-4474-9edf-fb71b12c56b7" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een OCMW vereniging." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/6af17b61-e9c0-4c34-ab22-df5dab0800b4> .

    <http://data.lblod.info/id/criterion-requirement/6af17b61-e9c0-4c34-ab22-df5dab0800b4>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "6af17b61-e9c0-4c34-ab22-df5dab0800b4" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode OCMW vereniging." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089> .
  
  }
}