PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    <http://data.lblod.info/id/criterions/be6b5c33-f4f0-45bc-b7ae-d8aa9c214843>
      a <http://data.europa.eu/m8g/Criterion> ;
      mu:uuid "be6b5c33-f4f0-45bc-b7ae-d8aa9c214843" ;
      <http://purl.org/dc/terms/title> "Subsidiemaatregelaanbod: doelgroep welzijnsverenigingen" ;
      <http://data.europa.eu/m8g/fulfilledByRequirementGroup> <http://data.lblod.info/id/requirement-groups/506f93e9-3858-4648-b52f-dda5d3d8dc14> .

    <http://data.lblod.info/id/requirement-groups/506f93e9-3858-4648-b52f-dda5d3d8dc14>
      a <http://data.europa.eu/m8g/RequirementGroup> ;
      mu:uuid "506f93e9-3858-4648-b52f-dda5d3d8dc14" ;
      <http://purl.org/dc/terms/description> "Criteriumgroep: het bestuur moet voldoen aan de vereisten van een welzijnsvereniging." ;
      <http://data.europa.eu/m8g/hasCriterionRequirement> <http://data.lblod.info/id/criterion-requirement/a7d506c4-18c2-43cf-b2b1-e4bc5bd774b8> .

    <http://data.lblod.info/id/criterion-requirement/a7d506c4-18c2-43cf-b2b1-e4bc5bd774b8>
     a <http://data.europa.eu/m8g/CriterionRequirement> ;
     mu:uuid "a7d506c4-18c2-43cf-b2b1-e4bc5bd774b8" ;
     <http://purl.org/dc/terms/description> "Criteriumvereiste: het bestuur heeft classificatiecode welzijnsvereniging." ;
     lblodSubsidie:isSatisfiableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/e8294b73-87c9-4fa2-9441-1937350763c9> .
  }
}