INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    #Gemeenten zonder Gemeentehuis
    <http://lblod.data.info/id/subsidy-measure-offers/8379a4ea-fd83-47cc-89fa-1a72ee4fbaff> <http://data.europa.eu/m8g/hasCriterion>
      <http://data.lblod.info/id/criterions/be6b5c33-f4f0-45bc-b7ae-d8aa9c214843> . #Welzijnsvereniging
  }
}