PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20230928173137-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "37dc800e-2656-4c93-b414-56ee83df0cff" ;
      nfo:fileName "20230928173137-forms.ttl" ;
      dct:created "2023-09-28T17:31:37"^^xsd:dateTime ;
      dct:modified "2023-09-28T17:31:37"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "366831"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    