PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20231109110155-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "d2a48950-33e0-4167-83d5-e29e5c3dd8f7" ;
      nfo:fileName "20231109110155-forms.ttl" ;
      dct:created "2023-11-09T11:01:55"^^xsd:dateTime ;
      dct:modified "2023-11-09T11:01:55"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "376058"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    