PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH ?g {
     ?orgaan mandaat:isTijdspecialisatieVan ?bestuursorgaan .
  }

}
INSERT {
  GRAPH ?g {
     ?orgaan ext:isTijdspecialisatieVan ?bestuursorgaan .
  }
}
WHERE {
  GRAPH ?g {
    ?orgaan mandaat:isTijdspecialisatieVan ?bestuursorgaan;
     mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}