PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>

DELETE {
  GRAPH ?g {
  ?s ?p ?o.
  }
}

WHERE {
  GRAPH ?g {

    ?s a  ?type.
    FILTER (?type IN (ext:FormInput, ext:FormNode, ext:DynamicSubform, ext:FormSolution,
                      toezicht:TaxRate, toezicht:DecisionType, toezicht:InzendingType,
                      toezicht:DocumentAuthenticityType, toezicht:AccountAcceptanceStatus, toezicht:DeliveryReportType,
                      toezicht:FiscalPeriod, toezicht:Nomenclature, toezicht:TaxType, toezicht:InzendingVoorToezicht ) ).
    ?s ?p ?o.
 }
}