PREFIX schema: <http://schema.org/> 

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/71fa6cff-5215-408b-b8e0-b518245f3a2f> schema:url ?url .
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/71fa6cff-5215-408b-b8e0-b518245f3a2f> schema:url <http://www.ledegem.be> .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/71fa6cff-5215-408b-b8e0-b518245f3a2f> a schema:PostalAddress ;
      schema:url ?url .
  }
}

;

DELETE WHERE {
  GRAPH ?g { # Poperinge
    <http://data.lblod.info/id/contactpunt/59ca1beb-4bd8-48b6-814f-842e81aeb204> <http://schema.org/url> ?url 
  }
}

;

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/5c59a610-2b97-481f-b325-3716ca9b9f1d> schema:url ?url .
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/5c59a610-2b97-481f-b325-3716ca9b9f1d> schema:url <http://www.dilsen-stokkem.be> .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/contactpunt/5c59a610-2b97-481f-b325-3716ca9b9f1d> a schema:PostalAddress ;
      schema:url ?url .
  }
}

