INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/mailboxes/1> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Mailbox>;
       <http://mu.semte.ch/vocabularies/core/uuid> "cf9cb7e4-9a00-4855-9ee0-e8e3bbeba9e9";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/fni#hasPart> <http://data.lblod.info/id/mail-folders/1>;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/fni#hasPart> <http://data.lblod.info/id/mail-folders/2>;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/fni#hasPart> <http://data.lblod.info/id/mail-folders/3>.

    <http://data.lblod.info/id/mail-folders/1> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder>;
       <http://mu.semte.ch/vocabularies/core/uuid> "891c67e5-4719-47f8-aec2-d898ba2c09e8";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#title> "inbox";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#description> "Your incoming mail goes here.";
       <http://mu.semte.ch/vocabularies/ext/email/hasEmail> <http://data.lblod.info/id/emails/2>.

    <http://data.lblod.info/id/mail-folders/2> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder>;
       <http://mu.semte.ch/vocabularies/core/uuid> "786a8cb0-4452-40f5-b8d8-046dd2d63281";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#title> "outbox";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#description> "Your outgoing mail goes here.".

    <http://data.lblod.info/id/mail-folders/3> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder>;
       <http://mu.semte.ch/vocabularies/core/uuid> "a6fb03f9-11be-4401-9d8f-b4dc0e9df5ee";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#title> "sentbox";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#description> "Your sent mail goes here.";
       <http://mu.semte.ch/vocabularies/ext/email/hasEmail> <http://data.lblod.info/id/emails/1>;
       <http://mu.semte.ch/vocabularies/ext/email/hasEmail> <http://data.lblod.info/id/emails/3>.

    <http://data.lblod.info/id/emails/1> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>;
       <http://mu.semte.ch/vocabularies/core/uuid> "99d1d631-0d58-4d84-a189-38b60ef8b6fd";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageId> "326a7e87-a24d-4e29-8135-e685d41cd5bb@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageFrom> "a@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailTo> "b@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailCc> "";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageSubject> "Notificatie: nieuw bericht";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#plainTextMessageContent> "Hey,\n\nJe hebt een nieuw bericht!\n\nGrts,\n\nMe";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isRead> "false"^^xsd:boolean;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#sentDate> "2018-12-06T09:05:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#receivedDate> "2018-12-06T09:10:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isPartOf> <http://data.lblod.info/id/mail-folders/3>.

    <http://data.lblod.info/id/emails/2> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>;
       <http://mu.semte.ch/vocabularies/core/uuid> "0cad72fd-4f21-4ea7-af8c-88d24577ee56";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageId> "5f2fb1f7-e16b-4d69-b5d3-e2daff18b2c1@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageFrom> "b@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailTo> "a@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailCc> "";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageSubject> "Notificatie: nieuw bericht";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#plainTextMessageContent> "Ah, Echt waar?\n\nGrts,\n\nMe";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isRead> "false"^^xsd:boolean;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#sentDate> "2018-12-07T09:05:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#receivedDate> "2018-12-07T09:10:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#inReplyTo> <http://data.lblod.info/id/emails/1>;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isPartOf> <http://data.lblod.info/id/mail-folders/1>.

    <http://data.lblod.info/id/emails/3> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>;
       <http://mu.semte.ch/vocabularies/core/uuid> "42c5d492-9951-4bdb-8704-a4ac74739be4";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageId> "717e3184-ba1d-4efa-a395-c7b386970201@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageFrom> "a@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailTo> "b@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailCc> "";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageSubject> "Notificatie: nieuw bericht";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#plainTextMessageContent> "Jep!\n\nGrts,\n\nMe";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isRead> "false"^^xsd:boolean;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#sentDate> "2018-12-08T09:05:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#receivedDate> "2018-12-08T09:10:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#inReplyTo> <http://data.lblod.info/id/emails/2>;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isPartOf> <http://data.lblod.info/id/mail-folders/3>.
       
    <http://data.lblod.info/id/emails/4> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>;
       <http://mu.semte.ch/vocabularies/core/uuid> "9234286c-db7a-49a3-b7a5-46aab0e6f1a7";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageId> "19f5b61b-131c-4d84-90f8-b68968f615f6@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageFrom> "a@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailTo> "b@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailCc> "";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageSubject> "Notificatie: nieuw bericht";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#plainTextMessageContent> "Have a merry Christmas ...";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isRead> "false"^^xsd:boolean;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#sentDate> "2018-12-10T09:05:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#receivedDate> "2018-12-10T09:10:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isPartOf> <http://data.lblod.info/id/mail-folders/2>.
       
    <http://data.lblod.info/id/emails/5> a <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#Email>;
       <http://mu.semte.ch/vocabularies/core/uuid> "d5dfb6c9-48b1-4820-8e5b-f2ebd5a65d4b";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageId> "124e6d24-09f0-46ba-b470-3bd5c7bff90d@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageFrom> "a@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailTo> "b@test.be";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#emailCc> "";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#messageSubject> "Notificatie: nieuw bericht";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#plainTextMessageContent> "... and a happy new year!";
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isRead> "false"^^xsd:boolean;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#sentDate> "2018-12-10T09:05:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#receivedDate> "2018-12-10T09:10:00"^^xsd:dateTime;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#inReplyTo> <http://data.lblod.info/id/emails/4>;
       <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#isPartOf> <http://data.lblod.info/id/mail-folders/2>.

  }
}
