DELETE {
  GRAPH <http://mu.semte.ch/application> {
   ?bestuurseenheid <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?werkingsgebied .
 }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
   ?bestuurseenheid <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?werkingsgebied .
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/application> {
   ?bestuurseenheid <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?werkingsgebied .
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/application> {
   ?werkingsgebied a <http://www.w3.org/ns/prov#Location> ;
     ?p ?o .
 }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
   ?werkingsgebied a <http://www.w3.org/ns/prov#Location> ;
     ?p ?o .
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/application> {
   ?werkingsgebied a <http://www.w3.org/ns/prov#Location> ;
     ?p ?o .
  }
}
