PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX org:     <http://www.w3.org/ns/org#>
WITH <http://mu.semte.ch/application>
INSERT {
?eenheid org:hasPost <http://data.lblod.info/id/positie/ce33791d-c816-4467-88bd-a8ad849cc1e1>.
?eenheid org:hasPost <http://data.lblod.info/id/positie/476fe2de-97ba-41c0-ad2c-1aa5b2295809>.
?eenheid org:hasPost <http://data.lblod.info/id/positie/242aff2f-a587-4fae-945c-1e333d34adbf>.
?eenheid org:hasPost <http://data.lblod.info/id/positie/2137188c-d783-4bd8-aa40-4c05405d30b2>.
?eenheid org:hasPrimarySite  <http://data.lblod.info/id/vestiging/2cc11f2f-ec27-4e35-bd78-538e8d3b5b6c>.
?eenheid org:linkedTo <http://data.lblod.info/id/organisatie/dfbe1e2b-eae2-4b30-b7e1-de5a0c58c985>.
}
WHERE {
?eenheid a besluit:Bestuurseenheid;
         besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>;
         besluit:werkingsgebied/rdfs:label "Gent".
}