PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT {
  GRAPH ?graph {
    ?s a toezicht:InzendingVoorToezicht ;
       dct:subject ?bestuurseenheid ;
       ?p ?o .
 
   ?s toezicht:taxRate ?tax .
   ?tax ?taxP ?taxO .

   ?solution toezicht:hasInzendingVoorToezicht ?s .
   ?solution ?solutionP ?solutionO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a toezicht:InzendingVoorToezicht ;
       dct:subject ?bestuurseenheid ;
       ?p ?o .
    ?bestuurseenheid mu:uuid ?groupId .

    OPTIONAL {
      ?s toezicht:taxRate ?tax .
      ?tax ?taxP ?taxO .
    }

    OPTIONAL {
      ?solution toezicht:hasInzendingVoorToezicht ?s .
      ?solution ?solutionP ?solutionO .
    }

  }
  BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-toezichtGebruiker")) as ?graph)
}

;

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a toezicht:InzendingVoorToezicht ;
       ?p ?o .

    OPTIONAL {
      ?s toezicht:taxRate ?tax .
      ?tax ?taxP ?taxO .
    }

    OPTIONAL {
      ?solution toezicht:hasInzendingVoorToezicht ?s .
      ?solution ?solutionP ?solutionO .
    }
  }
}


