PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX bbcdr: <http://mu.semte.ch/vocabularies/ext/bbcdr/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX schema: <http://schema.org/>
PREFIX person: <http://www.w3.org/ns/person#>

INSERT {
  GRAPH ?graph {
    ?bestuurseenheid org:linkedTo ?politiezone .
    ?politiezone ?politiezoneP ?politiezoneO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     mu:uuid ?groupId .

    BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-mandaatGebruiker")) as ?graph)

    ?bestuurseenheid org:linkedTo ?politiezone .
    ?politiezone ?politiezoneP ?politiezoneO .
  }
}

;

INSERT {
  GRAPH ?graph {
    ?bestuurseenheid org:hasPrimarySite ?vestiging .
    ?vestiging ?vestigingP ?vestigingO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     mu:uuid ?groupId .

    BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-mandaatGebruiker")) as ?graph)

    ?bestuurseenheid org:hasPrimarySite ?vestiging .
    ?vestiging ?vestigingP ?vestigingO .
  }
}

;

INSERT {
  GRAPH ?graph {
    ?bestuurseenheid org:hasPost ?positie .
    ?positie ?positieP ?positieO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     mu:uuid ?groupId .

    BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-mandaatGebruiker")) as ?graph)

    ?bestuurseenheid org:hasPost ?positie .
    ?positie ?positieP ?positieO .
  }
}

;

INSERT {
  GRAPH ?graph {
    ?bestuurseenheid schema:contactPoint ?contactPunt .
    ?contactPunt ?contactPuntP ?contactPuntO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
                     mu:uuid ?groupId .

    BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-mandaatGebruiker")) as ?graph)

    ?bestuurseenheid schema:contactPoint ?contactPunt .
    ?contactPunt ?contactPuntP ?contactPuntO .
  }
}

;

INSERT {
  GRAPH ?g {
    ?politiezone org:hasPrimarySite ?pzVestiging .
    ?pzVestiging ?pzVestigingP ?pzVestigingO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 

    ?politiezone a org:Organization .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?politiezone org:hasPrimarySite ?pzVestiging .
    ?pzVestiging ?pzVestigingP ?pzVestigingO .
  }  
}

;

INSERT {
  GRAPH ?g {
    ?politiezone schema:contactPoint ?pzContactpunt .
    ?pzContactpunt ?pzContactpuntP ?pzContactpuntO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 

    ?politiezone a org:Organization .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?politiezone schema:contactPoint ?pzContactpunt .
    ?pzContactpunt ?pzContactpuntP ?pzContactpuntO .
  }  
}

;

INSERT {
  GRAPH ?g {
    ?vestiging schema:contactPoint ?vestContactpunt .
    ?vestContactpunt ?vestContactpuntP ?vestContactpuntO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 

    ?vestiging a org:Site .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?vestiging schema:contactPoint ?vestContactpunt .
    ?vestContactpunt ?vestContactpuntP ?vestContactpuntO .
  }  
}

;

INSERT {
  GRAPH ?g {
    ?politiezone org:hasPost ?pzPositie .
    ?pzPositie ?pzPositieP ?pzPositieO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 

    ?politiezone a org:Organization .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?politiezone org:hasPost ?pzPositie .
    ?pzPositie ?pzPositieP ?pzPositieO .
  }  
}
