PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX bbcdr: <http://mu.semte.ch/vocabularies/ext/bbcdr/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX schema: <http://schema.org/>
PREFIX person: <http://www.w3.org/ns/person#>

INSERT {
  GRAPH ?graph {
    ?persoon ?persoonP ?persoonO .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?persoon ?persoonP ?persoonO .
    ?lijst mandaat:heeftKandidaat ?persoon.
    ?lijst mandaat:behoortTot/mandaat:steltSamen ?bestuursorgaanInTijd.
  }
  GRAPH ?g {
    ?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan .
    ?bestuursorgaan besluit:bestuurt ?bestuurseenheid .
    ?bestuurseenheid mu:uuid ?groupId .
 }
 BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "/LoketLB-mandaatGebruiker")) as ?graph)
  }
}

;

INSERT {
  GRAPH ?g {
    ?geboorte ?geboorteP ?geboorteO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 
    ?persoon a person:Person .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?persoon persoon:heeftGeboorte ?geboorte .
  }
  ?geboorte ?geboorteP ?geboorteO .
  }
}

;

INSERT {
  GRAPH ?g {
    ?identificator ?identificatorP ?identificatorO .
  }
} WHERE {
  GRAPH ?g {
    FILTER(STRENDS(STR(?g), "/LoketLB-mandaatGebruiker")) 
    ?persoon a person:Person .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?persoon adms:identifier ?identificator .
    ?identificator ?identificatorP ?identificatorO .
  }
}

;


DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a ?type ;
       ?p ?o .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a ?type ;
       ?p ?o .
  }

  VALUES ?type {
    <http://data.vlaanderen.be/ns/persoon#Geboorte>
    <http://www.w3.org/ns/person#Person>
    <http://www.w3.org/ns/adms#Identifier>
  }
}

;
