PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX bbcdr: <http://mu.semte.ch/vocabularies/ext/bbcdr/>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT {
  GRAPH ?graph {
    ?s a bbcdr:Report ;
       dct:subject ?bestuurseenheid ;
       ?p ?o .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a bbcdr:Report ;
       dct:subject ?bestuurseenheid ;
       ?p ?o .
    ?bestuurseenheid mu:uuid ?groupId .
  }
  BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", ?groupId, "LoketLB-mandaatGebruiker")) as ?graph)
}

;

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a bbcdr:Report ;
       ?p ?o .
  }
}

