WITH <http://mu.semte.ch/application>
DELETE {
  ?person ?pp ?po.
  ?account ?ap ?ao.
}
WHERE {
  ?person a <http://xmlns.com/foaf/0.1/Person>;
  ?pp ?po;
  <http://xmlns.com/foaf/0.1/account> ?account.
  ?account ?ap ?ao;
  ?account <http://xmlns.com/foaf/0.1/accountServiceHomepage> <https://github.com/lblod/mock-login-service>.
}