PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> a besluit:Bestuurseenheid ;
       mu:uuid "ec044510-9e82-4b07-b135-39877ed2dde8" ;
       skos:prefLabel "Intergas" ;
       dcterms:identifier "0249598618" ;
       ext:kbonummer "0249598618" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000004> ;
       besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/6bc83ffdb2f695736e65a59b48f285ce7d1d3ee004271d83221255493b4a36b5> .

   <http://data.lblod.info/id/bestuursorganen/f219f954-9bb2-465d-b0d1-7be3c072f588> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "f219f954-9bb2-465d-b0d1-7be3c072f588" ;
       skos:prefLabel "Algemene vergadering Intergas" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> .

   <http://data.lblod.info/id/bestuursorganen/9cdae787-fbca-4b62-980f-bed5656907cd> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/f219f954-9bb2-465d-b0d1-7be3c072f588> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "9cdae787-fbca-4b62-980f-bed5656907cd" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .

   <http://data.lblod.info/id/bestuursorganen/c9e47da8-669c-4118-b225-9bd4be8db8ab> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "c9e47da8-669c-4118-b225-9bd4be8db8ab" ;
       skos:prefLabel "Directiecomité Intergas" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> .

   <http://data.lblod.info/id/bestuursorganen/b072351c-2191-470b-a774-91b3bceb0ac0> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/c9e47da8-669c-4118-b225-9bd4be8db8ab> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "b072351c-2191-470b-a774-91b3bceb0ac0" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .

   <http://data.lblod.info/id/bestuursorganen/835ec48f-cc2b-4996-be1e-313f4840c65a> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "835ec48f-cc2b-4996-be1e-313f4840c65a" ;
       skos:prefLabel "Regionaal bestuurscomité Intergas" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/17e76b36-64a1-4db1-8927-def3064b4bf1> .

   <http://data.lblod.info/id/bestuursorganen/25198ceb-7ae4-4e35-bb80-cfd1728e7fec> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/835ec48f-cc2b-4996-be1e-313f4840c65a> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "25198ceb-7ae4-4e35-bb80-cfd1728e7fec" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .

   <http://data.lblod.info/id/bestuursorganen/8e8d066a-f096-48c3-89b4-ef9500df7045> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "8e8d066a-f096-48c3-89b4-ef9500df7045" ;
       skos:prefLabel "Raad van bestuur Intergas" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> .

   <http://data.lblod.info/id/bestuursorganen/ee159f3d-04aa-47ee-8462-1d3b3eca987d> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/8e8d066a-f096-48c3-89b4-ef9500df7045> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "ee159f3d-04aa-47ee-8462-1d3b3eca987d" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

INSERT {
  GRAPH ?g {
     ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> ;
           foaf:account ?account.
     ?account a foaf:OnlineAccount;
           mu:uuid ?uuidAccount;
           foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
           ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker". 
  }
} WHERE {
     <http://data.lblod.info/id/bestuurseenheden/ec044510-9e82-4b07-b135-39877ed2dde8> a besluit:Bestuurseenheid;
     skos:prefLabel ?naam;
     besluit:classificatie/skos:prefLabel ?classificatie.
     BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
     BIND(MD5(?volledigeNaam) as ?uuidPersoon)
     BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
     BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
     BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

     VALUES ?g {
        <http://mu.semte.ch/graphs/organizations/ec044510-9e82-4b07-b135-39877ed2dde8> 
        <http://mu.semte.ch/graphs/public> 
     } 
}
