PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/application> {
    <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> a besluit:Bestuurseenheid ;
       mu:uuid "141d9d6b-54af-4d17-b313-8d1c30bc3f5b" ;
       skos:prefLabel "Agentschap Binnenlands Bestuur" ;
       dcterms:identifier "OVO001835" .
  }
}
