INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913/LoketLB-berichtenGebruiker> {
    <http://data.lblod.info/id/conversaties/1> a <http://schema.org/Conversation>;
       <http://mu.semte.ch/vocabularies/core/uuid> "76e84155-89a3-4965-8576-a34a61969d2d";
       <http://schema.org/identifier> "2018.00301";
       <http://schema.org/about> "Meerjarenplanwijziging 2014-2018";
       <http://purl.org/dc/terms/type> "Opvraging in kader van een toezichtsdossier";
       <http://schema.org/processingTime> "P30D";
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/1>;
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/2>;
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/3>;
       <http://mu.semte.ch/vocabularies/ext/lastMessage> <http://data.lblod.info/id/berichten/3>.

    <http://data.lblod.info/id/berichten/1> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "2d0ffd49-b2f9-42c5-bcdc-f1426d9fbcf6";
       <http://schema.org/dateSent> "2018-12-06T09:00:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-06T09:00:00"^^xsd:dateTime;
       <http://schema.org/text> "Knock knock";
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.

    <http://data.lblod.info/id/berichten/2> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "546ab178-94c8-4479-b92e-771fb42c6aef";
       <http://schema.org/dateSent> "2018-12-06T09:05:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-06T09:05:00"^^xsd:dateTime;
       <http://schema.org/text> "Who's there?";
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.

    <http://data.lblod.info/id/berichten/3> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "979baa08-306d-45a7-83a1-6235787ef8de";
       <http://schema.org/dateSent> "2018-12-06T09:10:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-06T09:10:00"^^xsd:dateTime;
       <http://schema.org/text> "It's me";
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.

    <http://data.lblod.info/id/conversaties/2> a <http://schema.org/Conversation>;
       <http://mu.semte.ch/vocabularies/core/uuid> "6bcb9330-b669-47cd-8fd3-dda6e8f5e8b4";
       <http://schema.org/identifier> "2018.00504";
       <http://schema.org/about> "Is dat wel juist?";
       <http://purl.org/dc/terms/type> "Kennisname aan bestuur";
       <http://schema.org/processingTime> "P30D";
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/4>;
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/5>;
       <http://schema.org/hasPart> <http://data.lblod.info/id/berichten/6>;
       <http://mu.semte.ch/vocabularies/ext/lastMessage> <http://data.lblod.info/id/berichten/6>.

    <http://data.lblod.info/id/berichten/4> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "c53986e9-2d53-455d-b45d-6a6a5e67ed18";
       <http://schema.org/dateSent> "2018-12-07T09:00:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-07T09:00:00"^^xsd:dateTime;
       <http://schema.org/text> "Knock knock 2";
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.

    <http://data.lblod.info/id/berichten/5> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "12a16740-ce98-45d5-83a5-3ffeebd5770b";
       <http://schema.org/dateSent> "2018-12-07T09:05:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-07T09:05:00"^^xsd:dateTime;
       <http://schema.org/text> "Who's there? 2";
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.

    <http://data.lblod.info/id/berichten/6> a <http://schema.org/Message>;
       <http://mu.semte.ch/vocabularies/core/uuid> "f4ff8ff9-42eb-4268-a94c-2c813e8bdb1a";
       <http://schema.org/dateSent> "2018-12-07T09:10:00"^^xsd:dateTime;
       <http://schema.org/dateReceived> "2018-12-07T09:10:00"^^xsd:dateTime;
       <http://schema.org/text> "It's me 2";
       <http://schema.org/sender> <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b>;
       <http://schema.org/recipient> <http://data.lblod.info/id/bestuurseenheden/aa368412c2a6d17d41b78030f2914211a77e5cda29c673afc49bf4ac655bc913>.
  }
}
