PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/251143c6-2094-4ad5-8b54-26cfded0082a> a besluit:Bestuurseenheid ;
       mu:uuid "251143c6-2094-4ad5-8b54-26cfded0082a" ;
       skos:prefLabel "Autonome Verzorginstelling Henri Serruysziekenhuis" ;
       dcterms:identifier "0473908049" ;
       ext:kbonummer "0212216402" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cc4e2d67-603b-4784-9b61-e50bac1ec089> .

   <http://data.lblod.info/id/bestuursorganen/486dc6e5-d230-4eec-88d5-4e9da825f827> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/251143c6-2094-4ad5-8b54-26cfded0082a> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "486dc6e5-d230-4eec-88d5-4e9da825f827" ;
       skos:prefLabel "Raad van bestuur Autonome Verzorginstelling Henri Serruysziekenhuis" ;
       besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> .

   <http://data.lblod.info/id/bestuursorganen/1e24ced5-7d5e-45e6-940d-ed3e342c681e> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/486dc6e5-d230-4eec-88d5-4e9da825f827> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "1e24ced5-7d5e-45e6-940d-ed3e342c681e" ;
       mandaat:bindingStart "1971-11-03"^^<http://www.w3.org/2001/XMLSchema#date>
  }
}

;

INSERT {
  GRAPH ?g {
     ?persoon a foaf:Person;
           mu:uuid ?uuidPersoon;
           foaf:firstName ?classificatie;
           foaf:familyName ?naam;
           foaf:member <http://data.lblod.info/id/bestuurseenheden/251143c6-2094-4ad5-8b54-26cfded0082a> ;
           foaf:account ?account.
     ?account a foaf:OnlineAccount;
           mu:uuid ?uuidAccount;
           foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
           ext:sessionRole "LoketLB-toezichtGebruiker", "LoketLB-bbcdrGebruiker", "LoketLB-mandaatGebruiker". 
  }
} WHERE {
     <http://data.lblod.info/id/bestuurseenheden/251143c6-2094-4ad5-8b54-26cfded0082a> a besluit:Bestuurseenheid;
     skos:prefLabel ?naam;
     besluit:classificatie/skos:prefLabel ?classificatie.
     BIND(CONCAT(?classificatie, " ", ?naam) as ?volledigeNaam)
     BIND(MD5(?volledigeNaam) as ?uuidPersoon)
     BIND(MD5(CONCAT(?volledigeNaam,"ACCOUNT")) as ?uuidAccount)
     BIND(IRI(CONCAT("http://data.lblod.info/id/persoon/", ?uuidPersoon)) AS ?persoon)
     BIND(IRI(CONCAT("http://data.lblod.info/id/account/", ?uuidAccount)) AS ?account)

     VALUES ?g {
        <http://mu.semte.ch/graphs/organizations/251143c6-2094-4ad5-8b54-26cfded0082a> 
        <http://mu.semte.ch/graphs/public> 
     } 
}
