PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX toezicht: <http://mu.semte.ch/vocabularies/ext/supervision/>

DELETE {
  GRAPH ?g {
  ?s ?p ?o.
  }
}

WHERE {
  GRAPH ?g {

    ?s a  ?type.
    FILTER (?type IN (toezicht:DecisionType ) ).
    ?s ?p ?o.
 }
}