PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# Deletes the end dates and format them to a new temporary property
DELETE {
  GRAPH ?g {
    ?mandataris mandaat:einde ?endDate .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris ext:endDateDT ?endDateDT .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris a mandaat:Mandataris ;
      mandaat:einde ?endDate .
    BIND (if(regex(str(?endDate), '\\d{4}-\\d\\d-\\d\\d'), xsd:dateTime(?endDate), ?endDate) AS ?endDateDT)
  }
}
