PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# New bestuurseenheden (fusiegemeentes) don't have provincies attached (by ext:inProvincie), attach them (making sure not to create doubles)
# Attach ext:inProvincie to the werkingsgebieden of aforementioned bestuurseenheden as well (making sure not to create doubles)
DELETE  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?provincie.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?provincie.
  }
  VALUES ?bestuurseenheid {
    <http://data.lblod.info/id/bestuurseenheden/d93451bf-e89a-4528-80f3-f0a1c19361a8>     # Gemeente Deinze
    <http://data.lblod.info/id/bestuurseenheden/a4fd24f3-cc6d-4ea5-91c7-efa02d3b970f>     # OCMW Deinze
    <http://data.lblod.info/id/bestuurseenheden/5116efa8-e96e-46a2-aba6-c077e9056a96>     # Gemeente Aalter
    <http://data.lblod.info/id/bestuurseenheden/f73c7109-06a0-45d7-b558-879d87ca3553>     # OCMW Aalter
    <http://data.lblod.info/id/bestuurseenheden/57b1646f-bf4c-4dc4-8bc9-6ec8a6486018>     # Gemeente Lievegem
    <http://data.lblod.info/id/bestuurseenheden/120d2462-0e97-4636-b8dd-78edc4b2ba14>     # OCMW Lievegem
    <http://data.lblod.info/id/bestuurseenheden/c8f33e80-6f19-4ba1-a758-9d85f42d28d4>     # Gemeente Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/a25044d6-d9f9-496e-9061-b0c858dda944>     # OCMW Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/47857958-7d00-47e0-ae83-00d914eca93f>     # Gemeente Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/13b25c80-8d3a-4821-95b0-ffc4e850cb4b>     # OCMW Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4>     # Gemeente Kruisem
    <http://data.lblod.info/id/bestuurseenheden/d26e802b-cae8-4c52-bad6-39e349d46862>     # OCMW Kruisem
    <http://data.lblod.info/id/bestuurseenheden/8d7de878-db13-4fe1-8d74-bb8c9a690d90>     # Gemeente Pelt
    <http://data.lblod.info/id/bestuurseenheden/fad1ca7a-ac26-43fc-b167-b8ae4f873553>     # OCMW Pelt
    <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a>     # Autonoom gemeentebedrijf AGB Izegem
  }
}

;

PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT DATA{
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/d93451bf-e89a-4528-80f3-f0a1c19361a8> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # Gemeente Deinze
    <http://data.lblod.info/id/bestuurseenheden/a4fd24f3-cc6d-4ea5-91c7-efa02d3b970f> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # OCMW Deinze
    <http://data.lblod.info/id/bestuurseenheden/5116efa8-e96e-46a2-aba6-c077e9056a96> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # Gemeente Aalter
    <http://data.lblod.info/id/bestuurseenheden/f73c7109-06a0-45d7-b558-879d87ca3553> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # OCMW Aalter
    <http://data.lblod.info/id/bestuurseenheden/57b1646f-bf4c-4dc4-8bc9-6ec8a6486018> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # Gemeente Lievegem
    <http://data.lblod.info/id/bestuurseenheden/120d2462-0e97-4636-b8dd-78edc4b2ba14> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # OCMW Lievegem
    <http://data.lblod.info/id/bestuurseenheden/c8f33e80-6f19-4ba1-a758-9d85f42d28d4> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b>.     # Gemeente Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/a25044d6-d9f9-496e-9061-b0c858dda944> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b>.     # OCMW Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/47857958-7d00-47e0-ae83-00d914eca93f> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/b6868be9ca6881b1020e6cff8d431531a1cff64b39dc92646a5173b3ee144516>.     # Gemeente Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/13b25c80-8d3a-4821-95b0-ffc4e850cb4b> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/b6868be9ca6881b1020e6cff8d431531a1cff64b39dc92646a5173b3ee144516>.     # OCMW Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # Gemeente Kruisem
    <http://data.lblod.info/id/bestuurseenheden/d26e802b-cae8-4c52-bad6-39e349d46862> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c>.     # OCMW Kruisem
    <http://data.lblod.info/id/bestuurseenheden/8d7de878-db13-4fe1-8d74-bb8c9a690d90> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/b6868be9ca6881b1020e6cff8d431531a1cff64b39dc92646a5173b3ee144516>.     # Gemeente Pelt
    <http://data.lblod.info/id/bestuurseenheden/fad1ca7a-ac26-43fc-b167-b8ae4f873553> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/b6868be9ca6881b1020e6cff8d431531a1cff64b39dc92646a5173b3ee144516>.     # OCMW Pelt
    <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a> ext:inProvincie <http://data.lblod.info/id/werkingsgebieden/9c503a712d448bc8b89c1f8802c207e30bd192bc8da3bf22509a547949a45301>.     # Autonoom gemeentebedrijf AGB Izegem
  }
}

;

PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX prov: <http://www.w3.org/ns/prov#>


DELETE  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?werkingsgebied ext:inProvincie ?provincie.
  }
}
INSERT  {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?werkingsgebied ext:inProvincie ?beprovincie.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?bestuurseenheid ext:inProvincie ?beprovincie;
      besluit:werkingsgebied ?werkingsgebied.
    ?werkingsgebied a prov:Location.
    OPTIONAL {
      ?werkingsgebied ext:inProvincie ?provincie.
    }
  }
  VALUES ?bestuurseenheid {
    <http://data.lblod.info/id/bestuurseenheden/d93451bf-e89a-4528-80f3-f0a1c19361a8>     # Gemeente Deinze
    <http://data.lblod.info/id/bestuurseenheden/a4fd24f3-cc6d-4ea5-91c7-efa02d3b970f>     # OCMW Deinze
    <http://data.lblod.info/id/bestuurseenheden/5116efa8-e96e-46a2-aba6-c077e9056a96>     # Gemeente Aalter
    <http://data.lblod.info/id/bestuurseenheden/f73c7109-06a0-45d7-b558-879d87ca3553>     # OCMW Aalter
    <http://data.lblod.info/id/bestuurseenheden/57b1646f-bf4c-4dc4-8bc9-6ec8a6486018>     # Gemeente Lievegem
    <http://data.lblod.info/id/bestuurseenheden/120d2462-0e97-4636-b8dd-78edc4b2ba14>     # OCMW Lievegem
    <http://data.lblod.info/id/bestuurseenheden/c8f33e80-6f19-4ba1-a758-9d85f42d28d4>     # Gemeente Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/a25044d6-d9f9-496e-9061-b0c858dda944>     # OCMW Puurs-Sint-Amands
    <http://data.lblod.info/id/bestuurseenheden/47857958-7d00-47e0-ae83-00d914eca93f>     # Gemeente Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/13b25c80-8d3a-4821-95b0-ffc4e850cb4b>     # OCMW Oudsbergen
    <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4>     # Gemeente Kruisem
    <http://data.lblod.info/id/bestuurseenheden/d26e802b-cae8-4c52-bad6-39e349d46862>     # OCMW Kruisem
    <http://data.lblod.info/id/bestuurseenheden/8d7de878-db13-4fe1-8d74-bb8c9a690d90>     # Gemeente Pelt
    <http://data.lblod.info/id/bestuurseenheden/fad1ca7a-ac26-43fc-b167-b8ae4f873553>     # OCMW Pelt
    <http://data.lblod.info/id/bestuurseenheden/20ed2789-2e69-47bf-ab84-64433d59fa3a>     # Autonoom gemeentebedrijf AGB Izegem
  }
}
