PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
  <http://data.lblod.info/id/bestuursorganen/6f3fb0ed-c62d-4847-96a0-e64621c1f8a3> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/4b114b8e-11c5-4bc8-a3c2-4f5f05d7f430> .
  <http://data.lblod.info/id/bestuursorganen/b4f6117c-08c0-4b62-b327-bc45a431386c> mandaat:bindingStart "2017-11-27"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://data.lblod.info/id/bestuursorganen/d46795a1-b4d9-48ac-89db-e6ae36681995> besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/4b114b8e-11c5-4bc8-a3c2-4f5f05d7f430> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "d46795a1-b4d9-48ac-89db-e6ae36681995" ;
       skos:prefLabel "Algemene vergadering Zorgbedrijf Vilvoorde" ;
       besluit:classificatie  <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> .

   <http://data.lblod.info/id/bestuursorganen/65b15c9a-d587-4837-b421-39cb75f1578d> mandaat:isTijdspecialisatieVan <http://data.lblod.info/id/bestuurseenheden/d46795a1-b4d9-48ac-89db-e6ae36681995> ;
       a besluit:Bestuursorgaan ;
       mu:uuid "65b15c9a-d587-4837-b421-39cb75f1578d" ;
       mandaat:bindingStart "2017-11-27"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}
