DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?name .
    ?geboorte <http://data.vlaanderen.be/ns/persoon#datum> ?date .
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth" .
    ?geboorte <http://data.vlaanderen.be/ns/persoon#datum> "1973-08-16"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?name .
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2> <http://data.vlaanderen.be/ns/persoon#heeftGeboorte> ?geboorte .
    ?geboorte <http://data.vlaanderen.be/ns/persoon#datum> ?date .
 }

 VALUES ?g {
   <http://mu.semte.ch/graphs/organizations/8620c62b9e51d2275c98cb724ce4b6784b432db8e1e0376ac70cbda098ea0d0a/LoketLB-mandaatGebruiker>
   <http://mu.semte.ch/graphs/organizations/99551d67fc22a429595d9fac5dba1babd38cbd823c7ea107b73382c30787b6c9/LoketLB-mandaatGebruiker>
 }
}
