PREFIX    mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX    besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX    persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX    foaf: <http://xmlns.com/foaf/0.1/>
PREFIX    org: <http://www.w3.org/ns/org#>
PREFIX    skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX    rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX    ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX    regorg: <https://www.w3.org/ns/regorg#>
PREFIX    person: <http://www.w3.org/ns/person#>
PREFIX    schema: <http://schema.org/>
PREFIX    prov: <http://www.w3.org/ns/prov#>
PREFIX    adms: <http://www.w3.org/ns/adms#>
PREFIX    mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX    lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX    prov: <http://www.w3.org/ns/prov#>

# Rename
DELETE {
  GRAPH ?g {
  <http://data.lblod.info/id/bestuurseenheden/9e1a43e3eea9453e9141292a3d28aa82e41b65ec7089208c3bbe2aca902ec640> skos:prefLabel ?oldLabel.
 }

}
INSERT {
 GRAPH ?g {
  <http://data.lblod.info/id/bestuurseenheden/9e1a43e3eea9453e9141292a3d28aa82e41b65ec7089208c3bbe2aca902ec640> skos:prefLabel "Intergemeentelijk Samenwerkingsverband voor ruimtelijke ordening en socio-economische expansie (SOLVA)"
 }

}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/9e1a43e3eea9453e9141292a3d28aa82e41b65ec7089208c3bbe2aca902ec640> skos:prefLabel ?oldLabel.
  }
}

;

# Delete obsolete bestuurseenheid (make sure some backup before)
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b> ?eenheidP ?eenheidO.
    ?bo ?boPtarget <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b>.
    ?bo besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b>.
    ?bo ?boP ?boO.
    ?bot ?botPtarget ?bo.
    ?bot ?botP ?botO.
  }
}

WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b> ?eenheidP ?eenheidO.
    ?bo ?boPtarget <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b>.
    ?bo besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/0259a186-8826-4e3d-934a-30810867ed4b>.
    ?bo ?boP ?boO.
    ?bot ?botPtarget ?bo.
    ?bot ?botP ?botO.
  }
}

;

# delete mock user
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/account/ef0445c82461eae18ac8e0fa0b364fd4> ?accP ?accO.
    <http://data.lblod.info/id/persoon/b1617b9806497b8524dbce75982ebae4> ?p <http://data.lblod.info/id/account/ef0445c82461eae18ac8e0fa0b364fd4>.
    <http://data.lblod.info/id/persoon/b1617b9806497b8524dbce75982ebae4> ?persP ?persO.
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/account/ef0445c82461eae18ac8e0fa0b364fd4> ?accP ?accO.
    <http://data.lblod.info/id/persoon/b1617b9806497b8524dbce75982ebae4> ?p <http://data.lblod.info/id/account/ef0445c82461eae18ac8e0fa0b364fd4>.
    <http://data.lblod.info/id/persoon/b1617b9806497b8524dbce75982ebae4> ?persP ?persO.
  }
}

;

# update label mock user
DELETE {
  GRAPH ?g {
  <http://data.lblod.info/id/persoon/5455c0cd7dcb1f9c32fb20488277ecec> foaf:familyName ?oldLabel.
 }

}
INSERT {
 GRAPH ?g {
  <http://data.lblod.info/id/persoon/5455c0cd7dcb1f9c32fb20488277ecec> foaf:familyName "Intergemeentelijk Samenwerkingsverband voor ruimtelijke ordening en socio-economische expansie (SOLVA)"
 }

}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/5455c0cd7dcb1f9c32fb20488277ecec> foaf:familyName ?oldLabel.
  }
}
