INSERT {
  GRAPH ?g {
    ?message <http://purl.org/dc/terms/type> ?type .
  }
}
WHERE {
  GRAPH ?g {
    ?message a <http://schema.org/Message> ;
      ^<http://schema.org/hasPart> ?conversatie .
    ?conversatie a <http://schema.org/Conversation> ;
      <http://purl.org/dc/terms/type> ?type .
  }
}
