DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/bd0c1d83-fcc8-4447-b2cb-97869edecf6c> ?p ?o .
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/bd0c1d83-fcc8-4447-b2cb-97869edecf6c> ?p ?o .
  }
}
;
DELETE {
  GRAPH ?h {
    <http://data.lblod.info/id/bestuurseenheden/d497161c-4b30-402f-8daf-8c46333f21f5> ?p ?o .
  }
}
WHERE {
  GRAPH ?h {
    <http://data.lblod.info/id/bestuurseenheden/d497161c-4b30-402f-8daf-8c46333f21f5> ?p ?o .
  }
}
;
DELETE {
  GRAPH ?i {
    <http://data.lblod.info/id/bestuurseenheden/eac38ef4-6ba8-40a1-8c40-129f4ed30988> ?p ?o .
  }
}
WHERE {
  GRAPH ?i {
    <http://data.lblod.info/id/bestuurseenheden/eac38ef4-6ba8-40a1-8c40-129f4ed30988> ?p ?o .
  }
}
