PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH ?g {
    ?s ext:inProvincie ?prov .
  }
} INSERT {
  GRAPH ?g {
    ?s ext:inProvincie ?wprov .
  }
} WHERE {
  GRAPH ?g {
    ?s ext:inProvincie ?prov ; <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?w .
    ?w ext:inProvincie ?wprov .

    VALUES ?s {
      <http://data.lblod.info/id/bestuurseenheden/5567394c206a8da9fe1e8ab4dc1d043eabdb5915ecf3d06a9495dc64cc3c691e>
      <http://data.lblod.info/id/bestuurseenheden/a510e5ebd5798668f45080e36762539bd3bc5d5b5f05c5e1e7ecaf27e481ad31>
      <http://data.lblod.info/id/bestuurseenheden/b1cfcdebeee024e79b381d90a492a8eda63991d8e45c1f16330d78246194df6c>
      <http://data.lblod.info/id/bestuurseenheden/96ceb4cf-ece3-417d-914b-3e6eff293e6a>
    }
  }
}

;

DELETE {
  GRAPH ?g {
    ?w ext:inProvincie ?wprov .
  }
} INSERT {
  GRAPH ?g {
    ?w ext:inProvincie ?prov .
  }
} WHERE {
  GRAPH ?g {
    ?s ext:inProvincie ?prov ; <http://data.vlaanderen.be/ns/besluit#werkingsgebied> ?w .
    ?w ext:inProvincie ?wprov .

    VALUES ?s {
      <http://data.lblod.info/id/bestuurseenheden/39e0e2e69be463a4628f87bffe7dc6206aa6daa4a5516fb4ce11907f57d77079>
      <http://data.lblod.info/id/bestuurseenheden/ff7d80dc-ec00-43ac-ac7e-d51694df37ff>
    }
  }
}
