DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/805a977a29725d94f50bf7f0d91a0de1a727c4eec88940e90035f71c6c9b1655> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c> .
    <http://data.lblod.info/id/werkingsgebieden/c737024ea8adb2b8ab223928effce35b6fca284741775cdf12d8c5a0cda1e828> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c> .
  }
}
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/805a977a29725d94f50bf7f0d91a0de1a727c4eec88940e90035f71c6c9b1655> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .
    <http://data.lblod.info/id/werkingsgebieden/c737024ea8adb2b8ab223928effce35b6fca284741775cdf12d8c5a0cda1e828> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/f2bda6eb42c1ab85c4ef36588a043ac2bfeffa31bfb88bb7abc597f01efe270b> .
  }
}
