PREFIX    mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX    besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX    persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX    foaf: <http://xmlns.com/foaf/0.1/>
PREFIX    org: <http://www.w3.org/ns/org#>
PREFIX    skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX    rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX    ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX    regorg: <https://www.w3.org/ns/regorg#>
PREFIX    person: <http://www.w3.org/ns/person#>
PREFIX    schema: <http://schema.org/>
PREFIX    prov: <http://www.w3.org/ns/prov#>
PREFIX    adms: <http://www.w3.org/ns/adms#>
PREFIX    mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX    lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/mandaten/87af3906-b7b5-4116-b49f-6ad04b5e0528> a mandaat:Mandaat.
    <http://data.lblod.info/id/mandaten/87af3906-b7b5-4116-b49f-6ad04b5e0528> <http://www.w3.org/ns/org#role> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000012>.
    <http://data.lblod.info/id/mandaten/87af3906-b7b5-4116-b49f-6ad04b5e0528> mu:uuid "87af3906-b7b5-4116-b49f-6ad04b5e0528".
    <http://data.lblod.info/id/bestuursorganen/b67de9c18d80c9d79646602887e1193edf3f2754ba88bb3d3b5c75a5d0f6cfd7>  <http://www.w3.org/ns/org#hasPost> <http://data.lblod.info/id/mandaten/87af3906-b7b5-4116-b49f-6ad04b5e0528>.
  }
}