DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/a4fd24f3-cc6d-4ea5-91c7-efa02d3b970f/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/667d2e4e-46cb-4db0-8231-89ce34633f47> ?p1 ?o1 .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/a4fd24f3-cc6d-4ea5-91c7-efa02d3b970f/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/667d2e4e-46cb-4db0-8231-89ce34633f47> ?p1 ?o1 .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/organizations/f73c7109-06a0-45d7-b558-879d87ca3553/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/0a7ca195-0541-4ac1-ac37-f591cda42979> ?p2 ?o2 .
    <http://data.lblod.info/id/mandatarissen/f27988d3-c2e5-480d-aa83-071c26df1e26> ?p3 ?o3 .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/f73c7109-06a0-45d7-b558-879d87ca3553/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/0a7ca195-0541-4ac1-ac37-f591cda42979> ?p2 ?o2 .
    <http://data.lblod.info/id/mandatarissen/f27988d3-c2e5-480d-aa83-071c26df1e26> ?p3 ?o3 .
  }
}
