DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/d0ec3d07-a15c-4e04-bcbb-b05083262544> <http://mu.semte.ch/vocabularies/ext/inProvincie> ?prov .
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/d0ec3d07-a15c-4e04-bcbb-b05083262544> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/a9a0cabd376a2b3a8eb838f15f6aeb1b63ffe49d527598994962e0d15ad2081c> .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/d0ec3d07-a15c-4e04-bcbb-b05083262544> <http://mu.semte.ch/vocabularies/ext/inProvincie> ?prov .
  }
}
