PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

# New bestuursorganen in tijd have been disabled in previous migration.
# Now we restore them for all bestuursorganen starting on 01-01-2019

DELETE {
  GRAPH ?g {
     ?orgaan ext:isTijdspecialisatieVan ?bestuursorgaan .
  }

}
INSERT {
  GRAPH ?g {
      ?orgaan mandaat:isTijdspecialisatieVan ?bestuursorgaan .
  }
}
WHERE {
  GRAPH ?g {
    ?orgaan ext:isTijdspecialisatieVan ?bestuursorgaan;
            mandaat:bindingStart "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
  }
}
