DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/81334af3-1b6f-4308-aca3-107121462d56> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/ba8ffc97-5490-4ecc-b24e-aab26b23c026> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/71dc3947-975f-4540-bd50-1f50f29d7567> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/2559a855-a1c9-489d-964b-1d3c9bada85b> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/bfb82c94-06f6-452d-b01b-959258636833> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/531f08c0-65ac-4f47-ac15-066097ac5756> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/ba3bf570-b12b-4968-8d8d-9d1212e8076c> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/fa3f4f3c-02be-4a6a-ac1e-68264ba14d60> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/81334af3-1b6f-4308-aca3-107121462d56> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/ba8ffc97-5490-4ecc-b24e-aab26b23c026> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/71dc3947-975f-4540-bd50-1f50f29d7567> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/2559a855-a1c9-489d-964b-1d3c9bada85b> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/bfb82c94-06f6-452d-b01b-959258636833> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/531f08c0-65ac-4f47-ac15-066097ac5756> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/ba3bf570-b12b-4968-8d8d-9d1212e8076c> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
    <http://data.lblod.info/id/bestuurseenheden/fa3f4f3c-02be-4a6a-ac1e-68264ba14d60> <http://mu.semte.ch/vocabularies/ext/inProvincie> <http://data.lblod.info/id/werkingsgebieden/60a52229c92c1407e0549a573f820fb8a1f9fab5c82654b4b3493bc81be365de> .
  }
}
