PREFIX person: <http://www.w3.org/ns/person#>

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND ###
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> a <http://www.w3.org/ns/person#Person> .
    <http://dumm/data/4403c05f-8c45-4c5e-8d90-5772ef2df412> <http://www.w3.org/2002/07/owl#sameAs> <http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> .
    <http://dumm/data/5403c05f-8c45-4c5e-8d90-5772ef2df413> <http://dumm/data/predicate> <http://dumm/data/4403c05f-8c45-4c5e-8d90-5772ef2df412> .
  }
}
### END OF TRICK ###

;

DELETE {
  GRAPH ?g {
    ?s ?p ?person .
  }
} INSERT {
  GRAPH ?g {
    ?s ?p ?masterPerson .
  }
} WHERE {
  GRAPH ?g {
    ?s ?p ?person .
  }
  GRAPH ?h {
    ?person owl:sameAs ?masterPerson .
  }
  GRAPH ?i {
    ?masterPerson a person:Person .
  }
}

;

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND ###
DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?a ?b ?s.
  }
}
WHERE {
  BIND(<http://dumm/data/3403c05f-8c45-4c5e-8d90-5772ef2df411> as ?s)
  GRAPH ?g {
    ?s ?p ?o.
    ?a ?b ?s.
 }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o.
  }
}
WHERE {
  BIND(<http://dumm/data/4403c05f-8c45-4c5e-8d90-5772ef2df412> as ?s)
  GRAPH ?g {
   ?s ?p ?o.
 }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o.
  }
}
WHERE {
  BIND(<http://dumm/data/5403c05f-8c45-4c5e-8d90-5772ef2df413> as ?s)
  GRAPH ?g {
   ?s ?p ?o.
 }
}
### END OF TRICK ###