DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/3954ec78151e13f07f4ecfd15491198a> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/3954ec78151e13f07f4ecfd15491198a> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/b29736c378a48cb714b9ae6cb55d4dae> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/b29736c378a48cb714b9ae6cb55d4dae> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/01fb5143bfb2712d80388eef92a46dd0> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/01fb5143bfb2712d80388eef92a46dd0> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/ad8a186307a957dba966108d9258c2de> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/ad8a186307a957dba966108d9258c2de> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/40b643f4b8c8696d95f6d5ecbf7a8260> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/40b643f4b8c8696d95f6d5ecbf7a8260> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/927f68a70be47c39afdfa353a75fafa5> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/927f68a70be47c39afdfa353a75fafa5> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/827a69df02461cae21507c5b20086383> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/827a69df02461cae21507c5b20086383> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/46d741c6cc72aff540d2fc3156267610> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/46d741c6cc72aff540d2fc3156267610> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/d58555293524f6fcc019b0342eb58d94> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/d58555293524f6fcc019b0342eb58d94> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/0ec09e3f21d522933e45b3bf7228797a> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/0ec09e3f21d522933e45b3bf7228797a> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/a8a112b401b1419cc5518080ae27524d> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/a8a112b401b1419cc5518080ae27524d> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/e2d9fe9946b77860632edcf4882af8d0> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/e2d9fe9946b77860632edcf4882af8d0> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/a2c5ca1d5fec3eeae7bb6ee640326bac> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/a2c5ca1d5fec3eeae7bb6ee640326bac> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/aed08d70390c896d886c713af53891a6> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/aed08d70390c896d886c713af53891a6> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/cf5195a386bb39ae3f6dd4bc9c30a953> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/cf5195a386bb39ae3f6dd4bc9c30a953> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/fb0bd01ef48c7559ef1893afc75628e7> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/fb0bd01ef48c7559ef1893afc75628e7> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/689ac8248efb2dd12a86a42e3aaa3235> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/689ac8248efb2dd12a86a42e3aaa3235> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
;
DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/5fdfd3de8a31ecb8c919df2231012cfe> ?personP ?personO .
    ?account ?accountP ?accountO .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/persoon/5fdfd3de8a31ecb8c919df2231012cfe> <http://xmlns.com/foaf/0.1/account> ?account ;
      ?personP ?personO .
    ?account ?accountP ?accountO .
  }
}
