PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
  GRAPH ?g {
    ?message  <http://schema.org/dateSent> ?sent2 .
  }
} WHERE {
  GRAPH ?g {
    ?message a <http://schema.org/Message> ; <http://schema.org/dateSent> ?sent1 ;  <http://schema.org/dateSent> ?sent2 .
    FILTER ( ( STR(?sent1) != STR(?sent2) || datatype(?sent1) != datatype(?sent2) ) && datatype(?sent2) = xsd:date )
  }
}

;


DELETE {
  GRAPH ?g {
    ?message  <http://schema.org/dateReceived> ?received2 .
  }
} WHERE {
  GRAPH ?g {
    ?message a <http://schema.org/Message> ; <http://schema.org/dateReceived> ?received1 ;  <http://schema.org/dateReceived> ?received2 .
    FILTER ( ( STR(?received1) != STR(?received2) || datatype(?received1) != datatype(?received2) ) && datatype(?received2) = xsd:date )
  }
}
