INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/99b07146-80b1-4bfa-8835-7c43bccd264d> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
      <http://mu.semte.ch/vocabularies/core/uuid> "99b07146-80b1-4bfa-8835-7c43bccd264d" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Subsidy can be paid on known bank account"@en .

    <https://data.vlaanderen.be/id/concept/SubsidyCanBePaidOnBankAccount/8c7e83c6-5a06-4e19-9157-d890f244201c> a <http://www.w3.org/2004/02/skos/core#Concept>,
        <http://www.w3.org/2000/01/rdf-schema#Class>;
      <http://mu.semte.ch/vocabularies/core/uuid> "8c7e83c6-5a06-4e19-9157-d890f244201c" ;
      <http://www.w3.org/2004/02/skos/core#definition> "The subsidy can be paid on known bank account"@en;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/99b07146-80b1-4bfa-8835-7c43bccd264d>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Ja, gebruik het bankrekeningnummer dat gebruikt wordt voor het Gemeentefonds"@nl .

    <https://data.vlaanderen.be/id/concept/SubsidyCanBePaidOnBankAccount/54adc1e3-865a-4e5a-a3e2-03465ccd5f5b> a <http://www.w3.org/2004/02/skos/core#Concept>,
        <http://www.w3.org/2000/01/rdf-schema#Class>;
      <http://mu.semte.ch/vocabularies/core/uuid> "54adc1e3-865a-4e5a-a3e2-03465ccd5f5b" ;
      <http://www.w3.org/2004/02/skos/core#definition> "The subsidy can not be paid on known bank account"@en;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/99b07146-80b1-4bfa-8835-7c43bccd264d>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Nee, gebruik een alternatief bankrekeningnummer"@nl .
  }
}
