DELETE  {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
    <http://data.lblod.info/id/mailboxes/1> <http://www.semanticdesktop.org/ontologies/2007/03/22/fni#hasPart> ?folder
  }
}
INSERT  {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
     <http://data.lblod.info/id/mailboxes/1> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#hasPart> ?folder
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
    ?folder a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder>
  }
}
