# This fixes a bug happened during the migration of the old form to new forms.
# InzendingenVoorToezicht in status 'concept', were wrongly migrated.
# The fileType was wrong.

PREFIX dct: <http://purl.org/dc/terms/>
DELETE {
  GRAPH ?j {
    ?file dct:type ?fileType.
  }
}
WHERE {
  GRAPH ?g {
  ?s <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> .
  ?s <http://purl.org/dc/terms/source>  ?inzending.
  ?inzending <http://www.w3.org/ns/adms#status> <http://data.lblod.info/document-statuses/concept>.
  ?s  <http://purl.org/dc/terms/subject> ?subDoc.
  ?subDoc <http://purl.org/dc/terms/source> ?file .
  }
  GRAPH ?j {
        ?file dct:type <http://data.lblod.gift/concepts/form-data-file-type> .
        ?file dct:type ?fileType.
  }
  BIND( <http://mu.semte.ch/graphs/public> as ?j )
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?file dct:type <http://data.lblod.gift/concepts/additions-file-type>.
  }
}
WHERE {
  GRAPH ?g {
  ?s <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> .
  ?s <http://purl.org/dc/terms/source>  ?inzending.
  ?inzending <http://www.w3.org/ns/adms#status> <http://data.lblod.info/document-statuses/concept>.
  ?s  <http://purl.org/dc/terms/subject> ?subDoc.
  ?subDoc <http://purl.org/dc/terms/source> ?file .
  }
}