PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH ?g {
    ?birth ?p ?o .
  }
} INSERT {
  GRAPH ?g {
    ?birth owl:sameAs ?masterBirth .
  }
} WHERE {
  GRAPH ?g {
    ?birth a <http://data.vlaanderen.be/ns/persoon#Geboorte> ;
      owl:sameAs ?masterBirth ;
      ?p ?o .
  }
  GRAPH ?h {
    ?masterBirth a <http://data.vlaanderen.be/ns/persoon#Geboorte> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://data.vlaanderen.be/ns/persoon#datum> ?date .
  }
}
