DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
<http://data.lblod.info/id/bestuurseenheden/da9f38da-eb84-4578-a206-72baee1865fe> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
  }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
      <http://data.lblod.info/id/bestuurseenheden/da9f38da-eb84-4578-a206-72baee1865fe> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/cd93f147-3ece-4308-acab-5c5ada3ec63d> .
      <http://data.lblod.info/id/bestuurseenheden/da9f38da-eb84-4578-a206-72baee1865fe> <http://www.w3.org/2004/02/skos/core#altLabel> "IBEG" .
  }
}
