PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
    GRAPH ?g {
        ?org ext:submissionNotificationEmail ?mail ;
             ext:allowedSubmissionNotificationsMails ?allowed .
    }
}
WHERE {
    ?org a besluit:Bestuurseenheid.
    GRAPH ?h {
       ?org ext:mailAdresVoorNotificaties ?mail ;
            ext:wilMailOntvangen ?allowed .
    }
    BIND(?h as ?g)
}