DELETE {
  GRAPH ?g {
    ?s ?p "2019-01-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
}
WHERE {
  GRAPH ?g {
  ?s a <http://data.vlaanderen.be/ns/mandaat#Mandataris> ;
    ?p "2019-01-01T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
    ?p "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
}