DELETE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/personen/0d474db5-80cc-4b9f-a7b0-6f6607ec8558> .
  }
  GRAPH ?h {
    <http://data.lblod.info/id/personen/0d474db5-80cc-4b9f-a7b0-6f6607ec8558> ?pp ?op .
  }
} INSERT {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/personen/b94c1c86a08622ab6c182ce3cb450189980419c269d7a3b1ba6d3b6a537f9b78> .
  }
  GRAPH ?h {
    <http://data.lblod.info/id/personen/0d474db5-80cc-4b9f-a7b0-6f6607ec8558> <http://www.w3.org/2002/07/owl#sameAs> <http://data.lblod.info/id/personen/b94c1c86a08622ab6c182ce3cb450189980419c269d7a3b1ba6d3b6a537f9b78> .
  }
} WHERE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/personen/0d474db5-80cc-4b9f-a7b0-6f6607ec8558> .
  }
  GRAPH ?h {
    <http://data.lblod.info/id/personen/0d474db5-80cc-4b9f-a7b0-6f6607ec8558> ?pp ?op .
  }
}
