PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

# Remove bestuurseenheid

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> ?p ?o.
  }
}

WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> ?p ?o.
  }
}

;

# Remove bestuursorganen, bestuursorganen in tijd and bestuursfuncties

DELETE {
  GRAPH ?g {
    ?bestuursorgaan <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> ;
      ?boP ?boO .
    ?bestuursorgaanInTijd <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> ?bestuursfunctie ;
      ?botP ?botO .
    ?bestuursfunctie ?beP ?beO .
  }
}

WHERE {
  GRAPH ?g {
    ?bestuursorgaan <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc3770b6-20c1-4610-84f1-d7022a1569e7> ;
      ?boP ?boO ;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanInTijd .
    ?bestuursorgaanInTijd <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> ?bestuursfunctie ;
      ?botP ?botO .
    ?bestuursfunctie ?beP ?beO .
  }
}

;

DROP SILENT GRAPH <http://mu.semte.ch/graphs/organizations/cc3770b6-20c1-4610-84f1-d7022a1569e7/LoketLB-berichtenGebruiker>
