# Due to an issue with a previous migrations, old submission documents
# got two source files, this migrations rectifies this.
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
 PREFIX dct: <http://purl.org/dc/terms/>
 PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
 DELETE {
   GRAPH ?g {
    ?form dct:source  <share://semantic-forms/20200827091312-forms.ttl> .
   }
 }
 WHERE {
   GRAPH ?g {
     ?form dct:source  <share://semantic-forms/20200827091312-forms.ttl> .
     ?form dct:source  <share://semantic-forms/20200508151443-forms.ttl> .
   }
 }