PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/06bad311-e964-48a4-9b6b-f765819e76e0> a skos:ConceptScheme ;
    mu:uuid "06bad311-e964-48a4-9b6b-f765819e76e0" ;
    skos:prefLabel "Loket leidinggevenden export" .
    ?bestuursfunctie skos:inScheme <http://lblod.data.gift/concept-schemes/06bad311-e964-48a4-9b6b-f765819e76e0> .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
   ?bestuursfunctie a lblodlg:Bestuursfunctie .
  }
}