PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH ?g {
    ?s persoon:heeftGeboorte ?date .
  }
} INSERT {
  GRAPH ?g {
    ?s persoon:heeftGeboorte ?masterDate .
  }
} WHERE {
  GRAPH ?g {
    ?s persoon:heeftGeboorte ?date .
    ?date owl:sameAs ?masterDate .
  }
}
