DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/934917cdce95b7d47219ca88ba5dfaf99d41d1580985a3ff521650c115905da1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Infrax West" .
    <http://data.lblod.info/id/bestuurseenheden/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622> <http://www.w3.org/2004/02/skos/core#prefLabel> "Interkommunale voor Energie" .
    <http://data.lblod.info/id/persoon/64a5317adf11335a27bfce797d5e8b17> <http://xmlns.com/foaf/0.1/familyName> "Interkommunale voor Energie" .
    <http://data.lblod.info/id/bestuurseenheden/da9f38da-eb84-4578-a206-72baee1865fe> <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> .
    <http://data.lblod.info/id/persoon/f63a98b69ea93772f818a2647c381ef8> <http://xmlns.com/foaf/0.1/firstName> "Projectvereniging" .
  }
  GRAPH <http://mu.semte.ch/graphs/organizations/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622> {
    <http://data.lblod.info/id/persoon/64a5317adf11335a27bfce797d5e8b17> <http://xmlns.com/foaf/0.1/familyName> "Interkommunale voor Energie" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/934917cdce95b7d47219ca88ba5dfaf99d41d1580985a3ff521650c115905da1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Fluvius West" .
    <http://data.lblod.info/id/bestuurseenheden/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622> <http://www.w3.org/2004/02/skos/core#prefLabel> "Fluvius Antwerpen" .
    <http://data.lblod.info/id/persoon/64a5317adf11335a27bfce797d5e8b17> <http://xmlns.com/foaf/0.1/familyName> "Fluvius Antwerpen" .
    <http://data.lblod.info/id/persoon/f63a98b69ea93772f818a2647c381ef8> <http://xmlns.com/foaf/0.1/firstName> "Opdrachthoudende vereniging" .
  }
  GRAPH <http://mu.semte.ch/graphs/organizations/a75bdf601cf1ef3e0667c176348c1453d8513da729c8c9acf0179a2d610b4622> {
    <http://data.lblod.info/id/persoon/64a5317adf11335a27bfce797d5e8b17> <http://xmlns.com/foaf/0.1/familyName> "Fluvius Antwerpen" .
  }
}
