DELETE  {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
    ?folder <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#description> ?description
  }
}
INSERT  {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
    ?folder <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#description> ?description
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/system/email> {
    ?folder a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Folder>;
    <http://www.semanticdesktop.org/ontologies/2007/03/22/nie#description> ?description.
  }
}
