PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT {
  GRAPH ?g {
    ?person persoon:geslacht ?newGender .
  }
}
WHERE {
  GRAPH ?g {
    ?person a person:Person ;
      adms:identifier ?identifier .

    ?identifier skos:notation ?rrn .

    OPTIONAL {
      ?person persoon:geslacht ?gender .
    }

    FILTER ( NOT EXISTS { ?person persoon:geslacht ?gender . } )
    FILTER(STRLEN( ?rrn ) >= 11 )

    BIND ( xsd:float(SUBSTR(STR(?rrn), 7, 3)) as ?genderPart ) .
    BIND ( (?genderPart/2 =  FLOOR(?genderPart/2)) AS ?isAWoman ) .

    BIND ( IF(?isAWoman, <http://publications.europa.eu/resource/authority/human-sex/FEMALE>, <http://publications.europa.eu/resource/authority/human-sex/MALE>) as ?newGender)
  }
}
