DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/c6ce52f7a484e12c7f385f1116766fa9a8d1a1798e4e265a77a8881a2bda9b60/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Verreyt" .
    <http://data.lblod.info/id/personen/2c73eaa2030fa02c65d405d6197f015f4354137b98d505ddb18ea59ed4fc64e4> <http://xmlns.com/foaf/0.1/familyName> "Johan" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/752fe276-80d6-4b1e-b83b-d4876d1efe5c/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/9d43df6b328a03022ca6800987e09ebb0bf1ce421939ed02c50a71db940ee45f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vercruysse" .
    <http://data.lblod.info/id/personen/9d43df6b328a03022ca6800987e09ebb0bf1ce421939ed02c50a71db940ee45f> <http://xmlns.com/foaf/0.1/familyName> "Yves" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/752fe276-80d6-4b1e-b83b-d4876d1efe5c/LoketLB-leidinggevendenGebruiker> {
    <http://data.lblod.info/id/personen/9d43df6b328a03022ca6800987e09ebb0bf1ce421939ed02c50a71db940ee45f> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Vercruysse" .
    <http://data.lblod.info/id/personen/9d43df6b328a03022ca6800987e09ebb0bf1ce421939ed02c50a71db940ee45f> <http://xmlns.com/foaf/0.1/familyName> "Yves" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/d6a04c16b842c671407bccdad2d3b536b7d356096ae24e7c6c6e22cee4296db4/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/a081bb9039f85c1412d3bf6de52bb9a834880a9318d61696072e724762ef40b0> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "DE WACHTER" .
    <http://data.lblod.info/id/personen/a081bb9039f85c1412d3bf6de52bb9a834880a9318d61696072e724762ef40b0> <http://xmlns.com/foaf/0.1/familyName> "ARLETTE" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/c6ce52f7a484e12c7f385f1116766fa9a8d1a1798e4e265a77a8881a2bda9b60/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/b988302b36cc1c86ecb84c4fa952a43559be82c2881b88d4765f114256f72b09> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Verhoeven " .
    <http://data.lblod.info/id/personen/b988302b36cc1c86ecb84c4fa952a43559be82c2881b88d4765f114256f72b09> <http://xmlns.com/foaf/0.1/familyName> "Rudy " .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/cc1d56b39041957b17f7a24e80076b633e0ae7c582e616806b7112aff8e62efb/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/398ef4ff-3813-4d36-ae16-41b93cf7963b> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Willems" .
    <http://data.lblod.info/id/personen/398ef4ff-3813-4d36-ae16-41b93cf7963b> <http://xmlns.com/foaf/0.1/familyName> "Eva" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/60a7cee610b31a63473ef8f52665f60108cb2bb7ce0d1cba8bac7db5f00ab318/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reekmans" .
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://xmlns.com/foaf/0.1/familyName> "Peter" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/bc50bb1ff28814ab2441a22fe111d895742098d8a61d7f648efbd9ffd48446ed/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reekmans" .
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://xmlns.com/foaf/0.1/familyName> "Peter" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/4007911a9bdb6dde20cf16ade0a9520aee8b2c2b2a1edff7ab639eadf9e9432c/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reekmans" .
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://xmlns.com/foaf/0.1/familyName> "Peter" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/4007911a9bdb6dde20cf16ade0a9520aee8b2c2b2a1edff7ab639eadf9e9432c/LoketLB-leidinggevendenGebruiker> {
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Reekmans" .
    <http://data.lblod.info/id/personen/5D2DA519A3ACB600080002E8> <http://xmlns.com/foaf/0.1/familyName> "Peter" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/a605a770e69d0af2d501614a41b446c76328d2f32165be238458468fbd5f8b88/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/50b19256f0c539a99e017a1b31c872a281dea38b3bfc93d9ec13b1565fdc1e27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/a0e10593de20daec75c7c987f07db727dcd9dce7e2d2a8797b6a0f0f7157b14c/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/50b19256f0c539a99e017a1b31c872a281dea38b3bfc93d9ec13b1565fdc1e27> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Piet" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/4e6d15d5c7fd95c996087bb13cdee985f0b550256be745024d5facd1485df284/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5C9BEED1D5BECA000900017C> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristin Karel Maria" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/bd74ee38a4b1e296821a11729c1f704cf439576c7ab2c910c95b067cf183d923/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5C9BEED1D5BECA000900017C> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristin Karel Maria" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/96bad0ebf5866e1f4d792a276343d492ebf21ef4cb84634dfb27daf0fdd28ece/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5C9BEED1D5BECA000900017C> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristin Karel Maria" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/407bd6f1567ef56e51cbd0242cc6ebaf7608ec3bbb2bc2614b2bee95c7f77a88/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/5C9BEED1D5BECA000900017C> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Kristin Karel Maria" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/6c19ef9b94965f9ad2eaad940fb63f9ca7e23b3ac440fad96886e12725d61c4a/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/736168e94511a5eff8570b45c63f03297e1d999641d80bbe55dd982ef7f7b4ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/d59bf99ac29e71796ad7bdfe68cf74709c63721691d9680e0ea7636070f7513c/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/736168e94511a5eff8570b45c63f03297e1d999641d80bbe55dd982ef7f7b4ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth" .
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/94c56bcbb9692f00b27a7411599cc08f39128ddad93dd822344f428ef67550e5/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/personen/736168e94511a5eff8570b45c63f03297e1d999641d80bbe55dd982ef7f7b4ff> <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> "Liesbeth" .
  }
}