INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/33e233eb-6a9b-4141-b607-2ff72fe2ded2> a <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        <http://mu.semte.ch/vocabularies/core/uuid> "33e233eb-6a9b-4141-b607-2ff72fe2ded2" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Subsidy types"@en .

    <http://lblod.data.gift/concept/1df4b56a-3ccd-450d-93dc-317fda1ada38> a <http://www.w3.org/2004/02/skos/core#Concept>,
        <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "1df4b56a-3ccd-450d-93dc-317fda1ada38" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Day-care subsidy type"@en;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/33e233eb-6a9b-4141-b607-2ff72fe2ded2>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Kinderopvang"@nl .
  }
}
