# Un-archive mandatarissen that should still be active

DELETE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/5F5A0C1661114200090004F0> a ?type ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership ;
      <http://data.vlaanderen.be/ns/mandaat#status> ?status ;
      <http://www.w3.org/2004/02/skos/core#historyNote> ?note .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/56423901b281897688074e6ce6811a6a33eec4070da7e22c4fae65050d7b712f/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/5F5A0C1661114200090004F0> a <http://data.vlaanderen.be/ns/mandaat#Mandataris> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership ;
      <http://data.vlaanderen.be/ns/mandaat#status> ?status .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/5F5A0C1661114200090004F0> a ?type ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership ;
      <http://data.vlaanderen.be/ns/mandaat#status> ?status ;
      <http://www.w3.org/2004/02/skos/core#historyNote> ?note .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/5D399045A3ACB60008000584> a ?type ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership ;
      <http://www.w3.org/2004/02/skos/core#historyNote> ?note .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/30140eaed99f7bd21ae29da27e25c732a0e7ccd5a54b5fbc4afac00dafba6f3b/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/5D399045A3ACB60008000584> a <http://data.vlaanderen.be/ns/mandaat#Mandataris> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    <http://data.lblod.info/id/mandatarissen/5D399045A3ACB60008000584> a ?type ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid ;
      <http://www.w3.org/ns/org#holds> ?mandate ;
      <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?person ;
      <http://data.vlaanderen.be/ns/mandaat#start> ?start ;
      <http://www.w3.org/ns/org#hasMembership> ?membership ;
      <http://www.w3.org/2004/02/skos/core#historyNote> ?note .
  }
}
;
# Archive correct mandatarissen, linked to person <http://data.lblod.info/id/personen/60D08441CA2C91000800005A>
# who is merged from <http://data.lblod.info/id/personen/f6d29ac8-73f3-4962-8917-f24b97995d15>, based
# on the mandates showing in Gemeente Herent which are wrong

# Part 1
DELETE {
  GRAPH ?g {
    ?mandate ?p ?o .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    ?mandate ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?mandate ?p ?o .
  }
  VALUES ?mandate {
    <http://data.lblod.info/id/mandatarissen/60D0846DCA2C91000800005C>
    <http://data.lblod.info/id/mandatarissen/609A46FFABD6E00008000053>
    <http://data.lblod.info/id/mandatarissen/5D36DBAFA3ACB600080001AA>
    <http://data.lblod.info/id/mandatarissen/60A24614ABD6E00008000051>
    <http://data.lblod.info/id/mandatarissen/609A4541ABD6E0000800004D>
  }
}
;
# Part 2
DELETE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    ?mandate a ?type .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    ?mandate a <http://lblod.data.gift/vocabularies/mandaat/ArchivedMandataris> ;
      <http://www.w3.org/2004/02/skos/core#historyNote> "Mandataris archived because linked to the wrong person" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/graveyard/mandatarissen> {
    ?mandate a ?type .
  }
  VALUES ?mandate {
    <http://data.lblod.info/id/mandatarissen/60D0846DCA2C91000800005C>
    <http://data.lblod.info/id/mandatarissen/609A46FFABD6E00008000053>
    <http://data.lblod.info/id/mandatarissen/5D36DBAFA3ACB600080001AA>
    <http://data.lblod.info/id/mandatarissen/60A24614ABD6E00008000051>
    <http://data.lblod.info/id/mandatarissen/609A4541ABD6E0000800004D>
  }
}
