DELETE DATA {
  # HALLE GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/e84ba36959d82fc95bb17b25d2e70c135d8805737ba27bab572af670a2768338/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/600E9D170CCED4000800011E> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "5550.0"^^xsd:float.
  }

  # LAAKDAL GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/4e6d15d5c7fd95c996087bb13cdee985f0b550256be745024d5facd1485df284/LoketLB-subsidies> {
    <http://data.lblod.info/id/application-forms/60C74D7DCA2C9100080000E0> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "630.0"^^xsd:float.
  }

  # WAREGEM OCMW
  GRAPH <http://mu.semte.ch/graphs/organizations/371fa701c757106e5762f522e15517b043f0b01a5f7812de5b2142637c10d516/LoketLB-subsidies> {
    <http://data.lblod.info/id/application-forms/60C35741CA2C91000800007F> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "2660.0"^^xsd:float.
    <http://data.lblod.info/id/application-forms/60C355E4CA2C91000800007A> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "4360.0"^^xsd:float.
  } 

  # ANTWERPEN GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/670db1d66c0de3b931962e1044033ccfa9d6e3023aa9828a5f252c3bc69bd32c/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/609134A8ABD6E00008000291> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "63020.0"^^xsd:float.
    <http://data.lblod.info/application-forms/609134A8ABD6E00008000291> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "71420.0"^^xsd:float.
    <http://data.lblod.info/application-forms/609107D7ABD6E0000800021D> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "268950.0"^^xsd:float.
  }

  # SINT-NIKLAAS GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/71f6925a4b895c2a91dce039c87d227809edcda82963714814141b1e41631b08/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/5FF851740CCED4000800033E> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "1350.0"^^xsd:float.
    <http://data.lblod.info/application-forms/5FF851740CCED4000800033E> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "2040.0"^^xsd:float.
  }

  # TORHOUT GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/842737db3afe0bad6a72bbbdeee376fe49abe721975d549d81bb22c70bc7002d/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/60003FD60CCED400080000B4> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "6780.0"^^xsd:float.
  }

  # RANST GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/8fb90f367f105c14f37a7062d6732696dc2efc292f87fd5045548a0da407dbe4/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/6082D15DFC620200080004F4> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "2520.0"^^xsd:float.
    <http://data.lblod.info/application-forms/6082D15DFC620200080004F4> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "6275.0"^^xsd:float.
  }

  # VEURNE GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/a1f8ddebe40f6a09270fbe460e71ebb7adda7b1ac2e5c4ccb3fd6e9dda2162b6/LoketLB-subsidies> {
    <http://data.lblod.info/id/application-forms/60CB107ACA2C910008000119> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "6980.0"^^xsd:float.
  }

  # MECHELEN GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/be278471a2a318edba32e7ac4294c0eafbe4c8077a34dcbb9c2e43211d4a78a6/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/60A4F6ACABD6E000080002EC> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "5250.0"^^xsd:float.
  }

  # POPERINGE GEMEENTE
  GRAPH <http://mu.semte.ch/graphs/organizations/bf2ed8893d2ec4689b4c60b0b236edf11f381e247c535f0b12d132fc80ca1ad0/LoketLB-subsidies> {
    <http://data.lblod.info/id/application-forms/60D062C4CA2C91000800003A> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "4080.0"^^xsd:float.
  }

  # ZEDELGEM OCMW
  GRAPH <http://mu.semte.ch/graphs/organizations/acdeb7c6328dd534dc7a13c9e5cb0f46654ba89d062f2d4d957d8e5e898fdde4/LoketLB-subsidies> {
    <http://data.lblod.info/application-forms/607EE2DFFC620200080001D0> <http://lblod.data.gift/vocabularies/subsidie/totalAmount> "5240.0"^^xsd:float.
  }

}