INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        ########################################################
        ### CONCEPT - Brought forward Easter holidays 2021

        <http://lblod.data.gift/concepts/3e230d69-4dfb-4d99-8212-17e7921eb915>
            a   <http://www.w3.org/2004/02/skos/core#Concept>,
                <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "3e230d69-4dfb-4d99-8212-17e7921eb915" ;
            <http://www.w3.org/2004/02/skos/core#definition> """Subsidy season for subsidy measure emergency-care (children): \"brought forward Easter holidays 2021\""""@en;
            <https://www.gleif.org/ontology/Base/hasStart> "2021-03-29"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2021-04-02"^^<http://www.w3.org/2001/XMLSchema#date>;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Vervroeging Paasvakantie 2021 ( 29 maart 2021 — 2 april 2021)"@nl ;
            <http://purl.org/dc/terms/title> "Vervroeging Paasvakantie"@nl ;
            <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66> .

        ########################################################
        ### CONCEPT - Easter holidays 2021

        <http://lblod.data.gift/concepts/5578af16-8dc2-4361-98e0-12cddcdd9de5>
            a   <http://www.w3.org/2004/02/skos/core#Concept>,
                <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "5578af16-8dc2-4361-98e0-12cddcdd9de5" ;
            <http://www.w3.org/2004/02/skos/core#definition> """Subsidy season for subsidy measure emergency-care (children): \"Easter holidays 2021\""""@en;
            <https://www.gleif.org/ontology/Base/hasStart> "2021-04-05"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2021-04-16"^^<http://www.w3.org/2001/XMLSchema#date>;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Paasvakantie 2021 (5 april 2021 — 16 april 2021)"@nl ;
            <http://purl.org/dc/terms/title> "Paasvakantie"@nl ;
            <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66> .

        ########################################################
        ### CONCEPT - Spring 2021

        <http://lblod.data.gift/concepts/eaec78fb-2130-40c9-941b-6ad3bc129009>
            a   <http://www.w3.org/2004/02/skos/core#Concept>,
                <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "eaec78fb-2130-40c9-941b-6ad3bc129009" ;
            <http://www.w3.org/2004/02/skos/core#definition> """Subsidy season for subsidy measure emergency-care (children): \"Spring 2021\""""@en;
            <https://www.gleif.org/ontology/Base/hasStart> "2021-04-19"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2021-06-30"^^<http://www.w3.org/2001/XMLSchema#date>;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "Lente 2021 (19 april 2021 — 30 juni 2021)"@nl ;
            <http://purl.org/dc/terms/title> "Lente"@nl ;
            <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66> .

        ########################################################
        ### PERIOD - TODO — 31/07/2021

        <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66>
            a   <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "02a7807e-5352-44e3-b87c-c69b3876be66" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Submission period for a subsidy season"@en;
            # TODO Should be date of release <https://www.gleif.org/ontology/Base/hasStart> "2021-01-31"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2021-07-31"^^<http://www.w3.org/2001/XMLSchema#date>.
    }
}
