PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lblod: <http://data.lblod.info/id/conceptscheme/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    lblod:LocalOfficerMandateRole rdf:type skos:ConceptScheme ;
      dct:modified "2021-10-05"^^xsd:date ;
      skos:prefLabel "Concept Scheme grouping Officer Mandate Roles for Local Authorities" .

    # functionaris
    #  skos:prefLabel "Algemeen directeur-coordinator" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/932a0598-8f05-480e-abda-229365e99610> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Adjunct Algemeen Directeur" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Financieel directeur-coordinator" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/:d7c00cd1-baf1-4346-83c0-6796c0bedd84> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Algemeen directeur" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/39e08271-68db-4282-897f-5cba88c71862> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "OCMW-secretaris" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/b6eaf1d4-d9b4-409d-a137-af801cf96c67> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Financieel directeur" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/6d4cf4dd-2080-4752-8733-d02a036b2df0> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Financieel beheerder" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/b213c870-c762-4e39-9f78-3abdeda4b64a> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Leidend ambtenaar" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Financieel beheerder van het OCMW" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/1c9ea819-f7c3-4ff6-9e2c-8f83ada5794a> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .

    # functionaris
    #  skos:prefLabel "Griffier" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/63195ec6-02cb-4f86-ac8e-29c5183a11dc> skos:topConceptOf lblod:LocalOfficerMandateRole ;
      skos:inScheme lblod:LocalOfficerMandateRole .
  }
}