DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offers/64d40351-8128-464f-990f-41066154583e>
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Lokale Klimaatacties" ;
      <http://purl.org/dc/terms/title> "Lokale Klimaatacties" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offers/64d40351-8128-464f-990f-41066154583e>
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Lokaal Energie- en KlimaatPact" ;
      <http://purl.org/dc/terms/title> "Lokaal Energie- en KlimaatPact" .
  }
}
