PREFIX m8g: <http://data.europa.eu/m8g/>

DELETE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?deadline
            m8g:endTime ?end .
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        VALUES ?deadline {
            <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd>
            <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
            <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
            <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
        }
        ?deadline
            m8g:endTime ?end .
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd>
            m8g:endTime "2021-06-30T21:59:59Z"^^xsd:dateTime .
        <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
              m8g:endTime "2021-06-30T21:59:59Z"^^xsd:dateTime .
        <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
              m8g:endTime "2021-06-30T21:59:59Z"^^xsd:dateTime .
        <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
            m8g:endTime "2021-06-30T21:59:59Z"^^xsd:dateTime .
    }
}