PREFIX m8g: <http://data.europa.eu/m8g/>

DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            m8g:startTime "2021-06-21T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            m8g:startTime "2021-06-21T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    }
}