# Wrong active step set.
# Many duplicates in the original form, cleaning it out.

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/60C84EA2CA2C910008000153> <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/f135ee39-fff1-4cae-9b87-bf3cd9098b3e> . # step 1
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://schema.org/contactPoint> <http://data.lblod.info/form-data/nodes/66b43ee7-cd77-4839-a736-ce3a8739763b> .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://lblod.data.gift/vocabularies/subsidie/reportUpload> <http://data.lblod.info/form-data/nodes/95c4c367-219b-405c-b04e-43e0c9843f02> .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#estimatedCostTable> <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/table/ea74dad4-ee75-4e7c-87c0-841151b1f7ae> .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#objectiveTable> <http://lblod.data.gift/id/subsidie/bicycle-infrastructure/747fae48-6e30-439b-81ce-708a7f8b16ad> .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-AC3C2C" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-9968FB" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-05E597" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-9211C8" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-FA5A4C" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-E8FC29" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-726EDF" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-760FAC" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-01B9FD" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-DBDF9A" .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://lblod.data.gift/vocabularies/subsidie/decisionUpload> <http://data.lblod.info/form-data/nodes/694dca0c-292f-42e6-8263-0ab91056b1db> .
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://schema.org/bankAccount> <http://data.lblod.info/form-data/nodes/ce0f822b-8f6a-4f55-bdfc-e9b8a7fec070> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/60C84EA2CA2C910008000153> <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397> . # step 2
    <http://data.lblod.info/id/application-forms/60CC9828CA2C91000800003F> <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#identifier> "fiets-subsidie-002B47" .
  }
}