# Time is in UTC

# Increase deadlines
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
      <http://data.europa.eu/m8g/endTime> "2021-06-30T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
      <http://data.europa.eu/m8g/endTime> "2021-06-30T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd>
      <http://data.europa.eu/m8g/endTime> "2021-06-30T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
      <http://data.europa.eu/m8g/endTime> "2021-06-30T21:59:59Z"^^xsd:dateTime .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
  }
}
;
# Preventive fix on deadlines ending at midnight instead of 23h59 later, and add timezone
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/7457e7fb-db09-4dcf-82b1-ed4d08f81ecd>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T00:00:00"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/c979d93f-0f04-4296-a0f9-80306f5606e9>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T00:00:00"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/71ea26df-fd2a-4626-9a4c-93be0eb77367>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T00:00:00"^^xsd:dateTime .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/7457e7fb-db09-4dcf-82b1-ed4d08f81ecd>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/c979d93f-0f04-4296-a0f9-80306f5606e9>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/71ea26df-fd2a-4626-9a4c-93be0eb77367>
      <http://data.europa.eu/m8g/endTime> "2021-07-31T21:59:59Z"^^xsd:dateTime .
  }
}
