PREFIX adms: <http://www.w3.org/ns/adms#>

INSERT {
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76/LoketLB-mandaatGebruiker> {
        <http://data.lblod.info/id/personen/606ECBC6FC6202000800038E> adms:identifier ?id .
        ?id ?p ?o .
    }
} WHERE {
    VALUES ?id {
       <http://data.lblod.info/id/identificator/ac0fb3a1-2ed6-11e9-bd70-3fd92722c1ed>
    }
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76> {
       ?id ?p ?o .
    }
}
;;
INSERT {
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76/LoketLB-leidinggevendenGebruiker> {
        <http://data.lblod.info/id/personen/606ECBC6FC6202000800038E> adms:identifier ?id .
        ?id ?p ?o .
    }
} WHERE {
    VALUES ?id {
       <http://data.lblod.info/id/identificator/ac0fb3a1-2ed6-11e9-bd70-3fd92722c1ed>
    }
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76> {
       ?id ?p ?o .
    }
}
;;
INSERT {
    GRAPH <http://mu.semte.ch/graphs/organizations/2f003f9d0696af25e0864d01b3a40d3d38249d14f253edbafe2ff106237abf1c/LoketLB-mandaatGebruiker> {
        <http://data.lblod.info/id/persoon/d41800db-906c-4bd7-8dab-d0643270a03b> adms:identifier ?id .
        ?id ?p ?o .
    }
} WHERE {
    VALUES ?id {
       <http://data.lblod.info/id/identificator/ac0fb3a1-2ed6-11e9-bd70-3fd92722c1ed>
    }
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76> {
       ?id ?p ?o .
    }
}
;;
INSERT {
    GRAPH <http://mu.semte.ch/graphs/organizations/65cedd4d994aa2e818252bbb4672b7184fccce7edf673d3e5571da51dedf6a3a/LoketLB-mandaatGebruiker> {
        <http://data.lblod.info/id/persoon/d41800db-906c-4bd7-8dab-d0643270a03b> adms:identifier ?id .
        ?id ?p ?o .
    }
} WHERE {
    VALUES ?id {
       <http://data.lblod.info/id/identificator/ac0fb3a1-2ed6-11e9-bd70-3fd92722c1ed>
    }
    GRAPH <http://mu.semte.ch/graphs/organizations/d1a274073309ad03daf4f45139e48d74f26a20f5935376004033cd1d0d40ee76> {
       ?id ?p ?o .
    }
}