PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX lblod: <http://data.lblod.info/id/conceptscheme/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>


INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {

    lblod:LocalPoliticianMandateRole rdf:type skos:ConceptScheme ;
      dct:modified "2021-10-05"^^xsd:date ;
      skos:prefLabel "Concept Scheme grouping Politician Mandate Roles for Local Authorities" .

    #  skos:prefLabel "Districtsraadslid" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001b> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Provincieraadslid" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001f> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Adjunct Financieel Directeur" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Gedeputeerde" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000020> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Gemeenteraadslid" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000011> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van de gemeenteraad" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000012> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Burgemeester" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000013> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Schepen" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000014> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Lid van de Raad voor Maatschappelijk Welzijn" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000015> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van de Raad voor Maatschappelijk Welzijn" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000016> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Lid van het Vast Bureau" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000017> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Lid van het Bijzonder Comité voor de Sociale Dienst" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000019> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van de districtsraad" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001c> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Ocmw-ondervoorzitter" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000023> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van het districtscollege" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000026> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van de provincieraad" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000027> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Gouverneur" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/d7c00cd1-baf1-4346-83c0-6796c0bedd85> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Lid van het districtscollege" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000022> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Districtsschepen" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001e> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van het Vast bureau" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Gemeentesecretaris" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/789f263f-f789-4628-a541-b14fd9d38278> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Districtsburgemeester" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001d> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Voorzitter van het Bijzonder Comité voor de Sociale Dienst" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001a> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .

    #  skos:prefLabel "Toegevoegde schepen" ;
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/59a90e03-4f22-4bb9-8c91-132618db4b38> skos:topConceptOf lblod:LocalPoliticianMandateRole ;
      skos:inScheme lblod:LocalPoliticianMandateRole .
  }
}