PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offer-series/9a40c72c-4761-4cbd-8a85-96c30c3f829c> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      dct:title "September 2021"@nl.
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offer-series/9a40c72c-4761-4cbd-8a85-96c30c3f829c> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      dct:title "Oproep 1"@nl.
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidy-measure-offer-series/9a40c72c-4761-4cbd-8a85-96c30c3f829c> a lblodSubsidie:SubsidiemaatregelAanbodReeks;
      dct:title "September 2021"@nl.
  }
}
