# Avoid sprintf error
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://data.lblod.info/id/aanvraagen/test> <http://data.vlaanderen.be/ns/subsidie#aangevraagdBedrag> <http://data.lblod.info/id/bedrag/test> .
    <http://data.lblod.info/id/bedrag/test> <http://dummy/data/predicate> <http://dummy/data/object> .
    <http://data.lblod.info/id/consumptie/test> <http://www.w3.org/ns/prov#wasGeneratedBy> <http://data.lblod.info/id/aanvraagen/test> ;
      <http://data.europa.eu/m8g/hasParticipation> <http://data.lblod.info/id/participation/test> .
    <http://data.lblod.info/id/bestuur/test> <http://data.europa.eu/m8g/playsRole> <http://data.lblod.info/id/participation/test> .
    <http://data.lblod.info/id/participation/test> <http://dummy/data/predicate> <http://dummy/data/object> .
  }
}

;

DELETE {
  GRAPH ?g {
    ?aanvraag ?paanvraag ?oaanvraag .
    ?bedrag ?pbedrag ?obedrag .
    ?consumptie ?pconsumptie ?oconsumptie .
    ?bestuur <http://data.europa.eu/m8g/playsRole> ?participation .
    ?participation ?pparticipation ?oparticipation .
  }
} WHERE {
  GRAPH ?g {
    ?aanvraag <http://data.vlaanderen.be/ns/subsidie#aangevraagdBedrag> ?bedrag ;
      ?paanvraag ?oaanvraag .
    ?bedrag ?pbedrag ?obedrag .
    ?consumptie <http://www.w3.org/ns/prov#wasGeneratedBy> ?aanvraag ;
      <http://data.europa.eu/m8g/hasParticipation> ?participation ;
      ?pconsumptie ?oconsumptie .
    ?bestuur <http://data.europa.eu/m8g/playsRole> ?participation .
    ?participation ?pparticipation ?oparticipation .

    FILTER (?aanvraag IN (
      <http://data.lblod.info/id/aanvraagen/32b7fe1f4f222f46a8644b6633e24d6f>,
      <http://data.lblod.info/id/aanvraagen/ef31b2ab87672b5077df179b451dcc1a>,
      <http://data.lblod.info/id/aanvraagen/2c67152a24ab0138e4cf3e4a0693b0b9>,
      <http://data.lblod.info/id/aanvraagen/2e5177b974e72c3692cbc8a235bf284a>,
      <http://data.lblod.info/id/aanvraagen/49339a184da508727636f409b61e22df>,
      <http://data.lblod.info/id/aanvraagen/64a62fcbeaff43dab9f817a1ac230653>,
      <http://data.lblod.info/id/aanvraagen/test> # avoid sprintf
    ))
  }
}
