DELETE {
  GRAPH ?g {
    ?period <http://data.europa.eu/m8g/endTime> ?end
  }
} INSERT {
  GRAPH ?g {
    ?period <http://data.europa.eu/m8g/endTime> "2025-09-15T03:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
  }
} WHERE {
  GRAPH ?g {
    ?step <https://data.vlaanderen.be/ns/mobiliteit#periode> ?period .
    ?period <http://data.europa.eu/m8g/endTime> ?end .
    VALUES ?step {
      <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d>
    } 
  }
}
