# This migrations removes SMC which were not properly migrated during the big move towards flow support of subsidies
# These forms were only partially filled in and did not contain sufficient information to be migrated.

# Sprintf workaround
INSERT DATA {
  GRAPH <http://sprinf.mu.semte.ch/graphs/dd9a3548-93cf-400b-826b-890f2d047be5> {
    <http://foo/275be3ed-61b1-4688-ab65-92ddaed8b03d> <http://bar> <http://baz>
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
}
WHERE {
  GRAPH ?g {
    ?s ?p ?o
  }

  VALUES ?s {
    <http://data.lblod.info/subsidiemaatregel-consumpties/97c2eeb2-ccf8-4691-8a40-94ff3aace271>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/0293be7e7dbd616417096a4f0a137fb7>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/9c0543153eb43d47f88f50c59e5bcbf9>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/50fdc725ef1bea0fc100476fafd3db5b>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/f3d8d4883c217f08a3673b2607618f82>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/04bf4574acb51e21a61f8a57c594ed2f>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/e72da4588c11f6fb4cf458ccbcfa6139>
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/70ad8f7202125930c2e259d339333c12>
    <http://foo/275be3ed-61b1-4688-ab65-92ddaed8b03d>
  }
}

;

# Sprintf workaround
DELETE DATA {
  GRAPH <http://sprinf.mu.semte.ch/graphs/dd9a3548-93cf-400b-826b-890f2d047be5> {
    <http://foo/275be3ed-61b1-4688-ab65-92ddaed8b03d> <http://bar> <http://baz>
  }
}