PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20231004172419-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "b7fe0f8e-2320-427f-94de-473b58389715" ;
      nfo:fileName "20231004172419-forms.ttl" ;
      dct:created "2023-10-04T17:24:19"^^xsd:dateTime ;
      dct:modified "2023-10-04T17:24:19"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "375420"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    