PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct:  <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/77604806-1006-459b-9228-583d279c7a1c>
        a skos:ConceptScheme, rdfs:Class ;
        mu:uuid "77604806-1006-459b-9228-583d279c7a1c" ;
        dct:title "subsidy-procedure-step-types"@en ;
        dct:title "subsidieprocedure-stap-types"@nl .

    <http://lblod.data.gift/concepts/ee855aae-eb10-44aa-ae01-38c4f6cca0f6>
        a skos:Concept, rdfs:Class;
        mu:uuid "ee855aae-eb10-44aa-ae01-38c4f6cca0f6" ;
        skos:prefLabel "Aanvraag"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/77604806-1006-459b-9228-583d279c7a1c> .
  }
}
