PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{
    <http://lblod.data.info/id/subsidie-application-flow-steps/b9034a4b-adf6-4077-8dae-f9bebae4515e> dct:source <config://forms/climate/step-submit-pact/versions/20210420172044/form.ttl>.
    <http://lblod.data.info/id/subsidie-application-flow-steps/c50d7726-4880-43e2-b098-c356722a3096> dct:source <config://forms/climate/step-submit-proposal/versions/20210420172044/form.ttl>.
  }
}