PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT {
  GRAPH ?g {
   ?afs dct:source <config://forms/emergency-day-care/versions/20210420104208-initial-version/form.ttl>.
  }
}
WHERE {
  GRAPH ?h {
    <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38> lblodSubsidie:heeftReeks ?series .
    ?series common:active ?af .
    ?afs dct:isPartOf ?af .
  }
  BIND(?h as ?g)
}