PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

############################################################
## DELETE all period data for bicycle subsidies
DELETE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?series
            dct:title ?title ;
            mobiliteit:periode ?claim .
        ?claim ?cp ?co .
        ?step mobiliteit:periode ?deadline .
        ?deadline ?dp ?do .
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        VALUES ?series {
            <http://lblod.data.info/id/subsidy-measure-offer-series/87b87f00-6f87-4412-be26-ea531220457c>
        }
        ?series
            dct:title ?title ;
            mobiliteit:periode ?claim ;
            lblodSubsidie:heeftSubsidieprocedurestap ?step .

        ?step mobiliteit:periode ?deadline .

        ?claim ?cp ?co .
        ?deadline ?dp ?do .
    }
}
;
###################################################################
# INSERT claim & deadline for emergency contact-tracing, Winter
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/d7b3851d-70f7-4929-b226-73d3343c954d>
            a m8g:PeriodOfTime ;
            mu:uuid "d7b3851d-70f7-4929-b226-73d3343c954d" ;
            m8g:startTime "2021-01-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2025-12-31T00:00:00"^^xsd:dateTime .

        <http://lblod.data.info/id/subsidy-measure-offer-series/87b87f00-6f87-4412-be26-ea531220457c>
            mobiliteit:periode <http://data.lblod.info/id/periodes/d7b3851d-70f7-4929-b226-73d3343c954d> .

        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            a m8g:PeriodOfTime ;
            mu:uuid "6123b1b9-b75b-4235-9cc6-58b1d7fa6872" ;
            m8g:startTime "2021-05-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2026-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidy-procedural-steps/d6ec1fb1-a991-47ba-95f1-afdd87e4553c> # Pact
            mobiliteit:periode <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872> .

        <http://data.lblod.info/id/periodes/a7de09df-c62f-4c70-a8fa-b9634112d10e>
            a m8g:PeriodOfTime ;
            mu:uuid "a7de09df-c62f-4c70-a8fa-b9634112d10e" ;
            # m8g:startTime "2021-05-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2026-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidy-procedural-steps/233f0b64-d261-469e-9ef3-e0e2d64d42de> # Proposal
            mobiliteit:periode <http://data.lblod.info/id/periodes/a7de09df-c62f-4c70-a8fa-b9634112d10e> .

        <http://data.lblod.info/id/periodes/c251381e-300f-43e0-a83c-b1ffdfd06b48>
            a m8g:PeriodOfTime ;
            mu:uuid "c251381e-300f-43e0-a83c-b1ffdfd06b48" ;
            # m8g:startTime "2021-05-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2026-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidy-procedural-steps/c6c9af62-a29b-11eb-b06c-9bc0fbd1bfa6> # Request
            mobiliteit:periode <http://data.lblod.info/id/periodes/c251381e-300f-43e0-a83c-b1ffdfd06b48> .
    }
}