PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dbpedia: <http://dbpedia.org/resource/>


##########################################################
# ADD old-meta file to the data
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <data://meta-files/initial/20210401111656-meta.ttl>
            a nfo:FileDataObject;
            mu:uuid """1ddcf650-929d-4c02-bcc5-13823bfc1ae2""" ;
            nfo:fileName "20210401111656-meta.ttl" ;
            dct:format "application/n-triples" ;
            dbpedia:fileExtension ".ttl" ;
            dct:created """2021-04-29"""^^xsd:date ;
            dct:modified """2021-04-29"""^^xsd:date .
    }
}