INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/70cc4947-33a3-4d26-82e0-2e1eacd2fea2>
        a   <http://www.w3.org/2000/01/rdf-schema#Class>,
            <http://www.w3.org/2004/02/skos/core#Concept>,
            <http://www.w3.org/2004/02/skos/core#ConceptScheme>,
            <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelAanbod>;
        <http://mu.semte.ch/vocabularies/core/uuid> "70cc4947-33a3-4d26-82e0-2e1eacd2fea2" ;
        <http://www.w3.org/2004/02/skos/core#definition> "Subsidy measure offer: Bicycle infrastructure"@en;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/33e233eb-6a9b-4141-b607-2ff72fe2ded2>;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Fietsinfrastructuur"@nl ;
        <http://purl.org/dc/terms/title> "Fietsinfrastructuur"@nl .
  }
}
