PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH ?h {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> skos:prefLabel ?o .
  }
} INSERT {
  GRAPH ?h {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f>  skos:prefLabel  """26 februari 2021 — 30 september 2022 (aanmelding)"""@nl .
  }
} WHERE {
  GRAPH ?g {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> skos:prefLabel ?o .
  }
  BIND(?g as ?h)
}