INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f>
            a   <http://www.w3.org/2004/02/skos/core#Concept>,
                <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "2e77f4ea-05f6-4771-ae4b-8cee72d2459f" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Timeblock: 2021-2025"@en;
            <https://www.gleif.org/ontology/Base/hasStart> "2021-03-26"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2025-09-15"^^<http://www.w3.org/2001/XMLSchema#date>;
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concepts/70cc4947-33a3-4d26-82e0-2e1eacd2fea2>;
            <http://www.w3.org/2004/02/skos/core#prefLabel> "26 maart 2021 — 15 september 2025"@nl ;
            <http://mu.semte.ch/vocabularies/ext/submissionPeriod> <http://lblod.data.gift/periods/f90004eb-e65d-4cd5-91ae-e342b0d26700>.
        <http://lblod.data.gift/periods/f90004eb-e65d-4cd5-91ae-e342b0d26700>
            a   <http://www.w3.org/2000/01/rdf-schema#Class>,
                <https://www.gleif.org/ontology/Base/Period>;
            <http://mu.semte.ch/vocabularies/core/uuid> "f90004eb-e65d-4cd5-91ae-e342b0d26700" ;
            <http://www.w3.org/2004/02/skos/core#definition> "Submission Period for timeblock"@en;
            <https://www.gleif.org/ontology/Base/hasStart> "2021-01-01"^^<http://www.w3.org/2001/XMLSchema#date>;
            <https://www.gleif.org/ontology/Base/hasEnd> "2025-12-31"^^<http://www.w3.org/2001/XMLSchema#date>.
    }
}