INSERT DATA {

  GRAPH <http://mu.semte.ch/graphs/public> {
  
    <https://data.vlaanderen.be/id/concept/BesluitType/8597e056-b96d-4213-ad4c-37338f2aaf35> a <http://www.w3.org/2004/02/skos/core#Concept>;
       <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
       <http://www.w3.org/2004/02/skos/core#prefLabel> "Kohierbelasting"@nl;
       <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/ac9bc402-c8e6-41fd-ad57-fad15622e560> .

    <https://data.vlaanderen.be/id/concept/BesluitType/b2d0734d-13d0-44b4-9af8-1722933c5288> a <http://www.w3.org/2004/02/skos/core#Concept>;
       <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
       <http://www.w3.org/2004/02/skos/core#prefLabel> "Aanvullende belasting of opcentiem"@nl;
       <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/ac9bc402-c8e6-41fd-ad57-fad15622e560> .

    <https://data.vlaanderen.be/id/concept/BesluitType/4c22ef0a-f808-41dd-9c9f-2aff17fd851f> a <http://www.w3.org/2004/02/skos/core#Concept>;
       <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/3037c4f4-1c63-43ac-bfc4-b41d098b15a6>;
       <http://www.w3.org/2004/02/skos/core#prefLabel> "Contantbelasting"@nl;
       <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/ac9bc402-c8e6-41fd-ad57-fad15622e560> .

   <https://data.vlaanderen.be/id/concept/BesluitType/8597e056-b96d-4213-ad4c-37338f2aaf35> <http://mu.semte.ch/vocabularies/core/uuid> "332f06e0ac5a934407648281bf2564c8bc796bdb9c5e79ab6d928d0788770d4e" .
   <https://data.vlaanderen.be/id/concept/BesluitType/8597e056-b96d-4213-ad4c-37338f2aaf35> a <http://mu.semte.ch/vocabularies/ext/TaxType> .

   <https://data.vlaanderen.be/id/concept/BesluitType/b2d0734d-13d0-44b4-9af8-1722933c5288> <http://mu.semte.ch/vocabularies/core/uuid> "3a815e496cadcc497ead75d7ceea376a4a523f3ff765b32abf1ec608fe6b6746" .
   <https://data.vlaanderen.be/id/concept/BesluitType/b2d0734d-13d0-44b4-9af8-1722933c5288> a <http://mu.semte.ch/vocabularies/ext/TaxType> .

   <https://data.vlaanderen.be/id/concept/BesluitType/4c22ef0a-f808-41dd-9c9f-2aff17fd851f> <http://mu.semte.ch/vocabularies/core/uuid> "50dcd5efc1a21ccb619bb761eef40e300eed9e6b59eb9cc9d49e9b47bbb57779" .
   <https://data.vlaanderen.be/id/concept/BesluitType/4c22ef0a-f808-41dd-9c9f-2aff17fd851f> a <http://mu.semte.ch/vocabularies/ext/TaxType> .

  }

}