PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/automatic-submission> {
    <http://data.lblod.info/vendors/lblod-as-vendor/993b42f4-bd97-44ab-9719-667146a78f86> a foaf:Agent ;
    foaf:name "lblod submitter" ;
    mu:uuid "993b42f4-bd97-44ab-9719-667146a78f86" .
  }
}
