PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA{
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
   <share://semantic-forms/20210120121332-forms.ttl> a nfo:FileDataObject ;
 				  dct:type <http://data.lblod.gift/concepts/form-file-type> ;
                                  mu:uuid "dfb3c5b7-31e8-4764-9d3b-d34b83c9724d" ;
                                  nfo:fileName "20210120121332-forms.ttl" ;
                                  dct:created "2021-01-20Z"^^xsd:dateTime;
                                  dct:modified "2021-01-20Z"^^xsd:dateTime;
                                  dct:format "text/turtle";
                                  nfo:fileSize "250300"^^xsd:integer;
                                  dbpedia:fileExtension "ttl" .
  }
}
