PREFIX dct: <http://purl.org/dc/terms/>
PREFIX org: <http://www.w3.org/ns/org#>

CONSTRUCT {
  ?s ?p ?oString .
} WHERE {
  ?s a org:ChangeEvent;
    ?p ?o.

  FILTER (?p IN (
    dct:description
  ))

  BIND(STR(?o) AS ?oString)
}
