PREFIX mg8: <http://data.europa.eu/m8g/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Period of step Indienen pact
    <http://data.lblod.info/id/periodes/0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389> mg8:endTime "2022-10-28T21:59:00Z"^^xsd:dateTime .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://data.lblod.info/id/periodes/0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389> mg8:endTime "2022-12-05T21:59:00Z"^^xsd:dateTime .
  }
}