PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # Period of the series
    <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f>
        a mg8:PeriodOfTime ;
        mu:uuid "f3357ba2-abd4-44b3-a66b-70e8f3f9671f" ;
        mg8:startTime "2020-12-25T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2021-12-25T21:59:59Z"^^xsd:dateTime .

    # Step(s) of the series
    <http://data.lblod.info/id/subsidy-procedural-steps/570fb5da-4874-46f5-8adb-3467cf88f3f2>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "570fb5da-4874-46f5-8adb-3467cf88f3f2";
        dct:description """Externe verwerking""";
        subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/3ded9eab-ff5b-4a20-a095-0825de486f42> ; # External processing
        mobiliteit:periode <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f>.

    # Series for call up off 2021
    <http://lblod.data.info/id/subsidy-measure-offer-series/3bfba485-f211-445c-80b7-e340c410ce1d>
        a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
        mu:uuid "3bfba485-f211-445c-80b7-e340c410ce1d" ;
        dct:title "Oproep 2021"@nl ;
        dct:description "25/12/2020 — 25/12/2021"@nl ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f> .

    # Offer for "hoppinpunten"
    <http://lblod.data.info/id/subsidy-measure-offers/b6e5ccd5-ddaf-4b74-b023-a712886f3814>
        a subsidie:SubsidiemaatregelAanbod;
        mu:uuid "b6e5ccd5-ddaf-4b74-b023-a712886f3814";
        dct:title """Subsidie voor hoppinpunten""";
        skos:prefLabel """Subsidie voor hoppinpunten""";
        skos:related <https://www.vlaanderen.be/basisbereikbaarheid/combimobiliteit/hoppinpunten>;
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/570fb5da-4874-46f5-8adb-3467cf88f3f2>;
        lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/3bfba485-f211-445c-80b7-e340c410ce1d>.
  }
}