INSERT {
  GRAPH ?g {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/subsidies/bicycle-infrastructure/decision-upload/FormData> .
  }
}
WHERE {
  GRAPH ?g {
    ?applicationForm <http://lblod.data.gift/vocabularies/subsidie/decisionUpload> ?formData .
    ?formData ?p_f ?o_f .
  }

  FILTER NOT EXISTS {
    ?formData <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
  }
}
