PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>

CONSTRUCT {
  ?s a besluit:Bestuurseenheid, regorg:RegisteredOrganization ;
    skos:topConceptOf <http://lblod.data.gift/concept-schemes/7e2b965e-c824-474f-b5d5-b1c115740083> ;
    skos:inScheme <http://lblod.data.gift/concept-schemes/7e2b965e-c824-474f-b5d5-b1c115740083> .
} WHERE {
  ?s a regorg:RegisteredOrganization.
}
