PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>

# Move the tailored-meta files
DELETE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?vFile a nfo:FileDataObject;
            mu:uuid ?vUUID;
            nfo:fileName ?vName;
            dct:format ?vMime;
            dbpedia:fileExtension ?vExt;
            dct:created ?vCreated;
            dct:modified ?vModified;
            dct:publisher ?vPublisher.
        ?tailored a nfo:FileDataObject;
            mu:uuid ?pUUID;
            nfo:fileName ?pName;
            dct:format ?pMime;
            dbpedia:fileExtension ?pExt;
            dct:created ?pCreated;
            dct:modified ?pModified;
            nie:dataSource ?vFile.
    }
}
INSERT {
  GRAPH ?g {
        ?vFile a nfo:FileDataObject;
            mu:uuid ?vUUID;
            nfo:fileName ?vName;
            dct:format ?vMime;
            dbpedia:fileExtension ?vExt;
            dct:created ?vCreated;
            dct:modified ?vModified;
            dct:publisher ?vPublisher.
        ?tailored a nfo:FileDataObject;
            mu:uuid ?pUUID;
            nfo:fileName ?pName;
            dct:format ?pMime;
            dbpedia:fileExtension ?pExt;
            dct:created ?pCreated;
            dct:modified ?pModified;
            nie:dataSource ?vFile.
  }
}
WHERE {
    GRAPH ?g {
        ?uri rdf:type <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm>;
            dct:source ?tailored.
        FILTER(REGEX(STR(?tailored), "^data:\\/\\/tailored-meta-files\\/.*-additions-meta.ttl"))
    }
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?vFile a nfo:FileDataObject;
            mu:uuid ?vUUID;
            nfo:fileName ?vName;
            dct:format ?vMime;
            dbpedia:fileExtension ?vExt;
            dct:created ?vCreated;
            dct:modified ?vModified;
            dct:publisher ?vPublisher.
        ?tailored a nfo:FileDataObject;
            mu:uuid ?pUUID;
            nfo:fileName ?pName;
            dct:format ?pMime;
            dbpedia:fileExtension ?pExt;
            dct:created ?pCreated;
            dct:modified ?pModified;
            nie:dataSource ?vFile.
    }
    FILTER(REGEX(STR(?userGraph), "^http://mu.semte.ch/graphs/organizations/"))
}