PREFIX dbpediaResource: <http://dbpedia.org/resource/>
PREFIX dbpediaOntology: <http://dbpedia.org/ontology/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
    GRAPH ?g {
        ?vFile
            dbpediaResource:fileExtension ?vExt.
        ?pFile
            dbpediaResource:fileExtension ?pExt.
    }
}
INSERT {
    GRAPH ?g {
        ?vFile
            dbpediaOntology:fileExtension ?vExt.
        ?pFile
            dbpediaOntology:fileExtension ?pExt.
    }
}
WHERE {
    GRAPH ?g {
        ?vFile
            dbpediaResource:fileExtension ?vExt;
            dct:publisher ?publisher.
        ?pFile
            dbpediaResource:fileExtension ?pExt;
            nie:dataSource ?vFile.
    }
    FILTER(REGEX(STR(?publisher), "^http://data.lblod.info/services/subsidy-application-management-service"))
}
