PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>

# Avoid sprintf error: adding dummy data
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dummy/data/form> a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
            dct:source <share://versions/20201130150729-form> ,
                       <share://versions/20201207135752-form> ,
                       <share://versions/20210108094916-form> ,
                       <share://versions/20210113150324-form> ,
                       <share://versions/20210113153339-form> ,
                       <share://versions/20210121152225-introduction-subsidy-form-contact-tracing> .
  }
}

;

# Update source for semantic-forms with version <share://versions/20201130150729-form>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20201130150729-form> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20201130150729/form.ttl> ,
                  <config://versions/20201130150729/form.json> ,
                  <config://versions/20201130150729/mapper.js> ,
                  <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20201130150729-form> .
  }
  BIND(?g as ?h)
}

;

# Update source for semantic-forms with version <share://versions/20201207135752-form>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20201207135752-form> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20201207135752/form.ttl> ,
                  <config://versions/20201207135752/form.json> ,
                  <config://versions/20201207135752/mapper.js> ,
                  <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20201207135752-form> .
  }
  BIND(?g as ?h)
}

;

# Update source for semantic-forms with version <share://versions/20210108094916-form>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20210108094916-form> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20210108094916/form.ttl> ,
                  <config://versions/20210108094916/form.json> ,
                  <config://versions/20210108094916/mapper.js> ,
                  <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20210108094916-form> .
  }
  BIND(?g as ?h)
}

;

# Update source for semantic-forms with version <share://versions/20210108094916-form>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20210113150324-form> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20210113150324/form.ttl> ,
                  <config://versions/20210113150324/form.json> ,
                  <config://versions/20210113150324/mapper.js>
                  <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20210113150324-form> .
  }
  BIND(?g as ?h)
}

;

# Update source for semantic-forms with version <share://versions/20210113153339-form>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20210113153339-form> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20210113153339/form.ttl> ,
                  <config://versions/20210113153339/form.json> ,
                  <config://versions/20210113153339/mapper.js> ,
                  <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20210113153339-form> .
  }
  BIND(?g as ?h)
}

;

# Update source for semantic-forms with version <share://versions/20210121152225-introduction-subsidy-form-contact-tracing>
DELETE {
  GRAPH ?h {
    ?s dct:source <share://versions/20210121152225-introduction-subsidy-form-contact-tracing> .
  }
} INSERT {
  GRAPH ?h {
    ?s dct:source <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/form.ttl> ,
                  <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/form.json> ,
                  <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/mapper.js> ,
                  <data://meta-files/20210204172413-after-contact-tracing-meta.ttl> .
  }
} WHERE {
  GRAPH ?g {
    ?s dct:source <share://versions/20210121152225-introduction-subsidy-form-contact-tracing> .
  }
  BIND(?g as ?h)
}

;

# Avoid sprintf error: delete dummy data
DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dummy/data/form> a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
            dct:source <config://versions/20201130150729/form.ttl> ,
                       <config://versions/20201130150729/form.json> ,
                       <config://versions/20201130150729/mapper.js> ,
                       <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> ,
                       <config://versions/20201207135752/form.ttl> ,
                       <config://versions/20201207135752/form.json> ,
                       <config://versions/20201207135752/mapper.js> ,
                       <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> ,
                       <config://versions/20210108094916/form.ttl> ,
                       <config://versions/20210108094916/form.json> ,
                       <config://versions/20210108094916/mapper.js> ,
                       <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> ,
                       <config://versions/20210113150324/form.ttl> ,
                       <config://versions/20210113150324/form.json> ,
                       <config://versions/20210113150324/mapper.js> ,
                       <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> ,
                       <config://versions/20210113153339/form.ttl> ,
                       <config://versions/20210113153339/form.json> ,
                       <config://versions/20210113153339/mapper.js> ,
                       <data://meta-files/20210204172412-before-contact-tracing-meta.ttl> ,
                       <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/form.ttl> ,
                       <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/form.json> ,
                       <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/mapper.js> ,
                       <data://meta-files/20210204172412-after-contact-tracing-meta.ttl> .
  }
}