(define-resource log-entry ()
  :class (s-prefix "rlog:Entry")
  :properties `((:class-name :url ,(s-prefix "rlog:className"))
                (:source :url ,(s-prefix "dct:source"))
                (:message :string ,(s-prefix "rlog:message"))
                (:resource :url ,(s-prefix "rlog:resource"))
                (:datetime :datetime ,(s-prefix "rlog:date")))
  :has-one `((log-level :via ,(s-prefix "rlog:level")
                   :as "log-level")
              (status-code :via ,(s-prefix "rlog:hasCode")
                   :as "status-code"))
  :resource-base (s-url "http://data.lblod.info/id/log-entries/")
  :features `(include-uri)
  :on-path "log-entries")

(define-resource log-level ()
  :class (s-prefix "rlog:Level")
  :properties `((:priority :number ,(s-prefix "rlog:priority"))
                (:label :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://data.lblod.info/id/log-levels/")
  :features `(include-uri)
  :on-path "log-levels")

(define-resource status-code ()
  :class (s-prefix "rlog:StatusCode")
  :properties `((:code :number ,(s-prefix "rlog:codeId")))
  :resource-base (s-url "http://data.lblod.info/id/status-codes/")
  :features `(include-uri)
  :on-path "status-codes")

(define-resource acm-idm-service-log-entry ()
  :class (s-prefix "ext:AcmIdmServiceLogEntry")
  :properties `((:session-uri :url ,(s-prefix "ext:sessionUri"))
                (:kbonummer :string ,(s-prefix "ext:kbonummer")))
  :resource-base (s-url "http://data.lblod.info/id/acm-idm-service-log-entries/")
  :features `(include-uri)
  :on-path "acm-idm-service-log-entries")
