(define-resource bbcdr-report ()
  :class (s-prefix "bbcdr:Report") ;; subclass of nie:InformationElement > nfo:DataContainer
  :properties `((:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-one `((document-status :via ,(s-prefix "adms:status")
                              :as "status")
             (gebruiker :via ,(s-prefix "ext:lastModifiedBy")
                      :as "last-modifier")
             (bestuurseenheid :via ,(s-prefix "dct:subject")
                      :as "bestuurseenheid"))
  :has-many `((file :via ,(s-prefix "nie:hasPart")
                    :as "files"))
  :resource-base (s-url "http://data.lblod.info/bbcdr-reports/")
  :on-path "bbcdr-reports")
