(define-resource harvesting-collection ()
  :class (s-prefix "hrvst:HarvestingCollection")
  :properties `((:status :url ,(s-prefix "adms:status"))
                (:creator :url ,(s-prefix "dct:creator")))
  :has-one `((authentication-configuration :via ,(s-prefix "dgftSec:targetAuthenticationConfiguration")
              :as "authentication-configuration"))              
  :has-many `((remote-data-object :via ,(s-prefix "dct:hasPart")
                                  :as "remote-data-objects")
              (data-container :via ,(s-prefix "task:hasHarvestingCollection")
                              :inverse t
                              :as "data-container"))
  :resource-base (s-url "http://data.lblod.info/id/harvesting-collection/")
  :features '(include-uri)
  :on-path "harvesting-collections")