(define-resource application-form ()
  :class (s-prefix "lblodSubsidie:ApplicationForm")
  :properties `((:aangevraagd-bedrag :number ,(s-prefix "subsidie:aangevraagdBedrag"))
                (:aanvraagdatum :datetime ,(s-prefix "subsidie:aanvraagdatum"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:usedFormFile :uri ,(s-prefix "lblodSubsidie:usedFormFile"))
                (:can-be-paid-on-known-bank-account :bool ,(s-prefix "lblodSubsidie:canBePaidOnKnownBankAccount")))
  :has-one `((bestuurseenheid :via ,(s-prefix "pav:createdBy")
                              :as "organization")
             (contact-punt :via ,(s-prefix "schema:contactPoint")
                            :as "contactinfo")
             (bank-account :via ,(s-prefix "schema:bankAccount")
                           :as "bank-account")
             (time-block :via ,(s-prefix "lblodSubsidie:timeBlock")
                         :as "time-block")
             (gebruiker :via ,(s-prefix "ext:lastModifiedBy")
                        :as "last-modifier")
             (gebruiker :via ,(s-prefix "dct:creator")
                        :as "creator")
             (submission-document-status :via ,(s-prefix "adms:status")
                                         :as "status"))
  :resource-base (s-url "http://data.lblod.info/subsidie-aanvragen/")
  :features '(include-uri)
  :on-path "application-forms")

(define-resource bank-account ()
  :class (s-prefix "schema:BankAccount")
  :properties `((:bank-account-number :string ,(s-prefix "schema:identifier")))
  :resource-base (s-url "http://data.lblod.info/bank-accounts/")
  :features '(include-uri)
  :on-path "bank-accounts")

(define-resource time-block () ;; subclass of skos:Concept
  :class (s-prefix "gleif:Period")
  :properties `((:label :string ,(s-prefix "skos:label"))
                (:start :date ,(s-prefix "gleif:hasStart"))
                (:end :date ,(s-prefix "gleif:hasEnd")))
  :has-one `((concept-scheme :via ,(s-prefix "skos:inScheme")
                              :as "concept-scheme"))
  :resource-base (s-url "http://lblod.data.gift/concepts/")
  :features '(include-uri)
  :on-path "time-blocks")
