(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "tmp" "http://mu.semte.ch/vocabularies/tmp/")

(add-prefix "besluit" "http://data.vlaanderen.be/ns/besluit#")
(add-prefix "mandaat" "http://data.vlaanderen.be/ns/mandaat#")
(add-prefix "persoon" "http://data.vlaanderen.be/ns/persoon#") ;;  TODO: this is incorrect, should be https
(add-prefix "generiek" "http://data.vlaanderen.be/ns/generiek#") ;; TODO: this is incorrect, should be https
(add-prefix "subsidie" "http://data.vlaanderen.be/ns/subsidie#")

(add-prefix "eli" "http://data.europa.eu/eli/ontology#")
(add-prefix "m8g" "http://data.europa.eu/m8g/")
(add-prefix "dcat" "http://www.w3.org/ns/dcat#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "cpsv" "http://purl.org/vocab/cpsv#")
(add-prefix "dul" "http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "person" "http://www.w3.org/ns/person#")
(add-prefix "org" "http://www.w3.org/ns/org#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "regorg" "https://www.w3.org/ns/regorg#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "nao" "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#")
(add-prefix "pav" "http://purl.org/pav/")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "schema" "http://schema.org/")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "export" "http://mu.semte.ch/vocabularies/ext/export/")
(add-prefix "bbcdr" "http://mu.semte.ch/vocabularies/ext/bbcdr/")
(add-prefix "validation" "http://mu.semte.ch/vocabularies/validation/")
(add-prefix "toezicht" "http://mu.semte.ch/vocabularies/ext/supervision/")
(add-prefix "toezichtReport" "http://mu.semte.ch/vocabularies/ext/supervision/reporting/")
(add-prefix "nmo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#")

(add-prefix "email" "http://mu.semte.ch/vocabularies/ext/email/")
(add-prefix "lblodlg" "http://data.lblod.info/vocabularies/leidinggevenden/")

(add-prefix "rlog" "http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#")

(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "adres" "https://data.vlaanderen.be/ns/adres#")

(add-prefix "empl" "http://lblod.data.gift/vocabularies/employee/")
(add-prefix "sdmxDim" "http://purl.org/linked-data/sdmx/2009/dimension#")
(add-prefix "sdmxAttr" "http://purl.org/linked-data/sdmx/2009/attribute#")
(add-prefix "sdmxMeasure" "http://purl.org/linked-data/sdmx/2009/measure#")
(add-prefix "sdmxCode" "http://purl.org/linked-data/sdmx/2009/code#")
(add-prefix "qb" "http://purl.org/linked-data/cube#")
(add-prefix "time" "http://www.w3.org/2006/time#")

(add-prefix "meb" "http://rdf.myexperiment.org/ontologies/base/")
(add-prefix "melding" "http://lblod.data.gift/vocabularies/automatische-melding/")
(add-prefix "muAccount" "http://mu.semte.ch/vocabularies/account/")
(add-prefix "elod" "http://linkedeconomy.org/ontology#")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "sign" "http://mu.semte.ch/vocabularies/ext/signing/")
(add-prefix "lblodBesluit" "http://lblod.data.gift/vocabularies/besluit/")
(add-prefix "lblodSubsidie" "http://lblod.data.gift/vocabularies/subsidie/")
(add-prefix "gleif" "https://www.gleif.org/ontology/Base/")
(add-prefix "transactie" "http://data.vlaanderen.be/ns/transactie#")
(add-prefix "mobiliteit" "https://data.vlaanderen.be/ns/mobiliteit#")
(add-prefix "task" "http://redpencil.data.gift/vocabularies/tasks/")
(add-prefix "common" "http://www.w3.org/2007/uwa/context/common.owl#")
(add-prefix "xkos" "http://rdf-vocabulary.ddialliance.org/xkos#")
(add-prefix "hrvst" "http://lblod.data.gift/vocabularies/harvesting/")
(add-prefix "ndo" "http://oscaf.sourceforge.net/ndo.html#")
(add-prefix "rpioHttp" "http://redpencil.data.gift/vocabularies/http/")
(add-prefix "http" "http://www.w3.org/2011/http#")
(add-prefix "nuao" "http://www.semanticdesktop.org/ontologies/2010/01/25/nuao#")
(add-prefix "lblodJob" "http://lblod.data.gift/vocabularies/lblodJob/")
(add-prefix "oslc" "http://open-services.net/ns/core#")
(add-prefix "cogs" "http://vocab.deri.ie/cogs#")
(add-prefix "ere" "http://data.lblod.info/vocabularies/erediensten/")
(add-prefix "ch" "http://data.lblod.info/vocabularies/contacthub/")
(add-prefix "code" "http://lblod.data.gift/vocabularies/organisatie/")
(add-prefix "euvoc" "http://publications.europa.eu/ontology/euvoc#")
(add-prefix "organisatie" "https://data.vlaanderen.be/ns/organisatie#")

(add-prefix "pera" "http://publications.europa.eu/resource/authority/")
