(define-resource inzending-voor-toezicht()
  :class (s-prefix "ext:InzendingVoorToezicht")
  :resource-base (s-url "http://data.lblod.info/inzendingen-voor-toezicht/")
  :on-path "inzendingen-voor-toezicht")

(define-resource form-solution ()
  :class (s-prefix "ext:FormSolution")
  :properties `((:has-owner :string ,(s-prefix "ext:hasOwnerAsString")))
  :has-one `((form-node :via ,(s-prefix "ext:hasForm")
                        :as "form-node")
             (inzending-voor-toezicht :via ,(s-prefix "ext:hasInzendingVoorToezicht")
                      :as "inzending-voor-toezicht"))
  :resource-base (s-url "http://data.lblod.info/form-solutions/")
  :on-path "form-solutions")
