PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>

CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a org:Membership;
    ?p ?o.

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    org:organization,
    org:member,
    org:role
  ))
}
