PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20240227114037-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "23039495-113b-4bd0-a751-17f8b855bdcf" ;
      nfo:fileName "20240227114037-forms.ttl" ;
      dct:created "2024-02-27T11:40:37"^^xsd:dateTime ;
      dct:modified "2024-02-27T11:40:37"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "441047"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    