DELETE { GRAPH ?g {
    ?form <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#objectiveTable> ?table.
    ?table ?tablePreds ?tableObjects.
    ?entry ?entryPreds ?entryObjects.
  }
}
WHERE { GRAPH ?g {
    ?form ?mu "61B8C816E4465300080003FD";
      <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#objectiveTable> ?table.
    ?table ?tablePreds ?tableObjects.
    ?table <http://lblod.data.gift/vocabularies/subsidie/bicycle-infrastructure#objectiveEntry> ?entry.
    ?entry ?entryPreds ?entryObjects.
  }
}