# Those triples have a notion of versionning.
# We will delete them if they are old enough and have a more recent version of them.
# That way we ensure keeping at least one version, even if it's an old one.

# Reports : comparing on the title to find same type reports, deleting the ones older
# than a month and with a more recent version of the same type.

# The query is heavy, so splitting on title.

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of Send GzG Report" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of Send GzG Report" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of balance requests for fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of balance requests for fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of contact tracing subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of contact tracing subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of pacts for climate subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of pacts for climate subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of proposals of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of proposals of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of requests of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of requests of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of requests of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of requests of fiets subsidies" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of the gemeentewegen submissions of the Toezicht part of Loket" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of the gemeentewegen submissions of the Toezicht part of Loket" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of the submissions of the Toezicht part of Loket" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List of the submissions of the Toezicht part of Loket" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List persons having two different first names" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "List persons having two different first names" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Mandatendatabank CSV" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Mandatendatabank CSV" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Persons missing data CSV" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Persons missing data CSV" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Totaal aantal BBC-DR Dossiers" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "Totaal aantal BBC-DR Dossiers" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?reportToProcess ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?reportToProcess a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "contactTracingSubsidiesDetailedReport" ;
      <http://purl.org/dc/terms/created> ?createdReportToProcess .

    FILTER (?createdReportToProcess < "2021-12-31"^^<http://www.w3.org/2001/XMLSchema#date>)

    ?reportToCompare a <http://lblod.data.gift/vocabularies/reporting/Report> ;
      <http://purl.org/dc/terms/title> "contactTracingSubsidiesDetailedReport" ;
      <http://purl.org/dc/terms/created> ?createdReportToCompare .

    FILTER (?createdReportToProcess < ?createdReportToCompare)

    ?reportToProcess ?p ?o .
  }
}
