# Those errors are created when an error happen in the delta flow. They might be linked to
# nothing and they have no date indication. We assume we can clear them entirely once in a while.

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://redpencil.data.gift/vocabularies/deltas/Error> .

    FILTER NOT EXISTS { ?a ?b ?s . }

    ?s ?p ?o .
  }
}