PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

<http://lblod.data.gift/concepts/7ff9914a-517d-4af1-8896-f4256308722f> qb:order 1 .

  <http://lblod.data.gift/concepts/c3f26429-776b-4ae3-a608-dfbb0b2a2cbd> qb:order 2 .

  <http://lblod.data.gift/concepts/f9fbf216-58fc-4083-a111-87c831999f1b> qb:order 3 .

  <http://lblod.data.gift/concepts/531a388c-4220-41a8-8399-250b3dd58e3a> qb:order 4 .

  <http://lblod.data.gift/concepts/84708640-241b-4758-bd52-46135bc9b333> qb:order 5 .

  <http://lblod.data.gift/concepts/2ec5db96-f1d6-499c-8c75-92d51ed68d12> qb:order 6 .

  <http://lblod.data.gift/concepts/540b3a69-3b01-49e4-9634-60b6ebe15869> qb:order 7 .

  }
}