DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/7ff9914a-517d-4af1-8896-f4256308722f> <http://www.w3.org/2004/02/skos/core#prefLabel> "Nieuwe (deel)databron"@nl. 
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://lblod.data.gift/concepts/7ff9914a-517d-4af1-8896-f4256308722f> <http://www.w3.org/2004/02/skos/core#prefLabel> " Nieuwe (deel)databron"@nl.
    
    }
}