DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/cbaf5b3a-b255-44d0-8658-40f0eecf6f0f> <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 2: Klimaattafels"@nl .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://lblod.data.gift/concepts/cbaf5b3a-b255-44d0-8658-40f0eecf6f0f> <http://www.w3.org/2004/02/skos/core#prefLabel> "Werf 2: Verrijk je wijk - Klimaattafels"@nl .
  }
}