PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20220323150741-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "0393b9d7-2974-48a0-a6a4-e3a45a0fffdc" ;
      nfo:fileName "20220323150741-forms.ttl" ;
      dct:created "2022-03-23T15:07:41"^^xsd:dateTime ;
      dct:modified "2022-03-23T15:07:41"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "297682"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    