INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
     <https://data.vlaanderen.be/id/concept/BesluitType/2b12630f-8c4e-40a4-8a61-a0c45621a1e6>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        <http://mu.semte.ch/vocabularies/core/uuid> "2b12630f-8c4e-40a4-8a61-a0c45621a1e6";
        <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>;
        # Only visible for "RO"
        <http://lblod.data.gift/vocabularies/besluit/decidableBy> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36372fad-0358-499c-a4e3-f412d2eae213>;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/71e6455e-1204-46a6-abf4-87319f58eaa5>;
        <http://www.w3.org/2004/02/skos/core#definition> "De budgetten en budgetwijzigingen van de besturen van de eredienst zijn onderworpen aan het advies van het representatief orgaan." ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Advies budget(wijziging)"@nl.
  }
} 