DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/subsidy-procedural-steps/c6c9af62-a29b-11eb-b06c-9bc0fbd1bfa6>
            <http://purl.org/dc/terms/description> "Aanvraag".
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/id/subsidy-procedural-steps/c6c9af62-a29b-11eb-b06c-9bc0fbd1bfa6>
            <http://purl.org/dc/terms/description> "Opvolgmoment"@nl .
    }
}
