PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        
        # Period of the Series/Step
        <http://data.lblod.info/id/periodes/52c53e5d-e522-4063-b229-0ec942732710>
            a mg8:PeriodOfTime ;
            mu:uuid "52c53e5d-e522-4063-b229-0ec942732710" ;
            mg8:startTime "2022-06-20T03:00:00Z"^^xsd:dateTime ;
            mg8:endTime "2022-09-09T21:59:59Z"^^xsd:dateTime .

        # Subsidy Procedural Step
        <http://data.lblod.info/id/subsidy-procedural-steps/80b5770f-f80b-42c8-bd7e-e7126fa0e00f>
            a subsidie:Subsidieprocedurestap;
            mu:uuid "80b5770f-f80b-42c8-bd7e-e7126fa0e00f";
            dct:description """Indienen voorstel""";
            mobiliteit:periode <http://data.lblod.info/id/periodes/52c53e5d-e522-4063-b229-0ec942732710>.

        # Create Series for call up 6
        <http://lblod.data.info/id/subsidy-measure-offer-series/5cb2d19e-51c6-4970-a7be-7f438b3e0917>
            a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
            mu:uuid "5cb2d19e-51c6-4970-a7be-7f438b3e0917" ;
            dct:title "Oproep 6"@nl ;
            dct:description "20/06/2022 — 09/09/2022"@nl ;
            mobiliteit:periode <http://data.lblod.info/id/periodes/52c53e5d-e522-4063-b229-0ec942732710> ;
            lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/80b5770f-f80b-42c8-bd7e-e7126fa0e00f> ;
            common:active <http://lblod.data.info/id/subsidie-application-flows/8739db1c-e987-4d75-bbdc-29d1c5eed74a> .

         # Link to existing Subsidy Offer for GZG
        <http://lblod.data.info/id/subsidy-measure-offers/8379a4ea-fd83-47cc-89fa-1a72ee4fbaff>
            cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/80b5770f-f80b-42c8-bd7e-e7126fa0e00f> ;
            lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/5cb2d19e-51c6-4970-a7be-7f438b3e0917> .

        
         # Subsidy Active Submission Flow Step 0
        <http://lblod.data.info/id/subsidie-application-flow-steps/cb6a3ea8-e888-4a80-b790-8af2ff0bcf5f>
            a lblodSubsidie:ApplicationStep ;
            mu:uuid "cb6a3ea8-e888-4a80-b790-8af2ff0bcf5f";
            qb:order 0 ;
            dct:references <http://data.lblod.info/id/subsidy-procedural-steps/80b5770f-f80b-42c8-bd7e-e7126fa0e00f>;
            dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/8739db1c-e987-4d75-bbdc-29d1c5eed74a>;
            dct:source <config://forms/GZG/proposal/versions/20220524130000-sixth-call/form.ttl> .

        # Subsidy Active Submission Flow
        <http://lblod.data.info/id/subsidie-application-flows/8739db1c-e987-4d75-bbdc-29d1c5eed74a>
            a lblodSubsidie:ApplicationFlow ;
            mu:uuid "8739db1c-e987-4d75-bbdc-29d1c5eed74a" ;
            xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/5cb2d19e-51c6-4970-a7be-7f438b3e0917> ;
            xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/cb6a3ea8-e888-4a80-b790-8af2ff0bcf5f> .

    }
}