
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ere:	<http://data.lblod.info/vocabularies/erediensten/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>


INSERT DATA {
    graph <http://mu.semte.ch/graphs/public> {
             <http://lblod.data.gift/concepts/7d8e0c15-7726-4196-9416-6dc40ed858bb> a <http://lblod.data.gift/vocabularies/organisatie/EredienstBeroepen>;
                                                                               mu:uuid "7d8e0c15-7726-4196-9416-6dc40ed858bb";
                                                                               skos:prefLabel "Waarnemende Imam";
                                                                               <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/0637cccd657df25049af6c4580c6b2be>;
                                                                               <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/0637cccd657df25049af6c4580c6b2be>.
   }
}


