PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # Period of the Series
    <http://data.lblod.info/id/periodes/d177ffb3-5934-4005-b481-5a424f136ec6>
        a mg8:PeriodOfTime ;
        mu:uuid "d177ffb3-5934-4005-b481-5a424f136ec6" ;
        mg8:startTime "2022-11-01T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2023-12-31T22:59:00Z"^^xsd:dateTime .

    # Period of step Indienen pact
    <http://data.lblod.info/id/periodes/0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389>
        a mg8:PeriodOfTime ;
        mu:uuid "0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389" ;
        mg8:startTime "2022-03-14T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2022-10-28T21:59:00Z"^^xsd:dateTime .

    # Period of step Indienen voorstel
    <http://data.lblod.info/id/periodes/fa65749c-6657-483f-89e1-b5467c8fe7c8>
        a mg8:PeriodOfTime ;
        mu:uuid "fa65749c-6657-483f-89e1-b5467c8fe7c8" ;
        mg8:startTime "2022-03-14T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2023-10-31T22:59:00Z"^^xsd:dateTime .

    # Period of step Opvolgmoment
    <http://data.lblod.info/id/periodes/c3a9c017-e66c-4bdc-aa61-f80158ff0d2d>
        a mg8:PeriodOfTime ;
        mu:uuid "c3a9c017-e66c-4bdc-aa61-f80158ff0d2d" ;
        mg8:startTime "2022-03-14T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2024-03-01T22:59:00Z"^^xsd:dateTime .

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/0463452b-ada8-4c13-a014-9b02da96d57f>
        a subsidie:Subsidieprocedurestap ;
        mu:uuid "0463452b-ada8-4c13-a014-9b02da96d57f" ;
        dct:description """Indienen pact""" ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389>.

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/ac021f91-95af-4aa5-b316-68770bb1813e>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "ac021f91-95af-4aa5-b316-68770bb1813e";
        dct:description """Indienen voorstel""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/fa65749c-6657-483f-89e1-b5467c8fe7c8>.

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/05f41a29-6903-43ae-a899-0e0e3a9bc733>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "05f41a29-6903-43ae-a899-0e0e3a9bc733";
        dct:description """Opvolgmoment""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/c3a9c017-e66c-4bdc-aa61-f80158ff0d2d>.

    # Create Series for call called 2022
    <http://lblod.data.info/id/subsidy-measure-offer-series/51d5ede8-4e7a-4d80-ab1b-2bdc5294fdcf>
        a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
        mu:uuid "51d5ede8-4e7a-4d80-ab1b-2bdc5294fdcf" ;
        dct:title "2022"@nl ;
        dct:description "01/11/2022 — 31/12/2023"@nl ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/d177ffb3-5934-4005-b481-5a424f136ec6> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/0463452b-ada8-4c13-a014-9b02da96d57f> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/ac021f91-95af-4aa5-b316-68770bb1813e> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/05f41a29-6903-43ae-a899-0e0e3a9bc733> ;
        common:active <http://lblod.data.info/id/subsidie-application-flows/049c2a16-ba71-42c7-82d4-0749c3ccf9c2> .

    # Link to existing Subsidy Offer for Climate
    <http://lblod.data.info/id/subsidy-measure-offers/64d40351-8128-464f-990f-41066154583e>
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/0463452b-ada8-4c13-a014-9b02da96d57f> ;
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/ac021f91-95af-4aa5-b316-68770bb1813e> ;
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/05f41a29-6903-43ae-a899-0e0e3a9bc733> ;
        lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/51d5ede8-4e7a-4d80-ab1b-2bdc5294fdcf> .

    # Subsidy Active Submission Flow Step 0
    <http://lblod.data.info/id/subsidie-application-flow-steps/335aedd4-c494-485b-9d78-d57bd975df55>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "335aedd4-c494-485b-9d78-d57bd975df55" ;
        qb:order 0 ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/c8cc24af-52fd-40b6-a364-ec0880f6ad89> ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/0463452b-ada8-4c13-a014-9b02da96d57f> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/049c2a16-ba71-42c7-82d4-0749c3ccf9c2> ;
        dct:source <config://forms/climate/oproep-2/step-submit-pact/versions/20220314162358/form.ttl> .

    # Subsidy Active Submission Flow Step 1
    <http://lblod.data.info/id/subsidie-application-flow-steps/c8cc24af-52fd-40b6-a364-ec0880f6ad89>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "c8cc24af-52fd-40b6-a364-ec0880f6ad89" ;
        qb:order 1 ;
        xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/335aedd4-c494-485b-9d78-d57bd975df55> ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/629edada-bea3-418d-be40-9a5b1ba8caf9> ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/ac021f91-95af-4aa5-b316-68770bb1813e> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/049c2a16-ba71-42c7-82d4-0749c3ccf9c2> ;
        dct:source <config://forms/climate/oproep-2/step-submit-proposal/versions/20220314162442/form.ttl> .

    # Subsidy Active Submission Flow Step 2
    <http://lblod.data.info/id/subsidie-application-flow-steps/629edada-bea3-418d-be40-9a5b1ba8caf9>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "629edada-bea3-418d-be40-9a5b1ba8caf9" ;
        qb:order 2 ;
        xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/c8cc24af-52fd-40b6-a364-ec0880f6ad89> ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/05f41a29-6903-43ae-a899-0e0e3a9bc733> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/049c2a16-ba71-42c7-82d4-0749c3ccf9c2> ;
        dct:source <config://forms/climate/oproep-2/step-submit-opvolgmoment/versions/20220314162333/form.ttl> .

    # Subsidy Active Submission Flow
    <http://lblod.data.info/id/subsidie-application-flows/049c2a16-ba71-42c7-82d4-0749c3ccf9c2>
        a lblodSubsidie:ApplicationFlow ;
        mu:uuid "049c2a16-ba71-42c7-82d4-0749c3ccf9c2" ;
        xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/51d5ede8-4e7a-4d80-ab1b-2bdc5294fdcf> ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/335aedd4-c494-485b-9d78-d57bd975df55> .
  }
}