DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
        <http://www.w3.org/2004/02/skos/core#definition> "Subsidy Measure: day-care"@en;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Kinderopvang"@nl .
   }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
        <http://www.w3.org/2004/02/skos/core#definition> "Subsidy Measure: emergency child care"@en;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Noodopvang (kinderen)"@nl .
   }
}
