PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?bestuurseenheid ext:isTrailUser "true"^^xsd:boolean .
  }
}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
     ?bestuurseenheid ext:isTrailUser "true"^^xsd:boolean .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
     VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/0f8e458aac514d1966ff7594b23fe784dba93ccff5d63fdfa279879eb007233a>
      <http://data.lblod.info/id/bestuurseenheden/484b4d65dee04db442889741026527199e484ad1249a9a96401b45718d6d497b>
      <http://data.lblod.info/id/bestuurseenheden/4f0eb4436c88cf831c35f84e7c34ce32f9ee4e99c5139aff62990e5e531aa1e7>
      <http://data.lblod.info/id/bestuurseenheden/4fd07fa6c794ef12a12c17976570c2bae5fe62dcc373a09032276397ae153f04>
      <http://data.lblod.info/id/bestuurseenheden/f4a187c72e551b9d7745e3b8602b11f12ce0fd5399c7f8aebbd4f8f42dc9c028>
     }
     ?bestuurseenheid a besluit:Bestuurseenheid .
  }
}
