PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?s ?p ?o.
} WHERE {
  ?s a locn:Address;
    ?p ?o.

  FILTER (?p IN (
    rdf:type,
    mu:uuid,
    adres:Adresvoorstelling.huisnummer,
    adres:Adresvoorstelling.busnummer,
    locn:thoroughfare,
    locn:postCode,
    adres:gemeentenaam,
    locn:adminUnitL2,
    adres:verwijstNaar,
    dct:source
  ))
}
