PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX cube: <http://purl.org/linked-data/cube#>

### CREATE NEW FLOW FOR UPDATED CONFIGURATION
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Flow
    <http://lblod.data.info/id/subsidie-application-flows/26e0050a-3c55-4e54-8212-82b77280b17a>
      a lblodSubsidie:ApplicationFlow ;
      mu:uuid "26e0050a-3c55-4e54-8212-82b77280b17a" ;
      xkos:belongsTo <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/07102db6-239d-4c57-9350-91f882e48d14> .

    # Proposal step
    <http://lblod.data.info/id/subsidie-application-flow-steps/07102db6-239d-4c57-9350-91f882e48d14>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "07102db6-239d-4c57-9350-91f882e48d14" ;
      dct:source <config://forms/bicycle-infrastructure/proposal/versions/20210420163405-initial-version/form.ttl> ;
      cube:order 0 ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/5f6193e5-7427-4ec8-90b1-636ed5181c19> ;
      dct:references <http://data.lblod.info/id/subsidieprocedurestappen/002f93ed-bdb0-4e3a-af13-ef6c00e89651> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/26e0050a-3c55-4e54-8212-82b77280b17a> .

    # Request step
    <http://lblod.data.info/id/subsidie-application-flow-steps/5f6193e5-7427-4ec8-90b1-636ed5181c19>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "5f6193e5-7427-4ec8-90b1-636ed5181c19" ;
      dct:source <config://forms/bicycle-infrastructure/request/versions/20220228164354-additional-fields/form.ttl> ;
      cube:order 1 ;
      xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/07102db6-239d-4c57-9350-91f882e48d14> ;
      xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/ad08beb8-b4a5-4a0e-ae99-1174b3b47d47>;
      dct:references <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/26e0050a-3c55-4e54-8212-82b77280b17a> .

    # Request balance step

    <http://lblod.data.info/id/subsidie-application-flow-steps/ad08beb8-b4a5-4a0e-ae99-1174b3b47d47>
      a lblodSubsidie:ApplicationStep ;
      mu:uuid "ad08beb8-b4a5-4a0e-ae99-1174b3b47d47" ;
      dct:source <config://forms/bicycle-infrastructure/request-balance/versions/20220110162327-initial-version/form.ttl> ;
      cube:order 2 ;
      xkos:previous <http://lblod.data.info/id/subsidie-application-flow-steps/5f6193e5-7427-4ec8-90b1-636ed5181c19> ;
      dct:references <http://data.lblod.info/id/subsidy-procedural-steps/ac33d0fe-ff5a-41ea-8730-1d655cca8cce> ;
      dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/26e0050a-3c55-4e54-8212-82b77280b17a> .
  }
}

;
### SET THAT NEW FLOW AS THE ACTIVE ONE
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> common:active <http://lblod.data.info/id/subsidie-application-flows/6d850270-a84b-466d-a572-84a17a734267> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f> common:active <http://lblod.data.info/id/subsidie-application-flows/26e0050a-3c55-4e54-8212-82b77280b17a> .
  }
}