#################################################
# cleans up backup graph and application graph
# TO RUN IN LOKET
#################################################
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mu:      <http://mu.semte.ch/vocabularies/core/>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX sd:      <http://www.w3.org/ns/sparql-service-description#>
PREFIX nie:     <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ext:     <http://mu.semte.ch/vocabularies/ext/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX pav:  <http://purl.org/pav/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/mandaten/bilzen/20190808> {
    ?s ?p ?o.
  }

}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/mandaten/bilzen/20190808> {
   ?s ext:generatedFrom ext:mandatenExtractorService.
   ?s ?p ?o.
  }

}