DELETE {
  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> ?path.
  }
}
INSERT {
  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> <config://forms/climate/step-submit-opvolgmoment/versions/20210420172044/form.json>.
  }
}
WHERE {
  BIND(<config://forms/climate/step-submit-aanvraag/versions/20210420172044/form.json> as ?path)

  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> ?path.
  }
}


;

DELETE {
  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> ?path.
  }
}
INSERT {
  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> <config://forms/climate/step-submit-opvolgmoment/versions/20210420172044/form.ttl>.
  }
}
WHERE {
  BIND(<config://forms/climate/step-submit-aanvraag/versions/20210420172044/form.ttl> as ?path)

  GRAPH ?g {
    ?file <http://purl.org/dc/terms/source> ?path.
  }
}
