DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/subsidy-procedural-steps/c6c9af62-a29b-11eb-b06c-9bc0fbd1bfa6> <http://data.vlaanderen.be/ns/subsidie#Subsidieprocedurestap.type> ?type.
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/subsidy-procedural-steps/c6c9af62-a29b-11eb-b06c-9bc0fbd1bfa6> <http://data.vlaanderen.be/ns/subsidie#Subsidieprocedurestap.type> ?type.
  }
}