# Currently last step of climate subsidy, if people end up in this step, it has status concept
# The problem is then, data is not extracted then from step 1
# This migration puts these back to status new, to trigger the extraction from step 1
# This is ok, as no one has been able to submit or save data yet

DELETE {
  GRAPH ?g {
    ?form <http://www.w3.org/ns/adms#status> ?status.
  }
}
INSERT {
  GRAPH ?g {
    ?form <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/6b7ae118-4653-48f2-9d9a-4712f8c30da9>.
  }
}
WHERE {
  GRAPH ?g {
    ?form <http://www.w3.org/ns/adms#status> ?status;
      a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm>;
      <http://purl.org/dc/terms/isPartOf> <http://lblod.data.info/id/subsidie-application-flow-steps/6977011a-a29c-11eb-b62a-7fee2a9561b8>.
  }
}