DELETE {
  GRAPH ?g {
    ?period <http://data.europa.eu/m8g/endTime> ?end.
  }
}
INSERT {
  GRAPH ?g {
    ?period <http://data.europa.eu/m8g/endTime> "2023-03-01T22:59:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/c251381e-300f-43e0-a83c-b1ffdfd06b48> as ?period)
  GRAPH ?g {
    ?period <http://data.europa.eu/m8g/endTime> ?end.
  }
}