services:
  script:
    image: semtech/mu-javascript-template:1.8.0
    restart: 'no'
    labels:
      - 'logging=true'
    environment:
      - NODE_ENV=development
      - NO_BABEL_NODE=true
      - SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES=500
      - LOG_SPARQL_ALL=false
      - DEBUG_AUTH_HEADERS=false
    ports:
      - '8083:80'
      - '9221:9229'
    volumes:
      - ./:/app
    networks:
      - script

networks:
  script:
    external: true
