services:
  script:
    image: semtech/mu-javascript-template:1.8.0
    restart: 'no'
    labels:
      - 'logging=true'
    environment:
      - NODE_ENV=development
      - NO_BABEL_NODE=true
      - SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES=500
      - LOG_SPARQL_ALL=false
      - DEBUG_AUTH_HEADERS=false
    ports:
      - '8083:80'
      - '9221:9229'
    volumes:
      - ./:/app
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./../../data/db:/data
      #- ./../../config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./../../config/virtuoso/virtuoso-production.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./../../config/virtuoso/:/opt/virtuoso-scripts
