PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/f44a31d9-7932-4dcb-a58a-daaceef4ac23> mg8:endTime ?end.
    <http://lblod.data.info/id/subsidy-measure-offer-series/48baa777-d460-436c-a0af-6b3ba80e6586> dct:description ?description .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/f44a31d9-7932-4dcb-a58a-daaceef4ac23> mg8:endTime "2022-03-25T21:59:59Z"^^xsd:dateTime .
    <http://lblod.data.info/id/subsidy-measure-offer-series/48baa777-d460-436c-a0af-6b3ba80e6586> dct:description "20/12/2021 — 25/03/2022"@nl .
  }
}