PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

############################################################
## DELETE all period data for bicycle subsidies
DELETE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?series
            dct:title ?title ;
            mobiliteit:periode ?claim .

        ?claim ?cp ?co .
        ?step mobiliteit:periode ?deadline .
        ?deadline ?dp ?do .
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        VALUES ?series {
            <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f>
        }
        ?series
            dct:title ?title ;
            mobiliteit:periode ?claim ;
            lblodSubsidie:heeftSubsidieprocedurestap ?step .

        ?step mobiliteit:periode ?deadline .

        ?claim ?cp ?co .
        ?deadline ?dp ?do .
    }
}
;
###################################################################
# INSERT claim & deadline for emergency contact-tracing, Winter
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/c49ebb70-3026-448a-88f5-97126ef3d322>
            a m8g:PeriodOfTime ;
            mu:uuid "c49ebb70-3026-448a-88f5-97126ef3d322" ;
            m8g:startTime "2021-02-26T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2022-09-30T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/2e77f4ea-05f6-4771-ae4b-8cee72d2459f>
            mobiliteit:periode <http://data.lblod.info/id/periodes/c49ebb70-3026-448a-88f5-97126ef3d322> .

        <http://data.lblod.info/id/periodes/001dac27-0146-4eb5-9313-8967e20d599b>
            a m8g:PeriodOfTime ;
            mu:uuid "001dac27-0146-4eb5-9313-8967e20d599b" ;
            m8g:startTime "2021-01-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2025-12-31T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/52f0b7dd244e42e0cda83804508e2e89d94ed098f3df8b4f9913a14f2be2423d> # Request
            mobiliteit:periode <http://data.lblod.info/id/periodes/001dac27-0146-4eb5-9313-8967e20d599b> .
    }
}