PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>

DELETE {
    GRAPH ?h {
        ?consumption common:active ?active .
    }
} WHERE {
    GRAPH ?g {
        ?consumption
            a subsidie:SubsidiemaatregelConsumptie ;
            adms:status <http://lblod.data.gift/concepts/2ea29fbf-6d46-4f08-9343-879282a9f484> ; # INGEDIEND
            common:active ?active .
   }
   BIND(?g as ?h)
}