PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX nie: <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>

################################
# DELETE old form specifications
DELETE {
    GRAPH ?g {
        ?spec ?specP ?specO .
        ?virtual ?virtualP ?virtualO .
    }
} WHERE {
    GRAPH ?g {
        VALUES ?spec {
            <config://versions/20201130150729/form.ttl>
            <config://versions/20201207135752/form.ttl>
            <config://versions/20210108094916/form.ttl>
            <config://versions/20210113150324/form.ttl>
            <config://versions/20210113153339/form.ttl>
            <config://versions/20210121152225-introduction-subsidy-form-contact-tracing/form.ttl>
            <config://versions/20210309152225-introduction-subsidy-form-bicycle-infrastructure/form.ttl>
            <config://versions/20210329141908-contact-tracing-checkbox-multi-selection/form.ttl>
        }
        ?spec a nfo:FileDataObject;
              nie:dataSource ?virtual .
        ?spec ?specP ?specO .
        ?virtual ?virtualP ?virtualO .
    }
}
