PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

############################################################
## DELETE all period data for emergency child-care subsidies
DELETE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?series mobiliteit:periode ?claim .
        ?claim ?cp ?co .
        ?step mobiliteit:periode ?deadline .
        ?deadline ?dp ?do .
    }
} WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        VALUES ?series {
            <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257>
            <http://lblod.data.gift/concepts/eaec78fb-2130-40c9-941b-6ad3bc129009>
            <http://lblod.data.gift/concepts/3e230d69-4dfb-4d99-8212-17e7921eb915>
            <http://lblod.data.gift/concepts/5578af16-8dc2-4361-98e0-12cddcdd9de5>
            <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848>
            <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
            <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
        }
        ?series
            mobiliteit:periode ?claim ;
            lblodSubsidie:heeftSubsidieprocedurestap ?step .

        ?step mobiliteit:periode ?deadline .

        ?claim ?cp ?co .
        ?deadline ?dp ?do .
    }
}
;
###################################################################
# INSERT claim & deadline for emergency child-care, Christmas holidays
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/84c64077-e270-4a45-abd0-2443f7554221>
            a m8g:PeriodOfTime ;
            mu:uuid "84c64077-e270-4a45-abd0-2443f7554221" ;
            m8g:startTime "2020-12-21T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-01-03T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/5e1474df-dfc2-432c-94af-039298222257> # Christmas holidays
            mobiliteit:periode <http://data.lblod.info/id/periodes/84c64077-e270-4a45-abd0-2443f7554221> .

        <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd>
            a m8g:PeriodOfTime ;
            mu:uuid "f8c3956b-4795-493c-a924-cfe498be51cd" ;
            m8g:startTime "2021-01-04T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/4beae4a11ddb49c381c22745a090327cffe5693c60d2f20ac13a8acccb58db7a> # Request
            mobiliteit:periode <http://data.lblod.info/id/periodes/f8c3956b-4795-493c-a924-cfe498be51cd> .
    }
}
;
##########################################################
# INSERT claim & deadline for emergency child-care, Spring
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/eb0d2c06-20b1-4582-a570-4c607ab0ccd8>
            a m8g:PeriodOfTime ;
            mu:uuid "eb0d2c06-20b1-4582-a570-4c607ab0ccd8" ;
            m8g:startTime "2021-04-19T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/eaec78fb-2130-40c9-941b-6ad3bc129009>
            mobiliteit:periode <http://data.lblod.info/id/periodes/eb0d2c06-20b1-4582-a570-4c607ab0ccd8> .

        <http://data.lblod.info/id/periodes/71ea26df-fd2a-4626-9a4c-93be0eb77367>
            a m8g:PeriodOfTime ;
            mu:uuid "71ea26df-fd2a-4626-9a4c-93be0eb77367" ;
            m8g:startTime "2021-04-05T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-07-31T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/67fb349694b6fa141bea4ad3212bbae0db995b967152736aea304958dd9f7d72>
            mobiliteit:periode <http://data.lblod.info/id/periodes/71ea26df-fd2a-4626-9a4c-93be0eb77367> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Early Easter holiday
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/66471c4a-3bbb-4e1b-897b-c5f08043e0d8>
            a m8g:PeriodOfTime ;
            mu:uuid "66471c4a-3bbb-4e1b-897b-c5f08043e0d8" ;
            m8g:startTime "2021-03-29T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-04-02T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/3e230d69-4dfb-4d99-8212-17e7921eb915>
            mobiliteit:periode <http://data.lblod.info/id/periodes/66471c4a-3bbb-4e1b-897b-c5f08043e0d8> .

        <http://data.lblod.info/id/periodes/c979d93f-0f04-4296-a0f9-80306f5606e9>
            a m8g:PeriodOfTime ;
            mu:uuid "c979d93f-0f04-4296-a0f9-80306f5606e9" ;
            m8g:startTime "2021-04-05T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-07-31T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/aabe45ba93f31abbcb488cb090aac0158241c5f08e61cb41e1497ad386010aeb>
            mobiliteit:periode <http://data.lblod.info/id/periodes/c979d93f-0f04-4296-a0f9-80306f5606e9> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Easter holiday
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/ac50a335-86a9-4795-918e-31620de6fedf>
            a m8g:PeriodOfTime ;
            mu:uuid "ac50a335-86a9-4795-918e-31620de6fedf" ;
            m8g:startTime "2021-04-05T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-04-16T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/5578af16-8dc2-4361-98e0-12cddcdd9de5>
            mobiliteit:periode <http://data.lblod.info/id/periodes/ac50a335-86a9-4795-918e-31620de6fedf> .

        <http://data.lblod.info/id/periodes/7457e7fb-db09-4dcf-82b1-ed4d08f81ecd>
            a m8g:PeriodOfTime ;
            mu:uuid "7457e7fb-db09-4dcf-82b1-ed4d08f81ecd" ;
            m8g:startTime "2021-04-05T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-07-31T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/7da2c107da4c8fc3aaad374da2dd5392a8f88b2f1e192ce3813cee16038d6a09>
            mobiliteit:periode <http://data.lblod.info/id/periodes/7457e7fb-db09-4dcf-82b1-ed4d08f81ecd> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Winter 2020
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/621d9d3e-a9fa-4392-9717-5a221cbcc1ab>
            a m8g:PeriodOfTime ;
            mu:uuid "621d9d3e-a9fa-4392-9717-5a221cbcc1ab" ;
            m8g:startTime "2020-11-16T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2020-12-31T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848>
            mobiliteit:periode <http://data.lblod.info/id/periodes/621d9d3e-a9fa-4392-9717-5a221cbcc1ab> .

        <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
            a m8g:PeriodOfTime ;
            mu:uuid "65c08d9f-da88-4dfd-9afa-4e031a40816a" ;
            # m8g:startTime "2020-12-21T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/8bee70b3f7b762d48c57944302d0897f8360bed5d8d49f32264772d6ebf8bef7>
            mobiliteit:periode <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Winter 2021
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/708cfe30-7267-4e86-bf00-910ba34193c7>
            a m8g:PeriodOfTime ;
            mu:uuid "708cfe30-7267-4e86-bf00-910ba34193c7" ;
            m8g:startTime "2021-01-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-03-26T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
            mobiliteit:periode <http://data.lblod.info/id/periodes/708cfe30-7267-4e86-bf00-910ba34193c7> .

        <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
            a m8g:PeriodOfTime ;
            mu:uuid "b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c" ;
            # m8g:startTime "2020-12-21T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/7028ed3808e8d2dcb68abe1ecb44609c5a1a0971d6dfbee42fc14350c87742be>
            mobiliteit:periode <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Autumn holidays
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/628e5e84-0b64-4513-9c8d-b3db3a1cee54>
            a m8g:PeriodOfTime ;
            mu:uuid "628e5e84-0b64-4513-9c8d-b3db3a1cee54" ;
            m8g:startTime "2020-11-09T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2020-11-13T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
            mobiliteit:periode <http://data.lblod.info/id/periodes/628e5e84-0b64-4513-9c8d-b3db3a1cee54> .

        <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
            a m8g:PeriodOfTime ;
            mu:uuid "94c86e58-9eba-4641-b84f-a09b5292bcf8" ;
            # m8g:startTime "2020-12-21T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/d87de1deddc1bd6f9c8119c1e43dd26688e08ad56aa2e5c0fc287ecf0e202ba7>
            mobiliteit:periode <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8> .
    }
}