PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/f7274d7f-31d5-4b02-aca8-b96481115651>
        a skos:ConceptScheme, rdfs:Class ;
        mu:uuid "f7274d7f-31d5-4b02-aca8-b96481115651" ;
        dct:title "subsidy-measure-consumption-statuses"@en ;
        dct:title "subsidiemaatregel-consumptie-statussen"@nl ;
        dct:definition """Statuses that designate the progression of a subsidy measure consumption"""@en ;
        dct:definition """Statussen die het verloop van een subsidiemaatregel consumptie aangeven"""@nl .

    <http://lblod.data.gift/concepts/6373b454-22b6-4b65-b98f-3d86541f2fcf>
        a lblodSubsidie:SubsidiemaatregelConsumptieStatus, skos:Concept, rdfs:Class;
        mu:uuid "6373b454-22b6-4b65-b98f-3d86541f2fcf" ;
        skos:prefLabel "Concept"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/f7274d7f-31d5-4b02-aca8-b96481115651> .

    <http://lblod.data.gift/concepts/c849ca98-455d-4f31-9e95-a3d9d06e4497>
        a lblodSubsidie:SubsidiemaatregelConsumptieStatus, skos:Concept, rdfs:Class;
        mu:uuid "c849ca98-455d-4f31-9e95-a3d9d06e4497" ;
        skos:prefLabel "Actief"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/f7274d7f-31d5-4b02-aca8-b96481115651> .

    <http://lblod.data.gift/concepts/2ea29fbf-6d46-4f08-9343-879282a9f484>
        a lblodSubsidie:SubsidiemaatregelConsumptieStatus, skos:Concept, rdfs:Class;
        mu:uuid "2ea29fbf-6d46-4f08-9343-879282a9f484" ;
        skos:prefLabel "Aanvraag ingediend"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/f7274d7f-31d5-4b02-aca8-b96481115651> .
  }
}
