PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>

DELETE {
  GRAPH ?g {
    ?smc <http://mu.semte.ch/vocabularies/ext/lastModifiedBy> ?lastModifierSmc.
    ?smc <http://purl.org/dc/terms/creator> ?creatorSmc.
    ?smc <http://purl.org/dc/terms/created> ?createdSmc.
    ?smc <http://purl.org/dc/terms/modified> ?modifiedSmc.
  }
}
INSERT {
  GRAPH ?g {
    ?smc <http://mu.semte.ch/vocabularies/ext/lastModifiedBy> ?lastModifier.
    ?smc <http://purl.org/dc/terms/creator> ?creator.
    ?smc <http://purl.org/dc/terms/created> ?created.
    ?smc <http://purl.org/dc/terms/modified> ?modified.
  }
}
WHERE {

  GRAPH ?g {
    ?s a lblodSubsidie:ApplicationForm.
    ?s <http://mu.semte.ch/vocabularies/ext/lastModifiedBy> ?lastModifier.
    ?s <http://purl.org/dc/terms/creator> ?creator.
    ?s <http://purl.org/dc/terms/created> ?created.
    ?s <http://purl.org/dc/terms/modified> ?modified.

    ?smc a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelConsumptie>.
    ?smc <http://purl.org/dc/terms/source> ?s.

    OPTIONAL {
      ?smc <http://mu.semte.ch/vocabularies/ext/lastModifiedBy> ?lastModifierSmc.
    }

    OPTIONAL {
       ?smc <http://purl.org/dc/terms/creator> ?creatorSmc.
    }

    OPTIONAL {
       ?smc <http://purl.org/dc/terms/created> ?createdSmc.
    }

    OPTIONAL {
      ?smc <http://purl.org/dc/terms/modified> ?modifiedSmc.
    }
  }

}