PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

####################################################################
### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error
INSERT DATA {
    GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
        <http://dummy/application/6c68539a-f6de-4488-8c1b-1c182e07a142> a lblodSubsidie:ApplicationForm ;
            dct:source <config://versions/20210329141908-contact-tracing-checkbox-multi-selection/form.ttl> ,
                       <config://versions/20210412135856-bicycle-new-tables/form.ttl> ;
            dct:isPartOf <http://lblod.data.info/id/subsidie-application-flow-steps/126ff5d8460a5d9af8f7428fcc156c18bbd6876e6c0c82b40e7630d1f322d86e> .
    }
}
;

#######################################################
# UPDATE old forms for: Emergency day-care; Easter 2021
DELETE {
    GRAPH ?g {
        ?form dct:source ?sources .
    }
} INSERT {
    GRAPH ?g {
        ?form dct:source <config://forms/emergency-day-care/versions/20210420172419-easter-2021/form.ttl>,
                         <config://forms/emergency-day-care/versions/20210420172419-easter-2021/form.json>.
    }
} WHERE {
    GRAPH ?g {
        VALUES ?spec {
            <config://versions/20210329141908-contact-tracing-checkbox-multi-selection/form.ttl>
            <config://versions/20210412135856-bicycle-new-tables/form.ttl>
        }
        ?form a lblodSubsidie:ApplicationForm ;
              dct:source ?spec ;
              dct:source ?sources ;
              dct:isPartOf ?afs .
    }
    GRAPH ?public {
        VALUES ?measure {
            <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
        }
        VALUES ?series {
            <http://lblod.data.gift/concepts/5578af16-8dc2-4361-98e0-12cddcdd9de5>
        }
        ?afs dct:isPartOf ?flow .
        ?flow xkos:belongsTo ?series .
        ?measure lblodSubsidie:heeftReeks ?series .
    }
}
;
######################################################################
# TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error
DELETE {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5>  {
    ?s ?p ?o .
  }
}
WHERE {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5>  {
    ?s ?p ?o .
  }
}