PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?s <http://lblod.data.gift/vocabularies/subsidie/timeBlock> ?reeks.
  }
}
INSERT {
  GRAPH ?g {
   ?s dct:isPartOf ?next.
  }
}
WHERE
{
  GRAPH ?g
  {
    ?s a lblodSubsidie:ApplicationForm.
    ?s <http://lblod.data.gift/vocabularies/subsidie/timeBlock> ?reeks.
  }

 ?reeks <http://www.w3.org/2007/uwa/context/common.owl#active> ?flow.
 ?flow <http://rdf-vocabulary.ddialliance.org/xkos#next> ?next.
}