PREFIX m8g: <http://data.europa.eu/m8g/>

######################################################################################
# INSERT correct start-date format for subsidy "Noodopvang (kinderen); Herfstvakantie"
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
            m8g:startTime "2020-11-20"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    }
}
;
######################################################################################
# DELETE:
#   invalid start-date format for subsidy "Noodopvang (kinderen); Herfstvakantie"
#   start-date for subsidy "Klimaatsubsidies"
DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
            m8g:startTime "16/11/2020T00:00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

        <http://data.lblod.info/id/periodes/6123b1b9-b75b-4235-9cc6-58b1d7fa6872>
            m8g:startTime "2021-05-01"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
    }
}