PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

########################################################################
# INSERT claim & deadline for emergency child-care, Winter 2020
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/621d9d3e-a9fa-4392-9717-5a221cbcc1ab>
            a m8g:PeriodOfTime ;
            mu:uuid "621d9d3e-a9fa-4392-9717-5a221cbcc1ab" ;
            m8g:startTime "2020-11-16T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2020-12-31T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/6cb8bc01-5f99-4c9e-87a0-9b674efa3848>
            mobiliteit:periode <http://data.lblod.info/id/periodes/621d9d3e-a9fa-4392-9717-5a221cbcc1ab> .

        <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a>
            a m8g:PeriodOfTime ;
            mu:uuid "65c08d9f-da88-4dfd-9afa-4e031a40816a" ;
            m8g:startTime "2020-11-16T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/8bee70b3f7b762d48c57944302d0897f8360bed5d8d49f32264772d6ebf8bef7>
            mobiliteit:periode <http://data.lblod.info/id/periodes/65c08d9f-da88-4dfd-9afa-4e031a40816a> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Winter 2021
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/708cfe30-7267-4e86-bf00-910ba34193c7>
            a m8g:PeriodOfTime ;
            mu:uuid "708cfe30-7267-4e86-bf00-910ba34193c7" ;
            m8g:startTime "2021-01-01T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-03-26T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
            mobiliteit:periode <http://data.lblod.info/id/periodes/708cfe30-7267-4e86-bf00-910ba34193c7> .

        <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c>
            a m8g:PeriodOfTime ;
            mu:uuid "b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c" ;
            m8g:startTime "2020-11-16T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/7028ed3808e8d2dcb68abe1ecb44609c5a1a0971d6dfbee42fc14350c87742be>
            mobiliteit:periode <http://data.lblod.info/id/periodes/b96b05a5-3f8d-4d8f-bb42-ca6b0ddf0d7c> .
    }
}
;
########################################################################
# INSERT claim & deadline for emergency child-care, Autumn holidays
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {

        <http://data.lblod.info/id/periodes/628e5e84-0b64-4513-9c8d-b3db3a1cee54>
            a m8g:PeriodOfTime ;
            mu:uuid "628e5e84-0b64-4513-9c8d-b3db3a1cee54" ;
            m8g:startTime "2020-11-09T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2020-11-13T00:00:00"^^xsd:dateTime .

        <http://lblod.data.gift/concepts/ef073502-d7c4-4b0c-b399-a73b429f877d>
            mobiliteit:periode <http://data.lblod.info/id/periodes/628e5e84-0b64-4513-9c8d-b3db3a1cee54> .

        <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8>
            a m8g:PeriodOfTime ;
            mu:uuid "94c86e58-9eba-4641-b84f-a09b5292bcf8" ;
            m8g:startTime "16/11/2020T00:00:00"^^xsd:dateTime ;
            m8g:endTime "2021-06-30T00:00:00"^^xsd:dateTime .

        <http://data.lblod.info/id/subsidieprocedurestappen/d87de1deddc1bd6f9c8119c1e43dd26688e08ad56aa2e5c0fc287ecf0e202ba7>
            mobiliteit:periode <http://data.lblod.info/id/periodes/94c86e58-9eba-4641-b84f-a09b5292bcf8> .
    }
}