# This migration removes duplicate subsidie-maatregel-consumpties linked to an applicationform
# which have been wrongly created due to a bug

PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX transactie: <http://data.vlaanderen.be/ns/transactie#>

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error ###
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://dummy/application> a lblodSubsidie:ApplicationForm.
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/1> <http://purl.org/dc/terms/source> <http://dummy/application>.
    <http://data.lblod.info/id/subsidiemaatregel-consumpties/2> <http://purl.org/dc/terms/source> <http://dummy/application>.
  }
}
### END OF TRICK ###

;

DELETE {
  GRAPH ?g {
    ?smc ?p ?o.
  }
}
WHERE {
  {

    SELECT DISTINCT ?smc ?totalSmc WHERE {

      ?applicationform a lblodSubsidie:ApplicationForm.
       ?smc <http://purl.org/dc/terms/source> ?applicationform.

      {
        SELECT ?applicationform count(?smc) as ?totalSmc
          WHERE {
            ?applicationform a lblodSubsidie:ApplicationForm.
            ?smc <http://purl.org/dc/terms/source> ?applicationform.
          }
       }
    }

    GROUP BY ?applicationform
    HAVING (?totalSmc > 1)
    ORDER BY ?applicationform
  }

  GRAPH ?g {
    ?smc ?p ?o.
  }

  FILTER (regex(STR(?smc), 'http://data.lblod.info/id/subsidiemaatregel-consumpties/')) .
}

;

### TRICK TO AVOID QUERY CRASHING IF NO TRIPLE FOUND - sprintf error ###
DELETE {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5>  {
    ?s ?p ?o .
  }
}
WHERE {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5>  {
    ?s ?p ?o .
  }
}
### END OF TRICK ###
