PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
   ?afs dct:source ?spec .
  }
}
INSERT {
  GRAPH ?g {
   ?afs dct:source <config://forms/emergency-day-care/versions/20210420172419-easter-2021/form.ttl>.
  }
}
WHERE {
  GRAPH ?h {
    <http://lblod.data.gift/concepts/5578af16-8dc2-4361-98e0-12cddcdd9de5> common:active ?af .
    ?afs dct:isPartOf ?af .
    ?afs dct:source ?spec.
  }
  BIND(?h as ?g)
}