DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/012ee8325a88bf82c32b06bea1a0c54c6abf116304daa5bdd82b0c9f910a9c41> <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit over budge(wijziging) eredienstbestuur" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/DecisionType/012ee8325a88bf82c32b06bea1a0c54c6abf116304daa5bdd82b0c9f910a9c41> <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit over budget(wijziging) eredienstbestuur" .
  }
}
