DELETE {
  GRAPH ?g {
    ?subject a <http://mu.semte.ch/vocabularies/lpdcExt/PublicServiceConcept>
  }
}
INSERT {
  GRAPH ?g {
    ?subject a <http://lblod.data.gift/vocabularies/lpdc-ipdc/ConceptualPublicService>
  }
}
WHERE {
    GRAPH ?g {
      ?subject a <http://mu.semte.ch/vocabularies/lpdcExt/PublicServiceConcept>
  }
}