PREFIX    mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX    besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX    persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX    foaf: <http://xmlns.com/foaf/0.1/>
PREFIX    org: <http://www.w3.org/ns/org#>
PREFIX    skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX    rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX    ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX    regorg: <https://www.w3.org/ns/regorg#>
PREFIX    person: <http://www.w3.org/ns/person#>
PREFIX    schema: <http://schema.org/>
PREFIX    prov: <http://www.w3.org/ns/prov#>
PREFIX    adms: <http://www.w3.org/ns/adms#>
PREFIX    mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX    lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX    prov: <http://www.w3.org/ns/prov#>

# VAST BUREAU
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?newBot a besluit:Bestuursorgaan ;
    mandaat:isTijdspecialisatieVan ?bo ;
    mu:uuid ?uuidInTijd ;
    mandaat:bindingStart "2012-10-14"^^<http://www.w3.org/2001/XMLSchema#date> ;
    mandaat:bindingEinde "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .


    # lid van vast bureau
    ?lid a mandaat:Mandaat.
    ?lid mu:uuid ?lidUuid.
    ?lid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000017>.
    ?newBot org:hasPost ?lid.

    # voorzitter
    ?voorzitter a mandaat:Mandaat.
    ?voorzitter mu:uuid ?voorzitterUuid.
    ?voorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
    ?newBot org:hasPost ?voorzitter.

  }
}
WHERE {

  {
    SELECT COUNT(DISTINCT(?bot)) AS ?countBot ?bo WHERE {
       ?bo a besluit:Bestuursorgaan .
       ?bo besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> . # Vast bureau
       ?bot mandaat:isTijdspecialisatieVan ?bo.
     }
   }

  ?bo besluit:bestuurt ?eenheid.
  ?bo skos:prefLabel ?naam.

  FILTER(?countBot < 2).

  FILTER NOT EXISTS {
      ?bot mandaat:isTijdspecialisatieVan ?bo.
      ?bot mandaat:bindingStart ?start.
      FILTER(?start < "2019-01-01"^^xsd:date)
  }

  FILTER NOT EXISTS {
    ?eenheid prov:wasDerivedFrom ?eenheidVoorFusie
  } . #excludes newly created fusiegemeenten


  BIND(SHA256(CONCAT("1b3f9e72-12ae-4073-b472-b630c7335852", ":", STR(?bo))) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?newBot) .

  BIND(SHA256(CONCAT("a1920e80-c982-449a-987a-6ac46aa23ad6", ":", STR(?bo))) AS ?voorzitterUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?voorzitterUuid))) AS ?voorzitter) .

  BIND(SHA256(CONCAT("21df5c52-c979-46f8-b39a-c8ada7ee83cf", ":", STR(?bo))) AS ?lidUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?lidUuid))) AS ?lid) .
}

;

# BCSD
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?newBot a besluit:Bestuursorgaan ;
    mandaat:isTijdspecialisatieVan ?bo ;
    mu:uuid ?uuidInTijd ;
    mandaat:bindingStart "2012-10-14"^^<http://www.w3.org/2001/XMLSchema#date> ;
    mandaat:bindingEinde "2019-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .


    # lid
    ?lid a mandaat:Mandaat.
    ?lid mu:uuid ?lidUuid.
    ?lid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000019>.
    ?newBot org:hasPost ?lid.

    # voorzitter
    ?voorzitter a mandaat:Mandaat.
    ?voorzitter mu:uuid ?voorzitterUuid.
    ?voorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001a>.
    ?newBot org:hasPost ?voorzitter.

  }
}
WHERE {

  {
    SELECT COUNT(DISTINCT(?bot)) AS ?countBot ?bo WHERE {
       ?bo a besluit:Bestuursorgaan .
       ?bo besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .
       ?bot mandaat:isTijdspecialisatieVan ?bo.
     }
   }

  ?bo besluit:bestuurt ?eenheid.
  ?bo skos:prefLabel ?naam.

  FILTER(?countBot < 2).

  FILTER NOT EXISTS {
      ?bot mandaat:isTijdspecialisatieVan ?bo.
      ?bot mandaat:bindingStart ?start.
      FILTER(?start < "2019-01-01"^^xsd:date)
  }

  FILTER NOT EXISTS {
    ?eenheid prov:wasDerivedFrom ?eenheidVoorFusie
  } . #excludes newly created fusiegemeenten


  BIND(SHA256(CONCAT("71d99494-2273-4812-a081-7430d19a8700", ":", STR(?bo))) AS ?uuidInTijd) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", STR(?uuidInTijd))) AS ?newBot) .

  BIND(SHA256(CONCAT("ad7b76c0-66e4-48ed-b538-b6f76ab72f7a", ":", STR(?bo))) AS ?voorzitterUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?voorzitterUuid))) AS ?voorzitter) .

  BIND(SHA256(CONCAT("e54309d0-d8ee-4b69-98d5-8d7801bf972c", ":", STR(?bo))) AS ?lidUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?lidUuid))) AS ?lid) .
}

;


# CREATE MANDATEN VOORZITTER VAST BUREAU IF NOT EXISTING
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # voorzitter
    ?voorzitter a mandaat:Mandaat.
    ?voorzitter mu:uuid ?voorzitterUuid.
    ?voorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
    ?bot org:hasPost ?voorzitter.
  }
}





WHERE {
  ?bo a besluit:Bestuursorgaan .
  ?bo besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> . # Vast bureau
  ?bot mandaat:isTijdspecialisatieVan ?bo.

  FILTER NOT EXISTS {
      ?exVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
      ?bot org:hasPost ?exVoorzitter.
  }


  BIND(SHA256(CONCAT("73386072-12ee-4266-a0ea-2d1b684b8a70", ":", STR(?bo))) AS ?voorzitterUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?voorzitterUuid))) AS ?voorzitter) .

}

;

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # voorzitter
    ?voorzitter a mandaat:Mandaat.
    ?voorzitter mu:uuid ?voorzitterUuid.
    ?voorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
    ?bot org:hasPost ?voorzitter.
  }
}
WHERE {
  ?bo a besluit:Bestuursorgaan .
  ?bo besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> . # Vast bureau
  ?bot mandaat:isTijdspecialisatieVan ?bo.

  FILTER NOT EXISTS {
      ?exVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
      ?bot org:hasPost ?exVoorzitter.
  }


  BIND(SHA256(CONCAT("73386072-12ee-4266-a0ea-2d1b684b8a70", ":", STR(?bo))) AS ?voorzitterUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?voorzitterUuid))) AS ?voorzitter) .

}

;

# INSERT MISSING VOORZITTERS BCSD
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {

    # voorzitter
    ?voorzitter mu:uuid ?voorzitterUuid.
    ?voorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001a>.
    ?bot org:hasPost ?voorzitter.
  }
}
WHERE {
  ?bo a besluit:Bestuursorgaan .
  ?bo besluit:classificatie  <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009>. # bcsd
  ?bot mandaat:isTijdspecialisatieVan ?bo.

  FILTER NOT EXISTS {
      ?exVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001a> .
      ?bot org:hasPost ?exVoorzitter.
  }


  BIND(SHA256(CONCAT("f1da2081-d6e7-4a9b-b82a-2c13d84e2a9d", ":", STR(?bo))) AS ?voorzitterUuid) .
  BIND(IRI(CONCAT("http://data.lblod.info/id/mandaten/", STR(?voorzitterUuid))) AS ?voorzitter) .
}
