PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX person: <http://www.w3.org/ns/person#>

# An issue in the bestuursorganenselector made users
# add mandatarissen to the wrong bestuursorgaan in tijd
# by error.
# To correct the error, we need to first make sure that we keep track
# of the erroneous mandatarissen which were inserted before the issue with the selector.
# This data comes from a dump: 05-09-2022
INSERT DATA {
  GRAPH <http://debug/mandatarissen/05-09-2022/wrong> {
    <http://data.lblod.info/id/mandatarissen/5C3DF60C57753A0009000397>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E14DC9E5B640009000203>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E12529E5B6400090001BC>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E11B69E5B6400090001B2>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C3DF69957753A0009000399>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E132F9E5B6400090001D5>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E14FF9E5B640009000205>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E15179E5B640009000207>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E121E9E5B6400090001B8>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E13689E5B6400090001DC>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E10179E5B64000900018A>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C3DF62C57753A0009000398>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E10539E5B640009000190>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E12C39E5B6400090001CA>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E10FE9E5B64000900019E>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/0fb63f9e-4e5f-4120-986d-0d5c7341cffb>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E15779E5B64000900020F>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E0F1E9E5B640009000180>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E13D29E5B6400090001E8>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E13A39E5B6400090001E2>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E12899E5B6400090001C3>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E14079E5B6400090001EF>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E15309E5B640009000209>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E11409E5B6400090001A6>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E147C9E5B6400090001F7>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E14BB9E5B6400090001FC>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E12F59E5B6400090001CF>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E117D9E5B6400090001AB>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E0F8C9E5B640009000185>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E0F469E5B640009000183>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/5C2E15559E5B64000900020B>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
    <http://data.lblod.info/id/mandatarissen/32e1bd00debb62fd5de35e054c095e80adc2932842e3f0145920221884355d55>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://data.vlaanderen.be/ns/mandaat#Mandataris> .
  }
}