PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8: <http://data.europa.eu/m8g/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public>{

    # Period of the Series/Step
    <http://data.lblod.info/id/periodes/f44a31d9-7932-4dcb-a58a-daaceef4ac23>
        a mg8:PeriodOfTime ;
        mu:uuid "f44a31d9-7932-4dcb-a58a-daaceef4ac23" ;
        mg8:startTime "2021-12-20T03:00:00Z"^^xsd:dateTime ;
        mg8:endTime "2022-02-25T21:59:59Z"^^xsd:dateTime .

    # Subsidy Procedural Step
    <http://data.lblod.info/id/subsidy-procedural-steps/64afeb2f-9052-492e-ad45-eb689b5a8d1d>
        a subsidie:Subsidieprocedurestap;
        mu:uuid "64afeb2f-9052-492e-ad45-eb689b5a8d1d";
        dct:description """Indienen voorstel""";
        mobiliteit:periode <http://data.lblod.info/id/periodes/f44a31d9-7932-4dcb-a58a-daaceef4ac23>.

    # Create Series for call up 4
    <http://lblod.data.info/id/subsidy-measure-offer-series/48baa777-d460-436c-a0af-6b3ba80e6586>
        a lblodSubsidie:SubsidiemaatregelAanbodReeks ;
        mu:uuid "48baa777-d460-436c-a0af-6b3ba80e6586" ;
        dct:title "Oproep 4"@nl ;
        dct:description "20/12/2021 — 25/02/2022"@nl ;
        mobiliteit:periode <http://data.lblod.info/id/periodes/f44a31d9-7932-4dcb-a58a-daaceef4ac23> ;
        lblodSubsidie:heeftSubsidieprocedurestap <http://data.lblod.info/id/subsidy-procedural-steps/64afeb2f-9052-492e-ad45-eb689b5a8d1d> ;
        common:active <http://lblod.data.info/id/subsidie-application-flows/cb740ecb-01fa-42c6-bfe1-4b8b5b436a88> .

    # Link to existing Subsidy Offer for GZG
    <http://lblod.data.info/id/subsidy-measure-offers/8379a4ea-fd83-47cc-89fa-1a72ee4fbaff>
        cpsv:follows <http://data.lblod.info/id/subsidy-procedural-steps/64afeb2f-9052-492e-ad45-eb689b5a8d1d> ;
        lblodSubsidie:heeftReeks <http://lblod.data.info/id/subsidy-measure-offer-series/48baa777-d460-436c-a0af-6b3ba80e6586> .

    # Subsidy Active Submission Flow Step 0
    <http://lblod.data.info/id/subsidie-application-flow-steps/a2448281-6d10-4df7-bb6b-14711a104a7f>
        a lblodSubsidie:ApplicationStep ;
        mu:uuid "a2448281-6d10-4df7-bb6b-14711a104a7f" ;
        qb:order 0 ;
        dct:references <http://data.lblod.info/id/subsidy-procedural-steps/64afeb2f-9052-492e-ad45-eb689b5a8d1d> ;
        dct:isPartOf <http://lblod.data.info/id/subsidie-application-flows/cb740ecb-01fa-42c6-bfe1-4b8b5b436a88> ;
        dct:source <config://forms/GZG/proposal/versions/20211119134817-forth-call/form.ttl> .

    # Subsidy Active Submission Flow
    <http://lblod.data.info/id/subsidie-application-flows/cb740ecb-01fa-42c6-bfe1-4b8b5b436a88>
        a lblodSubsidie:ApplicationFlow ;
        mu:uuid "cb740ecb-01fa-42c6-bfe1-4b8b5b436a88" ;
        xkos:belongsTo <http://lblod.data.info/id/subsidy-measure-offer-series/48baa777-d460-436c-a0af-6b3ba80e6586> ;
        xkos:next <http://lblod.data.info/id/subsidie-application-flow-steps/a2448281-6d10-4df7-bb6b-14711a104a7f> .
  }
}