INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/concept-schemes/7db0bcc4-7ccf-4848-affd-cbd41124ef71>
            a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "7db0bcc4-7ccf-4848-affd-cbd41124ef71" ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 2,3 and 6."""@en .

        <http://lblod.data.gift/concept-schemes/6e9129dc-06aa-409f-af5e-fc450bf87123>
            a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "6e9129dc-06aa-409f-af5e-fc450bf87123" ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 5."""@en .

        <http://lblod.data.gift/concept-schemes/c200126a-e624-4a62-b2fd-db8dd419f053>
            a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
            <http://mu.semte.ch/vocabularies/core/uuid> "c200126a-e624-4a62-b2fd-db8dd419f053" ;
            <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 7."""@en .

        # Innovative services
        <http://lblod.data.gift/concepts/446ac005-7342-4f3a-b7a0-2b3c929d73ba>
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/7db0bcc4-7ccf-4848-affd-cbd41124ef71> ,
                                                           <http://lblod.data.gift/concept-schemes/6e9129dc-06aa-409f-af5e-fc450bf87123> ,
                                                           <http://lblod.data.gift/concept-schemes/c200126a-e624-4a62-b2fd-db8dd419f053> .

        # Digitale democratie
        <http://lblod.data.gift/concepts/6eca0908-de74-400e-9f6b-2ea0202ac05b>
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/6e9129dc-06aa-409f-af5e-fc450bf87123> .

        # Workplace of the future
        <http://lblod.data.gift/concepts/9fb0732f-e779-4d2b-b53d-159e7088c678>
            <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/7db0bcc4-7ccf-4848-affd-cbd41124ef71> .
    }
}
