DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d>
            <http://www.w3.org/2004/02/skos/core#prefLabel> """concept-scheme defining project types"""@en .
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/concept-schemes/fffb9b3a-21ba-4050-b171-0d9b84d1927d>
            <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 1 and 4."""@en .
    }
}