PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT {
  GRAPH ?g {
   ?s dct:identifier ?id.
  }
}
WHERE {
  GRAPH ?g {
    ?s a ere:RepresentatiefOrgaan;
      ext:kbonummer ?kbo.
  }
  BIND(?kbo as ?id)
}