PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
      <http://lblod.data.gift/concept-schemes/6e9129dc-06aa-409f-af5e-fc450bf87123>
        <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 5."""@en .
      <http://lblod.data.gift/concept-schemes/7db0bcc4-7ccf-4848-affd-cbd41124ef71>
        <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 2,3 and 6."""@en .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
     <http://lblod.data.gift/concept-schemes/6e9129dc-06aa-409f-af5e-fc450bf87123>
        <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 5,6 and 7."""@en .
      <http://lblod.data.gift/concept-schemes/7db0bcc4-7ccf-4848-affd-cbd41124ef71>
        <http://www.w3.org/2004/02/skos/core#prefLabel> """Project themes for GZG subsidy call-up 2 and 3."""@en .
  }
}