PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/111b848b-0590-42f2-a659-c91a9a5f7a0b> mg8:endTime ?end.
    <http://data.lblod.info/id/periodes/111b848b-0590-42f2-a659-c91a9a5f7a0b> mg8:startTime ?start.
   <http://lblod.data.info/id/subsidy-measure-offer-series/ec1c74eb-f62e-4c35-82d1-c79616471e3e> dct:description ?desc .
    
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/111b848b-0590-42f2-a659-c91a9a5f7a0b> mg8:endTime "2022-10-01T03:00:00Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/111b848b-0590-42f2-a659-c91a9a5f7a0b> mg8:startTime "2023-09-30T21:59:59Z"^^xsd:dateTime  .
    <http://lblod.data.info/id/subsidy-measure-offer-series/ec1c74eb-f62e-4c35-82d1-c79616471e3e> dct:description "01/10/2022 — 30/09/2023"@nl .
  }
}
