PREFIX contribution: <http://lblod.data.gift/vocabularies/subsidie/plan-samenleven/contribution/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://data.lblod.info/id/subsidies/rules/7f7f1d20-942d-48ac-85a0-748db7f3d835> contribution:multiplier "12500"^^xsd:integer.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
   <http://data.lblod.info/id/subsidies/rules/7f7f1d20-942d-48ac-85a0-748db7f3d835> contribution:multiplier "25000"^^xsd:integer.
  }
}