DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/974816591f269bb7d74aa1720922651529f3d3b2a787f5c60b73e5a0384950a4/LoketLB-berichtenGebruiker> {
    <http://data.lblod.info/id/conversaties/db3fcf5c-d187-11ea-bb78-0242c0a8201e> <http://mu.semte.ch/vocabularies/ext/currentType> "None" .
    <http://data.lblod.info/id/conversaties/db3fcf5c-d187-11ea-bb78-0242c0a8201e> <http://schema.org/identifier> "" .
  }
}
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/974816591f269bb7d74aa1720922651529f3d3b2a787f5c60b73e5a0384950a4/LoketLB-berichtenGebruiker> {
    <http://data.lblod.info/id/conversaties/db3fcf5c-d187-11ea-bb78-0242c0a8201e> <http://mu.semte.ch/vocabularies/ext/currentType> "Opvraging" .
    <http://data.lblod.info/id/conversaties/db3fcf5c-d187-11ea-bb78-0242c0a8201e> <http://schema.org/identifier> "KLACHT2020.002548" .
  }
}
