DELETE {
  GRAPH ?g {
    ?periode ?p ?o.
    ?oproep ?link ?periode.
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/9f272f95-45cf-47bf-84ad-7a889ec140e0> as ?periode)
  GRAPH ?g {
    ?periode ?p ?o.
    ?oproep ?link ?periode.
  }
}