PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>
# update GZG call 3 deadline

DELETE {
  GRAPH ?g {
   ?s m8g:endTime ?end.
  }
}
INSERT {
  GRAPH ?g {
   ?s m8g:endTime "2022-02-18T21:59:59Z"^^xsd:dateTime.
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/09af0425-12cc-411c-abcf-16ace6af3cfe> as ?s)
  GRAPH ?g {
   ?s m8g:endTime ?end.
  }
}
;
DELETE {
  GRAPH ?g {
   ?s dct:description ?description.
  }
}
INSERT {
  GRAPH ?g {
   ?s m8g:startTime "22/11/2021 — 18/02/2022"@nl.
  }
}
WHERE {
  BIND(<http://lblod.data.info/id/subsidy-measure-offer-series/4cebd644-d172-4bea-a38a-fc1f4449946e> as ?s)
  GRAPH ?g {
   ?s dct:description ?description.
  }
}