PREFIX m8g: <http://data.europa.eu/m8g/>
# update <http://lblod.data.info/id/subsidy-measure-offer-series/2a25de4e-126a-4eeb-ae27-fbdee1a5b6a4>
# contactracing oproep nazomer
DELETE {
  GRAPH ?g {
   ?s m8g:startTime ?start.
   ?s m8g:endTime ?end.
  }
}
INSERT {
  GRAPH ?g {
   ?s m8g:startTime "2021-09-01T00:00:00Z"^^xsd:dateTime.
   ?s m8g:endTime "2021-10-15T00:00:00Z"^^xsd:dateTime.
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/dbfc89c3-19f9-4dcc-afdf-b97a388eaf73> as ?s)
  GRAPH ?g {
   ?s m8g:startTime ?start.
   ?s m8g:endTime ?end.
  }
}
;
# contactracing operoep nazomer step aanvraag
DELETE {
  GRAPH ?g {
   ?s m8g:startTime ?start.
   ?s m8g:endTime ?end.
  }
}
INSERT {
  GRAPH ?g {
   ?s m8g:startTime "2021-11-01T03:00:00Z"^^xsd:dateTime.
   ?s m8g:endTime "2021-12-31T21:59:59Z"^^xsd:dateTime.
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/periodes/2a4d37e6-a75f-4207-88c2-0cb88c95fcbe> as ?s)
  GRAPH ?g {
   ?s m8g:startTime ?start.
   ?s m8g:endTime ?end.
  }
}