PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX http: <http://www.w3.org/2011/http#>

DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/request-headers/29b14d06-e584-45d6-828a-ce1f0c018a8e>
            http:fieldValue """application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-word.document.macroEnabled.12,text/html;q=0.8,application/xhtml+xml;q=0.8,application/xml;q=0.7""" .
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://data.lblod.info/request-headers/29b14d06-e584-45d6-828a-ce1f0c018a8e>
            http:fieldValue """text/html,application/xhtml+xml,application/xml;q=0.9,application/pdf;q=0.8,application/msword;q=0.7,application/vnd.openxmlformats-officedocument.wordprocessingml.document;q=0.7,application/vnd.ms-word.document.macroEnabled.12;q=0.7""" .
    }
}
