DELETE DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66>
            <https://www.gleif.org/ontology/Base/hasStart> "2021-04-12"^^<http://www.w3.org/2001/XMLSchema#date>.
    }
}
;
INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://lblod.data.gift/periods/02a7807e-5352-44e3-b87c-c69b3876be66>
            <https://www.gleif.org/ontology/Base/hasStart> "2021-04-05"^^<http://www.w3.org/2001/XMLSchema#date>.
    }
}
