PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX qb: <http://purl.org/linked-data/cube#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    ########################################################
    ### CONCEPT - Focused at-risk and vulnerable populations

    <http://data.lblod.info/id/subsidies/rules/4ca04e45-cfbd-44e5-a91b-d070caff6b49>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/d71b5fc9-c304-4687-b789-76a84296932f>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/9f483029-cdc4-43f2-b07b-c6d3d2bd32ec>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/384b2567-ab54-4b6f-b19c-a438829b3666>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/34bac9ee-29fd-4fa9-b4f3-aaacf2c14a20>
        qb:order 5 .

    <http://data.lblod.info/id/subsidies/rules/baef0751-81b2-4b0c-88c9-4cdd635e0a21>
        qb:order 6 .

    <http://data.lblod.info/id/subsidies/rules/49f168af-7cc2-412b-afb2-ec9a0fd9760d>
        qb:order 7 .

    <http://data.lblod.info/id/subsidies/rules/a10ccc14-6b46-4fd6-ab9b-c6e45c673287>
        qb:order 8 .

    <http://data.lblod.info/id/subsidies/rules/34eb316a-488b-4ec3-a29e-450b016a85b7>
        qb:order 9 .

    <http://data.lblod.info/id/subsidies/rules/409a270a-3e73-4466-9657-7a52b46b8490>
        qb:order 10 .

    <http://data.lblod.info/id/subsidies/rules/e9a7abaf-7098-4489-8fcb-aa73e80f0733>
        qb:order 11 .


    ################################
    ### CONCEPT - Types of contacts

    <http://data.lblod.info/id/subsidies/rules/94ee5c3c-2794-4fd2-9779-524f71e2005b>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/17eda7bf-ef96-4871-bc65-f7fd96a4d937>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/4899326e-096a-4a77-84d4-9af9ad70ab30>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/fb34b0bf-2dfa-4ac1-a091-fd8f191d8197>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/26bd1ec3-c601-4aaa-bdd0-6ee1855b1a99>
        qb:order 5 .


    ##########################################
    ### CONCEPT - Used methods for prevention

    <http://data.lblod.info/id/subsidies/rules/04a7e1c6-407a-4154-819e-de1cfa4dee92>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/dd80f93f-e013-4cbb-840d-53b3c3a888fb>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/1afe28e2-e6b7-4af3-86b6-1254e8ae7d87>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/f5d4ce8c-6baf-4304-8037-0aa7afe631e5>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/aa995916-6deb-478b-b332-9300f494044d>
        qb:order 5 .

    <http://data.lblod.info/id/subsidies/rules/e2ab52dc-7b22-40a7-9fa4-51973c3bad5a>
        qb:order 6 .

    <http://data.lblod.info/id/subsidies/rules/d0c60eba-dbd0-46a5-a237-7d26f465af28>
        qb:order 7 .

    <http://data.lblod.info/id/subsidies/rules/dee57634-9b26-454d-bb33-f32f4d1c9bf6>
        qb:order 8 .

    <http://data.lblod.info/id/subsidies/rules/f66f46b3-2fbc-4ce7-a8aa-deb947d4cee7>
        qb:order 9 .


    #################################################
    ### CONCEPT - Taken actions for source detection

    <http://data.lblod.info/id/subsidies/rules/e8fe4796-64be-4995-82ce-ba9f355fb5b4>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/acd2e32c-fdcd-4ff5-991b-b0399296ec24>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/9bd53c83-f67e-48a4-8b65-051e018cc3bf>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/06720e8f-f786-43cc-8d4a-3355505f7278>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/a13b8675-10fb-44d4-bdb0-e7bf141e96e5>
        qb:order 5 .

    <http://data.lblod.info/id/subsidies/rules/0bef5e29-c866-427c-88f9-187331b4bf3c>
        qb:order 6 .

    <http://data.lblod.info/id/subsidies/rules/d3dd104d-dac1-422e-9ad5-d9dabbcb2bbe>
        qb:order 7 .

    <http://data.lblod.info/id/subsidies/rules/21fd7549-7215-4f2e-b598-23adbcfc0569>
        qb:order 9 .

    ####################################################
    ### CONCEPT - Used methods for quarantaine-coaching

    <http://data.lblod.info/id/subsidies/rules/71ea6694-81df-43fb-a125-a328e71d22e2>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/9b6be38f-ea5d-4978-9a4b-59e8e235e772>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/7a1e123f-2f7e-44d0-a107-654eb1aa8746>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/c9190e70-2f94-4edb-8ea5-bcfbaf4a9cfc>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/60306cda-a2d2-40ea-99d2-0ec1bfa0805d>
        qb:order 5 .

    <http://data.lblod.info/id/subsidies/rules/9dbc9843-7ac4-47c5-a381-311735068ebf>
        qb:order 6 .

    <http://data.lblod.info/id/subsidies/rules/182df43f-10af-4be5-875e-1a0e8051d559>
        qb:order 7 .

    <http://data.lblod.info/id/subsidies/rules/92af1821-29f6-4b73-b9b5-95f1bf92fe3d>
        qb:order 8 .

    <http://data.lblod.info/id/subsidies/rules/1ae51af1-00f5-499a-8bb6-97113285ca5c>
        qb:order 9 .


    ########################################################
    ### CONCEPT - Organized help for vulnerable groups

    <http://data.lblod.info/id/subsidies/rules/2ddf912c-e71a-45ae-847b-f9e94ab90d70>
        qb:order 1 .

    <http://data.lblod.info/id/subsidies/rules/c34db3c6-157c-4115-86dd-de0cb953a240>
        qb:order 2 .

    <http://data.lblod.info/id/subsidies/rules/1bdfcee0-339e-4c94-8b76-386481b142cb>
        qb:order 3 .

    <http://data.lblod.info/id/subsidies/rules/4e035c5b-195f-42ff-b9b7-9f356949370d>
        qb:order 4 .

    <http://data.lblod.info/id/subsidies/rules/5458ea7e-8692-459c-8208-fef02601a757>
        qb:order 5 .

    <http://data.lblod.info/id/subsidies/rules/8a5c1696-7198-41af-8f41-d63f9a53f1a1>
        qb:order 6 .

    <http://data.lblod.info/id/subsidies/rules/e7c07f5f-803f-4c0a-b5e1-d1ac03a82dac>
        qb:order 7 .

    <http://data.lblod.info/id/subsidies/rules/2b4d4b9a-da9d-481a-aa8b-08c8fe89c230>
        qb:order 8 .
  }
}
