PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX owl:  <http://www.w3.org/2007/uwa/context/common.owl#>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/54c9a2a4a577fc2f6888bdf2b43d439ae59ae26a3db344546c7a713f2aab2bce/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/6169448E890F3E0008000048>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/6977011a-a29c-11eb-b62a-7fee2a9561b8> .
    <http://data.lblod.info/id/application-forms/61694516890F3E000800004A>
        adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c> . # Status SENT
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/54c9a2a4a577fc2f6888bdf2b43d439ae59ae26a3db344546c7a713f2aab2bce/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/6169448E890F3E0008000048>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/c50d7726-4880-43e2-b098-c356722a3096> .
    <http://data.lblod.info/id/application-forms/61694516890F3E000800004A>
        adms:status <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> . # Status CONCEPT
  }
}