PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
      gleif:hasEnd      "2021-02-12"^^xsd:date ;
      skos:prefLabel    "Winter 2021 (01 januari 2021 — 12 februari 2021)"@nl .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/a26aee99-8ea6-44d1-a72d-c04d3a37b690>
      gleif:hasEnd      "2021-03-26"^^xsd:date ;
      skos:prefLabel    "Winter 2021 (01 januari 2021 — 26 maart 2021)"@nl .
  }
}


