PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>

# Avoid sprintf error
INSERT DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://data.lblod.info/id/aanvraagen/test> a lblodSubsidie:ApplicationForm ;
      subsidie:aanvraagdatum "test" .
  }
}

;

# aanvraagdatum will now only be on the Aanvraag resource, created on submit
DELETE {
  GRAPH ?g {
    ?applicationForm subsidie:aanvraagdatum ?aanvraagdatum .
  }
} WHERE {
  GRAPH ?g {
    ?applicationForm a lblodSubsidie:ApplicationForm ;
      subsidie:aanvraagdatum ?aanvraagdatum .
  }
}

;

# Avoid sprintf error
DELETE DATA {
  GRAPH <http://dummy/data/graph/0dc61f81-6ec6-4e16-80d3-26a61079c3c5> {
    <http://data.lblod.info/id/aanvraagen/test> a lblodSubsidie:ApplicationForm .
  }
}
