INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/70cc4947-33a3-4d26-82e0-2e1eacd2fea2>
      skos:related <https://lokaalbestuur.vlaanderen.be/relance/fietspaden> .

    <http://lblod.data.gift/concepts/1df4b56a-3ccd-450d-93dc-317fda1ada38>
      skos:related <https://lokaalbestuur.vlaanderen.be/projectsubsidie-noodopvang-schoolkinderen-vanaf-9-november-2020> .

    <http://lblod.data.gift/concepts/2697fbe1-4226-4325-807b-5dfa58e40a95>
      skos:related <https://www.vlaanderenhelpt.be/lokale-contactopsporing> .
  }
}
