PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX owl:  <http://www.w3.org/2007/uwa/context/common.owl#>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/73840d393bd94828f0903e8357c7f328d4bf4b8fbd63adbfa443e784f056a589/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/61643D17E5754600080000D6>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/6977011a-a29c-11eb-b62a-7fee2a9561b8> .
    <http://data.lblod.info/id/application-forms/61643DAEE5754600080000D8>
        adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c> . # Status SENT
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/73840d393bd94828f0903e8357c7f328d4bf4b8fbd63adbfa443e784f056a589/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/61643D17E5754600080000D6>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/c50d7726-4880-43e2-b098-c356722a3096> .
    <http://data.lblod.info/id/application-forms/61643DAEE5754600080000D8>
        adms:status <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> . # Status CONCEPT
  }
}
;
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/dbf74e8b71e474626b7a7566e6b74db3a73790e8b991a385d404e2267378635e/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/61714BFB890F3E000800000C>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/6977011a-a29c-11eb-b62a-7fee2a9561b8> .
    <http://data.lblod.info/id/application-forms/61714C7C890F3E000800000E>
        adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c> . # Status SENT
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/dbf74e8b71e474626b7a7566e6b74db3a73790e8b991a385d404e2267378635e/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/61714BFB890F3E000800000C>
        owl:active <http://lblod.data.info/id/subsidie-application-flow-steps/c50d7726-4880-43e2-b098-c356722a3096> .
    <http://data.lblod.info/id/application-forms/61714C7C890F3E000800000E>
        adms:status <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd> . # Status CONCEPT
  }
}