
PREFIX subsidie: <http://lblod.data.gift/vocabularies/subsidie/>

DELETE {
    GRAPH ?g {
        ?form subsidie:totalAmount "0"^^xsd:float .
    }
} WHERE {
    GRAPH ?g {
        ?form
            subsidie:totalAmount "0"^^xsd:float ;
            subsidie:totalAmount ?amount .
    }
}
GROUP BY ?form
HAVING (COUNT(?amount) > 1)