PREFIX adms: <http://www.w3.org/ns/adms#>

###
# START WORKAROUND SPRINTF
###
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/dummy/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> adms:status <http://dummy/status>.
  }
}

;

# Move to status ACTIVE
DELETE {
  GRAPH ?g {
    ?consumption adms:status ?outdated .
  }
}
INSERT {
  GRAPH ?g {
    ?consumption adms:status <http://lblod.data.gift/concepts/c849ca98-455d-4f31-9e95-a3d9d06e4497> . # ACTIVE
  }
} WHERE {
  VALUES ?consumption {
    <http://data.lblod.info/id/subsidy-measure-consumptions/61696778890F3E0008000069>
    <http://data.lblod.info/id/subsidy-measure-consumptions/616954AB890F3E000800005F>
    <http://data.lblod.info/id/subsidy-measure-consumptions/6169448E890F3E0008000048>
    <http://data.lblod.info/id/subsidy-measure-consumptions/61693B91890F3E0008000040>
    <http://data.lblod.info/id/subsidy-measure-consumptions/61692D19890F3E0008000027>
    <http://data.lblod.info/id/subsidy-measure-consumptions/61692A68890F3E0008000023>
    <http://data.lblod.info/id/subsidy-measure-consumptions/616921E9890F3E000800000C>
    <http://data.lblod.info/id/subsidy-measure-consumptions/dummy/bd03941f-ee51-42e4-8de1-a1d66e20fe7c>
  }
  GRAPH ?g {
    ?consumption adms:status ?outdated .
  }
}

;

# move to status SENT
DELETE {
  GRAPH ?g {
    ?consumption adms:status ?outdated .
  }
}
INSERT {
  GRAPH ?g {
    ?consumption adms:status <http://lblod.data.gift/concepts/2ea29fbf-6d46-4f08-9343-879282a9f484> . # SENT
  }
} WHERE {
  VALUES ?consumption {
   <http://data.lblod.info/id/subsidy-measure-consumptions/61693A9A890F3E0008000039>
   <http://data.lblod.info/id/subsidy-measure-consumptions/616926C8890F3E000800001B>
   <http://data.lblod.info/id/subsidy-measure-consumptions/61692801890F3E0008000020>
   <http://data.lblod.info/id/subsidy-measure-consumptions/614C1EB0E5754600080001E9>
   <http://data.lblod.info/id/subsidy-measure-consumptions/615472E9E575460008000206>
   <http://data.lblod.info/id/subsidy-measure-consumptions/dummy/bd03941f-ee51-42e4-8de1-a1d66e20fe7c>
  }
  GRAPH ?g {
    ?consumption adms:status ?outdated .
  }
}

;

###
# START WORKAROUND SPRINTF
###
DELETE {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    ?s ?p ?o.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/dummy/sprintf/bd03941f-ee51-42e4-8de1-a1d66e20fe7c> {
    ?s ?p ?o.
  }
}