INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/6b7ae118-4653-48f2-9d9a-4712f8c30da9>
      a <http://www.w3.org/2004/02/skos/core#Concept>, <http://mu.semte.ch/vocabularies/ext/SubmissionDocumentStatus> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6b7ae118-4653-48f2-9d9a-4712f8c30da9" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Nieuw"@nl ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/9cf6fa63-1f49-4d53-af06-e1c235ece10b> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/9cf6fa63-1f49-4d53-af06-e1c235ece10b> .
  }
}
