PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {

    #################################################
    ### Concepts used in the contact tracing form ###
    #################################################

    ########################################################
    ### CONCEPT - Focused at-risk and vulnerable populations

    <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "b956a95b-bfb6-4094-b7f7-6b612e650c4f" ;
        skos:prefLabel "Focused at-risk and vulnerable populations"@en ;
        skos:definition "Which at-risk and vulnerable populations has your board focused on?"@en .

    <http://data.lblod.info/id/subsidies/rules/4ca04e45-cfbd-44e5-a91b-d070caff6b49> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "4ca04e45-cfbd-44e5-a91b-d070caff6b49" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Anderstaligen'@nl .

    <http://data.lblod.info/id/subsidies/rules/d71b5fc9-c304-4687-b789-76a84296932f> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "d71b5fc9-c304-4687-b789-76a84296932f" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel '65+plussers'@nl .

    <http://data.lblod.info/id/subsidies/rules/9f483029-cdc4-43f2-b07b-c6d3d2bd32ec> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "9f483029-cdc4-43f2-b07b-c6d3d2bd32ec" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Personen met een handicap'@nl .

    <http://data.lblod.info/id/subsidies/rules/384b2567-ab54-4b6f-b19c-a438829b3666> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "384b2567-ab54-4b6f-b19c-a438829b3666" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Ondernemers'@nl .

    <http://data.lblod.info/id/subsidies/rules/34bac9ee-29fd-4fa9-b4f3-aaacf2c14a20> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "34bac9ee-29fd-4fa9-b4f3-aaacf2c14a20" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Personen met beperkte mobiliteit'@nl .

    <http://data.lblod.info/id/subsidies/rules/baef0751-81b2-4b0c-88c9-4cdd635e0a21> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "baef0751-81b2-4b0c-88c9-4cdd635e0a21" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Werklozen'@nl .

    <http://data.lblod.info/id/subsidies/rules/49f168af-7cc2-412b-afb2-ec9a0fd9760d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "49f168af-7cc2-412b-afb2-ec9a0fd9760d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Daklozen'@nl .

    <http://data.lblod.info/id/subsidies/rules/a10ccc14-6b46-4fd6-ab9b-c6e45c673287> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "a10ccc14-6b46-4fd6-ab9b-c6e45c673287" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Woonwagenbewoners'@nl .

    <http://data.lblod.info/id/subsidies/rules/34eb316a-488b-4ec3-a29e-450b016a85b7> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "34eb316a-488b-4ec3-a29e-450b016a85b7" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Personen met een laag inkomen'@nl .

    <http://data.lblod.info/id/subsidies/rules/409a270a-3e73-4466-9657-7a52b46b8490> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "409a270a-3e73-4466-9657-7a52b46b8490" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Jongeren'@nl .

    <http://data.lblod.info/id/subsidies/rules/e9a7abaf-7098-4489-8fcb-aa73e80f0733> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "e9a7abaf-7098-4489-8fcb-aa73e80f0733" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b956a95b-bfb6-4094-b7f7-6b612e650c4f> ;
        skos:prefLabel 'Andere'@nl .


    ################################
    ### CONCEPT - Types of contacts

    <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "c319af9d-2e1f-4d2e-befd-43f0e895604b" ;
        skos:prefLabel "Types of contacts"@en ;
        skos:definition "What type of contacts did the board have during the duration of the project?"@en .

    <http://data.lblod.info/id/subsidies/rules/94ee5c3c-2794-4fd2-9779-524f71e2005b> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "94ee5c3c-2794-4fd2-9779-524f71e2005b" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b> ;
        skos:prefLabel 'Telefonische contacten'@nl .

    <http://data.lblod.info/id/subsidies/rules/17eda7bf-ef96-4871-bc65-f7fd96a4d937> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "17eda7bf-ef96-4871-bc65-f7fd96a4d937" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b> ;
        skos:prefLabel 'Huis-aan-huis-bezoeken'@nl .

    <http://data.lblod.info/id/subsidies/rules/4899326e-096a-4a77-84d4-9af9ad70ab30> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "4899326e-096a-4a77-84d4-9af9ad70ab30" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b> ;
        skos:prefLabel 'Burgerloket'@nl .

    <http://data.lblod.info/id/subsidies/rules/fb34b0bf-2dfa-4ac1-a091-fd8f191d8197> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "fb34b0bf-2dfa-4ac1-a091-fd8f191d8197" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b> ;
        skos:prefLabel 'E-mail'@nl .

    <http://data.lblod.info/id/subsidies/rules/26bd1ec3-c601-4aaa-bdd0-6ee1855b1a99> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "26bd1ec3-c601-4aaa-bdd0-6ee1855b1a99" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/c319af9d-2e1f-4d2e-befd-43f0e895604b> ;
        skos:prefLabel 'Andere'@nl .


    ##########################################
    ### CONCEPT - Used methods for prevention

    <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "9410a32e-308e-4bf0-a3b0-af8f9c9c19b2" ;
        skos:prefLabel "Used methods for prevention"@en ;
        skos:definition "What methods did you use ?"@en .

    <http://data.lblod.info/id/subsidies/rules/04a7e1c6-407a-4154-819e-de1cfa4dee92> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "04a7e1c6-407a-4154-819e-de1cfa4dee92" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Verspreiding van folders'@nl .

    <http://data.lblod.info/id/subsidies/rules/dd80f93f-e013-4cbb-840d-53b3c3a888fb> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "dd80f93f-e013-4cbb-840d-53b3c3a888fb" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Via website'@nl .

    <http://data.lblod.info/id/subsidies/rules/1afe28e2-e6b7-4af3-86b6-1254e8ae7d87> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "1afe28e2-e6b7-4af3-86b6-1254e8ae7d87" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Telefonische contacten'@nl .

    <http://data.lblod.info/id/subsidies/rules/f5d4ce8c-6baf-4304-8037-0aa7afe631e5> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "f5d4ce8c-6baf-4304-8037-0aa7afe631e5" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Huis-aan-huis bezoeken'@nl .

    <http://data.lblod.info/id/subsidies/rules/aa995916-6deb-478b-b332-9300f494044d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "aa995916-6deb-478b-b332-9300f494044d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Contacten via mutualiteiten'@nl .

    <http://data.lblod.info/id/subsidies/rules/e2ab52dc-7b22-40a7-9fa4-51973c3bad5a> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "e2ab52dc-7b22-40a7-9fa4-51973c3bad5a" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Via Influencers'@nl .

    <http://data.lblod.info/id/subsidies/rules/d0c60eba-dbd0-46a5-a237-7d26f465af28> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "d0c60eba-dbd0-46a5-a237-7d26f465af28" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Via Armoedeorganisaties'@nl .

    <http://data.lblod.info/id/subsidies/rules/dee57634-9b26-454d-bb33-f32f4d1c9bf6> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "dee57634-9b26-454d-bb33-f32f4d1c9bf6" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Via de Voedselbank'@nl .

    <http://data.lblod.info/id/subsidies/rules/f66f46b3-2fbc-4ce7-a8aa-deb947d4cee7> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "f66f46b3-2fbc-4ce7-a8aa-deb947d4cee7" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/9410a32e-308e-4bf0-a3b0-af8f9c9c19b2> ;
        skos:prefLabel 'Andere'@nl .


    #################################################
    ### CONCEPT - Taken actions for source detection

    <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "6fb38b16-9d92-49da-ae56-945505c12e1a" ;
        skos:prefLabel "Taken actions for source detection"@en ;
        skos:definition "What actions have you taken ?"@en .

    <http://data.lblod.info/id/subsidies/rules/e8fe4796-64be-4995-82ce-ba9f355fb5b4> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "e8fe4796-64be-4995-82ce-ba9f355fb5b4" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Contacteren van besmette personen uit de interne controletoren'@nl .

    <http://data.lblod.info/id/subsidies/rules/acd2e32c-fdcd-4ff5-991b-b0399296ec24> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "acd2e32c-fdcd-4ff5-991b-b0399296ec24" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Melden van clusters in het uitbraakvolgsysteem'@nl .

    <http://data.lblod.info/id/subsidies/rules/9bd53c83-f67e-48a4-8b65-051e018cc3bf> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "9bd53c83-f67e-48a4-8b65-051e018cc3bf" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Monitoren van evenementen'@nl .

    <http://data.lblod.info/id/subsidies/rules/06720e8f-f786-43cc-8d4a-3355505f7278> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "06720e8f-f786-43cc-8d4a-3355505f7278" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Verzamelen van horecalijsten'@nl .

    <http://data.lblod.info/id/subsidies/rules/a13b8675-10fb-44d4-bdb0-e7bf141e96e5> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "a13b8675-10fb-44d4-bdb0-e7bf141e96e5" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Doorgeven van contacten aan de centrale contactracing'@nl .

    <http://data.lblod.info/id/subsidies/rules/0bef5e29-c866-427c-88f9-187331b4bf3c> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "0bef5e29-c866-427c-88f9-187331b4bf3c" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Overleg met de zorgraad'@nl .

    <http://data.lblod.info/id/subsidies/rules/d3dd104d-dac1-422e-9ad5-d9dabbcb2bbe> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "d3dd104d-dac1-422e-9ad5-d9dabbcb2bbe" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Isoleren of tijdelijke sluiting van clusters'@nl .

    <http://data.lblod.info/id/subsidies/rules/21fd7549-7215-4f2e-b598-23adbcfc0569> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "21fd7549-7215-4f2e-b598-23adbcfc0569" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/6fb38b16-9d92-49da-ae56-945505c12e1a> ;
        skos:prefLabel 'Andere'@nl .


    ####################################################
    ### CONCEPT - Used methods for quarantaine-coaching

    <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "85b363cc-6d69-4aa4-88ed-ab5ba50b1993" ;
        skos:prefLabel "Used methods for quarantaine-coaching"@en ;
        skos:definition "What methods did you use?"@en .

    <http://data.lblod.info/id/subsidies/rules/71ea6694-81df-43fb-a125-a328e71d22e2> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "71ea6694-81df-43fb-a125-a328e71d22e2" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Tijdelijke woongelegenheid ter beschikking gesteld'@nl .

    <http://data.lblod.info/id/subsidies/rules/9b6be38f-ea5d-4978-9a4b-59e8e235e772> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "9b6be38f-ea5d-4978-9a4b-59e8e235e772" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Quarantaine een centrum voor herstelverblijf'@nl .

    <http://data.lblod.info/id/subsidies/rules/7a1e123f-2f7e-44d0-a107-654eb1aa8746> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "7a1e123f-2f7e-44d0-a107-654eb1aa8746" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Huisbezoek door quarantainecoach'@nl .

    <http://data.lblod.info/id/subsidies/rules/c9190e70-2f94-4edb-8ea5-bcfbaf4a9cfc> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "c9190e70-2f94-4edb-8ea5-bcfbaf4a9cfc" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Belronde door quarantainecoach'@nl .

    <http://data.lblod.info/id/subsidies/rules/60306cda-a2d2-40ea-99d2-0ec1bfa0805d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "60306cda-a2d2-40ea-99d2-0ec1bfa0805d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Uitleggen van maatregelen (met of zonder tolken)'@nl .

    <http://data.lblod.info/id/subsidies/rules/9dbc9843-7ac4-47c5-a381-311735068ebf> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "9dbc9843-7ac4-47c5-a381-311735068ebf" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Praktische hulp (boodschappen/voedselpakketten)'@nl .

    <http://data.lblod.info/id/subsidies/rules/182df43f-10af-4be5-875e-1a0e8051d559> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "182df43f-10af-4be5-875e-1a0e8051d559" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Doorverwijzing naar gespecialiseerde hulp'@nl .

    <http://data.lblod.info/id/subsidies/rules/92af1821-29f6-4b73-b9b5-95f1bf92fe3d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "92af1821-29f6-4b73-b9b5-95f1bf92fe3d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Financiële hulpvragen doorgeven naar de juiste instanties'@nl .

    <http://data.lblod.info/id/subsidies/rules/1ae51af1-00f5-499a-8bb6-97113285ca5c> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "1ae51af1-00f5-499a-8bb6-97113285ca5c" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/85b363cc-6d69-4aa4-88ed-ab5ba50b1993> ;
        skos:prefLabel 'Andere'@nl .


    ########################################################
    ### CONCEPT - Organized help for vulnerable groups

    <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>, <http://www.w3.org/2004/02/skos/core#ConceptScheme>;
        mu:uuid "4135a965-2cd9-425f-8c45-1223307c66d4" ;
        skos:prefLabel "Organized help for vulnerable groups"@en ;
        skos:definition "What help did you organize?"@en .

    <http://data.lblod.info/id/subsidies/rules/2ddf912c-e71a-45ae-847b-f9e94ab90d70> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "2ddf912c-e71a-45ae-847b-f9e94ab90d70" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Boodschappen gedaan voor de gezinnen (zelf of door andere actoren)'@nl .

    <http://data.lblod.info/id/subsidies/rules/c34db3c6-157c-4115-86dd-de0cb953a240> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "c34db3c6-157c-4115-86dd-de0cb953a240" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Samenaankoopactie georganiseerd'@nl .

    <http://data.lblod.info/id/subsidies/rules/1bdfcee0-339e-4c94-8b76-386481b142cb> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "1bdfcee0-339e-4c94-8b76-386481b142cb" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Informatie op maat'@nl .

    <http://data.lblod.info/id/subsidies/rules/4e035c5b-195f-42ff-b9b7-9f356949370d> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "4e035c5b-195f-42ff-b9b7-9f356949370d" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Coaching met tolk'@nl .

    <http://data.lblod.info/id/subsidies/rules/5458ea7e-8692-459c-8208-fef02601a757> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "5458ea7e-8692-459c-8208-fef02601a757" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Huisbezoek'@nl .

    <http://data.lblod.info/id/subsidies/rules/8a5c1696-7198-41af-8f41-d63f9a53f1a1> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "8a5c1696-7198-41af-8f41-d63f9a53f1a1" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Psychologische of mentale ondersteuning'@nl .

    <http://data.lblod.info/id/subsidies/rules/e7c07f5f-803f-4c0a-b5e1-d1ac03a82dac> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "e7c07f5f-803f-4c0a-b5e1-d1ac03a82dac" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Financiële ondersteuning'@nl .

    <http://data.lblod.info/id/subsidies/rules/2b4d4b9a-da9d-481a-aa8b-08c8fe89c230> a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class>;
        mu:uuid "2b4d4b9a-da9d-481a-aa8b-08c8fe89c230" ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/4135a965-2cd9-425f-8c45-1223307c66d4> ;
        skos:prefLabel 'Andere'@nl .

  }
}
