PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?smc dct:creator ?lastModifiedBy .
  }
} WHERE {
  GRAPH ?g {
    ?smc a subsidie:SubsidiemaatregelConsumptie ;
      ext:lastModifiedBy ?lastModifiedBy .
    FILTER NOT EXISTS { ?smc dct:creator ?creator . }
  }
}
