DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/ce89e6f8-5a72-4f5c-98dd-0f7128a6ca24>
      <http://data.europa.eu/m8g/endTime> "2021-06-11T00:00:00"^^xsd:dateTime .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/periodes/ce89e6f8-5a72-4f5c-98dd-0f7128a6ca24>
      <http://data.europa.eu/m8g/endTime> "2021-06-11T23:59:59"^^xsd:dateTime .
  }
}
