### Bredene
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/a0b451f349f1609834f2236ed8149e4f254e9aae1a897c531a99b9b0bbac0899/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/614C3A4EE57546000800021A> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/2ea29fbf-6d46-4f08-9343-879282a9f484> .
    <http://data.lblod.info/id/application-forms/614C3E9EE575460008000222> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/a0b451f349f1609834f2236ed8149e4f254e9aae1a897c531a99b9b0bbac0899/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/614C3A4EE57546000800021A> <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397> ;
      <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/c849ca98-455d-4f31-9e95-a3d9d06e4497> .
    <http://data.lblod.info/id/application-forms/614C3E9EE575460008000222> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/6b7ae118-4653-48f2-9d9a-4712f8c30da9> .
  }
}
;
### Wielsbeke
DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/11e23f966461f4740579b5ac2745421c6a3c3f42a9dbd4df7bd3d3f21e44f129/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/60EC47E4DCCA9300080001EC> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/2ea29fbf-6d46-4f08-9343-879282a9f484> .
    <http://data.lblod.info/id/application-forms/60ED70E4DCCA9300080002C1> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c> .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/11e23f966461f4740579b5ac2745421c6a3c3f42a9dbd4df7bd3d3f21e44f129/LoketLB-subsidies> {
    <http://data.lblod.info/id/subsidy-measure-consumptions/60EC47E4DCCA9300080001EC> <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397> ;
      <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/c849ca98-455d-4f31-9e95-a3d9d06e4497> .
    <http://data.lblod.info/id/application-forms/60ED70E4DCCA9300080002C1> <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/6b7ae118-4653-48f2-9d9a-4712f8c30da9> .
  }
}

