PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA{
  GRAPH <http://mu.semte.ch/graphs/public> {
   <share://semantic-forms/20210222214348-forms.ttl> a nfo:FileDataObject ;
 				  dct:type <http://data.lblod.gift/concepts/form-file-type> ;
                                  mu:uuid "e9761fdd-5476-426d-b099-8b55e7c15c1e" ;
                                  nfo:fileName "20210222214348-forms.ttl" ;
                                  dct:created "2021-02-22Z"^^xsd:dateTime ;
                                  dct:modified "2021-02-22Z"^^xsd:dateTime ;
                                  dct:format "text/turtle";
                                  nfo:fileSize "265045"^^xsd:integer;
                                  dbpedia:fileExtension "ttl" .
  }
}
