DELETE {
  GRAPH ?g {
   <http://data.lblod.info/id/bestuurseenheden/9e6b6eb3-2f0b-4723-876b-178dfaecfddf> <http://purl.org/dc/terms/identifier> ?identifier.
  }
}
INSERT {
  GRAPH ?g {
   <http://data.lblod.info/id/bestuurseenheden/9e6b6eb3-2f0b-4723-876b-178dfaecfddf> <http://purl.org/dc/terms/identifier> "OVO001151".
  }
}
WHERE {
  GRAPH ?g {
   <http://data.lblod.info/id/bestuurseenheden/9e6b6eb3-2f0b-4723-876b-178dfaecfddf> <http://purl.org/dc/terms/identifier> ?identifier.
  }
}