PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/d90c511e-f827-488c-84ba-432c8f69561c>
      a skos:Concept, ext:BestuurseenheidClassificatieCode ;
      mu:uuid "d90c511e-f827-488c-84ba-432c8f69561c" ;
      skos:prefLabel "Vlaamse gemeenschapscommissie" ;
      skos:inScheme <http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> ;
      skos:topConceptOf <http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> .

    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/7148e12a-ae03-4a7b-bb16-7b6269b84175>
      a skos:Concept, ext:BestuursorgaanClassificatieCode ;
      mu:uuid "7148e12a-ae03-4a7b-bb16-7b6269b84175" ;
      skos:prefLabel "College" ;
      skos:inScheme <http://data.vlaanderen.be/id/conceptscheme/BestuursorgaanClassificatieCode> ;
      skos:topConceptOf <http://data.vlaanderen.be/id/conceptscheme/BestuursorgaanClassificatieCode> .

    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ff20fa3e-806b-4160-b74b-7483fe3a6ecd>
      a skos:Concept, ext:BestuursorgaanClassificatieCode ;
      mu:uuid "ff20fa3e-806b-4160-b74b-7483fe3a6ecd" ;
      skos:prefLabel "Collegelid" ;
      skos:inScheme <http://data.vlaanderen.be/id/conceptscheme/BestuursorgaanClassificatieCode> ;
      skos:topConceptOf <http://data.vlaanderen.be/id/conceptscheme/BestuursorgaanClassificatieCode> .
  }
}
