# This mainly to clean up QA
# sprintf issue
INSERT DATA {
  GRAPH <http://stub-graph/for/migration-cleanup-step2> {
    <http://foo/19724e9b-124c-4d6a-a6d6-7396c0da33b7> a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelConsumptie>;
     <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397>.
  }
}

;

DELETE {
  GRAPH ?g {
   ?s a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelConsumptie>;
     <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397>.
  }
}
INSERT {
  GRAPH ?g {
   ?s a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelConsumptie>;
     <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/f135ee39-fff1-4cae-9b87-bf3cd9098b3e>.
  }
}
WHERE {
  GRAPH ?g {
   ?s a <http://data.vlaanderen.be/ns/subsidie#SubsidiemaatregelConsumptie>;
     <http://www.w3.org/2007/uwa/context/common.owl#active> <http://lblod.data.info/id/subsidie-application-flow-steps/eb633b90fee29738872ee370ec24d60da792c9bdf5b97e125c7a34653d5e4397>.
  }
}

;

DELETE {
  GRAPH <http://stub-graph/for/migration-cleanup-step2> {
    ?s ?p ?o.
  }
}
WHERE {
  GRAPH <http://stub-graph/for/migration-cleanup-step2> {
    ?s ?p ?o.
  }
}