PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <share://semantic-forms/20221220135616-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "92884e3b-a1eb-40aa-a2d3-883b9792299a" ;
      nfo:fileName "20221220135616-forms.ttl" ;
      dct:created "2022-12-20T13:56:16"^^xsd:dateTime ;
      dct:modified "2022-12-20T13:56:16"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "348394"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    