PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE {
  GRAPH ?g {
    ?burgemeester foaf:familyName ?familyName
  }
}
INSERT {
  GRAPH ?g {
    ?burgemeester foaf:familyName "Deschepper"
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/personen/0df4f9a3a1b13c6bc5d8e25c5d73a42f2eed1f4f0a246b9d309b0bf1ef04e7a8> as ?burgemeester)

  GRAPH ?g {
    ?burgemeester a person:Person ;
      foaf:familyName ?familyName .
  }
}
