PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX erediensten: <http://data.lblod.info/vocabularies/erediensten/>

INSERT {
  GRAPH ?g {
    ?account ext:sessionRole
        "LoketLB-databankEredienstenGebruiker",
        "LoketLB-eredienstOrganisatiesGebruiker".
  }
}
WHERE {
  VALUES ?classificatie {
     <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/f9cac08a-13c1-49da-9bcb-f650b0604054>
     <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/66ec74fd-8cfc-4e16-99c6-350b35012e86>
     <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36372fad-0358-499c-a4e3-f412d2eae213>
     <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>
     <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>

   }
  ?bestuurseenheid a besluit:Bestuurseenheid;
    <http://data.vlaanderen.be/ns/besluit#classificatie> ?classificatie.

  ?persoon a foaf:Person;
    foaf:member ?bestuurseenheid;
    foaf:account ?account.

  GRAPH ?g {
   ?account a foaf:OnlineAccount;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
       ext:sessionRole ?role.
  }
}