DELETE {
  GRAPH ?g {
   <http://data.lblod.info/id/periodes/2afe1031-b282-4351-a938-2de0a1306e53> <http://data.europa.eu/m8g/endTime> ?endtime
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/periodes/2afe1031-b282-4351-a938-2de0a1306e53> <http://data.europa.eu/m8g/endTime> "2023-09-19T21:59:58Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
  }
} WHERE {
  GRAPH ?g {
      <http://data.lblod.info/id/periodes/2afe1031-b282-4351-a938-2de0a1306e53> <http://data.europa.eu/m8g/endTime> ?endtime
  }
}