DELETE {
  GRAPH ?g {
    ?s ?p ?o.
    ?source ?sourceP ?s.
  }
} WHERE {
  GRAPH ?g {
   ?s a <http://lblod.data.gift/vocabularies/subsidie/ApplicationForm> ;
     <http://purl.org/dc/terms/isPartOf>	<http://lblod.data.info/id/subsidie-application-flow-steps/8922293b-d4e3-42d8-9f86-fe2ff7503ee8>;
     ?p ?o.
   ?source ?sourceP ?s.
  }
}
