DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/representatieveOrganen/b4d22cde910a7b58b6e4d9c1d3b15fbb> <http://www.w3.org/ns/org#linkedTo> ?o.
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/representatieveOrganen/2089dc85d4ba48a7f28ee4b521af2b26> <http://www.w3.org/ns/org#linkedTo> ?o.
  }
}
WHERE {
  VALUES ?o {
    <http://data.lblod.info/id/besturenVanDeEredienst/d264e200ccd91eb41f794efc98380f7c>
    <http://data.lblod.info/id/besturenVanDeEredienst/1ce3e84e6bc0b7303f45b339b47e8755>
    <http://data.lblod.info/id/besturenVanDeEredienst/6be88677571d7bf7272e10f3d76a5b6e>
    <http://data.lblod.info/id/besturenVanDeEredienst/3e0d4dbea78e2fa221d0be5037c63066>
    <http://data.lblod.info/id/besturenVanDeEredienst/0cf9e2ba13383363a0dafecd18c39fd4>
    <http://data.lblod.info/id/centraleBesturenVanDeEredienst/1e79c9d4e55e620ab86d6557b581e4a5>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/representatieveOrganen/b4d22cde910a7b58b6e4d9c1d3b15fbb> <http://www.w3.org/ns/org#linkedTo> ?o;
       a  <http://data.lblod.info/vocabularies/erediensten/RepresentatiefOrgaan>.
  }
}