# Removes all mandaten: Bestuurslid van het bestuur van de eredienst
# that are not attached to a mandataris. We'll run it a second time
# once the existing mandatarissen have been updated

PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

DELETE {
 GRAPH ?j {
   ?mandaat ?p ?o.
   ?org org:hasPost ?mandaat.
 }
}
WHERE {
 GRAPH ?j {
   ?mandaat org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/2e021095727b2464459a63e16ebeafd2>;
     ?p ?o.
   ?org org:hasPost ?mandaat.
 }

 FILTER NOT EXISTS {
   GRAPH ?g {
     ?mandataris a mandaat:Mandataris;
       org:holds ?mandaat.
   }
 }
}