PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX subsidie: <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif: <https://www.gleif.org/ontology/Base/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX common: <http://www.w3.org/2007/uwa/context/common.owl#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

# Insert only the specific SubsidiemaatregelAanbod into the graph of "Gemeente Deinze" while keeping other
# types (SubsidiemaatregelAanbodReeks, ApplicationFlow, ApplicationStep, periodOfTime) in the public graph
INSERT {
  GRAPH <http://mu.semte.ch/graphs/organizations/28346950e285b8b816133fece5ac9408097c3f190c7f32573cf0c640d6c34b1a/LoketLB-subsidies> { # Gemeente Deinze
    ?SubsidiemaatregelAanbod ?p ?o .
    ?SubsidiemaatregelAanbodReeks ?p2 ?o2 .
  }
}
WHERE {
  VALUES ?SubsidiemaatregelAanbod {
    <http://lblod.data.info/id/subsidy-measure-offers/c10fc76f-effe-430e-822f-60f03f575302>
  }

  VALUES ?SubsidiemaatregelAanbodReeks {
    <http://lblod.data.info/id/subsidy-measure-offer-series/7dab5e94-89d3-4e26-b28a-cc585652786b>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?SubsidiemaatregelAanbod ?p ?o .
    ?SubsidiemaatregelAanbodReeks ?p2 ?o2 .
  }
}

;

# Remove only the specific SubsidiemaatregelAanbod from the public graph while keeping other types
# (SubsidiemaatregelAanbodReeks, ApplicationFlow, ApplicationStep, periodOfTime) in the public graph

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?SubsidiemaatregelAanbod ?p ?o .
    ?SubsidiemaatregelAanbodReeks ?p2 ?o2 .
  }
}
WHERE {
  VALUES ?SubsidiemaatregelAanbod {
    <http://lblod.data.info/id/subsidy-measure-offers/c10fc76f-effe-430e-822f-60f03f575302>
  }

  VALUES ?SubsidiemaatregelAanbodReeks {
    <http://lblod.data.info/id/subsidy-measure-offer-series/7dab5e94-89d3-4e26-b28a-cc585652786b>
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?SubsidiemaatregelAanbod ?p ?o .
    ?SubsidiemaatregelAanbodReeks ?p2 ?o2 .
  }
}
