PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX financieringsPartnerType:  <http://lblod.data.gift/vocabularies/subsidie/concept/FinancieringPartnerType/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    lblodSubsidie:FinancieringPartnerType a skos:ConceptScheme ;
      mu:uuid "aa0017fe-9640-4af7-9820-8b15ef1028aa" ;
      skos:prefLabel "Financieringspartnertype"@nl ;
      skos:hasTopConcept financieringsPartnerType:EigenAandeel ;
      skos:hasTopConcept financieringsPartnerType:Publiek ;
      skos:hasTopConcept financieringsPartnerType:Privaat .

    financieringsPartnerType:EigenAandeel a skos:Concept ;
      mu:uuid "933b8282-4613-4557-8a02-fa97d5486370" ;
      skos:prefLabel "Eigen aandeel stad"@nl ;
      skos:inScheme lblodSubsidie:FinancieringPartnerType ;
      skos:topConceptOf lblodSubsidie:FinancieringPartnerType .

    financieringsPartnerType:Publiek a skos:Concept ;
      mu:uuid "926b78bc-4282-436d-b4ef-66330722eee6" ;
      skos:prefLabel "Publiek"@nl ;
      skos:inScheme lblodSubsidie:FinancieringPartnerType ;
      skos:topConceptOf lblodSubsidie:FinancieringPartnerType .

    financieringsPartnerType:Privaat a skos:Concept ;
      mu:uuid "c9151992-5cc6-4608-8d3b-cfe5eb81d03e" ;
      skos:prefLabel "Privaat"@nl ;
      skos:inScheme lblodSubsidie:FinancieringPartnerType ;
      skos:topConceptOf lblodSubsidie:FinancieringPartnerType .
  }
}