PREFIX dvc:   <https://productencatalogus.data.vlaanderen.be/id/concept/YourEuropeCategorie/>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    dvc:ProcedureStartenExploiterenSluitenBedrijf skos:prefLabel "Starten, exploiteren en sluiten van een bedrijf"@nl .
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    dvc:ProcedureStartenExploiterenSluitenBedrijf skos:prefLabel "Procedures voor starten, exploiteren en sluiten van een bedrijf"@nl .
  }
}
