PREFIX account: <http://mu.semte.ch/vocabularies/account/>
PREFIX ext:     <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/bf83abb71bd810ad1ebe05ac8cb72a1c> .  # Centraal Comité van de Anglicaanse Eredienst in België
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/6f79a1b89678b85009484da7c4a104bc> .  # Administratieve Raad van de Protestants-Evangelische Eredienst (ARPEE)
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/859ae3dff21dcfd97e70d180569ebad1> .  # Centraal Israëlitische Consistorie van België
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/0ebb44c2ef14d86978ea85e74d128ad1> .  # Oecumenisch Patriarchaat van Konstantinopel
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/e224c637ba8bb0e5dfbb87da225b4652> .  # Executief van de Moslims van België 
  }
}
WHERE {
  BIND(<http://data.lblod.info/vendors/b1e41693-639a-4f61-92a9-5b9a3e0b924e> as ?vendor)  # Vanden Broele
  GRAPH ?g {
    ?vendor a ext:Vendor
  }
}
