PREFIX mobiliteit:    <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct:           <http://purl.org/dc/terms/>
PREFIX subsidie:      <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif:         <https://www.gleif.org/ontology/Base/>
PREFIX mu:            <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv:          <http://purl.org/vocab/cpsv#>
PREFIX xkos:          <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb:            <http://purl.org/linked-data/cube#>
PREFIX xsd:           <http://www.w3.org/2001/XMLSchema#>
PREFIX mg8:           <http://data.europa.eu/m8g/>
PREFIX common:        <http://www.w3.org/2007/uwa/context/common.owl#>

#
# Create subsidy procedure step type for external processing
#
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/3ded9eab-ff5b-4a20-a095-0825de486f42>
      a               skos:Concept, rdfs:Class ;
      mu:uuid         "3ded9eab-ff5b-4a20-a095-0825de486f42" ;
      skos:prefLabel  "Externe verwerking"@nl ;
      skos:inScheme   <http://lblod.data.gift/concept-schemes/77604806-1006-459b-9228-583d279c7a1c> .
  }
}

;

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Period of the series
    <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f>
      a             mg8:PeriodOfTime ;
      mu:uuid       "f3357ba2-abd4-44b3-a66b-70e8f3f9671f" ;
      mg8:startTime "2023-05-29T21:59:59Z"^^xsd:dateTime .

    # Step(s) of the series
    <http://data.lblod.info/id/subsidy-procedural-steps/570fb5da-4874-46f5-8adb-3467cf88f3f2>
      a                                   subsidie:Subsidieprocedurestap ;
      mu:uuid                             "570fb5da-4874-46f5-8adb-3467cf88f3f2" ;
      dct:description                     """Externe verwerking""" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/3ded9eab-ff5b-4a20-a095-0825de486f42> ; # External processing
      mobiliteit:periode                  <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f> .

    # Step(s) of the active submission flow
    <http://lblod.data.info/id/subsidie-application-flow-steps/0a1bfaab-a3aa-478c-a843-9ad1444ad192>
      a                 lblodSubsidie:ApplicationStep ;
      mu:uuid           "0a1bfaab-a3aa-478c-a843-9ad1444ad192" ;
      qb:order          0 ;
      dct:references    <http://data.lblod.info/id/subsidy-procedural-steps/570fb5da-4874-46f5-8adb-3467cf88f3f2> ;
      dct:isPartOf      <http://lblod.data.info/id/subsidie-application-flows/394add49-28c4-48a4-bc67-c34db51502e3> ;
      dct:isReplacedBy  <https://subsidiesmobiliteitsbeleid.vlaanderen.be/> .

    # Active submission flow for latest hoppinpunten subsidy series
    <http://lblod.data.info/id/subsidie-application-flows/394add49-28c4-48a4-bc67-c34db51502e3>
      a               lblodSubsidie:ApplicationFlow ;
      mu:uuid         "394add49-28c4-48a4-bc67-c34db51502e3" ;
      xkos:belongsTo  <http://lblod.data.info/id/subsidy-measure-offer-series/3bfba485-f211-445c-80b7-e340c410ce1d> ;
      xkos:next       <http://lblod.data.info/id/subsidie-application-flow-steps/0a1bfaab-a3aa-478c-a843-9ad1444ad192> .

    # Create Series for subsidy call named "Oproep"
    <http://lblod.data.info/id/subsidy-measure-offer-series/3bfba485-f211-445c-80b7-e340c410ce1d>
      a                   lblodSubsidie:SubsidiemaatregelAanbodReeks ;
      mu:uuid             "3bfba485-f211-445c-80b7-e340c410ce1d" ;
      dct:title           "Oproep"@nl ;
      dct:description     "29/05/2023 — nvt"@nl ;
      mobiliteit:periode  <http://data.lblod.info/id/periodes/f3357ba2-abd4-44b3-a66b-70e8f3f9671f> ;
      common:active       <http://lblod.data.info/id/subsidie-application-flows/394add49-28c4-48a4-bc67-c34db51502e3> .

    # Subsidy offer for "hoppinpunten"
    <http://lblod.data.info/id/subsidy-measure-offers/b6e5ccd5-ddaf-4b74-b023-a712886f3814>
      a                         subsidie:SubsidiemaatregelAanbod ;
      mu:uuid                   "b6e5ccd5-ddaf-4b74-b023-a712886f3814" ;
      dct:title                 """Subsidie voor Hoppinpunten""" ;
      skos:prefLabel            """Subsidie voor Hoppinpunten""" ;
      skos:related              <https://www.vlaanderen.be/subsidies-voor-de-aanleg-of-herinrichting-van-een-hoppinpunt> ;
      cpsv:follows              <http://data.lblod.info/id/subsidy-procedural-steps/570fb5da-4874-46f5-8adb-3467cf88f3f2> ;
      lblodSubsidie:heeftReeks  <http://lblod.data.info/id/subsidy-measure-offer-series/3bfba485-f211-445c-80b7-e340c410ce1d> .
  }
}
