PREFIX mg8: <http://data.europa.eu/m8g/>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    #Nooddorpen Oekraïne
    <http://lblod.data.info/id/subsidy-measure-offer-series/4a40d903-d77f-49e0-8cf4-daa3ce623439> dct:description ?Description1 .
    <http://data.lblod.info/id/periodes/5ecb1512-e8b3-40bf-a0c4-a4087090c093> mg8:endTime ?end1.
    <http://data.lblod.info/id/periodes/8265739f-2f05-4ada-8a30-c813b4bd783c> mg8:endTime ?end2.

    #Opknapwerken slaapplekken Oekraïne
    <http://lblod.data.info/id/subsidy-measure-offer-series/fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773> dct:description ?Description2 .
    <http://data.lblod.info/id/periodes/cbc00fd0-0d0e-4c99-8dfc-691db7dde72d> mg8:endTime ?end3.
    <http://data.lblod.info/id/periodes/9e11f337-8575-4c8f-a9e5-34d7d91988da> mg8:endTime ?end4.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    #Nooddorpen Oekraïne
    <http://lblod.data.info/id/subsidy-measure-offer-series/4a40d903-d77f-49e0-8cf4-daa3ce623439> dct:description "14/03/2022 — 30/09/2023"@nl .
    <http://data.lblod.info/id/periodes/5ecb1512-e8b3-40bf-a0c4-a4087090c093> mg8:endTime "2023-09-30T03:00:00Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/8265739f-2f05-4ada-8a30-c813b4bd783c> mg8:endTime "2023-09-30T03:00:00Z"^^xsd:dateTime .

    #Opknapwerken slaapplekken Oekraïne
    <http://lblod.data.info/id/subsidy-measure-offer-series/fecdeba8-cabb-43b0-a0a1-3ab7a1d4a773> dct:description "14/03/2022 — 30/09/2023"@nl .
    <http://data.lblod.info/id/periodes/cbc00fd0-0d0e-4c99-8dfc-691db7dde72d> mg8:endTime "2023-09-30T03:00:00Z"^^xsd:dateTime .
    <http://data.lblod.info/id/periodes/9e11f337-8575-4c8f-a9e5-34d7d91988da> mg8:endTime "2023-09-30T03:00:00Z"^^xsd:dateTime .
  }
}