PREFIX m8g: <http://data.europa.eu/m8g/>

DELETE {
  GRAPH ?g {
    ?s m8g:startTime ?start .
    ?s m8g:endTime ?end .
  }
}
INSERT {
  GRAPH ?g {
    ?s m8g:startTime "2023-09-01T21:59:59Z"^^xsd:dateTime .
    ?s m8g:endTime "2023-12-06T22:59:59Z"^^xsd:dateTime .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?s {
      <http://data.lblod.info/id/periodes/0bbe9eb8-8814-4c86-8c3d-5d3aa12a7389> # LEKP 1.0 - Indienen Pact - periode
      <http://data.lblod.info/id/periodes/18374b39-b34b-43d1-b135-5e14007ca512> # LEKP 2.0 - Indienen Pact - periode
    }
    ?s m8g:startTime ?start.
    ?s m8g:endTime ?end .
  }
} 