DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <https://data.vlaanderen.be/id/concept/BesluitType/41a09f6c-7964-4777-8375-437ef61ed946> <http://www.w3.org/2004/02/skos/core#prefLabel> ?oldLabel .
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <https://data.vlaanderen.be/id/concept/BesluitType/41a09f6c-7964-4777-8375-437ef61ed946> <http://www.w3.org/2004/02/skos/core#prefLabel> "Besluit handhaven na ontvangst schorsingsbesluit" .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <https://data.vlaanderen.be/id/concept/BesluitType/41a09f6c-7964-4777-8375-437ef61ed946> <http://www.w3.org/2004/02/skos/core#prefLabel> ?oldLabel .
  }
}