PREFIX erediensten: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX account: <http://mu.semte.ch/vocabularies/account/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/c98e270d84a8455b2f4bf16b915aeff2> .  # Bisdom Hasselt
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/78dcd875a7f2a7d0b5767c9fd8052efa> .  # Bisdom Brugge
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/2089dc85d4ba48a7f28ee4b521af2b26> .  # Aartsbisdom Mechelen-Brussel
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/2267e8e132b5556bd4d0b454c9383ca0> .  # Bisdom Gent
    ?vendor account:canActOnBehalfOf <http://data.lblod.info/id/representatieveOrganen/b4d22cde910a7b58b6e4d9c1d3b15fbb> .  # Bisdom Antwerpen
  }
}
WHERE {
  BIND(<http://data.lblod.info/vendors/b1e41693-639a-4f61-92a9-5b9a3e0b924e> as ?vendor)
  GRAPH ?g {
    ?vendor a ext:Vendor
  }
}
