PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/> 

# Add status "EFFECTIEF" to erediest mandatarissen & ministers if they dont already have a status assigned
INSERT {
  GRAPH ?h {
     ?mandataris <http://data.vlaanderen.be/ns/mandaat#status> <http://data.vlaanderen.be/id/concept/MandatarisStatusCode/21063a5b-912c-4241-841c-cc7fb3c73e75> #Effectief
  }
} WHERE {
  GRAPH ?g {
    {
      ?mandataris a ere:EredienstMandataris
    } UNION {
      ?mandataris a ere:RolBedienaar
    }
    FILTER NOT EXISTS {
      ?mandataris <http://data.vlaanderen.be/ns/mandaat#status> ?statusCode
    }
  }
  BIND(?g as ?h)
};
