DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuursorganen/ad933a3247ab634eb1a8c7233e77d6ea8cd2b6e1950d302832d065dcb516bcf5>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Voeren" .
    <http://data.lblod.info/id/bestuursorganen/082976d57de0655ac4f123b57d5cb008f612956d0a6de1742c02913dcbfcf125>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Drogenbos" .
    <http://data.lblod.info/id/bestuursorganen/cc803c53b2e0b17aac1069f5566fb8e1c8dad2f702845515a662229721803c00>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Wezembeek-Oppem" .
    <http://data.lblod.info/id/bestuursorganen/f373ece36dc05b29737c0adc14de95682161bb78a55cb85f786fac3fbd5b1cfc>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Sint-Genesius-Rode" .
    <http://data.lblod.info/id/bestuursorganen/317126204426dc7cabb60ecb09cbe4ca4830882652884e1e5800e60231195f5c>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Linkebeek" .
    <http://data.lblod.info/id/bestuursorganen/db8c3e2da85d7621120a986adc19fd8d21f501b39c01952238073abfe7d4a7e7>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Wemmel" .
    <http://data.lblod.info/id/bestuursorganen/d7fffe5c17d1936d46b92620d1e454f38393736988514b5f339910a17c7134f0>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"OCMWraad(Rechtstreeksverkiezing) Kraainem" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuursorganen/f373ece36dc05b29737c0adc14de95682161bb78a55cb85f786fac3fbd5b1cfc>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Sint-Genesius-Rode" .
    <http://data.lblod.info/id/bestuursorganen/317126204426dc7cabb60ecb09cbe4ca4830882652884e1e5800e60231195f5c>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Linkebeek" .
    <http://data.lblod.info/id/bestuursorganen/cc803c53b2e0b17aac1069f5566fb8e1c8dad2f702845515a662229721803c00>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Wezembeek-Oppem" .
    <http://data.lblod.info/id/bestuursorganen/ad933a3247ab634eb1a8c7233e77d6ea8cd2b6e1950d302832d065dcb516bcf5>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Voeren" .
    <http://data.lblod.info/id/bestuursorganen/082976d57de0655ac4f123b57d5cb008f612956d0a6de1742c02913dcbfcf125>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Drogenbos" .
    <http://data.lblod.info/id/bestuursorganen/d7fffe5c17d1936d46b92620d1e454f38393736988514b5f339910a17c7134f0>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Kraainem" .
    <http://data.lblod.info/id/bestuursorganen/db8c3e2da85d7621120a986adc19fd8d21f501b39c01952238073abfe7d4a7e7>	<http://www.w3.org/2004/02/skos/core#prefLabel>	"Raad voor Maatschappelijk Welzijn Wemmel" .
  }
}
