PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?publicService ext:status <http://lblod.data.gift/concepts/176ec8a9-ffd6-4f0b-a302-84ef59b31c42>
  }
}
WHERE {
  GRAPH ?g {
   ?s a cpsv:PublicService
  }
  BIND(?s as ?publicService)
}