PREFIX eredienst: <http://data.lblod.info/vocabularies/erediensten/>

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Gemeente Antwerpen - Kathedrale kerkfabriek O.L.V. 
    <http://data.lblod.info/id/bestuurseenheden/670db1d66c0de3b931962e1044033ccfa9d6e3023aa9828a5f252c3bc69bd32c> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61EFBC33BA00DD4BE2501CB8> .
    
    # Gemeente Gent - Kathedrale kerkfabriek Sint-Baafs
    <http://data.lblod.info/id/bestuurseenheden/353234a365664e581db5c2f7cc07add2534b47b8e1ab87c821fc6e6365e6bef5> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F3A3DB51BFC225E4ECEF56> .

    # Gemeente Hasselt - Kathedrale kerkfabriek Sint-Quintinus
    <http://data.lblod.info/id/bestuurseenheden/9db1b46874a57fe63c08fb5f16b117e6f61fdd98e7f64f745d0fceb9d3731169> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F7A7EF51BFC225E4ECF099> .
  
    # Gemeente Mechelen - Kathedrale kerkfabriek Sint-Rumoldus
    <http://data.lblod.info/id/bestuurseenheden/be278471a2a318edba32e7ac4294c0eafbe4c8077a34dcbb9c2e43211d4a78a6> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F941EA51BFC225E4ECF3B4> .

    # Gemeente Brugge - Kathedrale kerkfabriek Sint-Salvator
    <http://data.lblod.info/id/bestuurseenheden/28346950e285b8b816133fece5ac9408097c3f190c7f32573cf0c640d6c34b1a> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F152FA51BFC225E4ECEE7A> .
  }
};
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Provincie Antwerpen - Kathedrale kerkfabriek O.L.V. 
    <http://data.lblod.info/id/bestuurseenheden/bd74ee38a4b1e296821a11729c1f704cf439576c7ab2c910c95b067cf183d923> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61EFBC33BA00DD4BE2501CB8> .
    
    # Oost-Vlaanderen - Kathedrale kerkfabriek Sint-Baafs
    <http://data.lblod.info/id/bestuurseenheden/298b13541e1e85de4b71535197aa1f3bbc4bdb67f0fe0f58ab4a7dc207af61fa> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F3A3DB51BFC225E4ECEF56> .

    # Limburg - Kathedrale kerkfabriek Sint-Quintinus
    <http://data.lblod.info/id/bestuurseenheden/14278813524c762255aeba149e7d7134ddecfbb43e7d56910731bd4e13e34f39> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F7A7EF51BFC225E4ECF099> .
  
    # Provincie Antwerpen - Kathedrale kerkfabriek Sint-Rumoldus
    <http://data.lblod.info/id/bestuurseenheden/bd74ee38a4b1e296821a11729c1f704cf439576c7ab2c910c95b067cf183d923> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F941EA51BFC225E4ECF3B4> .

    # West-Vlaanderen - Kathedrale kerkfabriek Sint-Salvator
    <http://data.lblod.info/id/bestuurseenheden/8152e68420f560b8493d6c555a5bd4186903dc341028bb9855af6c44a9464fea> eredienst:betrokkenBestuur <http://data.lblod.info/id/betrokkenLokaleBesturen/61F152FA51BFC225E4ECEE7A> .
  }
}