PREFIX mobiliteit:    <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX lblodSubsidie: <http://lblod.data.gift/vocabularies/subsidie/>
PREFIX dct:           <http://purl.org/dc/terms/>
PREFIX subsidie:      <http://data.vlaanderen.be/ns/subsidie#>
PREFIX gleif:         <https://www.gleif.org/ontology/Base/>
PREFIX mu:            <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv:          <http://purl.org/vocab/cpsv#>
PREFIX xkos:          <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX qb:            <http://purl.org/linked-data/cube#>
PREFIX xsd:           <http://www.w3.org/2001/XMLSchema#>
PREFIX m8g:           <http://data.europa.eu/m8g/>
PREFIX common:        <http://www.w3.org/2007/uwa/context/common.owl#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Period of the series
    <http://data.lblod.info/id/periodes/9afd5470-93e1-4ff8-8722-6ad648aa1d1e>
      a             m8g:PeriodOfTime ;
      mu:uuid       "9afd5470-93e1-4ff8-8722-6ad648aa1d1e" ;
      m8g:startTime "2023-05-29T21:59:59Z"^^xsd:dateTime ;
      m8g:endTime   "3000-05-29T21:59:59Z"^^xsd:dateTime .

    # Step(s) of the series
    <http://data.lblod.info/id/subsidy-procedural-steps/58a5b63c-f653-422c-87f2-94e1fc3779fd>
      a                                   subsidie:Subsidieprocedurestap ;
      mu:uuid                             "58a5b63c-f653-422c-87f2-94e1fc3779fd" ;
      dct:description                     """Externe verwerking""" ;
      subsidie:Subsidieprocedurestap.type <http://lblod.data.gift/concepts/3ded9eab-ff5b-4a20-a095-0825de486f42> ; # External processing
      mobiliteit:periode                  <http://data.lblod.info/id/periodes/9afd5470-93e1-4ff8-8722-6ad648aa1d1e> .

    # Step(s) of the active submission flow
    <http://lblod.data.info/id/subsidie-application-flow-steps/0dacd9e0-b454-4c4a-a836-09684cebcfe3>
      a                 lblodSubsidie:ApplicationStep ;
      mu:uuid           "0dacd9e0-b454-4c4a-a836-09684cebcfe3" ;
      qb:order          0 ;
      dct:references    <http://data.lblod.info/id/subsidy-procedural-steps/58a5b63c-f653-422c-87f2-94e1fc3779fd> ;
      dct:isPartOf      <http://lblod.data.info/id/subsidie-application-flows/46409542-df7a-4cc1-9457-816b46736fdd> ;
      dct:isReplacedBy  <https://subsidiesmobiliteitsbeleid.vlaanderen.be/> .

    # Active submission flow for latest hoppinpunten subsidy series
    <http://lblod.data.info/id/subsidie-application-flows/46409542-df7a-4cc1-9457-816b46736fdd>
      a               lblodSubsidie:ApplicationFlow ;
      mu:uuid         "46409542-df7a-4cc1-9457-816b46736fdd" ;
      xkos:belongsTo  <http://lblod.data.info/id/subsidy-measure-offer-series/edb2c04c-99a6-4f88-9418-1d928dfd8447> ;
      xkos:next       <http://lblod.data.info/id/subsidie-application-flow-steps/0dacd9e0-b454-4c4a-a836-09684cebcfe3> .

    # Create Series for subsidy call named "Oproep"
    <http://lblod.data.info/id/subsidy-measure-offer-series/edb2c04c-99a6-4f88-9418-1d928dfd8447>
      a                   lblodSubsidie:SubsidiemaatregelAanbodReeks ;
      mu:uuid             "edb2c04c-99a6-4f88-9418-1d928dfd8447" ;
      dct:title           "Oproep"@nl ;
      dct:description     "29/05/2023 — nvt"@nl ;
      mobiliteit:periode  <http://data.lblod.info/id/periodes/9afd5470-93e1-4ff8-8722-6ad648aa1d1e> ;
      common:active       <http://lblod.data.info/id/subsidie-application-flows/46409542-df7a-4cc1-9457-816b46736fdd> .

    # Subsidy offer for "hoppinpunten"
    <http://lblod.data.info/id/subsidy-measure-offers/60ea4171-e795-4138-998d-5888d29bdd21>
      a                         subsidie:SubsidiemaatregelAanbod ;
      mu:uuid                   "60ea4171-e795-4138-998d-5888d29bdd21" ;
      dct:title                 """Subsidie voor het toegankelijk aanleggen of herinrichten van haltes en de uitrusting van haltes""" ;
      skos:prefLabel            """Subsidie voor het toegankelijk aanleggen of herinrichten van haltes en de uitrusting van haltes""" ;
      skos:related              <https://www.vlaanderen.be/subsidies-voor-het-toegankelijk-aanleggen-of-herinrichten-van-haltes-en-de-uitrusting-van-haltes> ;
      m8g:hasCriterion          <http://data.lblod.info/id/criterions/f5ea0615-0b0a-47db-a38c-6097ff80815d> ; # Available only for "gemeenten"
      cpsv:follows              <http://data.lblod.info/id/subsidy-procedural-steps/58a5b63c-f653-422c-87f2-94e1fc3779fd> ;
      lblodSubsidie:heeftReeks  <http://lblod.data.info/id/subsidy-measure-offer-series/edb2c04c-99a6-4f88-9418-1d928dfd8447> .
  }
}
