PREFIX dct:     <http://purl.org/dc/terms/>
PREFIX schema:  <http://schema.org/>
PREFIX lpdcExt: <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#>

INSERT {
  GRAPH ?conceptualPublicServiceGraph {
    ?conceptualPublicService schema:productID ?productId .
  }
} WHERE {
  ?conceptualPublicServiceSnapshot a lpdcExt:ConceptualPublicService ;
    dct:isVersionOf   ?conceptualPublicService ;
    schema:productID  ?productId .

  GRAPH ?conceptualPublicServiceGraph {
    ?conceptualPublicService a lpdcExt:ConceptualPublicService .
    FILTER NOT EXISTS { ?conceptualPublicService schema:productID ?productId . }
  }
}
