PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX pera: <http://publications.europa.eu/resource/authority/>
PREFIX schema: <http://schema.org/>
PREFIX dct: <http://purl.org/dc/terms/>
DELETE{
  GRAPH ?graph{
    ?publicService schema:publication <http://lblod.data.gift/concepts/3369bb10-1962-11ed-b07c-132292303e92>.
  }
}
WHERE{
  GRAPH ?graph{
    ?publicService a cpsv:PublicService;
      schema:publication <http://lblod.data.gift/concepts/3369bb10-1962-11ed-b07c-132292303e92>.
    FILTER EXISTS{
      ?publicService pera:language ?language.
    }
  }
}