PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:  <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX dct:   <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    # Insert bestuurseenheid
    <http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "cc175465-0aa7-4f86-b6c1-fb9e4968def9" ;
      skos:prefLabel "Vrijetijdsregio Druivenstreek" ;
      <http://mu.semte.ch/vocabularies/ext/kbonummer>	"0733925457" ;
      dcterms:identifier "OVO036395", "0733925457" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/b156b67f-c5f4-4584-9b30-4c090be02fdc> . # Projectvereniging

    # Insert bestuursorganen
    <http://data.lblod.info/id/bestuursorganen/ec85573eb26ecce431e6408070eb9cfc>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"ec85573eb26ecce431e6408070eb9cfc" ;
      skos:prefLabel "Directiecomité Vrijetijdsregio Druivenstreek" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt>	<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9> .

    <http://data.lblod.info/id/bestuursorganen/1ead7587b839bca7c331badd4e80b30c>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"1ead7587b839bca7c331badd4e80b30c" ;
      skos:prefLabel "Raad van bestuur Vrijetijdsregio Druivenstreek" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9> .

    <http://data.lblod.info/id/bestuursorganen/853ba90019c0c1edc23ede21e446f044>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"853ba90019c0c1edc23ede21e446f044" ;
      skos:prefLabel "Bevoegd beslissingsorgaan Vrijetijdsregio Druivenstreek" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9> .

    <http://data.lblod.info/id/bestuursorganen/f24953cd349c0a5797b30c218a437254>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"f24953cd349c0a5797b30c218a437254" ;
      skos:prefLabel "Algemene vergadering Vrijetijdsregio Druivenstreek" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9> .

    <http://data.lblod.info/id/bestuursorganen/9416e5d71f5906a386fcf94ca4aab1f9>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"9416e5d71f5906a386fcf94ca4aab1f9" ;
      skos:prefLabel "Leidend Ambtenaar Vrijetijdsregio Druivenstreek" ;
      <http://data.vlaanderen.be/ns/besluit#classificatie> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4> ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9> .

    # Insert bestuursorganen in tijd
    <http://data.lblod.info/id/bestuursorganen/93797238f4583afcefbe664285b16751>
      rdf:type	<http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"93797238f4583afcefbe664285b16751" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/ec85573eb26ecce431e6408070eb9cfc> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/320619906425995397bed9082c51e47a>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "320619906425995397bed9082c51e47a" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/1ead7587b839bca7c331badd4e80b30c> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/98d614790246fd23ef2e3271f3820a6a>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"98d614790246fd23ef2e3271f3820a6a" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan>	<http://data.lblod.info/id/bestuursorganen/853ba90019c0c1edc23ede21e446f044> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/d1dc8cbbd3e070650c6b34533b51eec3>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"d1dc8cbbd3e070650c6b34533b51eec3" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/f24953cd349c0a5797b30c218a437254> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .

    <http://data.lblod.info/id/bestuursorganen/26cfe8befb96523a225d15a45dc9728a>
      rdf:type <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"26cfe8befb96523a225d15a45dc9728a" ;
      <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/9416e5d71f5906a386fcf94ca4aab1f9> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart>	"2019-01-01"^^xsd:date .
  }
}
