INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concept-schemes/60d620a5-ec34-4a91-ba84-fff0813d0ccc>
        a <http://www.w3.org/2004/02/skos/core#ConceptScheme> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "60d620a5-ec34-4a91-ba84-fff0813d0ccc" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Municipal road procedure type"@en ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Type procedure voor een gemeenteweg"@nl .

    <http://lblod.data.gift/concepts/0588da5c-08b2-4209-ab3c-efd1b94e1326>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "0588da5c-08b2-4209-ab3c-efd1b94e1326" ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/60d620a5-ec34-4a91-ba84-fff0813d0ccc> ;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/60d620a5-ec34-4a91-ba84-fff0813d0ccc> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Aanleg, verplaatsing of wijziging van een gemeenteweg"@nl .

    <http://lblod.data.gift/concepts/82813418-356b-49a6-be9e-c5ef1b7a70bc>
        a <http://www.w3.org/2004/02/skos/core#Concept>, <http://www.w3.org/2000/01/rdf-schema#Class> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "82813418-356b-49a6-be9e-c5ef1b7a70bc" ;
        <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/60d620a5-ec34-4a91-ba84-fff0813d0ccc> ;
        <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/60d620a5-ec34-4a91-ba84-fff0813d0ccc> ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Opheffing van een gemeenteweg"@nl .
  }
}
