INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/public/> {
<http://data.vlaanderen.be/id/concept/BestuursfunctieCode/63195ec6-02cb-4f86-ac8e-29c5183a11dc> a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>,
     <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://mu.semte.ch/vocabularies/core/uuid> "63195ec6-02cb-4f86-ac8e-29c5183a11dc";
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Griffier";
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> .
<http://data.vlaanderen.be/id/concept/BestuursfunctieCode/3200ffc1-bb72-4235-a81c-64aa578b0789> a <http://mu.semte.ch/vocabularies/ext/BestuursfunctieCode>,
     <http://www.w3.org/2004/02/skos/core#Concept>;
   <http://mu.semte.ch/vocabularies/core/uuid> "3200ffc1-bb72-4235-a81c-64aa578b0789";
   <http://www.w3.org/2004/02/skos/core#prefLabel> "Adjunct-financieel directeur";
   <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> .
}}