##################################
# To run in Loket
# Updates broken label
# removes double label
#################################

# remove double label
DELETE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/a34e11da-4e4e-43be-936e-b05ce0f992ac> ?p ?o.
  }
}
WHERE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/a34e11da-4e4e-43be-936e-b05ce0f992ac> ?p ?o.
  }
}


;


DELETE {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f> <http://www.w3.org/2004/02/skos/core#prefLabel> ?label.
   }
}
INSERT {
  GRAPH ?g {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f> <http://www.w3.org/2004/02/skos/core#prefLabel> "Leidend ambtenaar".
   }
}
WHERE {
  GRAPH ?g {
   <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f> <http://www.w3.org/2004/02/skos/core#prefLabel> ?label.
  }
}
