PREFIX adres: <https://data.vlaanderen.be/ns/adres#>

DELETE {
  GRAPH ?g {
    ?s adres:AdresVoorstelling.huisnummer ?o.
  }
}
INSERT {
  GRAPH ?g {
    ?s adres:Adresvoorstelling.huisnummer ?o.
  }
}
WHERE {
  GRAPH ?g {
    ?s adres:AdresVoorstelling.huisnummer ?o.
  }
}