PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/accounts/deltas> {
     <http://data.lblod.info/foaf/account/id/12020cc2-dbc6-4273-ab18-177571fd8b06> a foaf:OnlineAccount.

     <http://data.lblod.info/foaf/agent/id/d44c7ea0-dc5f-43b1-ad10-e281a8aa646c> a foaf:Agent;
         foaf:account <http://data.lblod.info/foaf/account/id/12020cc2-dbc6-4273-ab18-177571fd8b06>.

     <http://data.lblod.info/foaf/group/id/e0cae0c1-69e1-4318-9ac2-91210a6d133e> a foaf:Group;
       foaf:member <http://data.lblod.info/foaf/agent/id/d44c7ea0-dc5f-43b1-ad10-e281a8aa646c>;
       foaf:name "persons-sensitive-deltas".
  }
}