DELETE { GRAPH ?graph{
?id <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>.
}}
INSERT { GRAPH ?graph{
?id <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/79a52da4-f491-4e2f-9374-89a13cde8ecd>.
}}
WHERE { GRAPH ?graph{
?id a <http://purl.org/vocab/cpsv#PublicService>.
?id <http://www.w3.org/ns/adms#status> <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>.
}}