PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX schema: <http://schema.org/>
PREFIX adms: <http://www.w3.org/ns/adms#>

DELETE {
  GRAPH ?g {
  ?publicService schema:publication ?publication.
  }
}
WHERE {
  GRAPH ?g {
   ?publicService a cpsv:PublicService;
     adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>;
     schema:publication ?publication.
  }
}