PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/accounts/deltas> {
     <http://data.lblod.info/foaf/account/id/dd85f516-ee7c-406b-8245-91ce7f9545b7> a foaf:OnlineAccount.

     <http://data.lblod.info/foaf/agent/id/31aa5c86-b350-46d6-aedf-2cf9d968378a> a foaf:Agent;
         foaf:account <http://data.lblod.info/foaf/account/id/dd85f516-ee7c-406b-8245-91ce7f9545b7>.

     <http://data.lblod.info/foaf/group/id/5dddf870-c148-4e1f-a986-56ed599c3b1d> a foaf:Group;
       foaf:member <http://data.lblod.info/foaf/agent/id/31aa5c86-b350-46d6-aedf-2cf9d968378a>;
       foaf:name "worship-submissions-deltas".
  }
}