PREFIX muAccount: <http://mu.semte.ch/vocabularies/account/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/automatic-submission> {
   <http://data.lblod.info/vendors/b1e41693-639a-4f61-92a9-5b9a3e0b924e> a foaf:Agent, ext:Vendor ;
    foaf:name "Vanden Broele" ;
    mu:uuid "b1e41693-639a-4f61-92a9-5b9a3e0b924e".
  }
}