PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mandatarissen: <http://data.lblod.info/id/mandatarissen/>

DELETE {
  GRAPH ?g {
    ?mandataris mandaat:rangorde ?rangorde .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris mandaat:rangorde ?rangordeStripped .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris rdf:type mandaat:Mandataris .
    ?mandataris mandaat:rangorde ?rangorde .
    BIND (STR(?rangorde) AS ?rangordeStripped)
  }
}

