PREFIX      org: <http://www.w3.org/ns/org#>
PREFIX      xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX      rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX       ch: <http://data.lblod.info/vocabularies/contacthub/>
PREFIX     core: <http://mu.semte.ch/vocabularies/core/>
PREFIX  mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX personen: <http://data.lblod.info/id/personen/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/8620c62b9e51d2275c98cb724ce4b6784b432db8e1e0376ac70cbda098ea0d0a/LoketLB-mandaatGebruiker> {
    <http://data.lblod.info/id/mandatarissen/5C583FF5D5BECA000D00011D>
        a mandaat:Mandataris ,
          ch:AgentInPositie ;
        mandaat:einde "2024-12-31T00:00:00Z"^^xsd:dateTime ;
        mandaat:isBestuurlijkeAliasVan personen:5C583FA3D5BECA000D00011B ;
        mandaat:start "2019-01-02T00:00:00Z"^^xsd:dateTime ;
        core:uuid "5C583FF5D5BECA000D00011D" ;
        org:hasMembership <http://data.lblod.info/id/lidmaatschappen/5C583FF4D5BECA000D00011C> ;
        org:holds <http://data.lblod.info/id/mandaten/3af6944728ed2c373ef1775158914e9af1cdedece237de58732833a9ba1e7ea4> .
  }
}
