# Update prefLabel & title for existing and new "Lokaal Energie- en KlimaatPact subsidy"

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offers/64d40351-8128-464f-990f-41066154583e>
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Lokaal Energie- en KlimaatPact" ;
      <http://purl.org/dc/terms/title> "Lokaal Energie- en KlimaatPact" .
  }
};

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offers/64d40351-8128-464f-990f-41066154583e>
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Lokaal Energie- en Klimaatpact 1.0" ;
      <http://purl.org/dc/terms/title> "Lokaal Energie- en Klimaatpact 1.0" .
  }
};

# Update reeks title for existing and new "Lokaal Energie- en KlimaatPact subsidy"

DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offer-series/87b87f00-6f87-4412-be26-ea531220457c>
      <http://purl.org/dc/terms/title> "2022".
  }
};

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offer-series/87b87f00-6f87-4412-be26-ea531220457c>
      <http://purl.org/dc/terms/title> "2021".
  }
};


