INSERT {
  GRAPH ?g {
    ?s <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitDocumentType>.
    ?s <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://data.vlaanderen.be/id/conceptscheme/BesluitDocumentType>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/2004/02/skos/core#Concept>.
  }
  FILTER(STRSTARTS(STR(?s), "https://data.vlaanderen.be/id/concept/BesluitDocumentType/"))
  FILTER NOT EXISTS {
    ?s <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitDocumentType>.
  }
}

;

INSERT {
  GRAPH ?g {
   ?s <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>.
   ?s <http://www.w3.org/2004/02/skos/core#topConceptOf> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/2004/02/skos/core#Concept>.
  }
  FILTER(STRSTARTS(STR(?s), "https://data.vlaanderen.be/id/concept/BesluitType/"))
  FILTER NOT EXISTS {
    ?s <http://www.w3.org/2004/02/skos/core#inScheme> <https://data.vlaanderen.be/id/conceptscheme/BesluitType>.
  }
}