PREFIX kandidatenlijsten: <http://data.lblod.info/id/kandidatenlijsten/>
PREFIX personen:          <http://data.lblod.info/id/personen/>
PREFIX mandaat:           <http://data.vlaanderen.be/ns/mandaat#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    kandidatenlijsten:589972a7-795c-4937-a566-c6e7dba7e219
      mandaat:heeftKandidaat personen:5BADF17B98360D0009000225 .
  }
}
