PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
INSERT {
  GRAPH ?g {
    ?s owl:sameAs <http://data.lblod.info/id/personen/dd6d2c6a-eeb8-4f71-9bae-a34d35280c1d>.
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/personen/6320D149BC7AFA9A82B9007A>
    <http://data.lblod.info/id/personen/632435D755A59A45B09C0DFC>
  }
  FILTER (?g NOT IN (
    <http://redpencil.data.gift/id/deltas/producer/loket-leidinggevenden-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-mandatarissen-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-submissions> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-persons-sensitive> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-subsidies>
  ))
  GRAPH ?g {
    ?s ?p  ?o.
  }
}