PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dct:  <http://purl.org/dc/terms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/403b71bd-5ab9-4c92-8990-4bb19d5469d1>
        a skos:Concept, rdfs:Class;
        mu:uuid "403b71bd-5ab9-4c92-8990-4bb19d5469d1" ;
        skos:prefLabel "Publicatie op de eredienst beslissings database"@nl ;
        skos:inScheme <http://lblod.data.gift/concept-schemes/b6a991c7-e126-4f9e-a956-4a4684502ba6> . #publication-event-types
  }
}
