DELETE {
  GRAPH ?g {
    ?s ?p ?o.
  }
}
INSERT {
  GRAPH <http://redpencil.data.gift/id/deltas/producer/persons-sensitive-deltas> {
    ?s ?p ?o.
  }
}
WHERE {
  BIND(<http://redpencil.data.gift/id/deltas/producer/persons-sensitive/meta> as ?g)
  GRAPH ?g {
    ?s ?p ?o.
  }
}