PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
  GRAPH ?g {
    ?subject foaf:familyName ?familyname;
       foaf:firstName ?firstName.
  }
}
INSERT {
  GRAPH ?g {
  ?subject foaf:familyName """Kerkfabriek Vredegem""";
    foaf:firstName """Kerkfabriek Vredegem""".
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/persoon/20e72ad886aa41d5fac6507a5f593d0b> as ?subject)
  GRAPH ?g {
    ?subject foaf:familyName ?familyname;
       foaf:firstName ?firstName.
  }
}

;

DELETE {
  GRAPH ?g {
    ?subject ext:sessionRole """LoketLB-LPDCGebruiker""".
  }
}
INSERT {
  GRAPH ?g {
  ?subject ext:sessionRole """LoketLB-berichtenGebruiker""".
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/account/7c8f3283dc7d70834983f0bfd5676628> as ?subject)
  GRAPH ?g {
    ?subject a ?what.
  }
}

;

DELETE {
  GRAPH ?g {
    ?subject skos:prefLabel ?label.
  }
}
INSERT {
  GRAPH ?g {
  ?subject skos:prefLabel """Kerkfabriek Vredegem""".
  }
}
WHERE {
  BIND(<http://data.lblod.info/id/besturenVanDeEredienst/578bf96f86056e2260dc21cee91aa519> as ?subject)
  GRAPH ?g {
    ?subject skos:prefLabel ?label.
  }
}