# Propagate last names

INSERT {
  GRAPH ?g {
    ?s <http://xmlns.com/foaf/0.1/familyName> ?lastName .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/person#Person> ;
      <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?firstName .

    FILTER NOT EXISTS {
      ?s <http://xmlns.com/foaf/0.1/familyName> ?unexistingLastName .
    }
  }

  ?s <http://xmlns.com/foaf/0.1/familyName> ?lastName .
}

;

# Propagate first names

INSERT {
  GRAPH ?g {
    ?s <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?firstName .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/person#Person> ;
    <http://xmlns.com/foaf/0.1/familyName> ?lastName .

    FILTER NOT EXISTS {
      ?s <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?unexistingFirstName .
    }
  }

  ?s <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam> ?firstName .
}
