DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.info/id/subsidy-measure-offers/a2d920b2-d266-4555-b023-63632997c406> <http://data.europa.eu/m8g/hasCriterion>
      <http://data.lblod.info/id/criterions/80301a63-927c-48e5-8678-048c87c25847>, # vgc
      <http://data.lblod.info/id/criterions/f5ea0615-0b0a-47db-a38c-6097ff80815d>. # gemeente
  }
}