PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH ?g {
    ?sa ?pout ?oout .
  }
}
INSERT {
  GRAPH ?g {
    ?sa owl:sameAs ?sb .
    ?sb ?pout ?oout .
  }
}
WHERE {
  VALUES ?sa {
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2>
  }
  VALUES ?sb {
    <http://data.lblod.info/id/personen/5C583FA3D5BECA000D00011B>
  }
  FILTER (?g NOT IN (
    <http://redpencil.data.gift/id/deltas/producer/loket-leidinggevenden-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-mandatarissen-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-submissions> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-persons-sensitive> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-subsidies>
  ))
  GRAPH ?g {
    ?sa ?pout ?oout .
  }
}
;
DELETE {
  GRAPH ?g {
    ?sin ?pin ?sa .
  }
}
INSERT {
  GRAPH ?g {
    ?sin ?pin ?sb .
  }
}
WHERE {
  VALUES ?sa {
    <http://data.lblod.info/id/personen/a224dd4e872e45c62599b606a20fe586858fb31cbf3e2a85a58f793a4bb1ccd2>
  }
  VALUES ?sb {
    <http://data.lblod.info/id/personen/5C583FA3D5BECA000D00011B>
  }
  FILTER (?g NOT IN (
    <http://redpencil.data.gift/id/deltas/producer/loket-leidinggevenden-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-mandatarissen-producer> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-submissions> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-persons-sensitive> ,
    <http://redpencil.data.gift/id/deltas/producer/loket-subsidies>
  ))
  GRAPH ?g {
    ?sin ?pin ?sa .
  }
}
