PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ns1: <http://data.lblod.info/vocabularies/lpdc-ipdc/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cpsv: <http://purl.org/vocab/cpsv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX lpdcExt: <https://productencatalogus.data.vlaanderen.be/ns/ipdc-lpdc#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX m8g: <http://data.europa.eu/m8g/>
PREFIX lblodLpdc: <http://data.lblod.info/id/public-services/>
PREFIX lblodIpdcLpdc: <http://lblod.data.gift/vocabularies/lpdc-ipdc/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX lang: <http://publications.europa.eu/resource/authority/language/>
PREFIX lblodOrg: <http://data.lblod.info/id/concept/organisatie/>
PREFIX lblodIpdcThema: <http://data.lblod.info/id/concept/ipdc-thema/>
PREFIX belgif: <http://vocab.belgif.be/ns/publicservice#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ps: <http://vocab.belgif.be/ns/publicservice#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX dvcs: <https://productencatalogus.data.vlaanderen.be/id/conceptscheme/>
PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX pav: <http://purl.org/pav/>
PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX as: <https://www.w3.org/ns/activitystreams#>
DELETE {
  GRAPH ?g {
    ?s ?p ?o.
  }
}
INSERT {
  GRAPH ?g {
    ?s ?p ?updatedEmptyString.
  }
}
WHERE {
  GRAPH ?g {
    {
      VALUES ?p {
        dct:description
        dct:title
      }
     ?publicService a cpsv:PublicService;
      adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>.

     BIND(?publicService as ?s)
     ?s ?p ?o.
    }
    UNION {
      VALUES ?type {
        m8g:Requirement
        cpsv:Rule
        m8g:Cost
        lpdcExt:FinancialAdvantage
        schema:ContactPoint
        foaf:Document
        schema:WebSite
      }
      VALUES ?p {
        dct:description
        dct:title
      }

      ?publicService a cpsv:PublicService;
        adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>;
        ?link ?s.
      ?s ?p ?o;
        a ?type.
    }
    UNION {
      VALUES ?type {
        m8g:Evidence
        schema:WebSite
      }
      VALUES ?p {
        dct:description
        dct:title
      }
      ?publicService a cpsv:PublicService;
      adms:status <http://lblod.data.gift/concepts/9bd8d86d-bb10-4456-a84e-91e9507c374c>;
        ?hopP ?hop.

      ?hop ?hopPP ?s.
      ?s ?p ?o;
        a ?type.
    }
  }
  FILTER(isLiteral(?o) && (datatype(?o) = xsd:string || langMatches(lang(?o), "en") || langMatches(lang(?o), "nl") ))
  BIND(strlen(REPLACE(?o, " ", "") ) as ?len)
  FILTER(?len <= 0)

    BIND(
    IF(LANG(?o),
        STRLANG("-", LANG(?o)),
        ?o)
      AS ?updatedEmptyString
    )
}