PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/accounts/deltas> {
     <http://data.lblod.info/foaf/account/id/4171b7a5-a4d6-42d0-bf37-f97b135fb885> a foaf:OnlineAccount.

     <http://data.lblod.info/foaf/agent/id/6fe1f417-5cd9-47b8-8aa0-e4ee629e81e3> a foaf:Agent;
         foaf:account <http://data.lblod.info/foaf/account/id/4171b7a5-a4d6-42d0-bf37-f97b135fb885>.

     <http://data.lblod.info/foaf/group/id/fcc0cfd2-ad12-4cd2-94b5-49fa428d9589> a foaf:Group;
       foaf:member <http://data.lblod.info/foaf/agent/id/6fe1f417-5cd9-47b8-8aa0-e4ee629e81e3>;
       foaf:name "subsidies-deltas".
  }
}