PREFIX erediensten: <http://data.lblod.info/vocabularies/erediensten/>

INSERT {
  GRAPH ?g {
    ?vendor <http://mu.semte.ch/vocabularies/account/canActOnBehalfOf> ?eenheid
  }
}
WHERE {
   BIND(<http://data.lblod.info/vendors/b1e41693-639a-4f61-92a9-5b9a3e0b924e> as ?vendor)

   ?eenheid a erediensten:CentraalBestuurVanDeEredienst.
   GRAPH ?g {
     ?vendor a <http://mu.semte.ch/vocabularies/ext/Vendor>
   }
}