DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36372fad-0358-499c-a4e3-f412d2eae213>
        <http://mu.semte.ch/vocabularies/core/uuid> ?uuid .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36372fad-0358-499c-a4e3-f412d2eae213>
        <http://mu.semte.ch/vocabularies/core/uuid> ?uuid .
    
    FILTER(?uuid != "36372fad-0358-499c-a4e3-f412d2eae213")
  }
}