# Move mandatarissen to a single van rechtswege mandaat in case of duplicates
# Must be run BEFORE the OP migration

PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>

DELETE {
  GRAPH ?orgGraph {
    ?mandataris org:holds ?mandaat .
  }
}
INSERT {
  GRAPH ?orgGraph {
    ?mandataris org:holds ?canonicalMandaat .
  }
}
WHERE {
  GRAPH ?orgGraph {
    ?mandataris a mandaat:Mandataris ;
      org:holds ?mandaat .
  }

  GRAPH <http://mu.semte.ch/graphs/public> {
    ?mandaat org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5972fccd87f864c4ec06bfbd20b5008b> .
    ?orgaanInTime generiek:isTijdspecialisatieVan ?orgaan ;
      org:hasPost ?mandaat .
  }

  {
    SELECT ?orgaan (IRI(MIN(STR(?anyMandaat))) AS ?canonicalMandaat) WHERE {
      GRAPH <http://mu.semte.ch/graphs/public> {
        ?anyOrgaanInTime generiek:isTijdspecialisatieVan ?orgaan ;
          org:hasPost ?anyMandaat .
        ?anyMandaat org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5972fccd87f864c4ec06bfbd20b5008b> .
      }
    }
    GROUP BY ?orgaan
  }

  FILTER(?mandaat != ?canonicalMandaat)
}
