DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s skos:prefLabel ?l2 .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
     skos:prefLabel ?l1, ?l2 .

    FILTER(STRENDS(?l2, "Adjunct-algemeendirecteur"))
  }
}

;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s skos:prefLabel ?l2 .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
     skos:prefLabel ?l1, ?l2 .

    FILTER(STRENDS(?l2, "Leidend ambtenaren"))
  }
}
